import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/empire"),
);
const icons = requireAll(require.context("../../assets/icons/empire"));

export const data: TalentData = {
  "Pyromancer": {
    name: "Pyromancer",
    background: backgrounds["pyromancer"],
    icon: icons["archetype_dps"],
    talents: {
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 1,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "Emperor's Ward": {
        name: "Emperor's Ward",
        pos: "a2",
        icon: icons["tac_race_empire"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet of you with this tactic gain a 300 absorb for 3 seconds.`,
      },
      "Sigmar's Favored": {
        name: "Sigmar's Favored",
        pos: "b2",
        icon: icons["tac_race_empire"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you receive a direct heal, you will also be healed for 120 + 8% wounds.`,
      },
      "Embrace the Flames": {
        name: "Embrace the Flames",
        pos: "c2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Unquenchable Fury is now applied to all groupmates within 100 feet of you.`,
      },
      "Aqshy's Aegis": {
        name: "Aqshy's Aegis",
        pos: "d2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Explosion and Blast now deal 50% less damage to you and your groupmates.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specstaff"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Pyromancers equip staves.`,
      },
	  "Disengage": {
        name: "Disengage",
        pos: "f2",
        icon: icons["morale_disengage"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`You knock yourself back away from target enemy.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Explosive Impact": {
        name: "Explosive Impact",
        pos: "h2",
        icon: icons["morale_explosiveimpact"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 10 seconds. Whenever you hit a target with a single-target ability, you will deal 10% RAP + 150 corporeal damage and 10% SAP + 150 elemental damage to up to 24 enemies within 20ft of the target.`,
      },
      "Unleash the Winds": {
        name: "Unleash the Winds",
        pos: "i2",
        icon: icons["morale_unleashthewinds"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 96 enemies within a 20 feet location you select are knocked straight up into the air.`,
      },
      "Melt Armor": {
        name: "Melt Armor",
        pos: "i4",
        icon: icons["morale_melt"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Target enemy gains 4 stacks of Reduced Armor.`,
      },
      "Burnout": {
        name: "Burnout",
        pos: "i5",
        icon: icons["morale_burnout"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain 100 Combustion and take Explosion damage.`,
      },
      "Emperor's Champion": {
        name: "Emperor's Champion",
        pos: "i7",
        icon: icons["morale_empchamp"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 20 seconds. For the duration, gain 250 ballistic skill, 250 intelligence, and 250 strength.`,
      },
      "Burning Head": {
        name: "Burning Head",
        pos: "i8",
        icon: icons["abi_em_burninghead"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Summons a Burning Head which charges forward affecting up to 24 allies and 96 enemies every second with a 3 second effect within 20 feet of its location.\n\nAllies gain 50% critical chance and 15 adrenaline per second. Enemies take 10% SAP + 150 elemental damage every second and gain 15 adrenaline per second.`,
      },
      "Explosion and Blast": {
        name: "Explosion and Blast",
        pos: "a1",
        icon: icons["abi_blast"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Explosion stacks to 100 and you will gain 8% outgoing damage when above 89.\nExplosion deals 21% SAP + 280 elemental damage to you whenever you gain Combustion that takes you above 100. (1s ICD)\n\nBlast is a debuff that lasts for 4 seconds and stacks 10 times. At the end of the duration, target takes 8% SAP + 90 elemental damage per stack.`,
      },
      "Pyroclastic Surge": {
        name: "Pyroclastic Surge",
        pos: "b1",
        icon: icons["abi_pyroclasticsurge"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 6% SAP + 133 corporeal damage to the target. You generate 40 action points and 5 Combustion.`,
      },
      "Fireball": {
        name: "Fireball",
        pos: "c1",
        icon: icons["abi_fireball"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "36 action points",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        description: talentText`Deals 52% SAP + 716 elemental damage to target. You generate 10 Combustion.`,
      },
      "Withering Heat": {
        name: "Withering Heat",
        pos: "d1",
        icon: icons["abi_witheringheat"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Consumes all Combustion",
        description: talentText`You gain a buff for 10 seconds. For the duration, you will gain sagacity based on Combustion consumed. In addition, each skill you cast will deal Explosion damage to you.\n25 CBN: 10%\n50 CBN: 30%\n75 CBN: 60%\n100 CBN: 100%`,
      },
      "Unquenchable Fury": {
        name: "Unquenchable Fury",
        pos: "e1",
        icon: icons["abi_unquench"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "100 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "15s cooldown",
        description: talentText`Apply a blessing to yourself for 60 seconds. Whenever you deal direct damage to a target, you will apply Blast to them and yourself.`,
      },
      "Fire Cage": {
        name: "Fire Cage",
        pos: "f1",
        icon: icons["abi_firecage"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Applies Rooted and Immovable to target enemy.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nImmovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Ignite": {
        name: "Ignite",
        pos: "g1",
        icon: icons["abi_ignite"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "30 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Applies an ailment to target enemy for 15 seconds. You generate 3 Combustion and the target takes 8% SAP + 100 elemental damage every 3 seconds.\n\nCannot be applied to targets under the effect of Detonate.`,
      },
      "Meltdown": {
        name: "Meltdown",
        pos: "h1",
        icon: icons["abi_meltdown"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 20 Combustion",
        description: talentText`Deals 22% SAP + 283 corporeal damage to the target.`,
      },
      "Smokescreen": {
        name: "Smokescreen",
        pos: "i1",
        icon: icons["abi_smokescreen"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "15s cooldown",
        description: talentText`Target enemy will deal 50% less damage to you for 15 seconds. This effect is removed if you hit the target with an ability.`,
      },
	  "Sear": {
        name: "Sear",
        pos: "h4",
        icon: icons["abi_sear"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "75 action points",
        range: "100ft range",
        cast: "1.0s cast",
        cooldown: "5s cooldown",
        description: talentText`Deals 25% SAP + 335 elemental damage to target and applies a stack of Blast. You will take Explosion damage and gain 5 Combustion.`,
      },
	  "Playing With Fire": {
        name: "Playing With Fire",
        pos: "e5",
        icon: icons["abi_playingwithfire"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "1.5s cast",
        cooldown: "no cooldown",
        description: talentText`Applies an ailment to the target for 10 seconds. Whenever the target is healed, you will deal 13% SAP + 183 elemental damage to the healer and you generate 5 Combustion.`,
      },
      "Boiling Blood": {
        name: "Boiling Blood",
        pos: "e6",
        icon: icons["abi_boilingblood"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "40 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Applies an ailment to the target for 6 seconds. At the end of the duration, target will take 17% SAP + 252 indirect, corporeal damage. You generate 5 Combustion`,
      },
      "Funnel Power": {
        name: "Funnel Power",
        pos: "c8",
        icon: icons["abi_funnelpower"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "2s cooldown",
        blue: "Costs 40 Combustion\nOff the GCD",
        description: talentText`You take Explosion damage and gain 1 stack of Enhanced Potency.`,
      },
      "Fireball Barrage": {
        name: "Fireball Barrage",
        pos: "d9",
        icon: icons["abi_fireballbarrage"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "75 action points",
        range: "100ft range",
        cast: "3.0s channel",
        cooldown: "no cooldown",
        description: talentText`Deals 18% SAP + 227 elemental damage to the target and up to 2 additional enemies within 20ft of them every 1.5 seconds. You generate 3 Combustion each time this deals damage.`,
      },
      "Spreading Flames": {
        name: "Spreading Flames",
        pos: "f9",
        icon: icons["abi_spreadingflames"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Applys a debuff to the target enemy for 2s. Deals 6% + 20 elemental damage every 1 second. At the end of the duration, applies stage 2 of the debuff to up to 6 other enemies within 20ft. There are 5 stages, each stacks up to 10x.`,
      },
      "Fire of Battle": {
        name: "Fire of Battle",
        pos: "a5",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`You gain 50% pushback immunity but the cast time of Pyroclastic Surge and Sear is increased by 0.25s.`,
      },
      "Critical Mass": {
        name: "Critical Mass",
        pos: "b5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you cast an ability, you will gain 8% critical chance for 5 seconds. This stacks until you deal a critical hit at which point all stacks are removed.`,
      },
      "Fiery Reserves": {
        name: "Fiery Reserves",
        pos: "b6",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Blast will now generate 3 Combustion per stack whenever it expires.`,
      },
      "Devouring Flames": {
        name: "Devouring Flames",
        pos: "g6",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Whenever you critically hit an enemy, you and the target take Explosion damage.`,
      },
      "Scorching Ignition": {
        name: "Scorching Ignition",
        pos: "a7",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Ignite will now apply 1 stack of Blast and 1 stack of Reduced Elemental Resistance to the target each time it deals damage.`,
      },
      "Flash Fire": {
        name: "Flash Fire",
        pos: "h7",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Whenever you cast Meltdown, you will gain 1 stack of an enchantment for 8 seconds, stacking up to 3 times. Fireball will have a 40% reduced cast time and remove 1 stack.`,
      },
      "Rolling Boil": {
        name: "Rolling Boil",
        pos: "f8",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Boiling Blood",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Boiling Blood will prevent the target from gaining stacks of Blast for the duration.`,
      },
      "Explosive Action": {
        name: "Explosive Action",
        pos: "e3",
        icon: icons["abi_blast"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever you take Explosion damage, you will gain ${[
          6,
          12,
          18,
        ]} action points.`,
      },
      "Red Tide": {
        name: "Red Tide",
        pos: "b3",
        icon: icons["abi_pyroclasticsurge"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Pyroclastic surge now deals ${[
          50,
          100,
        ]}% additional damage.`,
      },
      "Hardened Casting": {
        name: "Hardened Casting",
        pos: "g5",
        icon: icons["itm_ch_charredsoulgem"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`You gain ${[
          15,
          30,
          50,
        ]}% pushback immunity`,
      },
      "Improved Fireball": {
        name: "Improved Fireball",
        pos: "c6",
        icon: icons["abi_fireball"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`The cast time of Fireball is reduced by ${[
          0.1,
          0.2,
          0.3,
          0.4,
          0.5,
        ]} seconds.`,
      },
      "Searing Blast": {
        name: "Searing Blast",
        pos: "h6",
        icon: icons["abi_sear"],
        maxRank: 2,
        reqPoints: 15,
        prereq: "Sear",
        arrows: [{ dir: "down", from: "h4", to: "h6" }],
        type: "passive",
        description: talentText`Sear will now apply ${[
          3,
          5,
        ]} stacks of Blast.`,
      },
      "Boiling Blood II-IV": {
        name: "Boiling Blood II-IV",
        pos: "e7",
        icon: icons["abi_boilingblood"],
        maxRank: 3,
        reqPoints: 20,
        prereq: "Boiling Blood",
        arrows: [{ dir: "down", from: "e6", to: "e7" }],
        type: "passive",
        description: talentText`Boiling Blood is now a ${[
          "ailment",
          "ailment",
          "cripple",
        ]} with a ${[
          6,
          5,
          5,
        ]} second duration that deals elemental damage.`,
      },
      "Extra Crit": {
        name: "Extra Crit",
        pos: "b7",
        icon: icons["abi_extracrit"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Your chance to critically hit is increased by ${[
          2,
          4,
		  6,
        ]} `,
	  },
      "Reckless Funnel": {
        name: "Reckless Funnel",
        pos: "d8",
        icon: icons["abi_funnelpower"],
        maxRank: 4,
        reqPoints: 25,
        prereq: "Funnel Power",
        arrows: [{ dir: "right", from: "c8", to: "d8" }],
        type: "passive",
        description: talentText`Funnel Power will now refund ${[
          5,
          10,
          15,
          20,
        ]} combustion and has a ${[
          5,
          15,
          30,
          50,
        ]}% chance to also apply a stack of Enhanced Critical Hit Rating.`,
      },
    },
  },
  "Arsonist": {
    name: "Arsonist",
    background: backgrounds["hothead"],
    icon: icons["archetype_dps"],
    talents: {
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 1,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Emperor's Ward": {
        name: "Emperor's Ward",
        pos: "a2",
        icon: icons["tac_race_empire"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, you will gain a 400 absorb for 3 seconds.`,
      },
      "Sigmar's Favored": {
        name: "Sigmar's Favored",
        pos: "b2",
        icon: icons["tac_race_empire"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you receive a direct heal, you will also be healed for 120 + 8% wounds.`,
      },
      "Embrace the Flames": {
        name: "Embrace the Flames",
        pos: "c2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Unquenchable Fury is now applied to all groupmates within 100ft of you.`,
      },
      "Aqshy's Aegis": {
        name: "Aqshy's Aegis",
        pos: "d2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Explosion and Blast now deal 50% less damage to you and your groupmates.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specsword"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Arsonists equip longswords with a free off-hand.`,
      },
      "Melt Armor": {
        name: "Melt Armor",
        pos: "i4",
        icon: icons["morale_melt"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Target enemy gains 4 stacks of Reduced Armor.`,
      },
      "Burnout": {
        name: "Burnout",
        pos: "i5",
        icon: icons["morale_burnout"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain 100 Combustion and take Explosion damage.`,
      },
      "Emperor's Champion": {
        name: "Emperor's Champion",
        pos: "i7",
        icon: icons["morale_empchamp"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 20 seconds. For the duration, gain 250 ballistic skill, 250 intelligence, and 250 strength.`,
      },
      "Burning Head": {
        name: "Burning Head",
        pos: "i8",
        icon: icons["abi_em_burninghead"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Summons a Burning Head which charges forward affecting up to 24 allies and 96 enemies every second with a 3 second effect within 20 feet of its location.\n\nAllies gain 50% critical chance and 15 adrenaline per second. Enemies take 10% SAP + 150 elemental damage every second and gain 15 adrenaline per second.`,
      },
      "Disengage": {
        name: "Disengage",
        pos: "f2",
        icon: icons["morale_disengage"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`You knock yourself back away from target enemy.`,
      },
      "Broad Swings": {
        name: "Broad Swings",
        pos: "g2",
        icon: icons["morale_broadswings"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a  buff for 10 seconds. Your single target abilities will target two additional enemies within 15ft in front of you.`,
      },
	  "Explosive Impact": {
        name: "Explosive Impact",
        pos: "h2",
        icon: icons["morale_explosiveimpact"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 10 seconds. Whenever you hit a target with a single-target ability, you will deal 10% RAP + 150 corporeal damage and 10% SAP + 150 elemental damage to up to 24 enemies within 20ft of the target.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "Explosion and Blast": {
        name: "Explosion and Blast",
        pos: "a1",
        icon: icons["abi_blast"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Explosion stacks to 100 and you will gain 8% outgoing damage when above 89.\nExplosion deals 21% SAP + 280 elemental damage to you whenever you gain Combustion that takes you above 100. (1s ICD)\n\nBlast is a debuff that lasts for 4 seconds and stacks 10 times. At the end of the duration, target takes 8% SAP + 90 elemental damage per stack.`,
      },
      "Sparking Swing": {
        name: "Sparking Swing",
        pos: "b1",
        icon: icons["abi_sparks"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 4% MAP + 30 elemental damage to target enemy. You generate 22 action points.`,
      },
      "Ignite": {
        name: "Ignite",
        pos: "c1",
        icon: icons["abi_ignite"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "30 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Applies an ailment to target enemy for 15 seconds. You generate 3 Combustion and the target takes 8% SAP + 100 elemental damage every 3 seconds.\n\nCannot be applied to targets under the effect of Detonate.`,
      },
      "Flaming Sword of Rhuin": {
        name: "Flaming Sword of Rhuin",
        pos: "d1",
        icon: icons["abi_flameofrhuin"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 30 Combustion",
        description: talentText`Deals 35% MAP + 469 corporeal damage to target enemy.`,
      },
      "Unquenchable Fury": {
        name: "Unquenchable Fury",
        pos: "e1",
        icon: icons["abi_unquench"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "15s cooldown",
        description: talentText`Apply a blessing to yourself for 60 seconds. Whenever you deal direct damage to a target, you will apply Blast to them and yourself.`,
      },
      "Fire Cage": {
        name: "Fire Cage",
        pos: "f1",
        icon: icons["abi_firecage"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Applies Rooted and Immovable to target enemy.\n\nRooted reduces target movement speed to 0 for 5 seconds. Immovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Fuel for the Fire": {
        name: "Fuel for the Fire",
        pos: "g1",
        icon: icons["abi_fuelfire"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "2s cooldown",
        blue: "Off the GCD",
        description: talentText`You take Explosion damage and gain 20 Combustion.`,
      },
      "Breath of Fire": {
        name: "Breath of Fire",
        pos: "h1",
        icon: icons["abi_flamebreath"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "80 action points",
        range: "self",
        cast: "1.5s cast",
        cooldown: "no cooldown",
        blue: "Castable while moving",
        description: talentText`Applies an ailment to up to 9 enemies within 30 feet in front of you for 9 seconds. For the duration, the target takes 10% SAP + 132 elemental damage and you gain 2 Combustion every 3 seconds.`,
      },
      "Vigilance": {
        name: "Vigilance",
        pos: "i1",
        icon: icons["abi_vigilance"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        description: talentText`You gain a buff for 7 seconds that reduces all incoming damage by 50% and all outgoing damage by 90%.`,
      },
      "Cauterize": {
        name: "Cauterize",
        pos: "h4",
        icon: icons["abi_cauterize"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 10 Combustion",
        description: talentText`Dispel 1 enchantment from and apply 1 stack of Purity to target enemy. Dispel 1 affliction from yourself. Dispel 2 stacks of Blast from yourself. Apply 2 stack of Purity to yourself.`,
      },
	  "Detonate": {
        name: "Detonate",
        pos: "e5",
        icon: icons["abi_detonate"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "60 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
		blue: "Requires Ignite on Target",
        description: talentText`Dispels Ignite from the target to apply a 12 second cripple to the target and up to 8 additional enemies within 20 feet of them. For the duration, target takes 5% SAP + 62 corporeal damage and you gain 1 Combustion every 3 seconds.`,
      },
      "Cascading Fire Cloak": {
        name: "Cascading Fire Cloak",
        pos: "f6",
        icon: icons["abi_flameshield"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "50 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`You gain a blessing for 10 seconds. For the duration, whenever you use Sparks or Flaming Sword of Rhuin you will gain 1 stack of Enhanced Armor.\n\nFor the duration, whenever an enemy hits you with an ability, you will gain 1 stack of Reduced Armor and up to 9 enemies within 30 feet of you will take 5% SAP + 57 elemental damage. (1s ICD)`,
      },
	  "Burning Step": {
        name: "Burning Step",
        pos: "d8",
        icon: icons["abi_firestep"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "20s cooldown",
        blue: "Costs 25 Combustion",
        description: talentText`(Movement Skill) You gain 100% dodge and 100% movement speed for 2 seconds. You also gain 3 stacks of Blast.`,
      },
      "Scorched Earth": {
        name: "Scorched Earth",
        pos: "d9",
        icon: icons["abi_scorched"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Consumes all Combustion",
        description: talentText`Deals 6% MAP + 80 corporeal damage per 10 Combustion consumed to up to 9 enemies within 30ft of you.\n\nAugmented: Does not consume Combustion.`,
      },
      "Supernova": {
        name: "Supernova",
        pos: "f9",
        icon: icons["abi_supernova"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "self",
        cast: "5.0s channel",
        cooldown: "30s cooldown",
        description: talentText`Deal 10% SAP + 50 elemental damage to up to 24 enemies within 30ft of you every second. Each enemy hit will increase your outgoing damage by 10% up to a maximum of 100 stacks. Effect is dispelled when channel ends. This ability deals no damage to targets that have Cover from you.\n\nAugmented: 100% pushback immunity.`,
      },
	  "Spontaneous Combustion": {
        name: "Spontaneous Combustion",
        pos: "a5",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Sparking Swing now has a 75ft range and will generate 3 Combustion.`,
      },
      "Rancid Breath": {
        name: "Rancid Breath",
        pos: "g5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Breath of Fire now deals 14% SAP + 187 corporeal damage to enemies on cast.`,
      },
      "Fiery Reserves": {
        name: "Fiery Reserves",
        pos: "b6",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Blast that you apply will now generate 3 Combustion per stack whenever it expires.`,
      },
      "Fan the Flames": {
        name: "Fan the Flames",
        pos: "e6",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Detonate",
        arrows: [{ dir: "down", from: "e5", to: "e6" }],
        type: "career tactic",
        description: talentText`Ignite can now be cast on a target with Detonate. Detonate no longer dispels Ignite and will deal 7% + 80 elemental damage to the initial target for each stack of Blast they have.`,
      },
      "Bleed Fire": {
        name: "Bleed Fire",
        pos: "g7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Breath of Fire, Detonate, Fiery Blast, and Rain of Fire will now hit up to 24 enemies. Flaming Sword of Rhuin will now hit up to 8 other enemies within 30 feet of the target, but deals 50% less damage.`,
      },
      "Explosive Force": {
        name: "Explosive Force",
        pos: "a7",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Whenever you take Explosion damage, all groupmates and up to 9 enemies within 30 feet of you also take Explosion damage.`,
      },
      "Trailblazer": {
        name: "TrailBlazer",
        pos: "e8",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Burning Step",
        arrows: [{ dir: "right", from: "d8", to: "e8" }],
        type: "career tactic",
        description: talentText`The cooldown on Burning Step is reduced by 8 seconds.`,
      },
      "Tempered Blast": {
        name: "Tempered Blast",
        pos: "e3",
        icon: icons["abi_blast"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Blast now deals ${[
          35,
          70,
        ]}% additional damage.`,
      },
	  "Master of Sparks": {
        name: "Master of Sparks",
        pos: "b3",
        icon: icons["abi_sparks"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Sparking Swing will deal an additional ${[
          75,
          150,
		  225,
        ]}% damage.`,
      },
      "Improved Vigilance": {
        name: "Improved Vigilance",
        pos: "c5",
        icon: icons["abi_vigilance"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Vigilance now only reduces your outgoing damage by ${[
          75,
          60,
		  45,
        ]}%.`,
      },
      "Rhuination": {
        name: "Rhuination",
        pos: "d6",
        icon: icons["abi_flameofrhuin"],
        maxRank: 4,
        reqPoints: 15,
        type: "passive",
        description: talentText`Flaming Sword of Rhuin will now refund ${[
          2,
          4,
		  6,
		  8,
        ]} Combustion.`,
      },
      "Singeing Disinfectant": {
        name: "Singeing Disinfectant",
        pos: "h6",
        icon: icons["abi_cauterize"],
        maxRank: 3,
        reqPoints: 15,
        prereq: "Cauterize",
        arrows: [{ dir: "down", from: "h4", to: "h6" }],
        type: "passive",
        description: talentText`Cauterize will now remove up to ${[
          3,
          4,
		  5,
        ]} stacks of Blast from you and apply ${[
          3,
          4,
		  5,
        ]} stacks of Purity to you.`,
      },
	  "World on Fire": {
        name: "World on Fire",
        pos: "c7",
        icon: icons["abi_em_conflagrationofdoom"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Whenever your Breath of Fire, Detonate, or Ignite deals damage, you have a ${[
          10,
          20,
		  30,
        ]}% chance to gain a stack of a buff that lasts 5 seconds. Each stack grants 1% increased outgoing damage and 1% increased incoming damage. Maximum of 10 stacks.`,
      },
	  "Extra Crit": {
        name: "Extra Crit",
        pos: "e7",
        icon: icons["abi_extracrit"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Your chance to critically hit is increased by ${[
          2,
          4,
		  6,
        ]} `,
      },
	  "Oppressive Heat": {
        name: "Oppressive Heat",
        pos: "f8",
        icon: icons["abi_em_heavensfury"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`You gain sagacity equal to ${[
          5,
          10,
		  15,
		  20,
        ]}% of your Ranged Attack Power. ${[
          "",
          "The damage over time from Detonate can now critically hit.",
		  "The damage over time from Breath of Fire and Detonate can now critically hit.",
		  "The damage over time from Breath of Fire, Detonate, and Ignite can now critically hit.",
        ]}`,
      },
    },
  },
  "Firewarden": {
    name: "Firewarden",
    background: backgrounds["battlewizard"],
    icon: icons["archetype_offsupport"],
    talents: {
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "Emperor's Ward": {
        name: "Emperor's Ward",
        pos: "a2",
        icon: icons["tac_race_empire"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, you will gain a 400 absorb for 3 seconds.`,
      },
      "Sigmar's Favored": {
        name: "Sigmar's Favored",
        pos: "b2",
        icon: icons["tac_race_empire"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you receive a direct heal, you will also be healed for 120 + 8% wounds.`,
      },
      "Embrace the Flames": {
        name: "Embrace the Flames",
        pos: "c2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Unquenchable Fury is now applied to all groupmates within 100ft of you.`,
      },
      "Aqshy's Aegis": {
        name: "Aqshy's Aegis",
        pos: "d2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Explosion and Blast now deal 50% less damage to you and your groupmates.`,
      },
	  "Explosion and Blast": {
        name: "Explosion and Blast",
        pos: "a1",
        icon: icons["abi_blast"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Explosion stacks to 100 and you will gain 8% outgoing damage when above 89.\nExplosion deals 21% SAP + 280 elemental damage to you whenever you gain Combustion that takes you above 100. (1s ICD)\n\nBlast is a debuff that lasts for 4 seconds and stacks 10 times. At the end of the duration, target takes 8% SAP + 90 elemental damage per stack.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specstaff"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Firewardens equip staves.`,
      },
      "Melt Armor": {
        name: "Morale 1c",
        pos: "i4",
        icon: icons["morale_melt"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Target enemy gains 4 stacks of Reduced Armor.`,
      },
      "Burnout": {
        name: "Burnout",
        pos: "i5",
        icon: icons["morale_burnout"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain 100 Combustion and take Explosion damage.`,
      },
      "Emperor's Champion": {
        name: "Emperor's Champion",
        pos: "i7",
        icon: icons["morale_empchamp"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 20 seconds. For the duration, gain 250 ballistic skill, 250 intelligence, and 250 strength.`,
      },
      "Burning Head": {
        name: "Burning Head",
        pos: "i8",
        icon: icons["abi_em_burninghead"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Summons a Burning Head which charges forward affecting up to 24 allies and 96 enemies every second with a 3 second effect within 20 feet of its location.\n\nAllies gain 50% critical chance and 15 adrenaline per second. Enemies take 10% SAP + 150 elemental damage every second and gain 15 adrenaline per second.`,
      },
	  "Return Life": {
        name: "Return Life",
        pos: "f2",
        icon: icons["morale_returnlife"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Return target groupmate back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
	  "Explosive Impact": {
        name: "Explosive Impact",
        pos: "h2",
        icon: icons["morale_explosiveimpact"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 10 seconds. Whenever you hit a target with a single-target ability, you will deal 10% RAP + 150 corporeal damage and 10% SAP + 150 elemental damage to up to 24 enemies within 20ft of the target.`,
      },
      "Unleash the Winds": {
        name: "Unleash the Winds",
        pos: "i2",
        icon: icons["morale_unleashthewinds"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 96 enemies within a 20ft location you select are knocked straight up into the air.`,
      },
      "Pyroclastic Surge": {
        name: "Pyroclastic Surge",
        pos: "b1",
        icon: icons["abi_pyroclasticsurge"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 6% SAP + 133 corporeal damage to the target. You generate 40 action points and 5 Combustion.`,
      },
	  "Fireball": {
        name: "Fireball",
        pos: "c1",
        icon: icons["abi_fireball"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "36 action points",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        description: talentText`Deals 52% SAP + 716 elemental damage to target. You generate 10 Combustion.`,
      },
      "Burning Iron": {
        name: "Burning Iron",
        pos: "d1",
        icon: icons["abi_burningiron"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "1.5s cast",
        cooldown: "no cooldown",
        blue: "Costs 15 Combustion",
        description: talentText`Deals 19% SAP + 263 elemental damage to the target and applies 1 stack of Reduced Weapon Skill.`,
      },
      "Unquenchable Fury": {
        name: "Unquenchable Fury",
        pos: "e1",
        icon: icons["abi_unquench"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "100 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "15s cooldown",
        description: talentText`Apply a blessing to yourself for 60 seconds. Whenever you deal direct damage to a target, you will apply Blast to them and yourself.`,
      },
      "Fire Cage": {
        name: "Fire Cage",
        pos: "f1",
        icon: icons["abi_firecage"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Applies Rooted and Immovable to target enemy.\n\nRooted reduces your movement speed to 0 for 5 seconds. Immovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Ignite": {
        name: "Ignite",
        pos: "g1",
        icon: icons["abi_ignite"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "30 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Applies an ailment to target enemy for 15 seconds. You generate 3 Combustion and the target takes 8% SAP + 100 elemental damage every 3 seconds.\n\nCannot be applied to targets under the effect of Detonate.`,
      },
	  "Cauterize": {
        name: "Cauterize",
        pos: "h1",
        icon: icons["abi_cauterize"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 10 Combustion",
        description: talentText`Dispel 1 enchantment from and apply 1 stack of Purity to target enemy. Dispel 1 affliction from yourself. Dispel 2 stacks of Blast from yourself. Apply 2 stack of Purity to yourself.`,
      },
      "Smokescreen": {
        name: "Smokescreen",
        pos: "i1",
        icon: icons["abi_smokescreen"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "15s cooldown",
        description: talentText`Target enemy will deal 50% less damage to you for 15 seconds. This effect is removed if you hit the target with an ability.`,
      },
	  "Fiery Blast": {
        name: "Fiery Blast",
        pos: "a4",
        icon: icons["abi_fieryblast"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "75 action points",
        range: "100ft range",
        cast: "2.5s cast",
        cooldown: "no cooldown",
        description: talentText`Deals 21% SAP + 284 elemental damage to up to 9 enemies within a 30 foot area you select. Generates 2 Combustion per enemy hit.`,
      },
	  "Detonate": {
        name: "Detonate",
        pos: "h5",
        icon: icons["abi_detonate"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "60 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
		blue: "Requires Ignite on Target",
        description: talentText`Dispels Ignite from the target to apply a 12 second cripple to the target and up to 8 additional enemies within 20 feet of them. For the duration, target takes 5% SAP + 62 corporeal damage and you gain 1 Combustion every 3 seconds.`,
      },
	  "Playing With Fire": {
        name: "Playing With Fire",
        pos: "e6",
        icon: icons["abi_playingwithfire"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "1.5s cast",
        cooldown: "no cooldown",
        description: talentText`Applies an ailment to the target for 10 seconds. Whenever the target is healed, you will deal 13% SAP + 183 elemental damage to the healer and you generate 5 Combustion.`,
      },
	  "Rain of Fire": {
        name: "Rain of Fire",
        pos: "c7",
        icon: icons["abi_rainoffire"],
        maxRank: 1,
        reqPoints: 20,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "6.0s channel",
        cooldown: "no cooldown",
		blue: "Costs 60 Combustion",
        description: talentText`Deals 6% SAP + 87 elemental damage every second to up to 9 enemies within a 30 foot area you select.`,
      },
	  "Stop, Drop, and Roll": {
        name: "Stop, Drop, and Roll",
        pos: "f8",
        icon: icons["abi_stopdropandroll"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "75 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Applies Knocked-down and Unstoppable to target enemy.\n\nKnocked-down prevents all control of your character for 3 seconds. Unstoppable prevents application of Knocked-down and Staggered for 30 seconds.`,
      },
      "Shield of Aqshy": {
        name: "Shield of Aqshy",
        pos: "d9",
        icon: icons["abi_shieldofaqshy"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "20s cooldown",
        blue: "Costs 40 Combustion",
        description: talentText`Applies a buff for 5s and a blessing for 10s to each groupmate within 100 feet. For the buff duration, groupmate and up to 9 enemies within 30 feet of them gain a stack of Blast every second. For the blessing duration, groupmate gains 2000 elemental resistance.`,
      },
      "Spreading Flames": {
        name: "Spreading Flames",
        pos: "f9",
        icon: icons["abi_spreadingflames"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Applys a debuff to the target enemy for 2s. Deals 6% + 20 elemental damage every 1 second. At the end of the duration, applies stage 2 of the debuff to up to 6 other enemies within 20ft. There are 5 stages, each stacks up to 10x.`,
      },
	  "Firebrand": {
        name: "Firebrand",
        pos: "b5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Burning Iron now applies 1 stack of Reduced Block and 1 stack of Reduced Hardiness.`,
      },
	  "Taste of Fire": {
        name: "Taste of Fire",
        pos: "c5",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Fireball now has a 1.5s cast time, deals 50% less damage, and generates 15 Combustion.`,
      },
	  "Bleed Fire": {
        name: "Bleed Fire",
        pos: "b7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Breath of Fire, Detonate, Fiery Blast, and Rain of Fire will now hit up to 24 enemies. Flaming Sword of Rhuin will now hit up to 8 other enemies within 30 feet of the target, but deals 50% less damage.`,
      },
	  "Fan the Flames": {
        name: "Fan the Flames",
        pos: "h6",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Detonate",
        arrows: [{ dir: "down", from: "h5", to: "h6" }],
        type: "career tactic",
        description: talentText`Ignite can now be cast on a target with Detonate. Detonate no longer dispels Ignite and will deal 7% + 80 elemental damage to the initial target for each stack of Blast they have.`,
      },
	  "Exquisite Firecraft": {
        name: "Exquisite Firecraft",
        pos: "a7",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Cauterize will now also dispel one blessing from the enemy. Cauterize's effects that targetted yourself will now apply to your defensive target instead.`,
      },
	  "You Get Burned": {
        name: "You Get Burned",
        pos: "e8",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Playing With Fire",
        arrows: [{ dir: "down", from: "e6", to: "e8" }],
        type: "career tactic",
        description: talentText`Playing With Fire is now a cripple. Whenever the target is healed, the target will gain 1 stack of Reduced Healing Received, and the healer will gain 1 stack of Reduced Willpower.`,
      },
	  "Scorching Ignition": {
        name: "Scorching Ignition",
        pos: "h7",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Ignite will now apply 1 stack of Blast and 1 stack of Reduced Elemental Resistance to the target each time it deals damage.`,
      },
	  "Firestarter": {
        name: "Firestarter",
        pos: "e3",
        icon: icons["abi_blast"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Blast stacks cause allies to gain ${[
          1,
          2,
        ]} adrenaline per second per stack.`,
      },
	  "Red Tide": {
        name: "Red Tide",
        pos: "b3",
        icon: icons["abi_pyroclasticsurge"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Pyroclastic surge now deals ${[
          50,
          100,
		  150,
        ]}% additional damage.`,
      },
	  "Hardened Casting": {
        name: "Hardened Casting",
        pos: "g5",
        icon: icons["itm_ch_charredsoulgem"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`You gain ${[
          15,
          30,
          50,
        ]}% pushback immunity`,
      },
	  "Fiery Medley": {
        name: "Fiery Medley",
        pos: "a6",
        icon: icons["abi_em_slowburn"],
        maxRank: 5,
        reqPoints: 15,
		prereq: "Fiery Blast",
        arrows: [{ dir: "down", from: "a4", to: "a6" }],
        type: "passive",
        description: talentText`Fireball has a ${[
          10,
          20,
          30,
		  40,
		  50,
        ]}% and Rain of Fire has a ${[
          2,
          4,
          6,
		  8,
		  10,
        ]}% chance each time they deal damage to make the next Fiery Blast cast within 10 seconds be instant cast.`,
      },
	  "Explosive Exercise": {
        name: "Explosive Exercise",
        pos: "c6",
        icon: icons["abi_fuelfire"],
        maxRank: 3,
        reqPoints: 15,
        type: "passive",
        description: talentText`Whenever you deal periodic damage you have a ${[
          33,
          66,
          100,
        ]}% chance to give 1 action point to all groupmates within 100 feet.`,
      },
	  "Cackling Fire-raiser": {
        name: "Cackling Fire-raiser",
        pos: "g7",
        icon: icons["abi_em_firestorm"],
        maxRank: 5,
        reqPoints: 20,
        type: "passive",
        description: talentText`Gain ${[
          2,
          4,
          6,
		  8,
		  10,
        ]} adrenaline per second while in combat.`,
      },
	  "Blinding Smoke": {
        name: "Blinding Smoke",
        pos: "d8",
        icon: icons["abi_em_ruinanddestruction"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`You have a ${[
          10,
          30,
          60,
		  100,
        ]}% chance whenever you critically hit an enemy to apply one stack of Reduced Dodge to them.`,
      },
    },
  },
};
