import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/empire"),
);
const icons = requireAll(require.context("../../assets/icons/empire"));

export const data: TalentData = {
  "Arsonist": {
    name: "Arsonist",
    background: backgrounds["hothead"],
    icon: icons["archetype_dps"],
    talents: {
      "Motivated": {
        name: "Motivated",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "b2",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 5 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 20 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "b4",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "b6",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a6",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a8",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Increases your mass by 1.`,
      },
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a9",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "b5",
        icon: icons["stat_agl"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`Increases your Agility by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "b7",
        icon: icons["stat_bal"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "b3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e7",
        icon: icons["stat_int"],
        maxRank: 4,
        reqPoints: 30,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "h7",
        icon: icons["stat_str"],
        maxRank: 4,
        reqPoints: 30,
        description: talentText`Increases your Strength by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "e5",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "h3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "h5",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "e3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 2.`,
      },
      "Disengage": {
        name: "Disengage",
        pos: "i2",
        icon: icons["morale_disengage"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`level 1\n30ft range\n360 adrenaline\ninstant cast\nability\n\nYou knock yourself back away from target enemy.`,
      },
      "Broad Swings": {
        name: "Broad Swings",
        pos: "i4",
        icon: icons["morale_broadswings"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`level 2\n720 adrenaline\ninstant cast\nability\n\nYou gain a  buff for 10 seconds. Your single target abilities will target two additional enemies within 15ft in front of you.`,
      },
      "Explosive Impact": {
        name: "Explosive Impact",
        pos: "i6",
        icon: icons["morale_explosiveimpact"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`level 3\n1800 adrenaline\ninstant cast\nability\n\nGain a buff for 10 seconds. Whenever you hit a target with a single-target ability, you will deal 10% RAP + 150 corporeal damage and 10% SAP + 150 elemental damage to up to 24 enemies within 20ft of the target.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i8",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 4\n3600 adrenaline\ninstant cast\nability\n\nAll groupmates within 100ft gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "Emperor's Champion": {
        name: "Emperor's Champion",
        pos: "b8",
        icon: icons["morale_empchamp"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 3\n1800 adrenaline\ninstant cast\nability\n\nYou gain a buff for 20 seconds. You gain 250 ballistic skill, 250 intelligence, and 250 strength.`,
      },
      "Melt Armor": {
        name: "Morale 1c",
        pos: "h2",
        icon: icons["morale_melt"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`level 1\n100ft range\n360 adrenaline\ninstant cast\nability\n\nTarget enemy gains 6 stacks of Reduced Armor.`,
      },
      "Burnout": {
        name: "Burnout",
        pos: "h4",
        icon: icons["morale_burnout"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`level 2\n720 adrenaline\ninstant cast\nability\n\nYou gain 100 Combustion and take Explosion damage.`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "h6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`level 1\n100ft range\n360 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "h8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 2\n100ft range\n720 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`level 4\n100ft range\n3600 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Emperor's Ward": {
        name: "Emperor's Ward",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you use a basic attack, you will gain a 400 absorb for 3 seconds.`,
      },
      "Sigmar's Favored": {
        name: "Sigmar's Favored",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you receive a direct heal, you will also be healed for 120 + 8% wounds.`,
      },
      "Tempered Blast": {
        name: "Tempered Blast",
        pos: "b1",
        icon: icons["abi_blast"],
        maxRank: 2,
        reqPoints: 0,
        description: talentText`Explosion deals 20% SAP + 300 elemental damage whenever you gain Combustion when you have 100. (1s ICD)\n\nBlast is a debuff that lasts for 4 seconds and stacks 10 times. At the end of the duration, target takes 6% SAP elemental damage per stack.\n\nTaking this passive increases the damage of Blast by ${[
          3,
          6,
        ]}% MAP.`,
      },
      "Unquenchable Fury": {
        name: "Unquenchable Fury",
        pos: "c1",
        icon: icons["abi_unquench"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`100 AP\ninstant cast\n15s CD\naspell\n\nApply a blessing to yourself for 60 seconds. Whenever you deal direct damage to a target, you will apply Blast to them and yourself.`,
      },
      "Embrace the Flames": {
        name: "Embrace the Flames",
        pos: "c2",
        icon: icons["tac_class_2"],
        maxRank: 1,
        reqPoints: 5,
        prereq: "Unquenchable Fury",
        arrows: [{ dir: "down", from: "c1", to: "c2" }],
        description: talentText`Unquenchable Fury is now applied to all groupmates within 100ft of you.`,
      },
      "Aqshy's Aegis": {
        name: "Aqshy's Aegis",
        pos: "d1",
        icon: icons["tac_class_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Unquenchable Fury",
        arrows: [{ dir: "right", from: "c1", to: "d1" }],
        description: talentText`Explosion and Blast now deal 50% less damage to you and your groupmates.`,
      },
      "Flaming Sword of Rhuin": {
        name: "Flaming Sword of Rhuin",
        pos: "e1",
        icon: icons["abi_flameofrhuin"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\n25 CBN\ninstant cast\nskill\n\nDeals 35% MAP + 275 corporeal damage to target enemy.`,
      },
      "Rhuination": {
        name: "Rhuination",
        pos: "e2",
        icon: icons["abi_flameofrhuin"],
        maxRank: 2,
        reqPoints: 5,
        prereq: "Flaming Sword of Rhuin",
        arrows: [{ dir: "down", from: "e1", to: "e2" }],
        description: talentText`Flaming Sword of Rhuin now costs ${[
          3,
          6,
        ]} less Combustion.`,
      },
      "Fuel for the Fire": {
        name: "Fuel for the Fire",
        pos: "f1",
        icon: icons["abi_fuelfire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`instant cast\nability\n\nYou take Explosion damage and gain 20 Combustion. This ability does not trigger the GCD.`,
      },
      "Sparking Swing": {
        name: "Sparking Swing",
        pos: "g1",
        icon: icons["abi_sparks"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\ninstant cast\nskill\n\nDeals 160 elemental damage to target enemy. You generate 30 action points.`,
      },
      "Master of Sparks": {
        name: "Master of Sparks",
        pos: "h1",
        icon: icons["abi_sparks"],
        maxRank: 2,
        reqPoints: 0,
        prereq: "Sparking Swing",
        arrows: [{ dir: "right", from: "g1", to: "h1" }],
        description: talentText`Sparking Swing will deal an additional ${[
          8,
          15,
        ]}% MAP elemental damage.`,
      },
      "Spontaneous Combustion": {
        name: "Spontaneous Combustion",
        pos: "g2",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 5,
        prereq: "Sparking Swing",
        arrows: [{ dir: "down", from: "g1", to: "g2" }],
        description: talentText`Sparking Swing now has a 75ft range and will generate 3 Combustion.`,
      },
      "Vigilance": {
        name: "Vigilance",
        pos: "d2",
        icon: icons["abi_vigilance"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`instant cast\n60s CD\nability\n\nAll damage you take is reduced by 50% but all damage you deal is reduced by 90% for 5 seconds.`,
      },
      "Improved Vigilance": {
        name: "Improved Vigilance",
        pos: "d4",
        icon: icons["abi_vigilance"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Vigilance",
        arrows: [{ dir: "down", from: "d2", to: "d4" }],
        description: talentText`Vigilance now only reduces your outgoing damage by 75%.`,
      },
      "Fire Cage": {
        name: "Fire Cage",
        pos: "f2",
        icon: icons["abi_firecage"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`30ft range\n40 AP\ninstant cast\n20s CD\nspell\n\nApplies Rooted and Immovable to target enemy.\n\nRooted reduces your movement speed to 0 for 5 seconds. Immovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Ignite": {
        name: "Ignite",
        pos: "c4",
        icon: icons["abi_ignite"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`100ft range\n30 AP\ninstant cast\naspell\n\nApplies an affliction to target enemy for 15 seconds. You generate 3 Combustion and the target takes 11% SAP + 78 elemental damage every 3 seconds.\n\nCannot be applied to targets under the effect of Detonate.`,
      },
      "Detonate": {
        name: "Detonate",
        pos: "c6",
        icon: icons["abi_detonate"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Ignite",
        arrows: [{ dir: "down", from: "c4", to: "c6" }],
        description: talentText`100ft range\n60 AP\ninstant cast\nspell\n\nRequires Ignite on the target. Dispels Ignite from the target to apply a cripple to the target and up to 8 additional enemies within 20ft of them for 12 seconds. You generate 1 Combustion and the target takes 5% SAP + 30 corporeal damage every 3 seconds.`,
      },
      "Fan the Flames": {
        name: "Fan the Flames",
        pos: "d6",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Detonate",
        arrows: [{ dir: "right", from: "c6", to: "d6" }],
        description: talentText`Ignite can now be cast on a target with Detonate. Detonate no longer dispels Ignite.`,
      },
      "Cauterize": {
        name: "Cauterize",
        pos: "f4",
        icon: icons["abi_cauterize"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`100ft range\n10 CBN\ninstant cast\n\nspell\n\nDispel 1 enchantment from target enemy. Dispel 1 affliction from yourself. Dispel 2 stacks of Blast from yourself but refresh the stack duration.`,
      },
      "Cascading Fire Cloak": {
        name: "Cascading Fire Cloak",
        pos: "g4",
        icon: icons["abi_flameshield"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`50 AP\ninstant cast\nspell\n\nYou gain a buff for 15 seconds. For the duration, whenever you use Sparks or Flaming Sword of Rhuin you will gain 1 stack of Enhanced Armor and 1 stack of Enhanced Corporeal Resistance.\n\nFor the duration, whenever an enemy deals direct damage to you, they will gain a stack of Blast and you will gain 1 stack of Reduced Armor or 1 stack of Reduced Corporeal Resistance.`,
      },
      "Bleed Fire": {
        name: "Bleed Fire",
        pos: "g8",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Cascading Fire Cloak",
        arrows: [{ dir: "down", from: "g4", to: "g8" }],
        description: talentText`Cascading Fire Cloak no longer grants stacks of Enhanced or Reduced Armor/Corporeal Resistance, but it will deal 13% MAP + 100 elemental damage to enemies when it applies Blast.`,
      },
      "Breath of Fire": {
        name: "Breath of Fire",
        pos: "e6",
        icon: icons["abi_flamebreath"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`80 AP\n1.5s cast\nspell\n\nApplies an affliction to up to 9 enemies within 30ft in front of you for 9 seconds. You generate 2 Combustion and the target takes 5% SAP + 18 elemental damage every 3 seconds. You can cast while moving.`,
      },
      "Rancid Breath": {
        name: "Rancid Breath",
        pos: "f6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Breath of Fire",
        arrows: [{ dir: "right", from: "e6", to: "f6" }],
        description: talentText`Breath of Fire now deals 8% SAP + 60 direct corporeal damage to enemies on cast and will now hit up to 15 enemies.`,
      },
      "Fiery Reserves": {
        name: "Fiery Reserves",
        pos: "c8",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Blast will now generate 2 Combustion per stack whenever it expires.`,
      },
      "Burning Step": {
        name: "Burning Step",
        pos: "d8",
        icon: icons["abi_firestep"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`25 CBN\ninstant cast\n20s CD\nspell\n\nYou gain 100% dodge and 100% movement speed for 1 second. You also gain 3 stacks of Blast.`,
      },
      "TrailBlazer": {
        name: "TrailBlazer",
        pos: "e8",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Burning Step",
        arrows: [{ dir: "right", from: "d8", to: "e8" }],
        description: talentText`The cooldown on Burning Step is reduced by 10 seconds.`,
      },
      "Explosive Force": {
        name: "Explosive Force",
        pos: "f8",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Whenever you take Explosion damage, all groupmates and up to 9 enemies within 30ft of you also take Explosion damage.`,
      },
      "Scorched Earth": {
        name: "Scorched Earth",
        pos: "d9",
        icon: icons["abi_scorched"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`10 CBN\ninstant cast\nspell\n\nRemoves all of your combustion and deals 4% MAP + 20 corporeal damage per 10 Combustion consumed to up to 9 enemies within 30ft of you.\n\nAugmented: Does not consume Combustion.`,
      },
      "Supernova": {
        name: "Supernova",
        pos: "f9",
        icon: icons["abi_supernova"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`150 AP\n5.0s channel\n30s CD\nspell\n\nDeal 10% SAP + 50 elemental damage to up to 24 enemies within 30ft of you every second. Each enemy hit will increase your outgoing damage by 10% up to a maximum of 100 stacks. Effect is dispelled when channel ends. This ability deals no damage to targets that have Cover from you.\n\nAugmented: 100% pushback immunity,`,
      },
    },
  },
  "Pyromancer": {
    name: "Pyromancer",
    background: backgrounds["pyromancer"],
    icon: icons["archetype_dps"],
    talents: {
      "Motivated": {
        name: "Motivated",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "b2",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 5 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 20 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "b4",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "b6",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a6",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a8",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Increases your mass by 1.`,
      },
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a9",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "b5",
        icon: icons["stat_agl"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`Increases your Agility by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "b7",
        icon: icons["stat_bal"],
        maxRank: 4,
        reqPoints: 30,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "b3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e7",
        icon: icons["stat_int"],
        maxRank: 5,
        reqPoints: 30,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "h7",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Strength by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "e5",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "h3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "h5",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "e3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Your range is increased by 20%.`,
      },
      "Disengage": {
        name: "Disengage",
        pos: "i2",
        icon: icons["morale_disengage"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`level 1\n30ft range\n360 adrenaline\ninstant cast\nability\n\nYou knock yourself back away from target enemy.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "i4",
        icon: icons["morale_focusedmind"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`level 2\n720 adrenaline\ninstant cast\nability\n\nYou gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Explosive Impact": {
        name: "Explosive Impact",
        pos: "i6",
        icon: icons["morale_explosiveimpact"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`level 3\n1800 adrenaline\ninstant cast\nability\n\nGain a tier3 buff for 10 seconds. Whenever you hit a target with a single-target ability, you will deal 10% RAP + 150 corporeal damage and 10% SAP + 150 elemental damage to up to 24 enemies within 20ft of the target.`,
      },
      "Unleash the Winds": {
        name: "Unleash the Winds",
        pos: "i8",
        icon: icons["morale_unleashthewinds"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 4\n100ft range\n3600 adrenaline\ninstant cast\nability\n\nUp to 96 enemies within a 20ft location are knocked straight up into the air.`,
      },
      "Emperor's Champion": {
        name: "Emperor's Champion",
        pos: "b8",
        icon: icons["morale_empchamp"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 3\n1800 adrenaline\ninstant cast\nability\n\nYou gain a buff for 20 seconds. You gain 250 ballistic skill, 250 intelligence, and 250 strength.`,
      },
      "Melt Armor": {
        name: "Morale 1c",
        pos: "h2",
        icon: icons["morale_melt"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`level 1\n100ft range\n360 adrenaline\ninstant cast\nability\n\nTarget enemy gains 6 stacks of Reduced Armor.`,
      },
      "Burnout": {
        name: "Burnout",
        pos: "h4",
        icon: icons["morale_burnout"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`level 2\n720 adrenaline\ninstant cast\nability\n\nYou gain 100 Combustion and take Explosion damage.`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "h6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`level 1\n100ft range\n360 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "h8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 2\n100ft range\n720 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`level 4\n100ft range\n3600 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Emperor's Ward": {
        name: "Emperor's Ward",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you use a basic attack, you will gain a 400 absorb for 3 seconds.`,
      },
      "Sigmar's Favored": {
        name: "Sigmar's Favored",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you receive a direct heal, you will also be healed for 120 + 8% wounds.`,
      },
      "Explosive Action": {
        name: "Explosive Action",
        pos: "b1",
        icon: icons["abi_blast"],
        maxRank: 2,
        reqPoints: 0,
        description: talentText`Explosion deals 20% SAP + 300 elemental damage whenever you gain Combustion when you have 100. (1s ICD)\n\nBlast is a debuff that lasts for 4 seconds and stacks 10 times. At the end of the duration, target takes 6% SAP elemental damage per stack.\n\nTaking this passive causes you to gain ${[
          10,
          20,
        ]} action points whenever you take Explosion damage.`,
      },
      "Unquenchable Fury": {
        name: "Unquenchable Fury",
        pos: "c1",
        icon: icons["abi_unquench"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`100 AP\ninstant cast\n15s CD\naspell\n\nApply a blessing to yourself for 60 seconds. Whenever you deal direct damage to a target, you will apply Blast to them and yourself.`,
      },
      "Embrace the Flames": {
        name: "Embrace the Flames",
        pos: "c2",
        icon: icons["tac_class_2"],
        maxRank: 1,
        reqPoints: 5,
        prereq: "Unquenchable Fury",
        arrows: [{ dir: "down", from: "c1", to: "c2" }],
        description: talentText`Unquenchable Fury is now applied to all groupmates within 100ft of you.`,
      },
      "Aqshy's Aegis": {
        name: "Aqshy's Aegis",
        pos: "d1",
        icon: icons["tac_class_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Unquenchable Fury",
        arrows: [{ dir: "right", from: "c1", to: "d1" }],
        description: talentText`Explosion and Blast now deal 50% less damage to you and your groupmates.`,
      },
      "Withering Heat": {
        name: "Withering Heat",
        pos: "e1",
        icon: icons["abi_witheringheat"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`25 CBN\ninstant cast\nspell\n\nConsumes all your Combustion to give you a buff for 10 seconds. For the duration, each skill you cast deals Explosion damage to you and you will gain resistance penetration based on Combustion spent.\n25 CBN: 10% WIL + 25\n50 CBN: 30% WIL + 60\n75 CBN: 60% WIL + 105\n100 CBN: 100% WIL + 160`,
      },
      "Fireball": {
        name: "Fireball",
        pos: "f1",
        icon: icons["abi_fireball"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`100ft range\n50 AP\n3.0s cast\nspell\n\nDeals 45% SAP + 225 elemental damage to target. You generate 15 Combustion.`,
      },
      "Meltdown": {
        name: "Meltdown",
        pos: "f2",
        icon: icons["abi_meltdown"],
        maxRank: 1,
        reqPoints: 5,
        prereq: "Fireball",
        arrows: [{ dir: "down", from: "f1", to: "f2" }],
        description: talentText`100ft range\n20 CBN\ninstant cast\nspell\n\nDeals 19% SAP + 150 corporeal damage to the target.`,
      },
      "Flash Fire": {
        name: "Flash Fire",
        pos: "f8",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Meltdown",
        arrows: [{ dir: "down", from: "f2", to: "f8" }],
        description: talentText`Whenever you cast Meltdown, you will gain 1 stack of a blessing for 8 seconds, stacking up to 3 times. Fireball will have a 50% reduced cast time and remove 1 stack.`,
      },
      "Pyroclastic Surge": {
        name: "Pyroclastic Surge",
        pos: "g1",
        icon: icons["abi_pyroclasticsurge"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`100ft range\n2.0s cast\nspell\n\nDeals 160 corporeal damage to the target. You generate 40 action points and 5 Combustion.`,
      },
      "Red Tide": {
        name: "Red Tide",
        pos: "h1",
        icon: icons["abi_pyroclasticsurge"],
        maxRank: 2,
        reqPoints: 0,
        prereq: "Pyroclastic Surge",
        arrows: [{ dir: "right", from: "g1", to: "h1" }],
        description: talentText`Pyroclastic Surge will deal ${[
          8,
          15,
        ]}% SAP additional damage.`,
      },
      "Smokescreen": {
        name: "Smokescreen",
        pos: "d2",
        icon: icons["abi_smokescreen"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`150ft range\ninstant cast\n15.0s CD\nability\n\nTarget enemy will deal 50% less damage to you for 15 seconds. This effect is removed if you hit the target with an ability.`,
      },
      "Fire Cage": {
        name: "Fire Cage",
        pos: "e2",
        icon: icons["abi_firecage"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`30ft range\n40 AP\ninstant cast\n20s CD\nspell\n\nApplies Rooted and Immovable to target enemy.\n\nRooted reduces your movement speed to 0 for 5 seconds. Immovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Sear": {
        name: "a",
        pos: "g2",
        icon: icons["abi_sear"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`100ft range\n80 AP\n1.0s cast\nspell\n\nDeals 19% SAP + 150 elemental damage to target and applies 2 stacks of Blast. You will take Explosion damage and gain 5 Combustion.`,
      },
      "Ignite": {
        name: "Ignite",
        pos: "c4",
        icon: icons["abi_ignite"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`100ft range\n30 AP\ninstant cast\naspell\n\nApplies an affliction to target enemy for 15 seconds. You generate 3 Combustion and the target takes 11% SAP + 78 elemental damage every 3 seconds.\n\nCannot be applied to targets under the effect of Detonate.`,
      },
      "Scorching Ignition": {
        name: "Scorching Ignition",
        pos: "c8",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Ignite",
        arrows: [{ dir: "down", from: "c4", to: "c8" }],
        description: talentText`Ignite will now apply 1 stack of Blast and 1 stack of Reduced Elemental Resistance to the target each time it deals damage.`,
      },
      "Critical Mass": {
        name: "Critical Mass",
        pos: "d4",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever you cast an ability, you will gain 8% critical chance for 5 seconds. This stacks until you deal a critical hit at which point all stacks are removed.`,
      },
      "Fire of Battle": {
        name: "Fire of Battle",
        pos: "g4",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`You gain 50% pushback immunity but the cast time of Pyroclastic Surge and Sear is increased by 0.25s.`,
      },
      "Playing With Fire": {
        name: "Playing With Fire",
        pos: "d6",
        icon: icons["abi_playingwithfire"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`100ft range\n50 AP\n1.5s cast\nspell\n\nApplies an affliction to the target for 10 seconds. Whenever the target is healed, you will deal 15% SAP + 100 elemental damage to the healer and you generate 5 Combustion.`,
      },
      "Devouring Flames": {
        name: "Devouring Flames",
        pos: "e6",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`Whenever you critically hit an enemy, you and the target take Explosion damage.`,
      },
      "Boiling Blood": {
        name: "Boiling Blood",
        pos: "g6",
        icon: icons["abi_boilingblood"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`100ft range\n40 AP\ninstant cast\nspell\n\nApplies a cripple to the target for 5 seconds. At the end of the duration, target will take 25% SAP + 200 corporeal damage. You generate 5 Combustion`,
      },
      "Rolling Boil": {
        name: "Rolling Boil",
        pos: "g8",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Boiling Blood",
        arrows: [{ dir: "down", from: "g6", to: "g8" }],
        description: talentText`Boiling Blood will prevent the target from gaining stacks of Blast for the duration.`,
      },
      "Fiery Reserves": {
        name: "Fiery Reserves",
        pos: "d8",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Blast will now generate 2 Combustion per stack whenever it expires.`,
      },
      "Funnel Power": {
        name: "Funnel Power",
        pos: "e8",
        icon: icons["abi_funnelpower"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`30 CBN\ninstant cast\nspell\n\nYou take Explosion damage and gain 1 stack of Enhanced Critical Damage.`,
      },
      "Fireball Barrage": {
        name: "Fireball Barrage",
        pos: "d9",
        icon: icons["abi_fireballbarrage"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`100ft range\n75 AP\n3.0s channel\nspell\n\nDeals 30% SAP + 150 elemental damage to the target and up to 2 additional enemies within 20ft of them every 1.5 seconds.`,
      },
      "Spreading Flames": {
        name: "Spreading Flames",
        pos: "f9",
        icon: icons["abi_spreadingflames"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`75ft range\n150 AP\n2.0s cast\n30s CD\nspell\n\nApplys a debuff to the target enemy for 2s. Deals 6% + 20 elemental damage every 1 second. At the end of the duration, applies stage 2 of the debuff to up to 6 other enemies within 20ft. There are 5 stages, each stacks up to 10x.`,
      },
    },
  },
  "Battle Wizard": {
    name: "Battle Wizard",
    background: backgrounds["battlewizard"],
    icon: icons["archetype_offsupport"],
    talents: {
      "Motivated": {
        name: "Motivated",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "b2",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 5 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 20 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "b4",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "b6",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a6",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a8",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Increases your mass by 1.`,
      },
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a9",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "b5",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases your Agility by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "b7",
        icon: icons["stat_bal"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "b3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e7",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "h7",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 30,
        description: talentText`Increases your Strength by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "e5",
        icon: icons["stat_tou"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "h3",
        icon: icons["stat_wil"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "h5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "e3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Your range is increased by 20%.`,
      },
      "Return Life": {
        name: "Return Life",
        pos: "i2",
        icon: icons["morale_returnlife"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`level 1\n100ft range\n360 adrenaline\ninstant cast\nability\n\nReturn target groupmate back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "i4",
        icon: icons["morale_focusedmind"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`level 2\n720 adrenaline\ninstant cast\nability\n\nYou gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Explosive Impact": {
        name: "Explosive Impact",
        pos: "i6",
        icon: icons["morale_explosiveimpact"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`level 3\n1800 adrenaline\ninstant cast\nability\n\nGain a tier3 buff for 10 seconds. Whenever you hit a target with a single-target ability, you will deal 10% RAP + 150 corporeal damage and 10% SAP + 150 elemental damage to up to 24 enemies within 20ft of the target.`,
      },
      "Unleash the Winds": {
        name: "Unleash the Winds",
        pos: "i8",
        icon: icons["morale_unleashthewinds"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 4\n100ft range\n3600 adrenaline\ninstant cast\nability\n\nUp to 96 enemies within a 20ft location are knocked straight up into the air.`,
      },
      "Emperor's Champion": {
        name: "Emperor's Champion",
        pos: "b8",
        icon: icons["morale_empchamp"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 3\n1800 adrenaline\ninstant cast\nability\n\nYou gain a buff for 20 seconds. You gain 250 ballistic skill, 250 intelligence, and 250 strength.`,
      },
      "Melt Armor": {
        name: "Morale 1c",
        pos: "h2",
        icon: icons["morale_melt"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`level 1\n100ft range\n360 adrenaline\ninstant cast\nability\n\nTarget enemy gains 6 stacks of Reduced Armor.`,
      },
      "Burnout": {
        name: "Burnout",
        pos: "h4",
        icon: icons["morale_burnout"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`level 2\n720 adrenaline\ninstant cast\nability\n\nYou gain 100 Combustion and take Explosion damage.`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "h6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`level 1\n100ft range\n360 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "h8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 2\n100ft range\n720 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`level 4\n100ft range\n3600 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Emperor's Ward": {
        name: "Emperor's Ward",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you use a basic attack, you will gain a 400 absorb for 3 seconds.`,
      },
      "Sigmar's Favored": {
        name: "Sigmar's Favored",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you receive a direct heal, you will also be healed for 120 + 8% wounds.`,
      },
      "Unquenchable Fury": {
        name: "Unquenchable Fury",
        pos: "c1",
        icon: icons["abi_unquench"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`100 AP\ninstant cast\n15s CD\naspell\n\nApply a blessing to yourself for 60 seconds. Whenever you deal direct damage to a target, you will apply Blast to them and yourself.`,
      },
      "Embrace the Flames": {
        name: "Embrace the Flames",
        pos: "c2",
        icon: icons["tac_class_2"],
        maxRank: 1,
        reqPoints: 5,
        prereq: "Unquenchable Fury",
        arrows: [{ dir: "down", from: "c1", to: "c2" }],
        description: talentText`Unquenchable Fury is now applied to all groupmates within 100ft of you.`,
      },
      "Aqshy's Aegis": {
        name: "Aqshy's Aegis",
        pos: "d1",
        icon: icons["tac_class_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Unquenchable Fury",
        arrows: [{ dir: "right", from: "c1", to: "d1" }],
        description: talentText`Explosion and Blast now deal 50% less damage to you and your groupmates.`,
      },
      "Fireball": {
        name: "Fireball",
        pos: "f1",
        icon: icons["abi_fireball"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`100ft range\n50 AP\n3.0s cast\nspell\n\nDeals 45% SAP + 225 elemental damage to target. You generate 15 Combustion.`,
      },
      "Taste of Fire": {
        name: "Taste of Fire",
        pos: "e2",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 5,
        prereq: "Fireball",
        arrows: [{ dir: "down", from: "e1", to: "e2" }],
        description: talentText`Fireball now has a 1.5s cast time, deals 50% less damage, and generates 20 Combustion.`,
      },
      "Burning Iron": {
        name: "Burning Iron",
        pos: "f1",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`100ft range\n15 CBN\n1.5s cast\nspell\n\nDeals 25% SAP + 200 elemental damage to the target and applies 1 stack of Reduced Weapon Skill.`,
      },
      "Firebrand": {
        name: "Firebrand",
        pos: "f2",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 5,
        prereq: "Burning Iron",
        arrows: [{ dir: "down", from: "f1", to: "f2" }],
        description: talentText`Burning Iron now applies 1 stack of Reduced Block and 1 stack of Reduced Hardiness.`,
      },
      "Pyroclastic Surge": {
        name: "Pyroclastic Surge",
        pos: "g1",
        icon: icons["abi_pyroclasticsurge"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`100ft range\n2.0s cast\nspell\n\nDeals 160 corporeal damage to the target. You generate 40 action points and 5 Combustion.`,
      },
      "Red Tide": {
        name: "Red Tide",
        pos: "h1",
        icon: icons["abi_pyroclasticsurge"],
        maxRank: 2,
        reqPoints: 0,
        prereq: "Pyroclastic Surge",
        arrows: [{ dir: "right", from: "g1", to: "h1" }],
        description: talentText`Pyroclastic Surge will deal ${[
          8,
          15,
        ]}% SAP additional damage.`,
      },
      "Smokescreen": {
        name: "Smokescreen",
        pos: "d2",
        icon: icons["abi_smokescreen"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`150ft range\ninstant cast\n15.0s CD\nability\n\nTarget enemy will deal 50% less damage to you for 15 seconds. This effect is removed if you hit the target with an ability.`,
      },
      "Fire Cage": {
        name: "Fire Cage",
        pos: "g2",
        icon: icons["abi_firecage"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`30ft range\n40 AP\ninstant cast\n20s CD\nspell\n\nApplies Rooted and Immovable to target enemy.\n\nRooted reduces your movement speed to 0 for 5 seconds. Immovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Ignite": {
        name: "Ignite",
        pos: "c4",
        icon: icons["abi_ignite"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`100ft range\n30 AP\ninstant cast\naspell\n\nApplies an affliction to target enemy for 15 seconds. You generate 3 Combustion and the target takes 11% SAP + 78 elemental damage every 3 seconds.\n\nCannot be applied to targets under the effect of Detonate.`,
      },
      "Scorching Ignition": {
        name: "Scorching Ignition",
        pos: "c8",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Ignite",
        arrows: [{ dir: "down", from: "c4", to: "c8" }],
        description: talentText`Ignite will now apply 1 stack of Blast and 1 stack of Reduced Elemental Resistance to the target each time it deals damage.`,
      },
      "Detonate": {
        name: "Detonate",
        pos: "d6",
        icon: icons["abi_detonate"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Ignite",
        arrows: [{ dir: "right-down", from: "c6", to: "d6" }],
        description: talentText`100ft range\n60 AP\ninstant cast\nspell\n\nRequires Ignite on the target. Dispels Ignite from the target to apply a cripple to the target and up to 8 additional enemies within 20ft of them for 12 seconds. You generate 1 Combustion and the target takes 5% SAP + 30 corporeal damage every 3 seconds.`,
      },
      "Fan the Flames": {
        name: "Fan the Flames",
        pos: "e6",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Detonate",
        arrows: [{ dir: "right", from: "d6", to: "e6" }],
        description: talentText`Ignite can now be cast on a target with Detonate. Detonate no longer dispels Ignite.`,
      },
      "Stop, Drop, and Roll": {
        name: "Stop, Drop, and Roll",
        pos: "d4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`100ft range\n80 AP\ninstant cast\n15s CD\nspell\n\nApplies Knocked-down and Unstoppable to target enemy.\n\nKbocked-down prevents all control of your character for 3 seconds. Unstoppable prevents application of Knocked-down and Staggered for 30 seconds.`,
      },
      "Cauterize": {
        name: "Cauterize",
        pos: "f4",
        icon: icons["abi_cauterize"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`100ft range\n10 CBN\ninstant cast\n\nspell\n\nDispel 1 enchantment from target enemy. Dispel 1 affliction from yourself. Dispel 2 stacks of Blast from yourself but refresh the stack duration.`,
      },
      "Exquisite Firecraft": {
        name: "Exquisite Firecraft",
        pos: "f8",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Cauterize",
        arrows: [{ dir: "down", from: "f4", to: "f8" }],
        description: talentText`Cauterize will now also dispel one blessing from the enemy. It now dispels affliction and blast on your defensive target if they are within 100ft instead of yourself.`,
      },
      "Fiery Blast": {
        name: "Fiery Blast",
        pos: "g4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`100ft range\n75 AP\n2.5s cast\nspell\n\nDeals 15% SAP + 68 elemental damage to up to 9 enemies within a 30ft area you select.`,
      },
      "Playing With Fire": {
        name: "Playing With Fire",
        pos: "i6",
        icon: icons["abi_playingwithfire"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`100ft range\n50 AP\n1.5s cast\nspell\n\nApplies an affliction to the target for 10 seconds. Whenever the target is healed, you will deal 15% SAP + 100 elemental damage to the healer and you generate 5 Combustion.`,
      },
      "You Get Burned": {
        name: "You Get Burned",
        pos: "i8",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Playing With Fire",
        arrows: [{ dir: "down", from: "i6", to: "i8" }],
        description: talentText`Playing With Fire will apply 1 stack of Reduced Willpower to targets it damages.`,
      },
      "Rain of Fire": {
        name: "Rain of Fire",
        pos: "f8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`100ft range\n100 AP\n6.0s cast\nspell\n\nDeals 6% SAP + 45 elemental damage to up to 9 enemies within a 20ft area you select every second.`,
      },
      "Fiery Reserves": {
        name: "Fiery Reserves",
        pos: "e8",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Blast will now generate 2 Combustion per stack whenever it expires.`,
      },
      "Shield of Aqshy": {
        name: "Shield of Aqshy",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`40 CDN\ninstant cast\n20s CD\nspell\n\nApplies a buff for 5s and a blessing for 10s to each groupmate within 100ft. For the buff duration, groupmate and all enemies within 20ft of them gain a stack of Blast every second. For the blessing duration, target groupmate gains 1000 elemental resistance.`,
      },
      "Spreading Flames": {
        name: "Spreading Flames",
        pos: "f9",
        icon: icons["abi_spreadingflames"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`75ft range\n150 AP\n2.0s cast\n30s CD\nspell\n\nApplys a debuff to the target enemy for 2s. Deals 6% + 20 elemental damage every 1 second. At the end of the duration, applies stage 2 of the debuff to up to 6 other enemies within 20ft. There are 5 stages, each stacks up to 10x.`,
      },
    },
  },
};
