import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/empire"),
);
const icons = requireAll(require.context("../../assets/icons/empire"));

export const data: TalentData = {
  Captain: {
    name: "Captain",
    background: backgrounds["captain"],
    icon: icons["archetype_tank"],
    talents: {
      "Motivated": {
        name: "Motivated",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "a3",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 3 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 20 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "a5",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a6",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`Increases your mass by 1.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "a7",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a8",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Masochist": {
        name: "Masochist",
        pos: "a9",
        icon: icons["rrtac_masochist"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`Whenever you are attacked while your Guard is active, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d7",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 30,
        description: talentText`Increases your Agility by ${[
          40,
          95,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "c2",
        icon: icons["stat_bal"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c5",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e2",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "g2",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Increases your Strength by ${[
          40,
          95,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "g5",
        icon: icons["stat_tou"],
        maxRank: 4,
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "b3",
        icon: icons["stat_wil"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f7",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "h3",
        icon: icons["stat_ws"],
        maxRank: 4,
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          95,
          165,
          250,
        ]}.`,
      },
      "Morale 1 Class": {
        name: "Morale 1c",
        pos: "i2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Class": {
        name: "Morale 2c",
        pos: "i3",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Arche": {
        name: "Morale 1a",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Race": {
        name: "Morale 3r",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Arche": {
        name: "Morale 4a",
        pos: "i6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Arche": {
        name: "Morale 2a",
        pos: "i7",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Arche": {
        name: "Morale 3a",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "c8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "g8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Increase your mass by 1.`,
      },
      "Emperor's Ward": {
        name: "Emperor's Ward",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you use a basic attack, you will gain a 500 absorb for 3 seconds.`,
      },
      "Sigmar's Favored": {
        name: "Sigmar's Favored",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you receive a direct heal, you will also be healed for 120 + 8% wounds.`,
      },
      "Stand Strong!": {
        name: "Stand Strong!",
        pos: "d9",
        icon: icons["abi_standstrong"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`30 mechanic\ninstant cast\nspell\nYou gain 125 action points.\nGroupmates within 100ft gain a tier 2 buff for 8 seconds. For the duration, they will have their AP costs reduced by 50%.\nGroupmates within 100ft gain a tier1 buff for 60 seconds. For the duration, they will gain 360 HP4.`,
      },
      "Emperor's Fury": {
        name: "Emperor's Fury",
        pos: "f9",
        icon: icons["abi_emperorsfury"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`80 AP\n2.0s cast\n30s CD\nspell\n\nYou apply Staggered and Unstoppable to up to 48 enemies within 30 feet in front of you. This effect does not apply to targets that have Cover to you.\n\nStaggered prevents all control of your character for 5 seconds or until you are attacked. Unstopped prevents you from being Staggered or Knocked-down for 30 seconds.`,
      },
      "On Your Guard!": {
        name: "On Your Guard!",
        pos: "d1",
        icon: icons["abi_onyourguard"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`30 mechanic\ninstant cast\nspell\n\nYou gain 125 action points.\nGroupmates within 100ft gain a tier2 buff for 8 seconds. For the duration, they will have their block chance increased by 30%.\nGroupmates within 100ft gain 1 stack of Enhanced Toughness and a tier1 buff for 60 seconds. For the duration, they will gain 1 stack of Enhanced Toughness every 10 seconds.`,
      },
      "To Victory!": {
        name: "To Victory!",
        pos: "g1",
        icon: icons["abi_tovictory"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`30 mechanic\ninstant cast\nspell\n\nYou gain 125 action points.\nGroupmates within 100ft gain a tier2 buff for 8 seconds. For the duration, they will have 1.0s faster cast times.\nGroupmates within 100ft gain a tier1 buff for 60 seconds. For the duration, they will gain 50% pushback immunity.`,
      },
      "Vicious Slash": {
        name: "Vicious Slash",
        pos: "h1",
        icon: icons["abi_viciousslash"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\n50 AP\ninstant cast\nskill\n\nDeals 30% MAP + 300 physical damage to the target. Generates 5 mechanic.`,
      },
      "Guard": {
        name: "Guard",
        pos: "e1",
        icon: icons["abi_guard"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`150ft range\ninstant cast\nability\n\nApplies Guard to target groupmate. While you are within 30ft of them, they will gain 50% of your armor, resistances, dodge, and block. You will lose these stats for the duration and for 5s after the effect is broken.`,
      },
      "Strike": {
        name: "Strike",
        pos: "b1",
        icon: icons["abi_strike"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\ninstant cast\n\skill\n\n(Basic Attack) Deals 160 physical damage to the target. Generates 5 mechanic.`,
      },
      "Improved Strike": {
        name: "Improved Strike",
        pos: "c1",
        icon: icons["abi_strike"],
        maxRank: 2,
        reqPoints: 0,
        prereq: "Strike",
        arrows: [{ dir: "right", from: "b1", to: "c1" }],
        description: talentText`Strike now deals additional damage equal to ${[
          8,
          15,
        ]}% MAP.`,
      },
      "Repel": {
        name: "Repel",
        pos: "d3",
        icon: icons["abi_repel"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Strike",
        arrows: [{ dir: "right", from: "b1", to: "c1" }],
        description: talentText`melee range\n50AP\ninstant cast\n10s CD\nskill\n\nKnocks the enemy away and applies Immovable to them. Generates 5 mechanic points.\n\nImmovable prevents application of Knockbacks, Pulls, and the Rooted status for 20 seconds.`,
      },
      "Crippling Blow": {
        name: "Crippling Blow",
        pos: "f3",
        icon: icons["abi_shackle"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`melee range\n30AP\ninstant cast\nskill\n\nDeals 10% MAP + 160 physical damage and applies Ensnared and Momentum to the target.\n\nEnsnared reduces movement speed by 30% for 8 seconds. Momentum prevents the application of Ensnared for 8 seconds.`,
      },
      "Cover": {
        name: "Cover",
        pos: "b4",
        icon: icons["abi_cover"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Enemies that are in front of you will deal 25% less area of effect damage and other reduced effects to groupmates that are within 50 feet behind you.`,
      },
      "copyme": {
        name: "copyme",
        pos: "b9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "masochist",
        arrows: [{ dir: "right", from: "a9", to: "b9" }],
        description: talentText`100ft range\n100AP\n2.0s cast\n5.0s CD\nability\n\nStrike now deals additional damage equal to ${[
          8,
          15,
        ]}% MAP.`,
      },
    },
  },
  "Reiksguard": {
    name: "Reiksguard",
    background: backgrounds["reiksguard"],
    icon: icons["archetype_tank"],
    talents: {
      "Motivated2": {
        name: "Motivated2",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "a3",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 3 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 20 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "a5",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a6",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`Increases your mass by 1.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "a7",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a8",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Masochist": {
        name: "Masochist",
        pos: "a9",
        icon: icons["rrtac_masochist"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`Whenever you are attacked while your Guard is active, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d7",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 30,
        description: talentText`Increases your Agility by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "c2",
        icon: icons["stat_bal"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c5",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e2",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "g2",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Increases your Strength by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "g5",
        icon: icons["stat_tou"],
        maxRank: 4,
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "b3",
        icon: icons["stat_wil"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f7",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "h3",
        icon: icons["stat_ws"],
        maxRank: 4,
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          95,
          165,
          250,
          350,

        ]}.`,
      },
      "Morale 1 Class": {
        name: "Morale 1c",
        pos: "i2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Class": {
        name: "Morale 2c",
        pos: "i3",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Arche": {
        name: "Morale 1a",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Race": {
        name: "Morale 3r",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Arche": {
        name: "Morale 4a",
        pos: "i6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Arche": {
        name: "Morale 2a",
        pos: "i7",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Arche": {
        name: "Morale 3a",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "c8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "g8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Increase your mass by 1.`,
      },
      "Emperor's Ward": {
        name: "Emperor's Ward",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you use a basic attack, you will gain a 500 absorb for 3 seconds.`,
      },
      "Sigmar's Favored": {
        name: "Sigmar's Favored",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you receive a direct heal, you will also be healed for 120 + 8% wounds.`,
      },
      "Power Ability 1": {
        name: "Power Aility 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Power Ability 2": {
        name: "Power Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`100ft range\n
        100 AP\n
        2.0s cast\n
        5.0s CD\n\n
        Skill text`,
      },
      "On Your Guard!": {
        name: "On Your Guard!",
        pos: "d1",
        icon: icons["abi_onyourguard"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`30 mechanic\ninstant cast\nspell\n\nYou gain 125 action points.\nGroupmates within 100ft gain a tier2 buff for 8 seconds. For the duration, they will have their block chance increased by 30%.\nGroupmates within 100ft gain 1 stack of Enhanced Toughness and a tier1 buff for 60 seconds. For the duration, they will gain 1 stack of Enhanced Toughness every 10 seconds.`,
      },
      "Press the Attack!": {
        name: "To Victory!",
        pos: "f1",
        icon: icons["abi_presstheattack"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`30 mechanic\ninstant cast\nspell\n\nYou gain 125 action points.\nGroupmates within 100ft gain a tier2 buff for 8 seconds. For the duration, they will have their critical chance increased by 15%.\nGroupmates within 100ft gain 1 stack of Enhanced Strength and a tier1 buff for 60 seconds. For the duration, they will gain 1 stack of Enhanced Strength every 10 seconds.`,
      },
      "Vicious Slash": {
        name: "Vicious Slash",
        pos: "h1",
        icon: icons["abi_viciousslash"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\n50 AP\ninstant cast\nskill\n\nDeals 30% MAP + 300 physical damage to the target. Generates 5 mechanic.`,
      },
      "Guard": {
        name: "Guard",
        pos: "e1",
        icon: icons["abi_guard"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`150ft range\ninstant cast\nability\n\nApplies Guard to target groupmate. While you are within 30ft of them, they will gain 50% of your armor, resistances, dodge, and block. You will lose these stats for the duration and for 5s after the effect is broken.`,
      },
      "Strike": {
        name: "Strike",
        pos: "b1",
        icon: icons["abi_strike"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\ninstant cast\nskill\n\n(Basic Attack) Deals 160 physical damage to the target. Generates 5 mechanic.`,
      },
      "Improved Strike": {
        name: "Improved Strike",
        pos: "c1",
        icon: icons["abi_strike"],
        maxRank: 2,
        reqPoints: 0,
        prereq: "Strike",
        arrows: [{ dir: "right", from: "b1", to: "c1" }],
        description: talentText`Strike now deals additional damage equal to ${[
          8,
          15,
        ]}% MAP.`,
       },
    },
  },
  "Knight of the Blazing Sun": {
    name: "Knight of the Blazing Sun",
    background: backgrounds["kotbs"],
    icon: icons["archetype_offsupport"],
    talents: {
      "Motivated": {
        name: "Motivated",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "a3",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 3 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 20 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "a5",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a6",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`Increases your mass by 1.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "a7",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a8",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Break Loose": {
        name: "Break Loose",
        pos: "a9",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d7",
        icon: icons["stat_agl"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Agility by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "c2",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c5",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e2",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "g2",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases your Strength by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "g5",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "b3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f7",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 30,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "h3",
        icon: icons["stat_ws"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          95,
          165,
          250,
          350,

        ]}.`,
      },
      "Morale 1 Class": {
        name: "Morale 1c",
        pos: "i2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Class": {
        name: "Morale 2c",
        pos: "i3",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Arche": {
        name: "Morale 1a",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Race": {
        name: "Morale 3r",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Arche": {
        name: "Morale 4a",
        pos: "i6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Arche": {
        name: "Morale 2a",
        pos: "i7",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Arche": {
        name: "Morale 3a",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "c8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "g8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 2.`,
      },
      "Emperor's Ward": {
        name: "Emperor's Ward",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you use a basic attack, you will gain a 500 absorb for 3 seconds.`,
      },
      "Sigmar's Favored": {
        name: "Sigmar's Favored",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you receive a direct heal, you will also be healed for 120 + 8% wounds.`,
      },
      "Power Ability 1": {
        name: "Power Aility 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Power Ability 2": {
        name: "Power Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`100ft range\n
        100 AP\n
        2.0s cast\n
        5.0s CD\n\n
        Skill text`,
      },
      "To Victory!": {
        name: "To Victory!",
        pos: "g1",
        icon: icons["abi_tovictory"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`30 mechanic\ninstant cast\nspell\n\nYou gain 125 action points.\nGroupmates within 100ft gain a tier2 buff for 8 seconds. For the duration, they will have 1.0s faster cast times.\nGroupmates within 100ft gain a tier1 buff for 60 seconds. For the duration, they will gain 50% pushback immunity.`,
      },
      "Press the Attack!": {
        name: "To Victory!",
        pos: "f1",
        icon: icons["abi_presstheattack"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`30 mechanic\ninstant cast\nspell\n\nYou gain 125 action points.\nGroupmates within 100ft gain a tier2 buff for 8 seconds. For the duration, they will have their critical chance increased by 15%.\nGroupmates within 100ft gain 1 stack of Enhanced Strength and a tier1 buff for 60 seconds. For the duration, they will gain 1 stack of Enhanced Strength every 10 seconds.`,
      },
      "Vicious Slash": {
        name: "Vicious Slash",
        pos: "h1",
        icon: icons["abi_viciousslash"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\n50 AP\ninstant cast\nskill\n\nDeals 30% MAP + 300 physical damage to the target. Generates 5 mechanic.`,
      },
      "Charge": {
        name: "Charge",
        pos: "e1",
        icon: icons["abi_charge"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`instant cast\n30s CD\nability\n\n(Movement Skill) You gain 40% movement speed for 8 seconds. Effect will end if you use any ability.`,
      },
      "Strike": {
        name: "Strike",
        pos: "b1",
        icon: icons["abi_strike"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\ninstant cast\nskill\n\n(Basic Attack) Deals 160 physical damage to the target. Generates 5 mechanic.`,
      },
      "Improved Strike": {
        name: "Improved Strike",
        pos: "c1",
        icon: icons["abi_strike"],
        maxRank: 2,
        reqPoints: 0,
        prereq: "Strike",
        arrows: [{ dir: "right", from: "b1", to: "c1" }],
        description: talentText`Strike now deals additional damage equal to ${[
          8,
          15,
        ]}% MAP.`,
       },
    },
  },
};
