import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/empire"),
);
const icons = requireAll(require.context("../../assets/icons/empire"));

export const data: TalentData = {
  Captain: {
    name: "Captain",
    background: backgrounds["captain"],
    icon: icons["archetype_tank"],
    talents: {
      "Motivated": {
        name: "Motivated",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "b2",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 3 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 20 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "b4",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "b6",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a6",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a8",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Increases your mass by 1.`,
      },
      "Masochist": {
        name: "Masochist",
        pos: "a9",
        icon: icons["rrtac_masochist"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`Whenever you are attacked while your Guard is active, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Morale 1 Class": {
        name: "Morale 1c",
        pos: "h2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Class": {
        name: "Morale 2c",
        pos: "h4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Arche": {
        name: "Morale 1a",
        pos: "i2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Race": {
        name: "Morale 3r",
        pos: "b8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Arche": {
        name: "Morale 4a",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Arche": {
        name: "Morale 2a",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Arche": {
        name: "Morale 3a",
        pos: "i6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "h6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "h8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Agility": {
        name: "Agility",
        pos: "b5",
        icon: icons["stat_agl"],
        maxRank: 5,
        reqPoints: 20,
        description: talentText`Increases your Agility by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "b7",
        icon: icons["stat_bal"],
        maxRank: 3
        reqPoints: 30,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "b3",
        icon: icons["stat_ini"],
        maxRank: 3
        reqPoints: 10,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e7",
        icon: icons["stat_int"],
        maxRank: 3
        reqPoints: 30,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "h7",
        icon: icons["stat_str"],
        maxRank: 2
        reqPoints: 30,
        description: talentText`Increases your Strength by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "e5",
        icon: icons["stat_tou"],
        maxRank: 4
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "h3",
        icon: icons["stat_wil"],
        maxRank: 1
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "h5",
        icon: icons["stat_wou"],
        maxRank: 3
        reqPoints: 20,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "e3",
        icon: icons["stat_ws"],
        maxRank: 4
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      "Stabilized": {
        name: "Stabilized",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Increase your mass by 1.`,
      },
      "Emperor's Ward": {
        name: "Emperor's Ward",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you use a basic attack, you will gain a 500 absorb for 3 seconds.`,
      },
      "Sigmar's Favored": {
        name: "Sigmar's Favored",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you receive a direct heal, you will also be healed for 120 + 8% wounds.`,
      },
      "Stand Strong!": {
        name: "Stand Strong!",
        pos: "d9",
        icon: icons["abi_standstrong"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`30 mechanic\ninstant cast\nspell\nYou gain 125 action points.\nGroupmates within 100ft gain a tier 2 buff for 8 seconds. For the duration, they will have their AP costs reduced by 50%.\n\nGroupmates within 100ft gain a tier1 buff for 60 seconds. For the duration, they will gain 360 HP4.`,
      },
      "Emperor's Fury": {
        name: "Emperor's Fury",
        pos: "f9",
        icon: icons["abi_emperorsfury"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`80 AP\n2.0s cast\n30s CD\nspell\n\nYou apply Staggered and Unstoppable to up to 48 enemies within 30 feet in front of you. This effect does not apply to targets that have Cover to you.\n\nStaggered prevents all control of your character for 5 seconds or until you are attacked. Unstopped prevents you from being Staggered or Knocked-down for 30 seconds.`,
      },
      "On Your Guard!": {
        name: "On Your Guard!",
        pos: "d1",
        icon: icons["abi_onyourguard"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`30 mechanic\ninstant cast\nspell\n\nYou gain 125 action points.\nGroupmates within 100ft gain a tier2 buff for 8 seconds. For the duration, they will have their block chance increased by 30%.\nGroupmates within 100ft gain 1 stack of Enhanced Toughness and a tier1 buff for 60 seconds. For the duration, they will gain 1 stack of Enhanced Toughness every 10 seconds.`,
      },
      "To Victory!": {
        name: "To Victory!",
        pos: "h1",
        icon: icons["abi_tovictory"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`30 mechanic\ninstant cast\nspell\n\nYou gain 125 action points.\nGroupmates within 100ft gain a tier2 buff for 8 seconds. For the duration, they will have 1.0s faster cast times.\nGroupmates within 100ft gain a tier1 buff for 60 seconds. For the duration, they will gain 50% pushback immunity.`,
      },
      "Vicious Slash": {
        name: "Vicious Slash",
        pos: "g1",
        icon: icons["abi_viciousslash"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\n50 AP\ninstant cast\nskill\n\nDeals 30% MAP + 300 physical damage to the target. Generates 5 mechanic.`,
      },
      "Guard": {
        name: "Guard",
        pos: "e1",
        icon: icons["abi_guard"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`150ft range\ninstant cast\nability\n\nApplies Guard to target groupmate. While you are within 30ft of them, they will gain 50% of your armor, resistances, dodge, and block. You will lose these stats for the duration and for 5s after the effect is broken.`,
      },
      "Strike": {
        name: "Strike",
        pos: "b1",
        icon: icons["abi_strike"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\ninstant cast\n\skill\n\n(Basic Attack) Deals 160 physical damage to the target. Generates 5 mechanic.`,
      },
      "Improved Strike": {
        name: "Improved Strike",
        pos: "c1",
        icon: icons["abi_strike"],
        maxRank: 2,
        reqPoints: 0,
        prereq: "Strike",
        arrows: [{ dir: "right", from: "b1", to: "c1" }],
        description: talentText`Strike now deals additional damage equal to ${[
          8,
          15,
        ]}% MAP.`,
      },
      "Repel": {
        name: "Repel",
        pos: "c2",
        icon: icons["abi_repel"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`melee range\n50AP\ninstant cast\n10s CD\nskill\n\nKnocks the enemy away and applies Immovable to them. Generates 5 mechanic points.\n\nImmovable prevents application of Knockbacks, Pulls, and the Rooted status for 20 seconds.`,
      },
      "Crippling Blow": {
        name: "Crippling Blow",
        pos: "f2",
        icon: icons["abi_shackle"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`melee range\n30AP\ninstant cast\nskill\n\nDeals 10% MAP + 160 physical damage and applies Ensnared and Momentum to the target.\n\nEnsnared reduces movement speed by 30% for 8 seconds. Momentum prevents the application of Ensnared for 8 seconds.`,
      },
      "Cover": {
        name: "Cover",
        pos: "b4",
        icon: icons["abi_cover"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Enemies that are in front of you will deal 25% less area of effect damage and other reduced effects to groupmates that are within 50 feet behind you.`,
      },
      "Well-Trained": {
        name: "Well-Trained",
        pos: "g2",
        icon: icons["tac_class_2"],
        maxRank: 1,
        reqPoints: 5,
        prereq: "Vicious Slash",
        arrows: [{ dir: "down", from: "g1", to: "g2" }],
        description: talentText`Vicious Slash will now apply a tier1 debuff to the target that deals 80% MAP + 90 physical damage over 9 seconds. This effect can stack up to 3 times.`,
      },
      "Improved Vicious Slash": {
        name: "Improved Vicious Slash",
        pos: "g4",
        icon: icons["abi_viciousslash"],
        maxRank: 2,
        reqPoints: 15,
        prereq: "Well-Trained",
        arrows: [{ dir: "down", from: "g2", to: "g4" }],
        description: talentText`Reduces the AP cost of Vicious Slash by ${[
          5,
          10,
        ]}.`,
      },
      "Bellow Commands": {
        name: "Bellow Commands",
        pos: "e6",
        icon: icons["tac_class_1"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 1 mechanic per second.`,
      },
      "Slice Through": {
        name: "Slice Through",
        pos: "f6",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Crippling Blow",
        arrows: [{ dir: "down", from: "f3", to: "f6" }],
        description: talentText`Crippling Blow will now apply to up to 2 other enemies within 15ft in front of you.`,
      },
      "Shining Blade": {
        name: "Shining Blade",
        pos: "b6",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`Whenever you critically hit, all groupmates within 100 feet will gain 1 stack of Enhanced Corporeal Resistance, Enhanced Elemental Resistance, or Enhanced Corporeal Resistance.`,
      },
      "Distract": {
        name: "Distract",
        pos: "c6",
        icon: icons["abi_distract"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`60ft range\n30AP\ninstant cast\n20s CD\nspell\n\nJams the target for the next 3 seconds interupting the next ability cast.`,
      },
      "Improved Distract": {
        name: "Improved Distract",
        pos: "c8",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Distract",
        arrows: [{ dir: "down", from: "c6", to: "c8" }],
        description: talentText`Distract will now work on up to 23 additional enemies within 20ft of the target as long as those targets do not have cover.`,
      },
      "Gilded Shield": {
        name: "Gilded Shield",
        pos: "d4",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "On Your Guard!",
        arrows: [{ dir: "down", from: "d1", to: "d4" }],
        description: talentText`Whenever you cast On Your Guard!, all groupmates within 100ft will gain 2 stacks of Enhanced Armor.`,
      },
      "Coordination": {
        name: "Coordination",
        pos: "e8",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`All of your abilities cost 5 less mechanic points.`,
      },
      "To Glory!": {
        name: "To Glory!",
        pos: "g6",
        icon: icons["abi_toglory"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`30 mechanic\ninstant cast\nspell\n\nYou gain 125 action points.\nGroupmates within 100ft gain a tier2 buff for 8 seconds. For the duration, they will gain 15 adrenaline per second.\nGroupmates within 100ft gain a tier1 buff for 60 seconds. For the duration, they will gain 2 action points per second.`,
      },
      "To Action!": {
        name: "To Action!",
        pos: "g8",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "To Glory!",
        arrows: [{ dir: "down", from: "g6", to: "g8" }],
        description: talentText`Increases the AP/s value of To Glory! by 3.`,
      },
      "Dirty Tricks": {
        name: "Dirty Tricks",
        pos: "d8",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Whenever you block an attack, two groupmates within 100ft gain 1 stack of Enhanced Fortitude.`,
      },
      "Bind Weapon": {
        name: "Bind Weapon",
        pos: "f8",
        icon: icons["abi_bindweapon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`melee range\n40AP\ninstant cast\n20s CD\nskill\n\nApplies Disarmed and Inevitable to the target.\n\nDisarmed prevents the use of skills for 5 seconds. Inevitable prevents the application of Disarmed and Silenced for 20 seconds.`,
      },
      "Perseverance": {
        name: "Perseverance",
        pos: "e2",
        icon: icons["abi_perseverance"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`instant cast\n20s CD\nspell\n\nYou gain a tier2 buff for 10 seconds. Each time you are attacked, you will gain 10 action points and gain 1 stack of Enhanced Armor.`,
      },
      "Stay Focused!": {
        name: "Stay Focused!",
        pos: "d6",
        icon: icons["abi_stayfocused"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`30 mechanic\ninstant cast\nspell\n\nYou gain 125 action points.\nGroupmates within 100ft gain a tier2 buff for 8 seconds. For the duration, they will gain 20% healing received.\nGroupmates within 100ft gain 1 stack of Enhanced Willpower and a tier1 buff for 60 seconds. For the duration, they will gain 1 stack of Enhanced Willpower every 10 seconds.`,
      },
    },
  },
  "Reiksguard": {
    name: "Reiksguard",
    background: backgrounds["reiksguard"],
    icon: icons["archetype_tank"],
    talents: {
      "Motivated": {
        name: "Motivated",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "b2",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 3 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 20 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "b4",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "b6",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a6",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a8",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Increases your mass by 1.`,
      },
      "Masochist": {
        name: "Masochist",
        pos: "a9",
        icon: icons["rrtac_masochist"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`Whenever you are attacked while your Guard is active, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Morale 1 Class": {
        name: "Morale 1c",
        pos: "h2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Class": {
        name: "Morale 2c",
        pos: "h4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Arche": {
        name: "Morale 1a",
        pos: "i2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Race": {
        name: "Morale 3r",
        pos: "b8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Arche": {
        name: "Morale 4a",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Arche": {
        name: "Morale 2a",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Arche": {
        name: "Morale 3a",
        pos: "i6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "h6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "h8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Agility": {
        name: "Agility",
        pos: "b5",
        icon: icons["stat_agl"],
        maxRank: 2
        reqPoints: 20,
        description: talentText`Increases your Agility by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "b7",
        icon: icons["stat_bal"],
        maxRank: 3
        reqPoints: 30,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "b3",
        icon: icons["stat_ini"],
        maxRank: 3
        reqPoints: 10,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e7",
        icon: icons["stat_int"],
        maxRank: 3
        reqPoints: 30,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "h7",
        icon: icons["stat_str"],
        maxRank: 2
        reqPoints: 30,
        description: talentText`Increases your Strength by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "e5",
        icon: icons["stat_tou"],
        maxRank: 4
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "h3",
        icon: icons["stat_wil"],
        maxRank: 1
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "h5",
        icon: icons["stat_wou"],
        maxRank: 3
        reqPoints: 20,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "e3",
        icon: icons["stat_ws"],
        maxRank: 4
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      "Stabilized": {
        name: "Stabilized",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Increase your mass by 1.`,
      },
      "Emperor's Ward": {
        name: "Emperor's Ward",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you use a basic attack, you will gain a 500 absorb for 3 seconds.`,
      },
      "Sigmar's Favored": {
        name: "Sigmar's Favored",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you receive a direct heal, you will also be healed for 120 + 8% wounds.`,
      },
      "Power Ability 1": {
        name: "Power Aility 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Power Ability 2": {
        name: "Power Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`100ft range\n
        100 AP\n
        2.0s cast\n
        5.0s CD\n\n
        Skill text`,
      },
      "On Your Guard!": {
        name: "On Your Guard!",
        pos: "d1",
        icon: icons["abi_onyourguard"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`30 mechanic\ninstant cast\nspell\n\nYou gain 125 action points.\nGroupmates within 100ft gain a tier2 buff for 8 seconds. For the duration, they will have their block chance increased by 30%.\nGroupmates within 100ft gain 1 stack of Enhanced Toughness and a tier1 buff for 60 seconds. For the duration, they will gain 1 stack of Enhanced Toughness every 10 seconds.`,
      },
      "Press the Attack!": {
        name: "To Victory!",
        pos: "f1",
        icon: icons["abi_presstheattack"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`30 mechanic\ninstant cast\nspell\n\nYou gain 125 action points.\nGroupmates within 100ft gain a tier2 buff for 8 seconds. For the duration, they will have their critical chance increased by 15%.\nGroupmates within 100ft gain 1 stack of Enhanced Strength and a tier1 buff for 60 seconds. For the duration, they will gain 1 stack of Enhanced Strength every 10 seconds.`,
      },
      "Vicious Slash": {
        name: "Vicious Slash",
        pos: "h1",
        icon: icons["abi_viciousslash"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\n50 AP\ninstant cast\nskill\n\nDeals 30% MAP + 300 physical damage to the target. Generates 5 mechanic.`,
      },
      "Guard": {
        name: "Guard",
        pos: "e1",
        icon: icons["abi_guard"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`150ft range\ninstant cast\nability\n\nApplies Guard to target groupmate. While you are within 30ft of them, they will gain 50% of your armor, resistances, dodge, and block. You will lose these stats for the duration and for 5s after the effect is broken.`,
      },
      "Strike": {
        name: "Strike",
        pos: "b1",
        icon: icons["abi_strike"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\ninstant cast\nskill\n\n(Basic Attack) Deals 160 physical damage to the target. Generates 5 mechanic.`,
      },
      "Improved Strike": {
        name: "Improved Strike",
        pos: "c1",
        icon: icons["abi_strike"],
        maxRank: 2,
        reqPoints: 0,
        prereq: "Strike",
        arrows: [{ dir: "right", from: "b1", to: "c1" }],
        description: talentText`Strike now deals additional damage equal to ${[
          8,
          15,
        ]}% MAP.`,
       },
    },
  },
  "Knight of the Blazing Sun": {
    name: "Knight of the Blazing Sun",
    background: backgrounds["kotbs"],
    icon: icons["archetype_offsupport"],
    talents: {
      "Motivated": {
        name: "Motivated",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "b2",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 3 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 20 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "b4",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "b6",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a6",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a8",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Increases your mass by 1.`,
      },
      "Break Loose": {
        name: "Break Loose",
        pos: "a9",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Morale 1 Class": {
        name: "Morale 1c",
        pos: "h2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Class": {
        name: "Morale 2c",
        pos: "h4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Arche": {
        name: "Morale 1a",
        pos: "i2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Race": {
        name: "Morale 3r",
        pos: "b8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Arche": {
        name: "Morale 4a",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Arche": {
        name: "Morale 2a",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Arche": {
        name: "Morale 3a",
        pos: "i6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "h6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "h8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Agility": {
        name: "Agility",
        pos: "b5",
        icon: icons["stat_agl"],
        maxRank: 3
        reqPoints: 20,
        description: talentText`Increases your Agility by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "b7",
        icon: icons["stat_bal"],
        maxRank: 2
        reqPoints: 30,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "b3",
        icon: icons["stat_ini"],
        maxRank: 3
        reqPoints: 10,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e7",
        icon: icons["stat_int"],
        maxRank: 3
        reqPoints: 30,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "h7",
        icon: icons["stat_str"],
        maxRank: 3
        reqPoints: 30,
        description: talentText`Increases your Strength by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "e5",
        icon: icons["stat_tou"],
        maxRank: 2
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "h3",
        icon: icons["stat_wil"],
        maxRank: 2
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "h5",
        icon: icons["stat_wou"],
        maxRank: 2
        reqPoints: 20,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "e3",
        icon: icons["stat_ws"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 2.`,
      },
      "Emperor's Ward": {
        name: "Emperor's Ward",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you use a basic attack, you will gain a 500 absorb for 3 seconds.`,
      },
      "Sigmar's Favored": {
        name: "Sigmar's Favored",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you receive a direct heal, you will also be healed for 120 + 8% wounds.`,
      },
      "Power Ability 1": {
        name: "Power Aility 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Power Ability 2": {
        name: "Power Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`100ft range\n
        100 AP\n
        2.0s cast\n
        5.0s CD\n\n
        Skill text`,
      },
      "To Victory!": {
        name: "To Victory!",
        pos: "g1",
        icon: icons["abi_tovictory"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`30 mechanic\ninstant cast\nspell\n\nYou gain 125 action points.\nGroupmates within 100ft gain a tier2 buff for 8 seconds. For the duration, they will have 1.0s faster cast times.\nGroupmates within 100ft gain a tier1 buff for 60 seconds. For the duration, they will gain 50% pushback immunity.`,
      },
      "Press the Attack!": {
        name: "To Victory!",
        pos: "f1",
        icon: icons["abi_presstheattack"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`30 mechanic\ninstant cast\nspell\n\nYou gain 125 action points.\nGroupmates within 100ft gain a tier2 buff for 8 seconds. For the duration, they will have their critical chance increased by 15%.\nGroupmates within 100ft gain 1 stack of Enhanced Strength and a tier1 buff for 60 seconds. For the duration, they will gain 1 stack of Enhanced Strength every 10 seconds.`,
      },
      "Vicious Slash": {
        name: "Vicious Slash",
        pos: "h1",
        icon: icons["abi_viciousslash"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\n50 AP\ninstant cast\nskill\n\nDeals 30% MAP + 300 physical damage to the target. Generates 5 mechanic.`,
      },
      "Charge": {
        name: "Charge",
        pos: "e1",
        icon: icons["abi_charge"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`instant cast\n30s CD\nability\n\n(Movement Skill) You gain 40% movement speed for 8 seconds. Effect will end if you use any ability.`,
      },
      "Strike": {
        name: "Strike",
        pos: "b1",
        icon: icons["abi_strike"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\ninstant cast\nskill\n\n(Basic Attack) Deals 160 physical damage to the target. Generates 5 mechanic.`,
      },
      "Improved Strike": {
        name: "Improved Strike",
        pos: "c1",
        icon: icons["abi_strike"],
        maxRank: 2,
        reqPoints: 0,
        prereq: "Strike",
        arrows: [{ dir: "right", from: "b1", to: "c1" }],
        description: talentText`Strike now deals additional damage equal to ${[
          8,
          15,
        ]}% MAP.`,
       },
      "copyme": {
        name: "copyme",
        pos: "b9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Break Loose",
        arrows: [{ dir: "right", from: "a9", to: "b9" }],
        description: talentText`100ft range\n100AP\n2.0s cast\n5.0s CD\nability\n\nStrike now deals additional damage equal to ${[
          8,
          15,
        ]}% MAP.`,
      },
    },
  },
};
