import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/empire"),
);
const icons = requireAll(require.context("../../assets/icons/empire"));

export const data: TalentData = {
  Captain: {
    name: "Captain",
    background: backgrounds["captain"],
    icon: icons["archetype_tank"],
    talents: {
      "Motivated": {
        name: "Motivated",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "a3",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 3 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 5 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "a5",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a6",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`Increases your mass by 1.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "a7",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a8",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Masochist": {
        name: "Masochist",
        pos: "a9",
        icon: icons["rrtac_masochist"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`Whenever you are attacked while your Guard is active, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d7",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 30,
        description: talentText`Increases your Agility by ${[
          40,
          95,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "c2",
        icon: icons["stat_bal"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c5",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e2",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "g2",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Increases your Strength by ${[
          40,
          95,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "g5",
        icon: icons["stat_tou"],
        maxRank: 4,
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "b3",
        icon: icons["stat_wil"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f7",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "h3",
        icon: icons["stat_ws"],
        maxRank: 4,
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          55,
          70,
          85,
        ]}.`,
      },
      "Morale 1 Class": {
        name: "Morale 1c",
        pos: "i2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Class": {
        name: "Morale 2c",
        pos: "i3",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Arche": {
        name: "Morale 1a",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Race": {
        name: "Morale 3r",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Arche": {
        name: "Morale 4a",
        pos: "i6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Arche": {
        name: "Morale 2a",
        pos: "i7",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Arche": {
        name: "Morale 3a",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "c8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "g8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Increase your mass by 1.`,
      },
      "Race Tactic 1": {
        name: "Archetype Tactic",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`placeholder atm`,
      },
      "Race Tactic 2": {
        name: "Race Tactic 2",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`placeholder atm`,
      },
      "Power Ability 1": {
        name: "Power Aility 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Power Ability 2": {
        name: "Power Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`100ft range
        100 AP
        2.0s cast
        5.0s CD
        Skill text`,
      },
    },
  "Reiksguard": {
    name: "Reiksguard",
    background: backgrounds["reiksguard"],
    icon: icons["archetype_tank"],
    talents: {
      "Motivated2": {
        name: "Motivated2",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "a3",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 3 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 5 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "a5",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a6",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`Increases your mass by 1.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "a7",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a8",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Masochist": {
        name: "Masochist",
        pos: "a9",
        icon: icons["rrtac_masochist"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`Whenever you are attacked while your Guard is active, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d7",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 30,
        description: talentText`Increases your Agility by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "c2",
        icon: icons["stat_bal"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c5",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e2",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "g2",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Increases your Strength by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "g5",
        icon: icons["stat_tou"],
        maxRank: 4,
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "b3",
        icon: icons["stat_wil"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f7",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "h3",
        icon: icons["stat_ws"],
        maxRank: 4,
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          55,
          70,
          85,
          100,
        ]}.`,
      },
      "Morale 1 Class": {
        name: "Morale 1c",
        pos: "i2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Class": {
        name: "Morale 2c",
        pos: "i3",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Arche": {
        name: "Morale 1a",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Race": {
        name: "Morale 3r",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Arche": {
        name: "Morale 4a",
        pos: "i6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Arche": {
        name: "Morale 2a",
        pos: "i7",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Arche": {
        name: "Morale 3a",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "c8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "g8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Increase your mass by 1.`,
      },
      "Race Tactic 1": {
        name: "Archetype Tactic",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`placeholder atm`,
      },
      "Race Tactic 2": {
        name: "Race Tactic 2",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`placeholder atm`,
      },
      "Power Ability 1": {
        name: "Power Aility 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Power Ability 2": {
        name: "Power Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`100ft range\n
        100 AP\n
        2.0s cast\n
        5.0s CD\n\n
        Skill text`,
      },
      "Wounds II": {
        name: "Wounds II",
        pos: "f8",
        icon: icons["stat_wou"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wounds",
        arrows: [{ dir: "down", from: "f7", to: "f8" }],
        description: talentText`Testing arrow function`,
      },
    },
  },
  "Knight of the Blazing Sun": {
    name: "Knight of the Blazing Sun",
    background: backgrounds["kotbs"],
    icon: icons["archetype_offsupport"],
    talents: {
      "Motivated": {
        name: "Motivated",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "a3",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 3 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 5 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "a5",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a6",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`Increases your mass by 1.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "a7",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a8",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Break Loose": {
        name: "Break Loose",
        pos: "a9",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d7",
        icon: icons["stat_agl"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Agility by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "c2",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c5",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e2",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "g2",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 5,
        description: talentText`Increases your Strength by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "g5",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "b3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f7",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 30,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "h3",
        icon: icons["stat_ws"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          55,
          70,
          85,
          100,
        ]}.`,
      },
      "Morale 1 Class": {
        name: "Morale 1c",
        pos: "i2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Class": {
        name: "Morale 2c",
        pos: "i3",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Arche": {
        name: "Morale 1a",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Race": {
        name: "Morale 3r",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Arche": {
        name: "Morale 4a",
        pos: "i6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Arche": {
        name: "Morale 2a",
        pos: "i7",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Arche": {
        name: "Morale 3a",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "c8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "g8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 2.`,
      },
      "Race Tactic 1": {
        name: "Archetype Tactic",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`placeholder atm`,
      },
      "Race Tactic 2": {
        name: "Race Tactic 2",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`placeholder atm`,
      },
      "Power Ability 1": {
        name: "Power Aility 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Power Ability 2": {
        name: "Power Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`100ft range\n
        100 AP\n
        2.0s cast\n
        5.0s CD\n\n
        Skill text`,
      },
      "Wounds II": {
        name: "Wounds II",
        pos: "f8",
        icon: icons["stat_wou"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wounds",
        arrows: [{ dir: "down", from: "f7", to: "f8" }],
        description: talentText`Testing arrow function`,
      },
    },
  },
  },
};
