import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/asur"),
);
const icons = requireAll(require.context("../../assets/icons/highelf"));

export const data: TalentData = {
  "Commander": {
    name: "Commander",
    background: backgrounds["noble"],
    icon: icons["archetype_tank"],
    talents: {
      "Masochist": {
        name: "Masochist",
        pos: "a8",
        icon: icons["rrtac_masochist"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you are attacked while your Guard is active, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Increase your mass by 1.`,
      },
      "Centuries of Training": {
        name: "centuries of Training",
        pos: "a2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you deal direct damage to an enemy, you have a 33% chance to apply one of three debuffs to them. Effects do not refresh and last 6 seconds.\nDeals 4% MAP + 56 impact damage every second.\nDeals 6% RAP + 80 piercing damage every 2 seconds.\nDeals 10% SAP + 134 spiritual damage every 3 seconds.`,
      },
      "Form Ranks": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, each groupmate within 100 feet that has this tactic will gain 1 stack of purity and a 4 second buff. For the duration, gain 450 penetration and 450 sagacity.`,
      },
      "Potent Enchantments": {
        name: "Potent Enchantments",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you strike an enemy with a blade enchantment active, you will deal 6% SAP + 77 spiritual damage every 2 seconds for 6 seconds. This effect does not refresh.`,
      },
      "Bound in Blue": {
        name: "Bound in Blue",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Cerulean Shield now applies the absorb to groupmates within 65 feet of you.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specadvancedshield"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Commanders equip one handed sword and shields.`,
      },
	  "Hedgehog": {
        name: "Hedgehog",
        pos: "f2",
        icon: icons["morale_hedgehog"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`All groupmates within 100 feet gain 3 stacks of Enhanced Block.`,
      },
      "Champion's Challenge": {
        name: "Champion's Chalenge",
        pos: "g2",
        icon: icons["morale_grapple"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Applies a debuff to target enemy and yourself for 10 seconds. Movement speed is reduced to 0 for the duration.`,
      },
      "Distracting Bellow": {
        name: "Distracting Bellow",
        pos: "h2",
        icon: icons["morale_distractingbellow"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Up to 48 enemies within 30 feet of you receive a debuff. For 10 seconds, they cannot benefit from Cover.`,
      },
      "Immaculate Defense": {
        name: "Immaculate Defense",
        pos: "i2",
        icon: icons["morale_immaculatedefense"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Groupmates within 100 feet gain 25 stacks of a buff for 20 seconds. Each stack grants 3% damage reduction. A stack is removed each time they are attacked by an ability; 4 additional stacks are removed if the ability is single target.`,
      },
      "White Tower Master": {
        name: "White Tower Master",
        pos: "i4",
        icon: icons["abi_he_dominance"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`You generate all 4 sigils.`,
      },
      "Wall of Darting Steel": {
        name: "Wall of Darting Steel",
        pos: "i5",
        icon: icons["abi_he_wallofdartingsteel"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "6.0s channel",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain 100% dodge for the duration.`,
      },
      "Wings of Heaven": {
        name: "Wings of Heaven",
        pos: "i7",
        icon: icons["abi_he_wingsofheaven"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Gain a debuff for 5 seconds which reduces your mass by 8. Leap forward and apply Ensnared to up to 9 enemies within 20 feet of where you land.\n\nEnsnared reduces movement speed by 30% for 16 seconds.`,
      },
	  "Unleash the Winds": {
        name: "Unleash the Winds",
        pos: "i8",
        icon: icons["morale_unleashthewinds"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 96 enemies within a 20 feet location you select are knocked straight up into the air.`,
      },
      "Balance": {
        name: "Balance",
        pos: "a1",
        icon: icons["abi_he_windsprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Abilities generate one of four sigils: Eldrazor, Hoeth, Vaul, and Asuryan. Each sigil will last for 15 seconds until used. Abilities gain augmented effects whenever a sigil is consumed.`,
      },
      "Heaven's Blade": {
        name: "Heaven's Blade",
        pos: "b1",
        icon: icons["abi_he_heavensblade"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Blade Enchantment",
        description: talentText`(Basic Attack) Deals 4% MAP + 30 elemental damage to target enemy. Generates 22 action points.\n\nAsuryan - Gain an enchantment for 10 seconds. Whenever you attack an enemy, you will apply a 6 second affliction that deals 5% SAP + 47 elemental damage every second.\n\nVaul - Gain an enchantment for 10 seconds. Whenever you attack an enemy, you will apply a 6 second enchantment that will absorb 11% RP + 155.`,
      },
      "Dragon's Talon": {
        name: "Dragon's Talon",
        pos: "c1",
        icon: icons["abi_he_dragonstrike"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Sigil of Asuryan",
        description: talentText`Dispel one enchantment from target enemy.\n\nHoeth - Also dispel one blessing.\nEldrazor - Also deals 21% MAP + 280 elemental damage.`,
      },
      "Quick Incision": {
        name: "Quick Incision",
        pos: "d1",
        icon: icons["abi_he_quickincision"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "25 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Sigil of Eldrazor",
        description: talentText`Applies Ensnared and Momentum to target enemy.\n\nEnsnared reduces movement speed by 30% for 16 seconds.\nMomentum prevents the application of Ensnared for 8 seconds.`,
      },
      "Guard": {
        name: "Guard",
        pos: "e1",
        icon: icons["abi_guard"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Applies Guard to target groupmate. While you are within 30 feet of them, they will gain 50% of your armor, resistances, and block. You will lose these stats for the duration and for 5 seconds after the effect is broken.`,
      },
      "Ether Dance": {
        name: "Ether Dance",
        pos: "f1",
        icon: icons["abi_he_etherdance"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "75 action points",
        range: "8ft range",
        cast: "3.0s channel",
        cooldown: "no cooldown",
        blue: "Sigil of Vaul",
        description: talentText`Deals 22% MAP + 312 spiritual damage every second to target enemy.\n\nEldrazor - Channel interval is reduced to 0.6 seconds.\nHoeth - Channel interval is increased to 2.0 seconds and the channel duration is increased to 6.0 seconds. For the duration, the target has its outoing damage and damage reduction reduced by 10%.`,
      },
      "Aethyric Dissipation": {
        name: "Aethyric Dissipation",
        pos: "g1",
        icon: icons["abi_he_instilfear"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "45 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Sigil of Hoeth",
        description: talentText`Applies Silenced and Inevitable to target enemy.\n\nSilence prevents the use of spells for 5 seconds.\nInevitable prevents the application of Disarmed and Silenced for 20 seconds.`,
      },
      "Ensorcelled Blow": {
        name: "Ensorcelled Blow",
        pos: "h1",
        icon: icons["abi_he_ensorcelledblow"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "36 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Sigil of Eldrazor",
        description: talentText`Deal 21% MAP + 280 elemental damage to target enemy.`,
      },
      "Cerulean Shield": {
        name: "Cerulean Shield",
        pos: "i1",
        icon: icons["abi_he_protectionofhoeth"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "8s cooldown",
        description: talentText`Gain an enchantment for 8 seconds. You will absorb 22% RP + 298 over the duration.`,
      },
	  "Dazzling Blade": {
        name: "Dazzling Blade",
        pos: "c4",
        icon: icons["abi_he_vortex"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "45 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Sigil of Hoeth",
        description: talentText`Applies a 6 second affliction to target enemy. Deals 9% SAP + 105 spiritual damage every 2 seconds.`,
      },
	  "Distract": {
        name: "Distract",
        pos: "h5",
        icon: icons["abi_distract"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "40 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Jams the target for the next 3 seconds interupting the next ability cast.`,
      },
	  "Phoenix Wing": {
        name: "Phoenix Wing",
        pos: "e6",
        icon: icons["abi_he_phoenixclaw"],
        maxRank: 1,
        reqPoints: 15,
        type: "skill",
        cost: "75 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Sigil of Vaul",
        description: talentText`Deals 8% MAP + 115 spiritual damage to up to 9 enemies within 30 feet of you.\nEldrazor - Applies a 9 second affliction to each enemy hit which deals 3% SAP + 12 spiritual damage every 3 seconds.\n\nHoeth - Interrupts each target hit.`,
      },
	  "Blessing of Heaven": {
        name: "Blessing of Heaven",
        pos: "c8",
        icon: icons["abi_he_bladeofleapinggold"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "65 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Sigil of Asuryan",
        description: talentText`Dispel one affliction from target ally.\n\nHoeth - Also dispels one cripple.\nEldrazor - Target gains a 8 second enchantment. For the duration, they will be healed for 6% RP + 68 each time they hit an enemy with an ability.`,
      },
      "Gusting Wind": {
        name: "Gusting Wind",
        pos: "d9",
        icon: icons["abi_he_freedom"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 4% SAP + 30 spiritual damage to target enemy. Generates 22 action points.\n\nAsuryan - Knocks up to 9 enemies within 30 feet of the target away and applies Immovable to them. This effect can only happen once every 20 seconds.\nVaul - Applies Knocked-down and Unstoppable to target enemy. This effect can only happen once every 20 seconds.\n\nKnocked-down prevents all control of your character for 3 seconds.\nImmovaled prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.\nUnstoppable prevents application of Knocked-down and Staggered for 30 seconds.`,
      },
      "Flames of the Phoenix": {
        name: "Flames of Phoenix",
        pos: "f9",
        icon: icons["abi_he_flamesofthephoenix"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "100ft range",
        cast: "3.0s channel",
        cooldown: "30s cooldown",
        description: talentText`Deals 10% SAP + 50 elemental damage every 0.5 seconds to up to 48 enemies within a 30 foot area you select. Each time an enemy is hit by this ability they gain a stack that increases damage they take from this ability by 25% for 1 second. This ability deals no damage to targets that have cover from you.`,
      },
	  "Vaul's Buffer": {
        name: "Vaul's Buffer",
        pos: "a5",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you consume a Sigil of Vaul, gain an enchantment for 8 seconds. For the duration, you will absorb up to 16% RP + 216.`,
      },
	  "Hoeth's Advancement": {
        name: "Hoeth's Advancement",
        pos: "b5",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you consume a Sigil of Hoeth, up to 3 groupmates within 100 feet gain 1 stack of Enhanced Intelligence.`,
      },
	  "Impeccable Reactions": {
        name: "Impeccable Reactions",
        pos: "b6",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Whenever you dodge an attack, all groupmates within 100 feet of you will gain 100% block chance against the next attack made against them within 3 seconds.`,
      },
	  "Improved Distract": {
        name: "Improved Distract",
        pos: "h6",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Distract",
		arrows: [
          { dir: "down", from: "h5", to: "h6" },
        ],
        type: "career tactic",
        description: talentText`Distract will now work on up to 23 additional enemeies within 20 feet of the target as long as those targets do not have cover.`,
      },
	  "Sapping Strikes": {
        name: "Sapping Strikes",
        pos: "a7",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Dazzling Blade, Heaven's Blade, Phoenix Wing will apply stacks of Reduced Spiritual Resistance and Reduced Elemental Resistance whenever they deal periodic damage.`,
      },
	  "Adept Movements": {
        name: "Adept Movements",
        pos: "g7",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Your absorb effects from Cerulean Shield, Eagle's Protection, Heaven's Blade, Whispering Wind, and Vaul's Buffer grant you 10% dodge.`,
      },
	  "Turbulent Winds": {
        name: "Turbulent Winds",
        pos: "g8",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Whenever you cast Dragon's Talon or Blessing of Heaven, you will gain 15 adrenaline per second for 3 seconds. In addition, each enemy you hit with Unleash the Winds will have their outgoing damage reduced by 20% for 10 seconds.`,
      },
	  "Balanced Defenses": {
        name: "Balanced Defenses",
        pos: "e3",
        icon: icons["abi_he_windsprotection"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever you consume a Sigil of Vaul or Sigil of Asuryan, all groupmates within 100 feet of you have their damage reduction increased by ${[
          3,
          6,
        ]}% for 5 seconds.`,
      },
	  "Improved Basic Attack": {
        name: "Improved Bassic Attack",
        pos: "g4",
        icon: icons["abi_he_heavensblade"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Your basic attacks will deal ${[
          75,
          150,
          225,
          300,
		  375,
        ]}% additional damage.`,
      },
	  "Bedazzle": {
        name: "Bedazzle",
        pos: "e5",
        icon: icons["abi_he_vortex"],
        maxRank: 2,
        reqPoints: 10,
        prereq: "Dazzling Blade",
        type: "passive",
        description: talentText`Increases the duration of Dazzling Blade by ${[
          2,
          4,
          6,
          8,
          10,
        ]} seconds.`,
      },
	  "Bladeshields": {
        name: "Bladeshields",
        pos: "d6",
        icon: icons["abi_he_bladeshield"],
        maxRank: 4,
        reqPoints: 15,
        type: "passive",
        description: talentText`Your absorb effects from Heaven's Blade, Cerulean Shield, and Vaul's Buffer will deal ${[
          5,
          14,
          23,
          33,
        ]}% SAP + 89 elemental damage to any enemy that attacks.`,
      },
	  "Engage": {
        name: "Engage",
        pos: "f6",
        icon: icons["abi_engage"],
        maxRank: 3,
        reqPoints: 15,
        type: "passive",
        description: talentText`Enemies that you deal direct damage to will have their outgoing damage reduced by ${[
          2,
          4,
          6,
        ]}% for 5 seconds.`,
      },
	  "Hold the Line": {
        name: "Hold the Line",
        pos: "c7",
        icon: icons["abi_cover"],
        maxRank: 1,
        reqPoints: 20,
        type: "passive",
        description: talentText`Groupmates within 50 feet behind you have Cover from all enemies up to 100 feet in front of you.\n\nCover reduces the damage of area of effect attacks by 25% in addition to providing immunity to some effects.`,
      },
	  "Redirected Force": {
        name: "Redirected Force",
        pos: "e7",
        icon: icons["abi_he_redirectforce"],
        maxRank: 5,
        reqPoints: 20,
        type: "passive",
        description: talentText`${[
          2,
          4,
          6,
          8,
          10,
        ]}% of enemy spells (not skills/abilities) that target groupmates within 30 feet of you are redirected to you but they deal twice as much damage to you.`,
      },
	  "The White Bulwark": {
        name: "The White Bulwark",
        pos: "e8",
        icon: icons["abi_he_shieldofvalor"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`All of your absorb effects are ${[
          6,
          12,
          18,
          24,
          32,
        ]}% more effective.`,
      },
    },
  },
  "Swordmaster": {
    name: "Swordmaster",
    background: backgrounds["swordmaster"],
    icon: icons["archetype_dps"],
    talents: {
      "Break Loose": {
        name: "Break Loose",
        pos: "a8",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 1,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Centuries of Training": {
        name: "centuries of Training",
        pos: "a2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you deal direct damage to an enemy, you have a 33% chance to apply one of three debuffs to them. Effects do not refresh and last 6 seconds.\nDeals 4% MAP + 56 impact damage every second.\nDeals 6% RAP + 80 piercing damage every 2 seconds.\nDeals 10% SAP + 134 spiritual damage every 3 seconds.`,
      },
      "Form Ranks": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, each groupmate within 100 feet that has this tactic will gain 1 stack of purity and a 4 second buff. For the duration, gain 450 penetration and 450 sagacity.`,
      },
      "Potent Enchantments": {
        name: "Potent Enchantments",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you strike an enemy with a blade enchantment active, you will deal 6% SAP + 77 spiritual damage every 2 seconds for 6 seconds. This effect does not refresh.`,
      },
      "Bound in Blue": {
        name: "Bound in Blue",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Cerulean Shield now applies the absorb to groupmates within 65 feet of you.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["abi_greatswordmastery"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Swordmasters equip two-handed swords.`,
      },
	  "Sever Nerve": {
        name: "Sever Nerve",
        pos: "f2",
        icon: icons["morale_severnerve"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Deals 50% MAP + 400 piercing damage to the target.`,
      },
      "Broad Swings": {
        name: "Broad Swings",
        pos: "g2",
        icon: icons["morale_broadswings"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 10 seconds. Your single target abilities will target two additional enemies within 20 feet in front of you.`,
      },
      "Force of Will": {
        name: "Force of Will",
        pos: "h2",
        icon: icons["morale_forceofwill"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 10 seconds. Action point costs are reduced by 75% for the duration.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "White Tower Master": {
        name: "White Tower Master",
        pos: "i4",
        icon: icons["abi_he_dominance"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`You generate all 4 sigils.`,
      },
      "Wall of Darting Steel": {
        name: "Wall of Darting Steel",
        pos: "i5",
        icon: icons["abi_he_wallofdartingsteel"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "6.0s channel",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain 100% dodge for the duration.`,
      },
      "Wings of Heaven": {
        name: "Wings of Heaven",
        pos: "i7",
        icon: icons["abi_he_wingsofheaven"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Gain a debuff for 5 seconds which reduces your mass by 8. Leap forward and apply Ensnared to up to 9 enemies within 20 feet of where you land.\n\nEnsnared reduces movement speed by 30% for 16 seconds.`,
      },
	  "Unleash the Winds": {
        name: "Unleash the Winds",
        pos: "i8",
        icon: icons["morale_unleashthewinds"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 96 enemies within a 20 feet location you select are knocked straight up into the air.`,
      },
      "Balance": {
        name: "Balance",
        pos: "a1",
        icon: icons["abi_he_windsprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Abilities generate one of four sigils: Eldrazor, Hoeth, Vaul, and Asuryan. Each sigil will last for 15 seconds until used. Abilities gain augmented effects whenever a sigil is consumed.`,
      },
      "Heaven's Blade": {
        name: "Heaven's Blade",
        pos: "b1",
        icon: icons["abi_he_heavensblade"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Blade Enchantment",
        description: talentText`(Basic Attack) Deals 4% MAP + 30 elemental damage to target enemy. Generates 22 action points.\n\nAsuryan - Gain an enchantment for 10 seconds. Whenever you attack an enemy, you will apply a 6 second affliction that deals 5% SAP + 47 elemental damage every second.\n\nVaul - Gain an enchantment for 10 seconds. Whenever you attack an enemy, you will apply a 6 second enchantment that will absorb 11% RP + 155.`,
      },
      "Dragon's Talon": {
        name: "Dragon's Talon",
        pos: "c1",
        icon: icons["abi_he_dragonstrike"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Sigil of Asuryan",
        description: talentText`Dispel one enchantment from target enemy.\n\nHoeth - Also dispel one blessing.\nEldrazor - Also deals 21% MAP + 280 elemental damage.`,
      },
      "Dazzling Blade": {
        name: "Dazzling Blade",
        pos: "d1",
        icon: icons["abi_he_vortex"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "45 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Sigil of Hoeth",
        description: talentText`Applies a 6 second affliction to target enemy. Deals 9% SAP + 105 spiritual damage every 2 seconds.`,
      },
      "Crushing Advance": {
        name: "Crushing Advance",
        pos: "e1",
        icon: icons["abi_he_switchfootwork"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "15s cooldown",
        description: talentText`Gain an enchantment for 5 seconds. For the duration, gain 20% movement speed.\n\nVaul - Gain 15% outgoing damage as well.\nAsuryan - Movement speed increase is now 40%.`,
      },
      "Ether Dance": {
        name: "Ether Dance",
        pos: "f1",
        icon: icons["abi_he_etherdance"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "75 action points",
        range: "8ft range",
        cast: "3.0s channel",
        cooldown: "no cooldown",
        blue: "Sigil of Vaul",
        description: talentText`Deals 22% MAP + 312 spiritual damage every second to target enemy.\n\nEldrazor - Channel interval is reduced to 0.6 seconds.\nHoeth - Channel interval is increased to 2.0 seconds and the channel duration is increased to 6.0 seconds. For the duration, the target has its outoing damage and damage reduction reduced by 10%.`,
      },
      "Eagle's Flight": {
        name: "Eagle's Flight",
        pos: "g1",
        icon: icons["abi_he_gracefulsweep"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "45 action points",
        range: "65ft range",
        cast: "1.5s cast",
        cooldown: "no cooldown",
        blue: "Sigil of Hoeth",
        description: talentText`Deals 30% SAP + 420 spiritual damage to target enemy.`,
      },
      "Ensorcelled Blow": {
        name: "Ensorcelled Blow",
        pos: "h1",
        icon: icons["abi_he_ensorcelledblow"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "36 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Sigil of Eldrazor",
        description: talentText`Deal 21% MAP + 280 elemental damage to target enemy.`,
      },
      "Cerulean Shield": {
        name: "Cerulean Shield",
        pos: "i1",
        icon: icons["abi_he_protectionofhoeth"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "8s cooldown",
        description: talentText`Gain an enchantment for 8 seconds. You will absorb 22% RP + 298 over the duration.`,
      },
	  "Crashing Wave": {
        name: "Crashing Wave",
        pos: "h4",
        icon: icons["abi_he_crashingwave"],
        maxRank: 1,
        reqPoints: 5,
        type: "skill",
        cost: "75 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Sigil of Eldrazor",
        description: talentText`Deals 10% MAP + 126 elemental damage to up to 9 enemies within 30 feet in front of you.`,
      },
	  "Blurring Shock": {
        name: "Blurring Shock",
        pos: "g5",
        icon: icons["abi_he_blurringshock"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "75 action points",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Sigil of Asuryan",
        description: talentText`Deals 28% SAP + 358 elemental damage to target enemy.\n\nEldrazor - deals 25% more damage.\nHoeth - now has a 65 foot range.`,
      },
	  "Phoenix Wing": {
        name: "Phoenix Wing",
        pos: "h6",
        icon: icons["abi_he_phoenixclaw"],
        maxRank: 1,
        reqPoints: 15,
        type: "skill",
        cost: "75 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Sigil of Vaul",
        description: talentText`Deals 8% MAP + 115 spiritual damage to up to 9 enemies within 30 feet of you.\n\nEldrazor - Applies a 9 second affliction to each enemy hit which deals 3% SAP + 12 spiritual damage every 3 seconds.\nHoeth - Interrupts each target hit.`,
      },
	  "Shadow Blade": {
        name: "Shadow Blade",
        pos: "h8",
        icon: icons["abi_he_shadowblades"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 1% MAP + 13 spiritual damage to up to 9 enemies within 30 feet of you. Generates 22 action points.\n\nVaul - Applies a 6 second ailment to each target hit. For the duration, targets take 5% MAP + 39 spiritual damage every 3 seconds.\nAsuryan - all groupmates within 100 feet gain 1 stack of Enhanced Willpower.`,
      },
      "Gusting Wind": {
        name: "Gusting Wind",
        pos: "d9",
        icon: icons["abi_he_freedom"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 4% SAP + 30 spiritual damage to target enemy. Generates 22 action points.\n\nAsuryan - Knocks up to 9 enemies within 30 feet of the target away and applies Immovable to them. This effect can only happen once every 20 seconds.\nVaul - Applies Knocked-down and Unstoppable to target enemy. This effect can only happen once every 20 seconds.\n\nKnocked-down prevents all control of your character for 3 seconds.\nImmovaled prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.\nUnstoppable prevents application of Knocked-down and Staggered for 30 seconds.`,
      },
      "Flames of the Phoenix": {
        name: "Flames of Phoenix",
        pos: "f9",
        icon: icons["abi_he_flamesofthephoenix"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "100ft range",
        cast: "3.0s channel",
        cooldown: "30s cooldown",
        description: talentText`Deals 10% SAP + 50 elemental damage every 0.5 seconds to up to 48 enemies within a 30 foot area you select. Each time an enemy is hit by this ability they gain a stack that increases damage they take from this ability by 25% for 1 second. This ability deals no damage to targets that have cover from you.`,
      },
	  "Poised Attacks": {
        name: "Poised Attacks",
        pos: "a5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you consume a Sigil of Eldrazor, you will gain 20% critical chance for 8 seconds.`,
      },
	  "Hoeth's Advancement": {
        name: "Hoeth's Advancement",
        pos: "b5",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you consume a Sigil of Hoeth, up to 3 groupmates within 100 feet gain 1 stack of Enhanced Intelligence.`,
      },
	  "Eagle's Protection": {
        name: "Eagle's Protection",
        pos: "b6",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Eagle's Flight will now apply an 8 second enchantment to your defensive target. For the duration, they will absorb up to 13% RP + 173 damage.`,
      },
	  "Master of the Blade": {
        name: "Master of the Blade",
        pos: "e6",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Your Eldrazor and Vaul skills deal 15% more damage, but your Hoeth and Asuryan skills deal 25% less damage.`,
      },
	  "Sapping Strikes": {
        name: "Sapping Strikes",
        pos: "a7",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Dazzling Blade, Heaven's Blade, Phoenix Wing will apply stacks of Reduced Spiritual Resistance and Reduced Elemental Resistance whenever they deal periodic damage.`,
      },
	  "Valor of Ages": {
        name: "Valor of Ages",
        pos: "c7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Crashing Wave, Phoenix Wing, and Shadow Blade will now hit up to 24 enemies.`,
      },
	  "Sweeping Dance": {
        name: "Sweeping Dance",
        pos: "b8",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Ether Dance will hit an additional enemy within 20 feet.`,
      },
	  "Balanced Accuracy": {
        name: "Balanced Accuracy",
        pos: "e3",
        icon: icons["abi_he_gryphonslash"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever you consume a Sigil of Vaul or a Sigil of Asuryan, you will gain 10% outgoing damage for ${[
          5,
          6,
          7,
          8,
        ]} seconds.`,
      },
	  "Fast Flight": {
        name: "Fast Flight",
        pos: "c4",
        icon: icons["abi_he_gracefulsweep"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Eagle's Flgith is now instant cast and deals 20% less damage.`,
      },
	  "Improved Basic Attack": {
        name: "Improved Bassic Attack",
        pos: "e5",
        icon: icons["abi_he_heavensblade"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Your basic attacks will deal ${[
          75,
          150,
          225,
          300,
		  375,
        ]}% additional damage.`,
      },
	  "Bedazzle": {
        name: "Bedazzle",
        pos: "d6",
        icon: icons["abi_he_vortex"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`Increases the duration of Dazzling Blade by ${[
          2,
          4,
          6,
          8,
          10,
        ]} seconds.`,
      },
	  "Harmonic Dieties": {
        name: "Harmonic Dieties",
        pos: "f6",
        icon: icons["abi_he_ensorcelledblow"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Ensorcelled Blow has a ${[
          10,
          20,
          30,
          40,
          50,
        ]}% chance to also generate a Sigil of Hoeth.`,
      },
	  "Blessing of Asuryan": {
        name: "Blessing of Asuryan",
        pos: "e7",
        icon: icons["abi_he_lawofage"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Gain ${[
          25,
          50,
          75,
          100,
        ]}% pushback immunity.`,
      },
	  "Long March": {
        name: "Long March",
        pos: "g7",
        icon: icons["abi_he_switchfootwork"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Crushing Advance now lasts ${[
          6,
          7,
          8,
        ]} seconds.`,
      },
	  "Dance of Blades": {
        name: "Dance of Blades",
        pos: "e8",
        icon: icons["abi_he_etherdance"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Ether Dance will deal  ${[
          2,
          5,
          9,
          15,
        ]}% additional damage for each Dazzling Blade and Heaven's Blade effect on the target.`,
      },	  
    },
  },
  "Loremaster": {
    name: "Loremaster",
    background: backgrounds["loremaster"],
    icon: icons["archetype_defsupport"],
    talents: {
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "What a Rush": {
        name: "What a Rush",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`The action point cost of your skills is reduced by 33% on allies that are lower than 40% health.`,
      },
      "Centuries of Training": {
        name: "centuries of Training",
        pos: "a2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you deal direct damage to an enemy, you have a 33% chance to apply one of three debuffs to them. Effects do not refresh and last 6 seconds.\nDeals 4% MAP + 56 impact damage every second.\nDeals 6% RAP + 80 piercing damage every 2 seconds.\nDeals 10% SAP + 134 spiritual damage every 3 seconds.`,
      },
      "Form Ranks": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, each groupmate within 100 feet that has this tactic will gain 1 stack of purity and a 4 second buff. For the duration, gain 450 penetration and 450 sagacity.`,
      },
      "Potent Enchantments": {
        name: "Potent Enchantments",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you strike an enemy with a blade enchantment active, you will deal 6% SAP + 77 spiritual damage every 2 seconds for 6 seconds. This effect does not refresh.`,
      },
      "Bound in Blue": {
        name: "Bound in Blue",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Cerulean Shield now applies the absorb to groupmates within 65 feet of you.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Loremasters equip staves.`,
      },
	  "Return Life": {
        name: "Return Life",
        pos: "f2",
        icon: icons["morale_returnlife"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Return target groupmate back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Divine Protection": {
        name: "Divine Protection",
        pos: "h2",
        icon: icons["morale_divineprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 15 seconds. They will absorb up to 120% RP + 1600 damage over the duration.`,
      },
      "Alter Fate": {
        name: "Alter Fate",
        pos: "i2",
        icon: icons["morale_alterfate"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Removes all afflictions and cripples from each groupmate within 100 feet. Also applies Return Life to each dead groupmate within 100ft.`,
      },
      "White Tower Master": {
        name: "White Tower Master",
        pos: "i4",
        icon: icons["abi_he_dominance"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`You generate all 4 sigils.`,
      },
      "Wall of Darting Steel": {
        name: "Wall of Darting Steel",
        pos: "i5",
        icon: icons["abi_he_wallofdartingsteel"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "6.0s channel",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain 100% dodge for the duration.`,
      },
      "Wings of Heaven": {
        name: "Wings of Heaven",
        pos: "i7",
        icon: icons["abi_he_wingsofheaven"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Gain a debuff for 5 seconds which reduces your mass by 8. Leap forward and apply Ensnared to up to 9 enemies within 20 feet of where you land.\n\nEnsnared reduces movement speed by 30% for 16 seconds.`,
      },
	  "Unleash the Winds": {
        name: "Unleash the Winds",
        pos: "i8",
        icon: icons["morale_unleashthewinds"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 96 enemies within a 20 feet location you select are knocked straight up into the air.`,
      },
      "Balance": {
        name: "Balance",
        pos: "a1",
        icon: icons["abi_he_windsprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Abilities generate one of four sigils: Eldrazor, Hoeth, Vaul, and Asuryan. Each sigil will last for 15 seconds until used. Abilities gain augmented effects whenever a sigil is consumed.`,
      },
      "Calming Wind": {
        name: "Calming Wind",
        pos: "b1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "65ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        blue: "Blade Enchantment",
        description: talentText`Generates 40 action points. Applies 5 second enchantment to target ally. Absorbs 7% RP + 76 damage.\n\nAsuryan - grants 1 stack of Enhanced Hardiness and Enhanced Fortitude.\nVaul - absorb is 225% more effective.`,
      },
	  "Dazzling Blade": {
        name: "Dazzling Blade",
        pos: "c1",
        icon: icons["abi_he_vortex"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "45 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Sigil of Hoeth",
        description: talentText`Applies a 6 second affliction to target enemy. Deals 9% SAP + 105 spiritual damage every 2 seconds.`,
      },
      "Ensorcelled Blow": {
        name: "Ensorcelled Blow",
        pos: "d1",
        icon: icons["abi_he_ensorcelledblow"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "36 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Sigil of Eldrazor",
        description: talentText`Deal 21% MAP + 280 elemental damage to target enemy.`,
      },
      "Dragon's Talon": {
        name: "Dragon's Talon",
        pos: "e1",
        icon: icons["abi_he_dragonstrike"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Sigil of Asuryan",
        description: talentText`Dispel one enchantment from target enemy.\n\nHoeth - Also dispel one blessing.\nEldrazor - Also deals 21% MAP + 280 elemental damage.`,
      },
      "Martial Prowess": {
        name: "Martial Prowess",
        pos: "f1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "40 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Sigil of Eldrazor",
        description: talentText`Grants target ally 1 stack of Enhanced Weapon Skill and Enhanced Initiative.`,
      },
      "Aethyric Dissipation": {
        name: "Aethyric Dissipation",
        pos: "g1",
        icon: icons["abi_he_instilfear"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "45 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Sigil of Hoeth",
        description: talentText`Applies Silenced and Inevitable to target enemy.\n\nSilence prevents the use of spells for 5 seconds.\nInevitable prevents the application of Disarmed and Silenced for 20 seconds.`,
      },
      "Eagle's Flight": {
        name: "Eagle's Flight",
        pos: "h1",
        icon: icons["abi_he_gracefulsweep"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "45 action points",
        range: "65ft range",
        cast: "1.5s cast",
        cooldown: "no cooldown",
        blue: "Sigil of Hoeth",
        description: talentText`Deals 30% SAP + 420 spiritual damage to target enemy.`,
      },
      "Cerulean Shield": {
        name: "Cerulean Shield",
        pos: "i1",
        icon: icons["abi_he_protectionofhoeth"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "8s cooldown",
        description: talentText`Gain an enchantment for 8 seconds. You will absorb 22% RP + 298 over the duration.`,
      },
	  "Phoenix Wing": {
        name: "Phoenix Wing",
        pos: "h4",
        icon: icons["abi_he_phoenixclaw"],
        maxRank: 1,
        reqPoints: 5,
        type: "skill",
        cost: "75 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Sigil of Vaul",
        description: talentText`Deals 8% MAP + 115 spiritual damage to up to 9 enemies within 30 feet of you.\n\nEldrazor - Applies a 9 second affliction to each enemy hit which deals 3% SAP + 12 spiritual damage every 3 seconds.\nHoeth - Interrupts each target hit.`,
      },
	  "Blessing of Heaven": {
        name: "Blessing of Heaven",
        pos: "g5",
        icon: icons["abi_he_bladeofleapinggold"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "65 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Sigil of Asuryan",
        description: talentText`Dispel one affliction from target ally.\n\nHoeth - Also dispels one cripple.\nEldrazor - Target gains a 8 second enchantment. For the duration, they will be healed for 6% RP + 68 each time they hit an enemy with an ability.`,
      },
	  "Whispering Wind": {
        name: "Whispering Wind",
        pos: "c6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "65 action points",
        range: "65ft range",
        cast: "2.5s cast",
        cooldown: "no cooldown",
        blue: "Sigil of Vaul",
        description: talentText`Applies a 8 second enchantment to target ally. For the duration, absorbs up to 60% RP + 801 damage.\n\nEldrazor - applies to an ally within 30 feet.\nHoeth - applies as a 15 second blessing.`,
      },
	  "Graceful Strike": {
        name: "Graceful Strike",
        pos: "d8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "50 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        blue: "Sigil of Asuryan",
        description: talentText`Applies Staggered and Unstoppable to target enemy.\n\nEldrazor - hits 2 other enemies within 30 feet.\nHoeth - increases range to 130 feet.\n\nStaggered prevents all control of the character for 9 seconds.\nUnstoppable prevents application of Knocked-down and Staggered effects for 30 seconds.`,
      },
      "Gifts of Isha": {
        name: "Gifts of Isha",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "100 action points",
        range: "65ft range self",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Applies a 5 second blessing to target ally. For the duration, absorb up to 35% RP + 476 damage. Consumes all sigils and applies to another target per sigil consumed.`,
      },
      "Flames of the Phoenix": {
        name: "Flames of Phoenix",
        pos: "f9",
        icon: icons["abi_he_flamesofthephoenix"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "100ft range",
        cast: "3.0s channel",
        cooldown: "30s cooldown",
        description: talentText`Deals 10% SAP + 50 elemental damage every 0.5 seconds to up to 48 enemies within a 30 foot area you select. Each time an enemy is hit by this ability they gain a stack that increases damage they take from this ability by 25% for 1 second. This ability deals no damage to targets that have cover from you.`,
      },
	  "Asuryan's Celerity": {
        name: "Asuryan's Celerity",
        pos: "a5",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you consume a Sigil of Asuryan, your next two spells cast within 8 seconds have a 0.5 second faster cast time.`,
      },
	  "Hoeth's Advancement": {
        name: "Hoeth's Advancement",
        pos: "e5",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you consume a Sigil of Hoeth, up to 3 groupmates within 100 feet gain 1 stack of Enhanced Intelligence.`,
      },
	  "Martial Mastery": {
        name: "Martial Mastery",
        pos: "b6",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Martial Prowess will apply to all groupmates within 65 feet.`,
      },
	  "Eagle's Protection": {
        name: "Eagle's Protection",
        pos: "h6",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Eagle's Flight will now apply an 8 second enchantment to your defensive target. For the duration, they will absorb up to 13% RP + 173 damage.`,
      },
	  "Mass Dissipation": {
        name: "Mass Dissipation",
        pos: "a7",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Aethyric Dissipation no longer generates a sigil but will hit 8 additional enemies within 65 feet.`,
      },
	  "Adept Movements": {
        name: "Adept Movements",
        pos: "g7",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Your absorb effects from Cerulean Shield, Eagle's Protection, Heaven's Blade, Whispering Wind, and Vaul's Buffer grant you 10% dodge.`,
      },
	  "Turbulent Winds": {
        name: "Turbulent Winds",
        pos: "f8",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Whenever you cast Dragon's Talon or Blessing of Heaven, you will gain 15 adrenaline per second for 3 seconds. In addition, each enemy you hit with Unleash the Winds will have their outgoing damage reduced by 20% for 10 seconds.`,
      },
	  "Balanced Signing": {
        name: "Balanced Signing",
        pos: "e3",
        icon: icons["noicon"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Your Sigils have a ${[
          5,
          10,
          15,
          20,
        ]}% chance to not be spent.`,
      },
	  "Blessing of Asuryan": {
        name: "Blessing of Asuryan",
        pos: "c5",
        icon: icons["abi_he_lawofage"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Gain ${[
          25,
          50,
          75,
          100,
        ]}% pushback immunity.`,
      },
	  "The White Bulwark": {
        name: "The White Bulwark",
        pos: "e6",
        icon: icons["abi_he_shieldofvalor"],
        maxRank: 4,
        reqPoints: 15,
        type: "passive",
        description: talentText`All of your absorb effects are ${[
          6,
          12,
          18,
          24,
          32,
        ]}% more effective.`,
      },
	  "Improved Blessing of Heaven": {
        name: "Improved Blessing of Heaven",
        pos: "g6",
        icon: icons["abi_he_bladeofleapinggold"],
        maxRank: 2,
        reqPoints: 15,
        prereq: "Blessing of Heaven",
		arrows: [
          { dir: "down", from: "g5", to: "g6" },
        ],
        type: "passive",
        description: talentText`Blessing of Heaven will apply to up to ${[
          1,
          2,
          3,
          4,
          5,
        ]} additional groupmates within 65 feet of you.`,
      },
	  "Engage": {
        name: "Engage",
        pos: "c7",
        icon: icons["abi_engage"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Enemies that you deal direct damage to will have their outgoing damage reduced by ${[
          2,
          4,
          6,
        ]}% for 5 seconds.`,
      },
	  "Touched by the Everqueen": {
        name: "Touched by the Everqueen",
        pos: "e7",
        icon: icons["noicon"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Whenever you consume a Sigil, you restore ${[
          "3% RP + 35",
          "6% RP + 70",
          "9% RP + 105",
        ]} health to all groupmates within 65 feet.`,
      },
	  "Restorative Protections": {
        name: "Restorative Protections",
        pos: "e8",
        icon: icons["noicon"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Your absorbs have a ${[
          5,
          15,
          30,
          50,
        ]}% chance to apply 1 stack of Enhanced Healing Received.`,
      },
	  
    },
  },
};