import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/greenskin"),
);
const icons = requireAll(require.context("../../assets/icons/greenskin"));

export const data: TalentData = {
  "Shoota": {
    name: "Shoota",
    background: backgrounds["shoota"],
    icon: icons["archetype_dps"],
    talents: {
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "Stop Hittin' Me!": {
        name: "Stop Hittin' Me!",
        pos: "a2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You have 1 less mass. In addition, each time you are attacked you will gain a stack that stacks up to 8 and lasts 6 seconds. Gain 5% movement speed for the duration.`,
      },
      "Waaagh": {
        name: "Waaagh",
        pos: "b2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that have this tactic gain 1 Fightiness, gain 3 Pyschic Energy, lose 1 Cowardice, or lose 1 Paranoia.`,
      },
      "Class Tactic 1": {
        name: "Class Tactic 1",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Gain 5 action points per second. Whenever you gain Cowardice, you will lose 8 action points per second for 3 seconds.`,
      },
      "Why Me?!": {
        name: "Why Me?!",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you gain Cowardice, you will gain 15% dodge for 3 seconds.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specbow"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Shoota equip a spear with a free offhand and a bow.`,
      },
	  "Disengage": {
        name: "Disengage",
        pos: "f2",
        icon: icons["morale_disengage"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`You knock yourself back away from target enemy.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Explosive Impact": {
        name: "Explosive Impact",
        pos: "h2",
        icon: icons["morale_explosiveimpact"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 10 seconds. Whenever you hit a target with a single-target ability, you will deal 10% RAP + 150 corporeal damage and 10% SAP + 150 elemental damage to up to 24 enemies within 20ft of the target.`,
      },
      "Unleash the Winds": {
        name: "Unleash the Winds",
        pos: "i2",
        icon: icons["morale_unleashthewinds"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 96 enemies within a 20ft location you select are knocked straight up into the air.`,
      },
      "Sever Nerve": {
        name: "Sever Nerve",
        pos: "i4",
        icon: icons["morale_severnerve"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Deals 50% MAP + 400 piercing damage to the target.`,
      },
      "Morale 2 Spec": {
        name: "Morale 2 Spec",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Ain't Dun Yet": {
        name: "Ain't Dun Yet",
        pos: "i7",
        icon: icons["abi_gs_gimmie"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Gain a buff for 20 seconds. For the duration, every second your Cowardice and Paranoia will lower by 1 and you will gain 20 action points.`,
      },
      "Instill Fear": {
        name: "Instill Fear",
        pos: "i8",
        icon: icons["abi_he_signaloursnipers"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "60ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Applies Marked to up to 96 enemies within a 30 feet area you select if they do not have cover from you.\nMarked reduces the target's damage reduction by 15% for 10 seconds.`,
      },
      "Cowardice": {
        name: "Cowardice",
        pos: "a1",
        icon: icons["abi_gs_notindaface"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Cowardice has a base of 0 and a maximum of 100. You gain 5 Cowardice each time you are hit by a melee ability, and lose 1 per second. Whenever you reach 100 cowardice you will gain Coward!\n\nCoward lasts for 15 seconds, reduces your cowardice by 10 per second as well as disabling and enabling different abilities.\n\nBleeding is a status effect that lasts 8 seconds and deals 2% MAP + 10 ichor damage every second.`,
      },
      "Shoot 'Em": {
        name: "Shoot 'Em",
        pos: "b1",
        icon: icons["abi_ge_shoot"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`Deals 6% RAP + 133 piercing damage to target enemy. Generates 40 action points.`,
      },
      "Plink": {
        name: "Plink",
        pos: "c1",
        icon: icons["abi_or_plink"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "36 action points",
        range: "100ft range",
        cast: "2.25s cast",
        cooldown: "no cooldown",
        description: talentText`Deals 37% RAP + 484 piercing damage to target enemy.`,
      },
      "Stabbity": {
        name: "Stabbity",
        pos: "d1",
        icon: icons["abi_or_stabbity"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled by Coward!",
        description: talentText`Deals 30% MAP + 387 piercing damage to target enemy removing 1 charge. Deals 37% MAP + 492 piercing damage to Bleeding targets. Gains 1 charge every 8 seconds with a maximum of 2 charges.`,
      },
      "Rotten Arrer": {
        name: "Rotten Arrer",
        pos: "e1",
        icon: icons["abi_gs_rottenarrer"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "30 action points",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`Applies a 10 second affliction to target enemy. For the duration, deals 12% RAP + 143 ichor damage every 2 seconds.`,
      },
      "Run N Shoot": {
        name: "Run N Shoot",
        pos: "f1",
        icon: icons["abi_gs_runnshoot"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Off the GCD\nRequires Coward!",
        description: talentText`Gain a buff for 10 seconds. For the duration, all of your abilities are castable while moving and you have +20% movement speed, but your accuracy is reduced by 30%.`,
      },
      "Drop That!": {
        name: "Drop That!",
        pos: "g1",
        icon: icons["abi_gs_dropthat"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "45 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Applies Disarmed and Inevitable to the target.\n\nDisarmed prevents the use of skills for 5 seconds.\nInevitable prevents the application of Disarmed and Silenced for 20 seconds.`,
      },
      "Cut Ya!": {
        name: "Cut Ya!",
        pos: "h1",
        icon: icons["abi_gs_cutya"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "65 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled by Cowardice",
        description: talentText`Applies a 10 second cripple to target enemy. For the duration deals 13% MAP + 168 ichor damage to target every 2 seconds.`,
      },
      "Don't Eat Me!": {
        name: "Don't Eat Me!",
        pos: "i1",
        icon: icons["abi_gs_stophittinme"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "15s cooldown",
        description: talentText`Target enemy will deal 50% less damage to you for 15 seconds. This effect is removed if you hit the target with an ability.\n\nIf you have Coward!, this ability does not apply to the target and instead applies to up to 9 enemies within 30 feet of you.`,
      },
	  "Wide Stabbin'": {
        name: "Wide Stabbin'",
        pos: "h4",
        icon: icons["abi_or_melee20"],
        maxRank: 1,
        reqPoints: 5,
        type: "skill",
        cost: "75 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled by Coward!",
        description: talentText`Deals 10% MAP + 126 piercing damage to up to 9 enemies within 30 feet in front of you.`,
      },
	  "Shrapnel Arrer": {
        name: "Shrapnel Arrer",
        pos: "h5",
        icon: icons["abi_gs_shrapnelarrer"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Wide Stabbin'",
		arrows: [
          { dir: "down", from: "h4", to: "h5" },
        ],
        type: "skill",
        cost: "60 action points",
        range: "100ft range",
        cast: "1.5s cast",
        cooldown: "no cooldown",
        description: talentText`Applies a 10 second affliction to up to 9 enemies within a 30 foot area you select. For the duration, deals 4% RAP + 43 ichor damage every 2 seconds.`,
      },
	  "Explodin' Arrer": {
        name: "Explodin' Arrer",
        pos: "c6",
        icon: icons["abi_gs_explodinarrer"],
        maxRank: 1,
        reqPoints: 15,
        type: "skill",
        cost: "75 action points",
        range: "100ft range",
        cast: "2.25s cast",
        cooldown: "no cooldown",
        description: talentText`Deals 18% RAP + 253 impact damage to up to 9 enemies within a 30 foot area you select.`,
      },
	  "Stop Runnin'": {
        name: "Stop Runnin'",
        pos: "d8",
        icon: icons["abi_or_foot01"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "65 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 11% RAP + 149 piercing damage to target enemy and applies Ensnared and Momentum.\n\nEnsnared reduces movement speed by 30% for 16 seconds.\nMomentum prevents the application of Ensnared for 8 seconds.`,
      },
      "Lots O' Arrers": {
        name: "Lots O' Arrers",
        pos: "d9",
        icon: icons["abi_gs_lotsofshootin"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "60 action points",
        range: "75ft range",
        cast: "3.0s channel",
        cooldown: "no cooldown",
        description: talentText`Deals 21% RAP + 294 piercing damage to target enemy every second.`,
      },
      "Penetrating Arrow": {
        name: "Penetrating Arrow",
        pos: "f9",
        icon: icons["abi_he_penetratingarrow"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "150 action points",
        range: "self",
        cast: "2.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Fire an arrow 65 feet in front of you. First enemy hit takes 5% RAP + 50 piercing damage. Each subsequent enemy takes additional damage.`,
      },
	  "Bleed Out": {
        name: "Bleed Out",
        pos: "a5",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Your Bleeding effect can now stack up to 3 times on a target. In addition, whenever Bleeding expires it has a 20% chance to reapply.`,
      },
	  "Yer Bleedin'": {
        name: "yer Bleedin'",
        pos: "b5",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Rotten Arrer and Cut Ya! now apply Bleeding to the target.`,
      },
	  "Tactic 4": {
        name: "T3",
        pos: "f6",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Rotten Arrer will now apply to two additional enemies within 15 feet of the target.`,
      },
	  "Aimin' Quickly": {
        name: "Aimin' Quickly",
        pos: "g6",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Plink has a 0.75 second faster cast time.`,
      },
	  "Bigger Arrers": {
        name: "Bigger Arrers",
        pos: "a7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Shrapnel Arrer and Explodin' Arrer now hit up to 24 targets.`,
      },
	  "Tactic 7": {
        name: "T6",
        pos: "g7",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Run N Shoot no longer reduces your accuracy, but the movement speed increase is halved.`,
      },
	  "Finish 'Em Off": {
        name: "Finish 'Em Off",
        pos: "f8",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Whenever you deal direct damage to an enemy under 50% health, you will deal an additional 7% RAP + 140 indirect ichor damage to them.`,
      },
	  "Sharpened Arrers": {
        name: "Sharpened Arrers",
        pos: "e3",
        icon: icons["abi_or_blood02"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Plink, Stabbity, and Explodin' Arrer have a ${[
          8,
          16,
          24,
          32,
          40,
        ]}% chance to apply Bleeding to the target(s).`,
      },
	  "Improved Basic Attack": {
        name: "Improved Basic Attack",
        pos: "e5",
        icon: icons["abi_ge_shoot"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Your basic attacks will deal ${[
          50,
          100,
		  150,
        ]}% additional damage.`,
      },
	  "Longa Range": {
        name: "Longa Range",
        pos: "d6",
        icon: icons["abi_or_range05"],
        maxRank: 3,
        reqPoints: 15,
        type: "passive",
        description: talentText`Increase the range on your bow skills by ${[
          5,
          10,
          15,
        ]}%.`,
      },
	  "Make It Last": {
        name: "Make It Last",
        pos: "e6",
        icon: icons["abi_or_melee18"],
        maxRank: 4,
        reqPoints: 15,
        type: "passive",
        description: talentText`Increase the durations of Rotten Arrer, Cut Ya!, and Shrapnel Arrer by ${[
          2,
          4,
          6,
          8,
        ]} seconds.`,
      },
	  "Bleedin' N Splodin'": {
        name: "Bleedin' N Splodin'",
        pos: "c7",
        icon: icons["abi_gs_explodinarrer"],
        maxRank: 3,
        reqPoints: 20,
        prereq: "Explodin' Arrer",
		arrows: [
          { dir: "down", from: "c6", to: "c7" },
        ],
        type: "passive",
        description: talentText`There is a ${[
          10,
          20,
          30,
        ]}% chance whenever Bleeding deals damage that your next Explodin' Arrer will be instant cast.`,
      },
	  "Open Wounds": {
        name: "Open Wounds",
        pos: "e7",
        icon: icons["abi_he_festeringwound"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Your Bleeding effects deal additional damage equal to ${[
          1,
          2,
          3,
          4,
          5,
        ]}% RAP.`,
      },
	  "Sharp Toofs": {
        name: "Sharp Toofs",
        pos: "e8",
        icon: icons["abi_or_blood01"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Increase your damage against bleeding targets by ${[
          3,
          6,
          9,
          12,
        ]}%.`,
      },
    },
  },
  "Squig Herder": {
    name: "Squig Herder",
    background: backgrounds["squig herder"],
    icon: icons["archetype_offsupport"],
    talents: {
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Stop Hittin' Me!": {
        name: "Stop Hittin' Me!",
        pos: "a2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You have 1 less mass. In addition, each time you are attacked you will gain a stack that stacks up to 8 and lasts 6 seconds. Gain 5% movement speed for the duration.`,
      },
      "Waaagh": {
        name: "Waaagh",
        pos: "b2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that have this tactic gain 1 Fightiness, gain 3 Pyschic Energy, lose 1 Cowardice, or lose 1 Paranoia.`,
      },
      "Class Tactic 1": {
        name: "Class Tactic 1",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Gain 5 action points per second. Whenever you gain Cowardice, you will lose 8 action points per second for 3 seconds.`,
      },
      "Why Me?!": {
        name: "Why Me?!",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you gain Cowardice, you will gain 15% dodge for 3 seconds.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specspear"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Squig Herders equip one-handed spears.`,
      },
	  "Sever Nerve": {
        name: "Sever Nerve",
        pos: "f2",
        icon: icons["morale_severnerve"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Deals 50% MAP + 400 piercing damage to the target.`,
      },
      "Broad Swings": {
        name: "Broad Swings",
        pos: "g2",
        icon: icons["morale_broadswings"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a  buff for 10 seconds. Your single target abilities will target two additional enemies within 15ft in front of you.`,
      },
      "Force of Will": {
        name: "Force of Will",
        pos: "h2",
        icon: icons["morale_forceofwill"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 10 seconds. Action point costs are reduced by 75% for the duration.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "Morale 1 Class": {
        name: "Morale 1 Class",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 2 Spec": {
        name: "Morale 2 Spec",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Ain't Dun Yet": {
        name: "Ain't Dun Yet",
        pos: "i7",
        icon: icons["abi_gs_gimmie"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Gain a buff for 20 seconds. For the duration, every second your Cowardice and Paranoia will lower by 1 and you will gain 20 action points.`,
      },
      "Morale 4 Spec": {
        name: "Morale 4 Spec",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Cowardice and Basic Squig": {
        name: "Cowardice and Basic Squig",
        pos: "a1",
        icon: icons["abi_gs_notindaface"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Cowardice has a base of 0 and a maximum of 100. You gain 5 Cowardice each time you are hit by a melee ability, and lose 1 per second. Whenever you reach 100 cowardice you will gain Coward!\n\nCoward lasts for 15 seconds, reduces your cowardice by 10 per second as well as disabling and enabling different abilities.\n\nBasic Squigs are uncontrolled summons that are aggressive to Order and friendly to Destro. They will attack at random, have stats independent of yours, will not follow you, and disappear after 15 seconds.`,
      },
      "Goblin Basic Attack": {
        name: "Goblin Basic Attack",
        pos: "b1",
        icon: icons["abi_or_melee05"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled By Coward!",
        description: talentText`Deals 4% MAP + 30 piercing damage to target enemy. Generates 22 action points.`,
      },
      "Ability 1": {
        name: "Ability 1",
        pos: "c1",
        icon: icons["abi_or_nofightinback"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "36 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled by Coward!",
        description: talentText`Deals 21% MAP + 280 elemental damage to target enemy.\n\nAugmented: counts as a basic attack.`,
      },
      "Stabbity": {
        name: "Stabbity",
        pos: "d1",
        icon: icons["abi_or_stabbity"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled by Coward!",
        description: talentText`Deals 30% MAP + 387 piercing damage to target enemy removing 1 charge. Deals 37% MAP + 492 piercing damage to Bleeding targets. Gains 1 charge every 8 seconds with a maximum of 2 charges.`,
      },
      "Summon Horned/Spiked/Gas Squig": {
        name: "Summon Horned/Spiked/Gas Squig",
        pos: "e1",
        icon: icons["abi_or_squig12"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "1.0s cast",
        cooldown: "90s cooldown",
        description: talentText`This is 3 different abilities with there own cooldowns. Cooldown starts when that squig dies. Unless otherwise stated, they have 100% of your stats but with a base health of 2000. You can only have one of these three squigs active.\n\nHorned: attacks in melee. Wounds 150%, Armor 150%.\nSpiked: attacks at 100ft range. Wounds 75%, Armor 0%.\nGas: attacks at 75ft range. Armor 75%.`,
      },
      "Ability 2": {
        name: "Ability 2",
        pos: "f1",
        icon: icons["abi_or_squig13"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Requires Pet",
        description: talentText`Commands your pet to attack its current target.\n\nHorned/Battle: deals 27% MAP + 348 impact damage.\nSpiked: deals 17% RAP + 224 piercing damage.\nGas: deals 20% RAP + 251 ichor damage.`,
      },
      "Ability 3": {
        name: "Ability 3",
        pos: "g1",
        icon: icons["abi_or_squig05"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "15s cooldown",
        blue: "Requires Pet",
        description: talentText`Applies an effect to your squig's target.\n\nHorned: applies Knocked-down and Unstoppable.\nSpiked: applies Ensnared and Momentum.\nGas: applies Silenced and Inevitable.`,
      },
      "Ability 4": {
        name: "Ability 4",
        pos: "h1",
        icon: icons["abi_or_squig11"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Your pet gains an 8 second blessing. For the duration, they gain 25% damage reduction.\n\nIf you are in Squig Armor, this will apply to you as well.\nIf you are a Coward!, this will apply to you but grant 30% movement speed instead.`,
      },
      "Vigilance": {
        name: "Vigilance",
        pos: "i1",
        icon: icons["abi_vigilance"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        description: talentText`Your damage reduction is increased by 50% but your outgoing damage is reduced by 90% for 7 seconds.`,
      },
	  "Wide Stabbin'": {
        name: "Wide Stabbin'",
        pos: "h4",
        icon: icons["abi_or_melee20"],
        maxRank: 1,
        reqPoints: 5,
        type: "skill",
        cost: "75 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled by Coward!",
        description: talentText`Deals 10% MAP + 126 piercing damage to up to 9 enemies within 30 feet in front of you.`,
      },
	  "Spore Toss": {
        name: "Spore Toss",
        pos: "c5",
        icon: icons["abi_or_squig15"],
        maxRank: 1,
        reqPoints: 10,
        type: "skill",
        cost: "40 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Requires Coward!",
        description: talentText`Deals 16% RAP + 205 ichor damage to target enemy. Has a 20% chance to summon a Basic Squig.`,
      },
	  "Explosive Squig": {
        name: "Explosive Squig",
        pos: "d6",
        icon: icons["abi_or_squig09"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "50 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Summon an explosive squig that promptly explodes dealing 7% RAP + 102 ichor damage to up to 9 enemies within 30 feet of you.`,
      },
	  "Ability 5": {
        name: "Ability 5",
        pos: "c8",
        icon: icons["abi_or_squig07"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "15s cooldown",
        blue: "Requires Pet",
        description: talentText`Your pet applies an effect to its current target.\n\nSpiked: applies Marked. Marked reduces a target's damage reduction by 15% for 10 seconds.\nSpiked: applies a 10 second affliction. For the duration, target mass is reduced by 2.\nGas: applies a 10s cripple. Target has 33% longer cast times.`,
      },
      "Squigpede": {
        name: "Squigpede",
        pos: "d9",
        icon: icons["abi_or_squig16"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "100 action points",
        range: "self",
        cast: "1.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Summons 4 basic squigs.`,
      },
      "Sneaky Waaagh": {
        name: "Sneaky Waaagh",
        pos: "f9",
        icon: icons["abi_gs_windupdawaaagh"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "75ft range",
        cast: "1.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Up to 10 enemies within a 30 foot area you select gain a debuff for 1 second if they do not have cover from you. At the end of the duration, they apply 1 stack of a 6 second debuff to up to 96 enemies within 30 feet of them. Enemies lose 5% damage reduction per stack.`,
      },
	  "Tactic 1": {
        name: "Tactic 1",
        pos: "a5",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Stabbity now has 5 charges.`,
      },
	  "Tactic 5": {
        name: "Tactic 5",
        pos: "g5",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Cooldown on Summon Horned Squig is now 10 seconds, but you can no longer summon spiked or gas squigs.`,
      },
	  "Tactic 15": {
        name: "Tactic 15",
        pos: "c6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Spore Toss",
		arrows: [
          { dir: "down", from: "c5", to: "c6" },
        ],
        type: "career tactic",
        description: talentText`Spore Toss no longer requires Coward! and will always summon a basic squig, but now has a cooldown of 10 seconds.`,
      },
	  "Tactic 3": {
        name: "Tactic 3",
        pos: "f6",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Ability 4 always provides the movement speed buff, but never applies the damage reduction.`,
      },
	  "Tactic 2": {
        name: "Tactic 2",
        pos: "a7",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Ability 2 will now apply a stack of Reduced Resistance to target enemy. Horned - Impact, Spiked - Piercing, Gas - Ichor.`,
      },
	  "Tactic 14": {
        name: "Tactic 14",
        pos: "e7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Wide Stabbin', Explosive Squig, and Ability 2 now hit up to 24 enemies. Ability 2 will deal 66% less damage.`,
      },
	  "Tactic 6": {
        name: "Tactic 6",
        pos: "g8",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Whenever you hit an enemy with a melee attack, the next ability 2 against that target will deal 33% increased damage.`,
      },
	  "Gotta Herd Em All": {
        name: "Gotta Herd Em All",
        pos: "e3",
        icon: icons["abi_or_squig16"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Your melee attacks have a ${[
          5,
          10,
          15,
          20,
          25,
        ]}% chance to summon a basic squig.`,
      },
	  "Passive 1": {
        name: "Passive 1",
        pos: "c4",
        icon: icons["abi_or_squig13"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`You have a ${[
          5,
          10,
        ]}% chance on any ability use to make the next Ability 2 cost no action points.`,
      },
	  "Passive 2": {
        name: "Passive 2",
        pos: "e5",
        icon: icons["abi_gs_donthitme"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`You have a ${[
          50,
          100,
        ]}% chance to lose 1 Cowardice whenever you use Ability 2.`,
      },
	  "Passive 3": {
        name: "Passive 3",
        pos: "e6",
        icon: icons["abi_or_squig09"],
        maxRank: 4,
        reqPoints: 15,
        prereq: "Explosive Squig",
		arrows: [
          { dir: "right", from: "d6", to: "e6" },
        ],
        type: "passive",
        description: talentText`You have a ${[
          15,
          30,
          45,
          60,
        ]}% chance whenever you summon a basic squig to also summon an Explosive Squig.`,
      },
	  "Improved Vigilance": {
        name: "Improved Vigilance",
        pos: "g6",
        icon: icons["abi_vigilance"],
        maxRank: 3,
        reqPoints: 15,
        type: "passive",
        description: talentText`Vigilance now only reduces your outgoing damage by ${[
          75,
		  60,
          45,
        ]}%.`,
      },
	  "Passive 5": {
        name: "Passive 5",
        pos: "b7",
        icon: icons["abi_or_stabbity"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Ability 2 has a ${[
          10,
          20,
          30,
          40,
          50,
        ]}% chance to generate 1 charge of Stabbity.`,
      },
	  "Passive 4": {
        name: "Passive 4",
        pos: "h7",
        icon: icons["abi_or_melee20"],
        maxRank: 3,
        reqPoints: 20,
        prereq: "Wide Stabbin'",
		arrows: [
          { dir: "down", from: "h4", to: "h7" },
        ],
        type: "passive",
        description: talentText`Wide Stabbin' deals ${[
          5,
          10,
          15,
        ]}% more damage.`,
      },
	  "Passive 6": {
        name: "Passive 6",
        pos: "e8",
        icon: icons["abi_or_squig08"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Your Horned, Spiked, and Gas squigs gain an additional ${[
          75,
          150,
          225,
          300,
        ]}% of your HP4.`,
      },
    },
  },
  "Squig Rider": {
    name: "Squig Rider",
    background: backgrounds["squig rider"],
    icon: icons["archetype_tank"],
    talents: {
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Stop Hittin' Me!": {
        name: "Stop Hittin' Me!",
        pos: "a2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You have 1 less mass. In addition, each time you are attacked you will gain a stack that stacks up to 8 and lasts 6 seconds. Gain 5% movement speed for the duration.`,
      },
      "Waaagh": {
        name: "Waaagh",
        pos: "b2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that have this tactic gain 1 Fightiness, gain 3 Pyschic Energy, lose 1 Cowardice, or lose 1 Paranoia.`,
      },
      "Class Tactic 1": {
        name: "Class Tactic 1",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Gain 5 action points per second. Whenever you gain Cowardice, you will lose 8 action points per second for 3 seconds.`,
      },
      "Why Me?!": {
        name: "Why Me?!",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you gain Cowardice, you will gain 15% dodge for 3 seconds.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specadvancedshield"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Squig Riders equip spears and shields.`,
      },
	  "Hedgehog": {
        name: "Hedgehog",
        pos: "f2",
        icon: icons["morale_hedgehog"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`All groupmates within 100ft gain 3 stacks of Enhanced Block.`,
      },
      "Champion's Challenge": {
        name: "Champion's Chalenge",
        pos: "g2",
        icon: icons["morale_grapple"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Applies a debuff to target enemy and yourself for 10 seconds. Movement speed is reduced to 0 for the duration.`,
      },
      "Distracting Bellow": {
        name: "Distracting Bellow",
        pos: "h2",
        icon: icons["morale_distractingbellow"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Up to 48 enemies within 30ft of you receive a debuff. For 10 seconds, they cannot benefit from Cover.`,
      },
      "Immaculate Defense": {
        name: "Immaculate Defense",
        pos: "i2",
        icon: icons["morale_immaculatedefense"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Groupmates within 100ft gain 25 stacks of a buff for 20 seconds. Each stack grants 3% damage reduction. A stack is removed each time they are attacked by an ability; 4 additional stacks are removed if the ability is single target.`,
      },
      "Morale 1 Class": {
        name: "Morale 1 Class",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 2 Spec": {
        name: "Morale 2 Spec",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Ain't Dun Yet": {
        name: "Ain't Dun Yet",
        pos: "i7",
        icon: icons["abi_gs_gimmie"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Gain a buff for 20 seconds. For the duration, every second your Cowardice and Paranoia will lower by 1 and you will gain 20 action points.`,
      },
      "Morale 4 Spec": {
        name: "Morale 4 Spec",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Cowardice": {
        name: "Cowardice",
        pos: "a1",
        icon: icons["abi_gs_notindaface"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Cowardice has a base of 0 and a maximum of 100. You gain 5 Cowardice each time you are hit by a melee ability, and lose 1 per second. Whenever you reach 100 cowardice you will gain Coward!\n\nCoward lasts for 15 seconds, reduces your cowardice by 10 per second as well as disabling and enabling different abilities.`,
      },
      "Goblin Basic Attack": {
        name: "Goblin Basic Attack",
        pos: "b1",
        icon: icons["abi_or_melee05"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled By Coward!",
        description: talentText`Deals 4% MAP + 30 piercing damage to target enemy. Generates 22 action points.`,
      },
      "Ability 1": {
        name: "Ability 1",
        pos: "c1",
        icon: icons["abi_or_nofightinback"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "36 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled by Coward!",
        description: talentText`Deals 21% MAP + 280 elemental damage to target enemy.\n\nAugmented: counts as a basic attack.`,
      },
      "Stabbity": {
        name: "Stabbity",
        pos: "d1",
        icon: icons["abi_or_stabbity"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled by Coward!",
        description: talentText`Deals 30% MAP + 387 piercing damage to target enemy removing 1 charge. Deals 37% MAP + 492 piercing damage to Bleeding targets. Gains 1 charge every 8 seconds with a maximum of 2 charges.`,
      },
      "Summon Battle Squig": {
        name: "Summon Battle Squig",
        pos: "e1",
        icon: icons["abi_or_squig01"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
		blue: "Cannot be in Squig Armor",
        description: talentText`Summons a Battle Squig with all of your stats and 4000 base health.`,
      },
      "Squig Armor": {
        name: "Squig Armor",
        pos: "f1",
        icon: icons["abi_gs_squigarmor"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Requires Pet",
        description: talentText`Engulf yourself in your Battle Squig gaining access to new abilities and effects. Your pet is "unsummoned" while Squig Armor is active, and resummoned whenever you leave it. You will leave Squig Armor when you become a Coward!`,
      },
      "Ability 7": {
        name: "Ability 7",
        pos: "g1",
        icon: icons["abi_or_squig14"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "75 action points",
        range: "65ft range",
        cast: "3.0s channel",
        cooldown: "30s cooldown",
        blue: "Requires Squig Armor\nCastable While Moving",
        description: talentText`Caster has their movement speed reduced by 15%. After 2.5 seconds, target enemy is Pulled and Immovable is applied to them.\n\nImmovable prevents aplication of Rooted, Knockback, and Pull effects for 20 seconds.`,
      },
      "Ability 6": {
        name: "Ability 6",
        pos: "h1",
        icon: icons["abi_or_squig02"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "30s cooldown",
        description: talentText`For the next 6 seconds, your squig will get hit by all abilities that would hit groupmates within 30 feet of it. If you are in Squig Armor, the abilities are redirected to you instead.`,
      },
      "Ability 4": {
        name: "Ability 4",
        pos: "i1",
        icon: icons["abi_or_squig11"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Your pet gains an 8 second blessing. For the duration, they gain 25% damage reduction.\n\nIf you are in Squig Armor, this will apply to you as well.\nIf you are a Coward!, this will apply to you but grant 30% movement speed instead.`,
      },
	  "Wide Stabbin'": {
        name: "Wide Stabbin'",
        pos: "h4",
        icon: icons["abi_or_melee20"],
        maxRank: 1,
        reqPoints: 5,
        type: "skill",
        cost: "75 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled by Coward!",
        description: talentText`Deals 10% MAP + 126 piercing damage to up to 9 enemies within 30 feet in front of you.`,
      },
	  "Ability 2": {
        name: "Ability 2",
        pos: "c5",
        icon: icons["abi_or_squig13"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Requires Pet",
        description: talentText`Commands your pet to attack its current target.\n\nHorned/Battle: deals 27% MAP + 348 impact damage.\nSpiked: deals 17% RAP + 224 piercing damage.\nGas: deals 20% RAP + 251 ichor damage.`,
      },
	  "Tastes Like Stuntie": {
        name: "Tastes Like Stuntie",
        pos: "h6",
        icon: icons["abi_squig_bite"],
        maxRank: 1,
        reqPoints: 15,
        type: "skill",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Requires Squig Armor",
        description: talentText`Deals 19% MAP + 262 piercing damage to target enemy. You are healed for 100% of the damage dealt.`,
      },
	  "Ability 8": {
        name: "Ability 8",
        pos: "d8",
        icon: icons["abi_squig_bounce"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "80 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Knocks back up to 9 enemies within 30 feet of you if you are in Squig Armor. If you pet is active, the effect is centered on your pet, but the pet dies.`,
      },
      "Ability 9": {
        name: "Ability 9",
        pos: "d9",
        icon: icons["abi_squig_shout"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "75 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Requires Squig Armor",
        description: talentText`Deals 10% MAP + 126 ichor damage to up to 24 enemies within 30 feet of you. You lose Squig Armor and knock yourself backwards.`,
      },
      "Sneaky Waaagh": {
        name: "Sneaky Waaagh",
        pos: "f9",
        icon: icons["abi_gs_windupdawaaagh"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "75ft range",
        cast: "1.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Up to 10 enemies within a 30 foot area you select gain a debuff for 1 second if they do not have cover from you. At the end of the duration, they apply 1 stack of a 6 second debuff to up to 96 enemies within 30 feet of them. Enemies lose 5% damage reduction per stack.`,
      },
	  "Tactic 1": {
        name: "Tactic 1",
        pos: "a5",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Stabbity now has 5 charges.`,
      },
	  "Tactic 10": {
        name: "Tactic 10",
        pos: "g5",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Your Battle Squig takes 90% less damage from AoE attacks.`,
      },
	  "Tactic 3": {
        name: "Tactic 3",
        pos: "b6",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Ability 4 always provides the movement speed buff, but never applies the damage reduction.`,
      },
	  "Tactic 13": {
        name: "Tactic 13",
        pos: "e6",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`While in Squig Armor, Stabbity will hit 2 additional enemies within 20 feet.`,
      },
	  "Tactic 8": {
        name: "Tactic 8",
        pos: "a7",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`If you drop below 20% maximum health while in Squig Armor, you will be healed for 20,000, lose Squig Armor, and your pet will be placed on cooldown.`,
      },
	  "Tactic 12": {
        name: "Tactic 12",
        pos: "h7",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Tastes Like Stuntie",
		arrows: [
          { dir: "down", from: "h6", to: "h7" },
        ],
        type: "career tactic",
        description: talentText`Tastes Like Stuntie will deal 50% less damage but will now heal you for 300% of the damage dealt.`,
      },
	  "Tactic 11": {
        name: "Tactic 11",
        pos: "f8",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Gain 2 mass while in Squig Armor.`,
      },
	  "Passive 7": {
        name: "Passive 7",
        pos: "e3",
        icon: icons["abi_squig_ardnoggin"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`While in Squig Armor, you will lose 1 Cowardice every ${[
          5,
          4,
          3,
        ]} seconds.`,
      },
	  "Improved Basic Attack": {
        name: "Improved Basic Attack",
        pos: "b4",
        icon: icons["abi_or_melee15"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Your basic attacks will deal ${[
          75,
          150,
          225,
        ]}% additional damage.`,
      },
	  "Passive 2": {
        name: "Passive 2",
        pos: "e5",
        icon: icons["abi_gs_donthitme"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`You have a ${[
          50,
          100,
        ]}% chance to lose 1 Cowardice whenever you use Ability 2.`,
      },
	  "Passive 8": {
        name: "Passive 8",
        pos: "d6",
        icon: icons["abi_or_squig11"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`The duration on Ability 4 is increased by ${[
          1,
          2,
          3,
          4,
          5,
        ]} seconds.`,
      },
	  "Band Together": {
        name: "Band Together",
        pos: "f6",
        icon: icons["abi_bandtogether"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Groupmates within 30 feet of you will have their damage reduction increased by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%. This effect is supressed for 5 seconds whenever you are hit by a single-target ability.`,
      },
	  "Engage": {
        name: "Engage",
        pos: "b7",
        icon: icons["abi_engage"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Enemies that you deal direct damage to will have their outgoing damage reduced by ${[
          2,
          4,
          6,
        ]}% for 5 seconds.`,
      },
	  "Passive 9": {
        name: "Passive 9",
        pos: "e7",
        icon: icons["abi_squig_spikeshield"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Gain ${[
          5,
          10,
          15,
          20,
          25,
        ]}% maximum health and armor while in Squig Armor.`,
      },
	  "Passive 10": {
        name: "Passive 10",
        pos: "e8",
        icon: icons["abi_or_squig02"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`The cooldown on Ability 6 is reduced by ${[
          2,
          4,
          6,
          8,
        ]} seconds.`,
      },
    },
  },
};