import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/chaos"),
);
const icons = requireAll(require.context("../../assets/icons/chaos"));

export const data: TalentData = {
  "Zealot": {
    name: "Zealot",
    background: backgrounds["placeholder"],
    icon: icons["archetype_healer"],
    talents: {
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "What a Rush": {
        name: "What a Rush",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`The action point cost of your skills is reduced by 33% on allies that are lower than 40% health.`,
      },
      "Follower of Chaos": {
        name: "Follower of Chaos",
        pos: "a2",
        icon: icons["tac_race_chaos"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You are immune to the negative effects of corruption.`,
      },
      "Bleed Corruption": {
        name: "Bleed Corruption",
        pos: "b2",
        icon: icons["tac_race_chaos"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you are hit by an enemy ability, apply a random corruption to them.`,
      },
      "Drink Deeply": {
        name: "Drink Deeply",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Every 6 seconds, gain a 5 second enchantment. For the duration, your next spell will not cost Blood Sacrifice.`,
      },
      "Plasma Reserves": {
        name: "Plasma Reserves",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Reduces the damage of Blood Sacrifice by 33%.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specdagger"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Zealots equip ritual daggers and fetishes.`,
      },
      "Changer's Touch": {
        name: "Changer's Touch",
        pos: "i4",
        icon: icons["abi_ch_mutatingrelease"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Applies 3 stacks of Reduced Corporeal Resistance, Reduced Elemental Resistance, and Reduced Spiritual Resistance to target enemy.`,
      },
      "Blood Be Gone": {
        name: "Blood Be Gone",
        pos: "i5",
        icon: icons["abi_ch_ritualofvulnerability"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Removes all stacks of Blood Sacrifice from you.`,
      },
      "Winds of Insanity": {
        name: "Winds of Insanity",
        pos: "i7",
        icon: icons["abi_ch_windblock"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "3.0s channel",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`For the duration you lose 3 mass. Every second up to 12 enemies within 20 feet of you are knocked back.`,
      },
      "Eye of Sheerian": {
        name: "Eye of Sheerian",
        pos: "i8",
        icon: icons["abi_ch_eyesofsheerian"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 96 allies within 100 feet of you gain 2 stacks of Enhanced for all resistances.`,
      },
	  "Return Life": {
        name: "Return Life",
        pos: "f2",
        icon: icons["morale_returnlife"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Return target groupmate back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Divine Protection": {
        name: "Divine Protection",
        pos: "h2",
        icon: icons["morale_divineprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 15 seconds. They will absorb up to 120% RP + 1600 damage over the duration.`,
      },
      "Alter Fate": {
        name: "Alter Fate",
        pos: "i2",
        icon: icons["morale_alterfate"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Removes all afflictions and cripples from each groupmate within 100 feet. Also applies Return Life to each dead groupmate within 100ft.`,
      },
      "Blood Sacrifice": {
        name: "Blood Sacrifice",
        pos: "a1",
        icon: icons["abi_ch_ravage"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`You are healed for 25% of all damage you deal.\n\nBlood Sacrifice stacks up to 100 times and lasts 6 seconds. For the duration, you take 6% wounds + 90 ichor damage every second.\n\nTzeentch Corruption - Gain 2% reduced cast time and 1 second cooldown reduction. Lose 250 spiritual resistance and 115 sagacity.`,
      },
      "Flash of Chaos": {
        name: "Flash of Chaos",
        pos: "b1",
        icon: icons["abi_ch_ritualoflethargy"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Restore 2% RP + 15 health to target ally. Applies 1 stack of Tzeentch Corruption to caster.`,
      },
      "Warp Reality": {
        name: "Warp Reality",
        pos: "c1",
        icon: icons["abi_ch_warpreality"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "1.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 2 Blood Sacrifice",
        description: talentText`Deals 15% SAP + 201 spiritual damage to the target. Target and caster gain 1 stack of Tzeentch Corruption.`,
      },
      "Dark Medicine": {
        name: "Dark Medicine",
        pos: "d1",
        icon: icons["abi_ch_darkmedicine"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "2.5s cast",
        cooldown: "10s cooldown",
        description: talentText`Restore 37% RP + 503 health to target ally.`,
      },
      "Manipulation": {
        name: "Manipulation",
        pos: "e1",
        icon: icons["abi_ch_quellthespirit"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Off the GCD",
        description: talentText`You lose all stacks of Tzeentch Corruption and gain 15 action points per stack lost.`,
      },
      "Daemonic Restoration": {
        name: "Daemonic Restoration",
        pos: "f1",
        icon: icons["abi_ch_demonicresistance"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3 Blood Sacrifice",
        description: talentText`Target ally gains a 12 second enchantment. For the duration, restore 7% RP + 102 health to the target every 3 seconds.`,
      },
      "Aethyric Shock": {
        name: "Aethyric Shock",
        pos: "g1",
        icon: icons["abi_ch_aethyricshock"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "65 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "30s cooldown",
        description: talentText`Applies Staggered and Unstoppable to target enemy.\n\nStaggered prevents all control of the character for 9 seconds unless attacked.\nUnstoppable prevents application of Knocked-down and Staggered effects for 30 seconds.`,
      },
      "Harbinger of Doom": {
        name: "Harbinger of Doom",
        pos: "h1",
        icon: icons["abi_ch_swataside"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        blue: "blue text",
        description: talentText`Applies a buff to target groupmate. You can only have 1 active. Whenever you are healed by your %lifetap, the target is healed for 50% of the amount.`,
      },
      "Dust of Pandemonium": {
        name: "Dust of Pandemonium",
        pos: "i1",
        icon: icons["abi_ch_dustofpandemonium"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "2.5s cast",
        cooldown: "no cooldown",
        blue: "Costs 3 Blood Sacrifice",
        description: talentText`Applies an 18 second affliction to target enemy. For the duration, they take 34% SAP + 440 elemental damage every 3 seconds.`,
      },
	  "Leaping Alteration": {
        name: "Leaping Alteration",
        pos: "b4",
        icon: icons["abi_ch_mirrorofmadness"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "1.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 5 Blood Sacrifice",
        description: talentText`Restores 13% RP + 155 health to target ally and one other ally within 30 feet of the target.`,
      },
	  "Tzeentch's Reflection": {
        name: "Tzeentch's Reflection",
        pos: "h5",
        icon: icons["abi_ch_theftofwords"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Applies 1 stack of Tzeentch Corruption, Silenced, and Inevitable to target enemy.\n\nSilenced prevents the use of spells for 5 seconds.\nInevitable prevents the application of Disarmed and Silenced for 20 seconds.`,
      },
	  "Rite of Agony": {
        name: "Rite of Agony",
        pos: "g6",
        icon: icons["abi_ch_hamstring"],
        maxRank: 1,
        reqPoints: 15,
        type: "skill",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Costs 1 Blood Sacrifice\nOff the GCD",
        description: talentText`Target ally gains 1 stack of Enhanced Critical Hit Rating and 1 stack of Khorne Corruption.`,
      },
	  "Tzeentch's Cry": {
        name: "Tzeentch's Cry",
        pos: "g8",
        icon: icons["abi_ch_mouthoftzeentch"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "no cost",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "6s cooldown",
        blue: "Costs 4 Blood Sacrifice",
        description: talentText`Deals 28% SAP + 375 spiritual damage to target enemy.`,
      },
      "Tzeentch Shall Remake You": {
        name: "Tzeentch Shall Remake You",
        pos: "d9",
        icon: icons["abi_ch_tzeentchshallremakeyou"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "100 action points",
        range: "self",
        cast: "3.0s cast",
        cooldown: "15s cooldown",
        description: talentText`Restores 22% RP + 440 health to all groupmates within 100 feet of you. Will not heal caster.`,
      },
      "The Great Change": {
        name: "The Great Change",
        pos: "f9",
        icon: icons["abi_ch_riteofresilence"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "self",
        cast: "1.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Deals 13% SAP + 186 spiritual damage to up to 48 enemies within 30 feet in front of you. For each target hit that did not have Cover, all groupmates within 150 feet gain a stack. The stacks heal for 6% RP + 8 each at the end of their 3 second duration.`,
      },
	  "Champion of Change": {
        name: "Champion of Change",
        pos: "a5",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Double the benefits of Tzeentch Corruption on you.`,
      },
	  "Vaulting Alterations": {
        name: "Vaulting Alterations",
        pos: "b5",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Leaping Alteration",
		arrows: [
          { dir: "down", from: "b4", to: "b5" },
        ],
        type: "career tactic",
        description: talentText`Leaping Alteration will heal a 3rd ally within 30 feet of the target.`,
      },
	  "Daemonic Fortitude": {
        name: "Daemonic Fortitude",
        pos: "b6",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Each time Daemonic Restoration heals a target, they have a 50% chance to gain 1 stack of Enhanced Toughness.`,
      },
	  "Bloody Restoration": {
        name: "Bloody Restoration",
        pos: "h6",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Daemonic Restoration now costs 4 Blood Sacrifice but lasts 6 more seconds.`,
      },
	  "Tzeentch's Freshment": {
        name: "Tzeentch's Refreshment",
        pos: "a7",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Groupmates under the effect of Harbinger of Doom now are healed for 100% of your lifetap.`,
      },
	  "Shared Agony": {
        name: "Shared Agony",
        pos: "g7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Rite of Agony",
		arrows: [
          { dir: "down", from: "g6", to: "g7" },
        ],
        type: "career tactic",
        description: talentText`Rite of Agony will always apply to you in addition to your target.`,
      },
	  "Blessing of Chaos": {
        name: "Blessing of Chaos",
        pos: "d8",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Whenever you critically heal a target, they will gain an enchantment for 8 seconds. For the duration their AP regen is increased by 5.`,
      },
	  "Mark of Remaking": {
        name: "Mark of Remaking",
        pos: "e3",
        icon: icons["abi_ch_ravage"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increase your life tap by ${[
          5,
          10,
          15,
          20,
          25,
        ]}%.`,
      },
	  "Improved Flash of Chaos": {
        name: "Improved Flash of Chaos",
        pos: "h4",
        icon: icons["abi_ch_ritualoflethargy"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Flash of Chaos will restore ${[
          50,
          10,
          150,
          200,
          250,
        ]}% additional health.`,
      },
	  "Sanguination of Chaos": {
        name: "Sanguination of Chaos",
        pos: "c6",
        icon: icons["abi_ch_powervortex"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Flash of Chaos has a ${[
          7,
          15,
        ]}% chance to apply a 5 second enchantment to caster. For the duration, the next skill will not cost Blood Sacrifice.`,
      },
	  "Improved Warp Reality": {
        name: "Improved Warp Reality",
        pos: "e6",
        icon: icons["abi_ch_warpreality"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Increases the damage of Warp Reality by ${[
          4,
          8,
          12,
          16,
          20,
        ]}%.`,
      },
	  "Settling Dust": {
        name: "Settling Dust",
        pos: "c7",
        icon: icons["abi_ch_dustofpandemonium"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Reduces the cast time of Dust of Pandemonium by ${[
          0.1,
          0.2,
          0.3,
        ]} seconds.`,
      },
	  "Spoonful of Chaos": {
        name: "Spoonful of Chaos",
        pos: "e7",
        icon: icons["abi_ch_darkmedicine"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Reduces the cast time of Dark Medicine by ${[
          0.1,
          0.2,
          0.3,
        ]} seconds.`,
      },
	  "Blood in Mouth": {
        name: "Blood of Mouth",
        pos: "f8",
        icon: icons["abi_ch_gleanmagic"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Each time you take damage from Blood Sacrifice, you have a ${[
          25,
          50,
          75,
          100,
        ]}% chance to restore health equal to the damage to a groupmate within 100 feet of you.`,
      },
    },
  },
  "Hedon": {
    name: "Hedon",
    background: backgrounds["placeholder"],
    icon: icons["archetype_defsupport"],
    talents: {
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "Follower of Chaos": {
        name: "Follower of Chaos",
        pos: "a2",
        icon: icons["tac_race_chaos"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You are immune to the negative effects of corruption.`,
      },
      "Bleed Corruption": {
        name: "Bleed Corruption",
        pos: "b2",
        icon: icons["tac_race_chaos"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you are hit by an enemy ability, apply a random corruption to them.`,
      },
      "Drink Deeply": {
        name: "Drink Deeply",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Every 6 seconds, gain a 5 second enchantment. For the duration, your next spell will not cost Blood Sacrifice.`,
      },
      "Plasma Reserves": {
        name: "Plasma Reserves",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Reduces the damage of Blood Sacrifice by 33%.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Hedons equip one-handed swords and shields.`,
      },
      "Changer's Touch": {
        name: "Changer's Touch",
        pos: "i4",
        icon: icons["abi_ch_mutatingrelease"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Applies 3 stacks of Reduced Corporeal Resistance, Reduced Elemental Resistance, and Reduced Spiritual Resistance to target enemy.`,
      },
      "Blood Be Gone": {
        name: "Blood Be Gone",
        pos: "i5",
        icon: icons["abi_ch_ritualofvulnerability"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Removes all stacks of Blood Sacrifice from you.`,
      },
      "Winds of Insanity": {
        name: "Winds of Insanity",
        pos: "i7",
        icon: icons["abi_ch_windblock"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "3.0s channel",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`For the duration you lose 3 mass. Every second up to 12 enemies within 20 feet of you are knocked back.`,
      },
      "Eye of Sheerian": {
        name: "Eye of Sheerian",
        pos: "i8",
        icon: icons["abi_ch_eyesofsheerian"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 96 allies within 100 feet of you gain 2 stacks of Enhanced for all resistances.`,
      },
	  "Return Life": {
        name: "Return Life",
        pos: "f2",
        icon: icons["morale_returnlife"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Return target groupmate back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Divine Protection": {
        name: "Divine Protection",
        pos: "h2",
        icon: icons["morale_divineprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 15 seconds. They will absorb up to 120% RP + 1600 damage over the duration.`,
      },
      "Alter Fate": {
        name: "Alter Fate",
        pos: "i2",
        icon: icons["morale_alterfate"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Removes all afflictions and cripples from each groupmate within 100 feet. Also applies Return Life to each dead groupmate within 100ft.`,
      },
      "Blood Sacrifice": {
        name: "Blood Sacrifice",
        pos: "a1",
        icon: icons["abi_ch_ravage"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`You are healed for 25% of all damage you deal.\n\nBlood Sacrifice stacks up to 100 times and lasts 6 seconds. For the duration, you take 6% wounds + 90 ichor damage every second.\n\nTzeentch Corruption - Gain 2% reduced cast time and 1 second cooldown reduction. Lose 250 spiritual resistance and 115 sagacity.`,
      },
      "Flash of Chaos": {
        name: "Flash of Chaos",
        pos: "b1",
        icon: icons["abi_ch_ritualoflethargy"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Restore 2% RP + 15 health to target ally. Applies 1 stack of Tzeentch Corruption to caster.`,
      },
      "Carnal Incense": {
        name: "Carnal Incense",
        pos: "c1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "36 action points",
        range: "100ft range",
        cast: "2.25s  cast",
        cooldown: "no cooldown",
        description: talentText`Deals X% SAP + Y elemental damage to target enemy. Dispels 1 ailment from, dispels 2 Blood Sacrifice from, and grants 1 stack of Slaanesh Corruption to your defensive target.`,
      },
      "Boon of Slaanesh": {
        name: "Boon of Slaanesh",
        pos: "d1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 6 Blood Sacrifice",
        description: talentText`Applies a 6 second enchantment and 2 stacks of Slaanesh Corruption to target ally. For the duration, they will absorb up to X% RP + Y damage. Enemies that attck the target while the effect is active will gain 1 stack of Slaanesh Corruption.`,
      },
      "Manipulation": {
        name: "Manipulation",
        pos: "e1",
        icon: icons["abi_ch_quellthespirit"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Off the GCD",
        description: talentText`You lose all stacks of Tzeentch Corruption and gain 15 action points per stack lost.`,
      },
      "Daemonic Restoration": {
        name: "Daemonic Restoration",
        pos: "f1",
        icon: icons["abi_ch_demonicresistance"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3 Blood Sacrifice",
        description: talentText`Target ally gains a 12 second enchantment. For the duration, restore 7% RP + 102 health to the target every 3 seconds.`,
      },
      "Aethyric Shock": {
        name: "Aethyric Shock",
        pos: "g1",
        icon: icons["abi_ch_aethyricshock"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "65 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "30s cooldown",
        description: talentText`Applies Staggered and Unstoppable to target enemy.\n\nStaggered prevents all control of the character for 9 seconds unless attacked.\nUnstoppable prevents application of Knocked-down and Staggered effects for 30 seconds.`,
      },
      "Harbinger of Doom": {
        name: "Harbinger of Doom",
        pos: "h1",
        icon: icons["abi_ch_swataside"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        blue: "blue text",
        description: talentText`Applies a buff to target groupmate. You can only have 1 active. Whenever you are healed by your %lifetap, the target is healed for 50% of the amount.`,
      },
      "Dust of Pandemonium": {
        name: "Dust of Pandemonium",
        pos: "i1",
        icon: icons["abi_ch_dustofpandemonium"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "2.5s cast",
        cooldown: "no cooldown",
        blue: "Costs 3 Blood Sacrifice",
        description: talentText`Applies an 18 second affliction to target enemy. For the duration, they take 34% SAP + 440 elemental damage every 3 seconds.`,
      },
	  "Wave of Chaos": {
        name: "Wave of Chaos",
        pos: "h4",
        icon: icons["abi_ch_waveofmutilation"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "85 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 10% MAP + 126 impact damage to up to 9 enemies within 30 feet of you. Applies 1 random chaos corruption to up to 9 enemies and up to 9 allies within 30 feet of you.`,
      },
	  "Rite of Agony": {
        name: "Rite of Agony",
        pos: "c5",
        icon: icons["abi_ch_hamstring"],
        maxRank: 1,
        reqPoints: 10,
        type: "skill",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Costs 1 Blood Sacrifice\nOff the GCD",
        description: talentText`Target ally gains 1 stack of Enhanced Critical Hit Rating and 1 stack of Khorne Corruption.`,
      },
	  "Warp Reality": {
        name: "Warp Reality",
        pos: "g6",
        icon: icons["abi_ch_warpreality"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "1.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 2 Blood Sacrifice",
        description: talentText`Deals 15% SAP + 201 spiritual damage to the target. Target and caster gain 1 stack of Tzeentch Corruption.`,
      },
	  "Tzeentch's Cry": {
        name: "Tzeentch's Cry",
        pos: "c8",
        icon: icons["abi_ch_mouthoftzeentch"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "no cost",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "6s cooldown",
        blue: "Costs 4 Blood Sacrifice",
        description: talentText`Deals 28% SAP + 375 spiritual damage to target enemy.`,
      },
      "Whisper Glory": {
        name: "Whisper Glory",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "6s cooldown",
        blue: "Costs 10 Blood Sacrifice",
        description: talentText`Target ally gains a buff for 3 seconds and 1 stack of Slaanesh Corruption. For the duration, their damage reduction is increased by 75%.`,
      },
      "The Great Decadence": {
        name: "The Great Decadence",
        pos: "f9",
        icon: icons["abi_ch_graspingdarkness"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "self",
        cast: "1.0s cast",
        cooldown: "30s cooldown",
        description: talentText`You apply Staggered and Unstoppable to up to 48 enemies within 30 feet in front of you. This effect does not apply to targets that have Cover from you.\n\nStaggered prevents all control of your character for 9 seconds or until you are attacked.\nUnstoppable prevents application of Kockdown and Staggered effects.`,
      },
	  "Rapturous Bliss": {
        name: "Rapturous Bliss",
        pos: "a5",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Double the benefits of Slaanesh Corruption on you.`,
      },
	  "Daemonic Fortitude": {
        name: "Daemonic Fortitude",
        pos: "g5",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Each time Daemonic Restoration heals a target, they have a 50% chance to gain 1 stack of Enhanced Toughness.`,
      },
	  "Embrace Doom": {
        name: "Embrace Doom",
        pos: "b6",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Your Harbinger of Doom now applies 1 stack of Enhanced Fortitude to its target every 2 seconds.`,
      },
	  "Honor in Blood": {
        name: "Honor in Blood",
        pos: "c6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Rite of Agony",
		arrows: [
          { dir: "down", from: "c5", to: "c6" },
        ],
        type: "career tactic",
        description: talentText`Rite of Agony now grants stacks of Enhanced Agility and Enhanced Initiative.`,
      },
	  "Light the Incense": {
        name: "Light the Incense",
        pos: "a7",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Reduce the cast time on Carnal Insence by 1.25 seconds and reduce the damage by X%.`,
      },
	  "Energy Ripple": {
        name: "Energy Ripple",
        pos: "e7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Demonic Restoration applies to up to 2 other allies within 30 feet of the target. Demonic Restoration now heals for 20% less.`,
      },
	  "Bloody Boon": {
        name: "Bloody Boon",
        pos: "g8",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Boon of Slaanesh now applies to all groupmates within 100 feet except yourself and lasts for 8 seconds. However, the ability now costs 15 Blood Sacrifice.`,
      },
	  "Acolytes of Hedonism": {
        name: "Acolytes of Hedonism",
        pos: "e3",
        icon: icons["noicon"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever you hit an enemy, you have a ${[
          6,
          12,
          18,
          24,
        ]}% chance to apply 1 stack of Reduced Sagacity to the target. You have the same chance to apply 1 stack of Reduced Penetration. (Rolled seperately)`,
      },
	  "Embrace the Warp": {
        name: "Embrace the Warp",
        pos: "c4",
        icon: icons["noicon"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`You gain ${[
          25,
          50,
        ]}% pushback immunity.`,
      },
	  "Sanguination of Chaos": {
        name: "Sanguination of Chaos",
        pos: "e5",
        icon: icons["abi_ch_powervortex"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Flash of Chaos has a ${[
          7,
          15,
        ]}% chance to apply a 5 second enchantment to caster. For the duration, the next skill will not cost Blood Sacrifice.`,
      },
	  "Settling Dust": {
        name: "Settling Dust",
        pos: "e6",
        icon: icons["abi_ch_dustofpandemonium"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Reduces the cast time of Dust of Pandemonium by ${[
          0.1,
          0.2,
          0.3,
		  0.4,
		  0.5,
        ]} seconds.`,
      },
	  "Wave of Slaanesh": {
        name: "Wave of Slaanesh",
        pos: "h6",
        icon: icons["abi_ch_concussivejolt"],
        maxRank: 2,
        reqPoints: 15,
        prereq: "Wave of Chaos",
		arrows: [
          { dir: "down", from: "h4", to: "h6" },
        ],
        type: "passive",
        description: talentText`Wave of Chaos now deals piercing damage, has a ${[
          35,
          70,
        ]}% chance to apply 1 stack of Reduced Weapon Skill, and a ${[
          50,
          100,
        ]}% chance to apply 1 stack of Slaanesh Corruption.`,
      },
	  "Divine Intervention": {
        name: "Divine Intervention",
        pos: "f7",
        icon: icons["abi_intervention"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Whenever you are effected by knocked-down, disarmed, silenced, or rooted effects; you will gain ${[
          8,
          16,
          24,
          32,
        ]}% damage reduction for 3 seconds.`,
      },
	  "Blood in Mouth": {
        name: "Blood of Mouth",
        pos: "f8",
        icon: icons["abi_ch_gleanmagic"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Each time you take damage from Blood Sacrifice, you have a ${[
          25,
          50,
          75,
          100,
        ]}% chance to restore health equal to the damage to a groupmate within 100 feet of you.`,
      },
    },
  },
  "Slaughterpriest": {
    name: "Slaughterpriest",
    background: backgrounds["placeholder"],
    icon: icons["archetype_dps"],
    talents: {
      "Break Loose": {
        name: "Break Loose",
        pos: "a8",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Masochist": {
        name: "Masochist",
        pos: "a8",
        icon: icons["rrtac_masochist"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you are attacked while your Guard is active, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Increase your mass by 1.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "What a Rush": {
        name: "What a Rush",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`The action point cost of your skills is reduced by 33% on allies that are lower than 40% health.`,
      },
      "Racial Tactic 1": {
        name: "Racial Tactic 1",
        pos: "a2",
        icon: icons["tac_race_"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Racial Tactic 2": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_race_"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 1": {
        name: "Class Tactic 1",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 2": {
        name: "Class Tactic 2",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Khorne Zealots equip one-handed axes and fetishes.`,
      },
      "Morale 1 Class": {
        name: "Morale 1 Class",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 2 Spec": {
        name: "Morale 2 Spec",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 3 Race": {
        name: "Morale 3 Race",
        pos: "i7",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 4 Spec": {
        name: "Morale 4 Spec",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Insert tooltip.`,
      },
	  "Sever Nerve": {
        name: "Sever Nerve",
        pos: "f2",
        icon: icons["morale_severnerve"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Deals 50% MAP + 400 physical damage to the target.`,
      },
      "Broad Swings": {
        name: "Broad Swings",
        pos: "g2",
        icon: icons["morale_broadswings"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a  buff for 10 seconds. Your single target abilities will target two additional enemies within 15ft in front of you.`,
      },
      "Force of Will": {
        name: "Force of Will",
        pos: "h2",
        icon: icons["morale_forceofwill"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 10 seconds. Action point costs are reduced by 75% for the duration.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "Specialization Mechanic": {
        name: "Specialization Mechanic",
        pos: "a1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 1": {
        name: "Core Ability 1",
        pos: "b1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 2": {
        name: "Core Ability 2",
        pos: "c1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 3": {
        name: "Core Ability 3",
        pos: "d1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 4": {
        name: "Core Ability 4",
        pos: "e1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 5": {
        name: "Core Ability 5",
        pos: "f1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 6": {
        name: "Core Ability 6",
        pos: "g1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 7": {
        name: "Core Ability 7",
        pos: "h1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 8": {
        name: "Core Ability 8",
        pos: "i1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 1": {
        name: "SA1",
        pos: "a9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 2": {
        name: "SA2",
        pos: "a9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 3": {
        name: "SA3",
        pos: "a9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 4": {
        name: "SA4",
        pos: "a9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 1": {
        name: "Capstone Ability 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 2": {
        name: "Capstone Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 1": {
        name: "T1",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 2": {
        name: "T2",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 3": {
        name: "T3",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 4": {
        name: "T4",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 5": {
        name: "T5",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 6": {
        name: "T6",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 7": {
        name: "T7",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Passive 1": {
        name: "Passive 1",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 2": {
        name: "Passive 2",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 3": {
        name: "Passive 3",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 4": {
        name: "Passive 4",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 5": {
        name: "Passive 5",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 6": {
        name: "Passive 6",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 7": {
        name: "Passive 7",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  
	  
      "blueprint": {
        name: "blueprint",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell career tactic renown tactic passive morale 1234",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
    },
  },
};