import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/dwarf"),
);
const icons = requireAll(require.context("../../assets/icons/dwarf"));

export const data: TalentData = {
  "Runelord": {
    name: "Runelord",
    background: backgrounds["runelord"],
    icon: icons["archetype_offsupport"],
    talents: {
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 1,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 1,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Ancestral Inheritance": {
        name: "Ancestral Inheritance",
        pos: "a2",
        icon: icons["tac_race_dwarf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You are immune to effects that apply stacks of Reduced Armor.`,
      },
      "Stoutness of Stone": {
        name: "Soutness of Stone",
        pos: "b2",
        icon: icons["tac_race_dwarf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Your mass is increased by 1.`,
      },
      "Efficient Runecarving": {
        name: "Efficient Runecarving",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Reduce the action point cost of Rune of Augmentation by 25.`,
      },
      "Favored of Grimnir": {
        name: "Favored of Grimnir",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`The shared cooldown on Grimnir Runes is reduced by 3 seconds.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specgreatweapon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Runelords equip two-handed hammers.`,
      },
	  "Disengage": {
        name: "Disengage",
        pos: "f2",
        icon: icons["morale_disengage"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`You knock yourself back away from target enemy.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Force of Will": {
        name: "Force of Will",
        pos: "h2",
        icon: icons["morale_forceofwill"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 10 seconds. Action point costs are reduced by 75% for the duration.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "Rune of Sanctuary": {
        name: "Rune of Sanctuary",
        pos: "i4",
        icon: icons["abi_dw_effectruneofwarding"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Target ally gains 3 stacks of Increased Elemental Resistance and Increased Spiritual Resistance.`,
      },
      "Morale 2 Spec": {
        name: "Morale 2 Spec",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Dwarven Sprint": {
        name: "Dwarven Sprint",
        pos: "i7",
        icon: icons["abi_dw_figure12"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 20 seconds. For the duration, you gain 5 mass and 25% movement speed.`,
      },
      "Morale 4 Spec": {
        name: "Morale 4 Spec",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Runic Magic": {
        name: "Runic Magic",
        pos: "a1",
        icon: icons["abi_dw_oath02"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Runescribe abilities fall under 3 ancestor rune categories: Grimnir, Valaya, and Grungni. Whenever an ability is used in that category, no other abilities may be cast in that category for a short period.`,
      },
      "Grimnir's Fury": {
        name: "Grimnir's Fury",
        pos: "b1",
        icon: icons["abi_dw_melee05"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deal 110 physical damage to target enemy. Generates 22 action points.`,
      },
      "Rune Augmentation": {
        name: "Rune Augmentation",
        pos: "c1",
        icon: icons["abi_dw_oathruneofhealing"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "75 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Off the GCD",
        description: talentText`Your next ability will be Augmented in addition to not triggering the Ancestor Rune.`,
      },
      "Venerate the Ancestors": {
        name: "Venerate the Ancestors",
        pos: "d1",
        icon: icons["abi_dw_chainhot"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Toggle: while active, you will lose 50% of your armor and all resistances. You will gain melee attack power equal to X% of your armor and corporeal resistance. You will gain spell attack power equal to X% of your elemental and spiritual resistance.`,
      },
	  "Rune of Striking": {
        name: "Rune of Striking",
        pos: "e1",
        icon: icons["abi_dw_runeofsuppression"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "25 action points",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Grimnir Rune",
        description: talentText`Deals 27% MAP + 356 physical damage to target enemy. Your defensive target will gain 1 stack of Enhanced Accuracy if they are within 100 feet.\n\nAugmented: You will also gain 1 stack of Enhanced Accuracy.`,
      },
	  "Rune of Immolation": {
        name: "Rune of Immolatio",
        pos: "f1",
        icon: icons["abi_dw_runeoffire"],
        maxRank: 1,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Grimnir Rune",
        description: talentText`Apply a 15 second ailment to target enemy. Every 3 seconds target will take 9% SAP + 108 elemental damage.\n\nAugmented: the effect is now a cripple.`,
      },
      "Rune of Binding": {
        name: "Rune of Binding",
        pos: "g1",
        icon: icons["abi_dw_runeofbinding"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "30s cooldown",
        blue: "Valaya Rune",
        description: talentText`Applies Staggered and Unstoppable to target enemy.\n\nStaggered prevents all control of the character for 9 seconds unless attacked.\nUnstoppable prevents application of Knocked-down and Staggered effects for 30 seconds.`,
      },
	  "Rune of Cleaving": {
        name: "Rune of Cleaving",
        pos: "h1",
        icon: icons["abi_dw_runeofcleaving"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "15s cooldown",
        blue: "Grungni Rune",
        description: talentText`Target ally gains a 30 second buff. For the next 5 basic attacks, they will deal an additional 5% MAP + 54 physical damage.\n\nAugmented: Ability has no cooldown.`,
      },
      "Thousand Meter Stare": {
        name: "Thousand Meter Stare",
        pos: "i1",
        icon: icons["abi_detaunt"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "15s cooldown",
        description: talentText`Reduces the damage target does to you by 50% for 15 seconds. Effect will be removed if you hit the opponent with an ability.`,
      },
	  "Rune of Flight": {
        name: "Rune of Flight",
        pos: "c4",
        icon: icons["abi_dw_kidneystrike"],
        maxRank: 1,
        reqPoints: 5,
        type: "skill",
        cost: "no cost",
        range: "50ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Grungni Rune",
        description: talentText`Throw your hammer at target enemy dealing 21% MAP + 273 physical damage before returning to you.\n\nAugmented: Deals additional physical damage equal to 18% MAP.`,
      },
	  "Rune of Shielding": {
        name: "Rune of Shielding",
        pos: "g5",
        icon: icons["abi_dw_shield03"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "60 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "8s cooldown",
        blue: "Valaya Rune",
        description: talentText`Applies a 8 second enchantment to target ally. They will absorb up to 22% RP + 292 damage for the duration.\n\nAugmented: the duration is increased by 7 seconds.`,
      },
	   "Rune of Burning": {
        name: "Rune of Burning",
        pos: "h6",
        icon: icons["abi_dw_runeofburning"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "35 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Grimnir Rune",
        description: talentText`Deals 9% SAP + 107 elemental damage to up to 9 enemy targets within a 20 foot area you select.\n\nAugmented: will now hit up to 24 enemeies.`,
      },
	   "Rune of Impact": {
        name: "Rune of Impact",
        pos: "d8",
        icon: icons["abi_dw_symbol0"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "60 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "15s cooldown",
        blue: "Grungni Rune",
        description: talentText`Applies a 15 second enchantment to target ally. Every 3 seconds, up to 9 enemies within 30ft of the target will take 3% SAP + 49 elemental damage.\n\nAugmented: Each enemy struck will lose 1 mass for 3 seconds.`,
      },
      "Rune of the Furnace": {
        name: "Rune of the Furnace",
        pos: "d9",
        icon: icons["abi_dw_runeofrenascence"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "self",
        cast: "3.0s channel",
        cooldown: "30s cooldown",
        blue: "Grimnir Rune",
        description: talentText`Every second, you will deal W% SAP + X elemental damage to up to 96 enemies within 30 feet of you and you will heal up to 24 allies within 30 feet of you for Y% RP + Z.`,
      },
      "Grip of Stone": {
        name: "Grip of Stone",
        pos: "f9",
        icon: icons["abi_dw_gripofstone"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "self",
        cast: "1.0s instant cast",
        cooldown: "30s cooldown",
        description: talentText`Up to 48 enemies within 30ft of you have their movement speed reduced by 90% for 3 seconds. Does not effect target that have Cover from you.`,
      },
	  "Cleft From Stone": {
        name: "Cleft From Stone",
        pos: "a5",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Targets hit by the additional damage applied by your Rune of Cleaving also take 1 stack of Reduced Toughness.`,
      },
	  "Tactic 5": {
        name: "Tactic 5",
        pos: "c5",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Rune of Flight",
        arrows: [{ dir: "down", from: "c4", to: "c5" }],
        type: "career tactic",
        description: talentText`Rune of Flight will now hit up to 8 other enemies between you and your target.`,
      },
	  "Into the Crucible": {
        name: "Into the Crucible",
        pos: "c6",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Each time Rune of Immolation deals damage, it will apply 1 stack of Reduced Armor to the target.`,
      },
	  "Splintering Shield": {
        name: "Splintering Shield",
        pos: "g6",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Rune of Shielding",
        arrows: [{ dir: "down", from: "g5", to: "g6" }],
        type: "career tactic",
        description: talentText`Rune of Shielding will deal 8% SAP + 98 elemental damage to up to 24 enemies within 30 feet whenever it breaks.`,
      },
	  "Grimnir's Gift": {
        name: "Grimnir's Gift",
        pos: "a7",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Whenever you cast a Grimnir Rune ability, 1 groupmate within 100 feet of you will gain 1 stack of Enhanced Strength, another will gain 1 stack of Enhanced Ballistic Skill, and another will gain 1 stack of Enhanced Intelligence.`,
      },
	  "Rune of Fire Spreading": {
        name: "Rune of Fire Spreading",
        pos: "h7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Rune of Burning",
        arrows: [{ dir: "down", from: "h6", to: "h7" }],
        type: "career tactic",
        description: talentText`Rune of Burning will now apply Rune of Immolation to each target it hits, but no longer benefits from Augmentation.`,
      },
	  "Concussive Rune": {
        name: "Concussive Rune",
        pos: "e8",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Rune of Impact",
        arrows: [{ dir: "right", from: "d8", to: "e8" }],
        type: "career tactic",
        description: talentText`Rune of Impact will now knock up to 9 enemies into the sky within 30 feet of the ally you cast it on.`,
      },
      "Ancestor Runes": {
        name: "Ancestor Runes",
        pos: "e3",
        icon: icons["abi_dw_oath02"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`You gain effects whenever your runes are on shared cooldown. Grimnir: You deal ${[
          2,
          4,
          6,
          8,
        ]}% more damage. Valaya: You gain ${[
          75,
          150,
          225,
          300,
        ]} HP4. Grungni: You gain ${[
          2,
          4,
          6,
          8,
        ]}% Reduced Incoming Damage.`,
      },
	  "Improved Grimnir's Fury": {
        name: "Improved Grimnir's Fury",
        pos: "e5",
        icon: icons["abi_dw_melee05"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Grimnir's fury will deal additional damage equal to ${[
          4,
          8,
          12,
          16,
        ]}% MAP.`,
      },
	  "Extra Cleaving": {
        name: "Extra Cleaving",
        pos: "b6",
        icon: icons["abi_dw_runeofcleaving"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Rune of Cleaving now applies ${[
          6,
          7,
          8,
          9,
          10,
        ]} stacks.`,
      },
	  "Improved Rune of Striking": {
        name: "Improved Rune of Striking",
        pos: "e6",
        icon: icons["abi_dw_runeofsuppression"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`Rune of Striking now applies 1 stack of Enhanced Weapon Skill and ${[
          0,
          1,
        ]} stack of Enhanced Initiative. This applies to the Augmented effect as well.`,
      },
	  "Master of the Forge": {
        name: "Master of the Forge",
        pos: "d7",
        icon: icons["abi_dw_masterruneoffury"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Groupmates within 30 feet of you have their outgoing damage increased by ${[
          2,
          4,
          6,
        ]}%.`,
      },
	  "Improved Rune of Shielding": {
        name: "Improved Rune of Shielding",
        pos: "g7",
        icon: icons["abi_dw_shield02"],
        maxRank: 3,
        reqPoints: 20,
        prereq: "Splintering Shield",
        arrows: [{ dir: "down", from: "g6", to: "g7" }],
        type: "passive",
        description: talentText`Rune of Shielding absorbs and Splintering Shield deals ${[
          5,
          10,
          15,
        ]}% more damage.`,
      },
	  "Ancestor's Fury": {
        name: "Ancestor's Fury",
        pos: "f8",
        icon: icons["abi_dw_chainhot"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Venerate the Ancestor provides ${[
          2,
          4,
          7,
          10,
        ]}% more MAP and SAP.`,
      },
    },
  },
  "Rune Priest": {
    name: "Rune Priest",
    background: backgrounds["runepriest"],
    icon: icons["archetype_healer"],
    talents: {
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "What a Rush": {
        name: "What a Rush",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`The action point cost of your skills is reduced by 33% on allies that are lower than 40% health.`,
      },
      "Ancestral Inheritance": {
        name: "Ancestral Inheritance",
        pos: "a2",
        icon: icons["tac_race_dwarf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You are immune to effects that apply stacks of Reduced Armor.`,
      },
      "Stoutness of Stone": {
        name: "Soutness of Stone",
        pos: "b2",
        icon: icons["tac_race_dwarf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Your mass is increased by 1.`,
      },
      "Efficient Runecarving": {
        name: "Efficient Runecarving",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Reduce the action point cost of Rune of Augmentation by 25.`,
      },
      "Favored of Grimnir": {
        name: "Favored of Grimnir",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`The shared cooldown on Grimnir Runes is reduced by 3 seconds.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Runepriests equip staves.`,
      },
	  "Return Life": {
        name: "Return Life",
        pos: "f2",
        icon: icons["morale_returnlife"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Return target groupmate back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Divine Protection": {
        name: "Divine Protection",
        pos: "h2",
        icon: icons["morale_divineprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 15 seconds. They will absorb up to 200% RP + 1500 damage over the duration.`,
      },
      "Alter Fate": {
        name: "Alter Fate",
        pos: "i2",
        icon: icons["morale_alterfate"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Removes all afflictions and cripples from each groupmate within 100ft. Also applies Return Life to each dead groupmate within 100ft.`,
      },
    },
  },
  "Runesmith": {
    name: "Runesmith",
    background: backgrounds["runesmith"],
    icon: icons["archetype_defsupport"],
    talents: {
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Ancestral Inheritance": {
        name: "Ancestral Inheritance",
        pos: "a2",
        icon: icons["tac_race_dwarf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You are immune to effects that apply stacks of Reduced Armor.`,
      },
      "Stoutness of Stone": {
        name: "Soutness of Stone",
        pos: "b2",
        icon: icons["tac_race_dwarf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Your mass is increased by 1.`,
      },
      "Efficient Runecarving": {
        name: "Efficient Runecarving",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Reduce the action point cost of Rune of Augmentation by 25.`,
      },
      "Favored of Grimnir": {
        name: "Favored of Grimnir",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`The shared cooldown on Grimnir Runes is reduced by 3 seconds.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Runesmiths equip one-handed hammers.`,
      },
	  "Return Life": {
        name: "Return Life",
        pos: "f2",
        icon: icons["morale_returnlife"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Return target groupmate back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn.`,
      },
      "Champion's Challenge": {
        name: "Champion's Chalenge",
        pos: "g2",
        icon: icons["morale_grapple"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Applies a debuff to target enemy and yourself for 10 seconds. Movement speed is reduced to 0 for the duration.`,
      },
      "Divine Protection": {
        name: "Divine Protection",
        pos: "h2",
        icon: icons["morale_divineprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 15 seconds. They will absorb up to 200% RP + 1500 damage over the duration.`,
      },
      "Alter Fate": {
        name: "Alter Fate",
        pos: "i2",
        icon: icons["morale_alterfate"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Removes all afflictions and cripples from each groupmate within 100ft. Also applies Return Life to each dead groupmate within 100ft.`,
      },
    },
  },
};
