import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/chaos"),
);
const icons = requireAll(require.context("../../assets/icons/chaos"));

export const data: TalentData = {
  "Bloodreaver": {
    name: "Bloodreaver",
    background: backgrounds["mara-khorne"],
    icon: icons["archetype_dps"],
    talents: {
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Follower of Chaos": {
        name: "Follower of Chaos",
        pos: "a2",
        icon: icons["tac_race_chaos"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You are immune to the negative effects of corruption.`,
      },
      "Bleed Corruption": {
        name: "Bleed Corruption",
        pos: "b2",
        icon: icons["tac_race_chaos"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you are hit by an enemy ability, apply a random corruption to them.`,
      },
      "Mutated Energy": {
        name: "Mutated Energy",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you gain a new Gift, you gain 50% AP cost reduction for 5 seconds.`,
      },
      "Warped Flesh": {
        name: "Warped Flesh",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Gift of Savagery will now grant 1000 elemental resistance and 1000 spiritual resistance. Gift of Pride will now grant 1000 ichor resistance and 1000 impact resistance. Gift of Plague will now grant 1000 corporeal resistance and 1000 piercing resistance.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specaxe"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Khorne marauders dual wield axes.`,
      },
      "Hunter's Trap": {
        name: "Hunter's Trap",
        pos: "i4",
        icon: icons["abi_he_ensnare"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Applies Rooted and Immovable to target enemy.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nImmovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Even the Odds": {
        name: "Even the Odds",
        pos: "i5",
        icon: icons["abi_dw_face20"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain 75 toughness for each enemy within 30 feet. Stacks up to 10 times and lasts for 15 seconds.`,
      },
      "Winds of Insanity": {
        name: "Winds of Insanity",
        pos: "i7",
        icon: icons["abi_ch_windblock"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "3.0s channel",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`For the duration you lose 3 mass. Every second up to 12 enemies within 20 feet of you are knocked back.`,
      },
      "Lashing Power": {
        name: "Lashing Power",
        pos: "i8",
        icon: icons["abi_ch_lashingpower"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 20 seconds. For the duration, 150% of damage dealt to them is returned to the source.`,
      },
	  "Sever Nerve": {
        name: "Sever Nerve",
        pos: "f2",
        icon: icons["morale_severnerve"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Deals 50% MAP + 400 piercing damage to the target.`,
      },
      "Broad Swings": {
        name: "Broad Swings",
        pos: "g2",
        icon: icons["morale_broadswings"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 10 seconds. Your single target abilities will target two additional enemies within 15ft in front of you.`,
      },
      "Force of Will": {
        name: "Force of Will",
        pos: "h2",
        icon: icons["morale_forceofwill"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 10 seconds. Action point costs are reduced by 75% for the duration.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "Gifts of the Gods": {
        name: "Gifts of the Gods",
        pos: "a1",
        icon: icons["abi_ch_giftofrelease"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Gift of Savagery: Gain 20% movement speed. All of your abilities apply 1 stack of Khorne Corruption to the target and cast as well as 1 stack of Savagery to target. At 5 stacks of Savagery, all stacks are dispelled and the target gains Blood-marked.\n\nGift of Pride: Gain 50% pushback immunity. All abilities apply 1 stack of Slaanesh Corruption to target and caster as well as 1 stack of Pride. At 10 stacks of Pride, dispel all stacks and apply Sleepy to target for 5 seconds.\n\nGift of Plague: Gain 20% lifetap. All of your abilities apply 1 stack of Nurgle Corruption to target and caster as well as 1 stack of Plagued.`,
      },
      "Blow": {
        name: "Blow",
        pos: "b1",
        icon: icons["abi_ch_downfall"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 4% MAP + 30 impact damage to target enemy. Generates 22 action points.`,
      },
      "Impale": {
        name: "Impale",
        pos: "c1",
        icon: icons["abi_ch_impale"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "36 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deal 21% MAP + 280 impact damage to target enemy. You shift into Gift of Brutality.\n\nBlood-marked lasts for 8 second and stacks up to 3 times. Khorne abilities often gain special benefits against Blood-marked targets.`,
      },
      "Tainted Claw": {
        name: "Tainted Claw",
        pos: "d1",
        icon: icons["abi_ch_waveofterror"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deal 17% MAP + 227 ichor damage to target enemy and they gain 1 stack of Reduced Healing Received. You shift into Gift of Plague.\n\nPlagued stacks up to 5 times and lasts for 6 seconds. For the duration, deals 3% MAP + 40 ichor damage every 3 seconds.`,
      },
      "Touched by the Gods": {
        name: "Touched by the Gods",
        pos: "e1",
        icon: icons["abi_ch_ferociousassault"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "30s cooldown",
        description: talentText`You gain an enchantment for 8 seconds depending on your active gift. Gift of Savagery: gain 20% movement speed. Gift of Pride: gain 1000 penetration. Gift of Plague: gain 80% lifetap.`,
      },
      "Flail": {
        name: "Core Ability 5",
        pos: "f1",
        icon: icons["abi_ch_infallibleprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "45 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Attack an enemy two times with each strike dealing 11% MAP + 140 piercing damage. You shift into Gift of Pride.\n\nSleepy reduces movement speed and accuracy by 25%.`,
      },
      "Terrible Embrace": {
        name: "Terrible Embrace",
        pos: "g1",
        icon: icons["abi_ch_terribleembrace"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "75 action points",
        range: "65ft range",
        cast: "3.0s channel",
        cooldown: "30s cooldown",
        blue: "Castable While Moving",
        description: talentText`Caster has their movement speed reduced by 15%. After 2.5 seconds, target enemy is Pulled and Immovable is applied to them.\n\nImmovable prevents application of Rooted, Knockback, and Pull effects for 20 seconds.`,
      },
      "Guillotine": {
        name: "Guillotine",
        pos: "h1",
        icon: icons["abi_ch_guillotine"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
		blue: "Must be Blood-marked",
        description: talentText`Deals 17% MAP + 227 impact damage to target enemy per stack of Blood-marked on them. Removes one stack of Blood-marked. You shift into Gift of Savagery.`,
      },
      "Vigilance": {
        name: "Vigilance",
        pos: "i1",
        icon: icons["abi_vigilance"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        description: talentText`Your damage reduction is increased by 50% but your outdoing damage is reduced by 90% for 7 seconds.`,
      },
	  "Wave of Chaos": {
        name: "Wave of Chaos",
        pos: "g4",
        icon: icons["abi_ch_waveofmutilation"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "85 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 10% MAP + 126 impact damage to up to 9 enemies within 30 feet of you. Applies 1 random chaos corruption to up to 9 enemies and up to 9 allies within 30 feet of you.`,
      },
	  "Gut Ripper": {
        name: "Gut Ripper",
        pos: "e5",
        icon: icons["abi_ch_gutripper"],
        maxRank: 1,
        reqPoints: 10,
        type: "skill",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deal 15% MAP + 204 impact damage to target enemy and apply an affliction on the target for 10 seconds.\nGift of Savagery: Target will take 9% MAP + 116 impact damage whenever they use a spell.\nGift of Pride: Target will take 9% MAP + 116 piercing damage whenever they use a skill.`,
      },
	  "Rend": {
        name: "Rend",
        pos: "e6",
        icon: icons["abi_ch_rend"],
        maxRank: 1,
        reqPoints: 15,
        type: "skill",
        cost: "45 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 15% MAP + 204 ichor damage to target enemy.\nGift of Plague: Apply a 10 second affliction to them that stacks up to 3 times; for the duration, deal 3% MAP + 44 ichor damage every second.\nGift of Savagery: Applies one stack of Reduced Toughness to target.`,
      },
	  "Wrecking Ball": {
        name: "Wrecking Ball",
        pos: "g8",
        icon: icons["abi_ch_wreckingball"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "50 action points",
        range: "self",
        cast: "3.0s channel",
        cooldown: "no cooldown",
        description: talentText`Deals 7% MAP + 94 piercing damage every second to up to 9 enemies within 30 feet of you.`,
      },
      "Mutated Aggressor": {
        name: "Mutated Aggressor",
        pos: "d9",
        icon: icons["abi_ch_ravage"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "30s cooldown",
        blue: "Off the GCD",
        description: talentText`Consume all Khorne Corruption on yourself to gain a buff whose duration equals stacks consumed. For the duration, your outgoing damage is increased by 25%.`,
      },
      "The Great Slaughter": {
        name: "The Grand Slaughter",
        pos: "f9",
        icon: icons["abi_ch_relentless"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "150 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "30s cooldown",
        description: talentText`Up to 96 enemies within 30 feet of gain a debuff for 6 seconds if they do not have Cover from you. If an enemy dies while under this effect, they will deal 10% MAP + 100 impact damage to up to 9 enemies within 30 feet of them.`,
      },
	  "Blood for the Blood God": {
        name: "Blood for the Blood God",
        pos: "a5",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Double the effects of Khorne Corruption on you.`,
      },
	  "Unfair Advantage": {
        name: "Unfair Advantage",
        pos: "b5",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you hit an enemy you are flanking, you will gain a buff for 2 seconds. For the duration, you will gain outgoing damage equal to 100% of your accuracy.`,
      },
	  "Admire the Corrupt": {
        name: "Admire the Corrupt",
        pos: "a6",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Impale will hit 2 additional enemies within 20 feet for 33% of its damage per stack of Blood-marked on the target.`,
      },
	  "Growing Instability": {
        name: "Growing Instability",
        pos: "b6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`You will gain 1 stack of Enhanced Critical Hit Rating whenever you cast Flail.`,
      },
	  "Rend Asunder": {
        name: "rend Asunder",
        pos: "a7",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Rend's Gift effects will now apply to up to 8 other enemies within 30 feet of you.`,
      },
	  "Widespread Demolition": {
        name: "Widespread Demolition",
        pos: "g7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Wave of Chaos",
		arrows: [
          { dir: "down", from: "g4", to: "g7" },
        ],
        type: "career tactic",
        description: talentText`Wave of Chaos and Wrecking Ball now hit up to 24 enemies.`,
      },
	  "Unrelenting Conflict": {
        name: "Unrelenting Conflict",
        pos: "c8",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Abilities cast in Gift of Plague and Gift of Pride have a 50% chance to apply a stack of Savagery to the target.`,
      },
	  "Forked Aggression": {
        name: "Forked Aggression",
        pos: "e3",
        icon: icons["abi_ch_challenge"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever you gain a new Gift, you will gain a buff for 5 seconds. For the duration, whenever you deal direct damage, you will deal an additional ${[
          3,
          6,
          9,
        ]}% MAP + 75 impact damage.`,
      },
	  "Improved Basic Attack": {
        name: "Improved Basic Attack",
        pos: "c4",
        icon: icons["abi_ch_downfall"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Your basic attacks will deal ${[
          75,
          150,
          225,
          300,
          375,
        ]}% additional damage.`,
      },
	  "Wave of Khorne": {
        name: "Wave of Khorne",
        pos: "h6",
        icon: icons["abi_ch_bloodyspin"],
        maxRank: 2,
        reqPoints: 15,
        prereq: "Wave of Chaos",
		arrows: [
          { dir: "right-down", from: "g4", to: "h4" },
          { dir: "right-down-down", from: "h4", to: "h6" }
        ],
        type: "passive",
        description: talentText`Wave of Chaos deals ${[
          5,
          10,
        ]}% more damage and has a ${[
          50,
          100,
        ]}% chance to always apply Khorne Corruption to enemies and allies.`,
      },
	  "Deeply Impaled": {
        name: "Deeply Impaled",
        pos: "i6",
        icon: icons["abi_ch_impale"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Whenever you cast Impale, the damage of your next Guillotine will be increased by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%. This effect stacks up to 3 times.`,
      },
	  "Improved Vigilance": {
        name: "Improved Vigilance",
        pos: "c7",
        icon: icons["abi_vigilance"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Vigilance now only reduces your outgoing damage by ${[
          75,
          60,
          45,
        ]}%.`,
      },
	  "Extra Crit": {
        name: "Extra Crit",
        pos: "e7",
        icon: icons["abi_extracrit"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Your chance to critically hit is increased by ${[
          1,
          2,
          3,
          4,
          5,
        ]}.`,
      },
	  "Serial Killer": {
        name: "Serial Killer",
        pos: "e8",
        icon: icons["abi_ch_exhaustivepower"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Guillotine has a ${[
          12.5,
          25,
          37.5,
          50,
        ]}% chance to apply Blood-marked to the target.`,
      },
    },
  },
  "Rotmire": {
    name: "Rotmire",
    background: backgrounds["mara-nurgle"],
    icon: icons["archetype_offsupport"],
    talents: {
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Follower of Chaos": {
        name: "Follower of Chaos",
        pos: "a2",
        icon: icons["tac_race_chaos"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You are immune to the negative effects of corruption.`,
      },
      "Bleed Corruption": {
        name: "Bleed Corruption",
        pos: "b2",
        icon: icons["tac_race_chaos"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you are hit by an enemy ability, apply a random corruption to them.`,
      },
      "Mutated Energy": {
        name: "Mutated Energy",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you gain a new Gift, you gain 50% AP cost reduction for 5 seconds.`,
      },
      "Warped Flesh": {
        name: "Warped Flesh",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Gift of Savagery will now grant 1000 elemental resistance and 1000 spiritual resistance. Gift of Pride will now grant 1000 ichor resistance and 1000 impact resistance. Gift of Plague will now grant 1000 corporeal resistance and 1000 piercing resistance.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_spechammer"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Rotmires dual wield hammers.`,
      },
      "Hunter's Trap": {
        name: "Hunter's Trap",
        pos: "i4",
        icon: icons["abi_he_ensnare"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Applies Rooted and Immovable to target enemy.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nImmovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Even the Odds": {
        name: "Even the Odds",
        pos: "i5",
        icon: icons["abi_dw_face20"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain 75 toughness for each enemy within 30 feet. Stacks up to 10 times and lasts for 15 seconds.`,
      },
      "Winds of Insanity": {
        name: "Winds of Insanity",
        pos: "i7",
        icon: icons["abi_ch_windblock"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "3.0s channel",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`For the duration you lose 3 mass. Every second up to 12 enemies within 20 feet of you are knocked back.`,
      },
      "Lashing Power": {
        name: "Lashing Power",
        pos: "i8",
        icon: icons["abi_ch_lashingpower"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 20 seconds. For the duration, 150% of damage dealt to them is returned to the source.`,
      },
	  "Sever Nerve": {
        name: "Sever Nerve",
        pos: "f2",
        icon: icons["morale_severnerve"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Deals 50% MAP + 400 piercing damage to the target.`,
      },
      "Broad Swings": {
        name: "Broad Swings",
        pos: "g2",
        icon: icons["morale_broadswings"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 10 seconds. Your single target abilities will target two additional enemies within 15ft in front of you.`,
      },
      "Force of Will": {
        name: "Force of Will",
        pos: "h2",
        icon: icons["morale_forceofwill"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 10 seconds. Action point costs are reduced by 75% for the duration.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "Gifts of the Gods": {
        name: "Gifts of the Gods",
        pos: "a1",
        icon: icons["abi_ch_giftofrelease"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Gift of Savagery: Gain 20% movement speed. All of your abilities apply 1 stack of Khorne Corruption to the target and cast as well as 1 stack of Savagery to target. At 5 stacks of Savagery, all stacks are dispelled and the target gains Blood-marked.\n\nGift of Pride: Gain 50% pushback immunity. All abilities apply 1 stack of Slaanesh Corruption to target and caster as well as 1 stack of Pride. At 10 stacks of Pride, dispel all stacks and apply Sleepy to target for 5 seconds.\n\nGift of Plague: Gain 20% lifetap. All of your abilities apply 1 stack of Nurgle Corruption to target and caster as well as 1 stack of Plagued.`,
      },
      "Blow": {
        name: "Blow",
        pos: "b1",
        icon: icons["abi_ch_downfall"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 4% MAP + 30 impact damage to target enemy. Generates 22 action points.`,
      },
      "Impale": {
        name: "Impale",
        pos: "c1",
        icon: icons["abi_ch_impale"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "36 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deal 21% MAP + 280 impact damage to target enemy. You shift into Gift of Brutality.\n\nBlood-marked lasts for 8 second and stacks up to 3 times. Khorne abilities often gain special benefits against Blood-marked targets.`,
      },
      "Tainted Claw": {
        name: "Tainted Claw",
        pos: "d1",
        icon: icons["abi_ch_waveofterror"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deal 17% MAP + 227 ichor damage to target enemy and they gain 1 stack of Reduced Healing Received. You shift into Gift of Plague.\n\nPlagued stacks up to 5 times and lasts for 6 seconds. For the duration, deals 3% MAP + 40 ichor damage every 3 seconds.`,
      },
      "Touched by the Gods": {
        name: "Touched by the Gods",
        pos: "e1",
        icon: icons["abi_ch_ferociousassault"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "30s cooldown",
        description: talentText`You gain an enchantment for 8 seconds depending on your active gift. Gift of Savagery: gain 20% movement speed. Gift of Pride: gain 1000 penetration. Gift of Plague: gain 80% lifetap.`,
      },
      "Flail": {
        name: "Core Ability 5",
        pos: "f1",
        icon: icons["abi_ch_infallibleprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "45 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Attack an enemy two times with each strike dealing 11% MAP + 140 piercing damage. You shift into Gift of Pride.\n\nSleepy reduces movement speed and accuracy by 25%.`,
      },
      "Terrible Embrace": {
        name: "Terrible Embrace",
        pos: "g1",
        icon: icons["abi_ch_terribleembrace"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "75 action points",
        range: "65ft range",
        cast: "3.0s channel",
        cooldown: "30s cooldown",
        blue: "Castable While Moving",
        description: talentText`Caster has their movement speed reduced by 15%. After 2.5 seconds, target enemy is Pulled and Immovable is applied to them.\n\nImmovable prevents application of Rooted, Knockback, and Pull effects for 20 seconds.`,
      },
      "Contaminating Claws": {
        name: "Contaminating Claws",
        pos: "h1",
        icon: icons["abi_ch_banefulclutch"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Applies an 18 second affliction to target enemy. For the duration, target will take 18% MAP + 231 ichor damage every 3 seconds.`,
      },
      "Vigilance": {
        name: "Vigilance",
        pos: "i1",
        icon: icons["abi_vigilance"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        description: talentText`Your damage reduction is increased by 50% but your outdoing damage is reduced by 90% for 7 seconds.`,
      },
	  "Wave of Chaos": {
        name: "Wave of Chaos",
        pos: "g4",
        icon: icons["abi_ch_waveofmutilation"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "85 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 10% MAP + 126 impact damage to up to 9 enemies within 30 feet of you. Applies 1 random chaos corruption to up to 9 enemies and up to 9 allies within 30 feet of you.`,
      },
	  "Rend": {
        name: "Rend",
        pos: "g5",
        icon: icons["abi_ch_rend"],
        maxRank: 1,
        reqPoints: 10,
        type: "skill",
        cost: "45 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 15% MAP + 204 ichor damage to target enemy.\nGift of Plague: Apply a 10 second affliction to them that stacks up to 3 times; for the duration, deal 3% MAP + 44 ichor damage every second.\nGift of Savagery: Applies one stack of Reduced Toughness to target.`,
      },
	  "Blissful Coquetry": {
        name: "Blissful Coquetry",
        pos: "c6",
        icon: icons["abi_ch_demonicinfestation"],
        maxRank: 1,
        reqPoints: 15,
        type: "skill",
        cost: "60 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Deals 12% SAP + 163 piercing damage to target.\nGift of Pride: Jams the target for 3 seconds, interupting the next ability cast.\nGift of Plague: deals 6% SAP + 80 ichor damage per stack of Plagued on the target.`,
      },
	  "Feeding on Fear": {
        name: "Feeding on Fear",
        pos: "h8",
        icon: icons["abi_ch_exhaustivepower"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "40 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`All groupmates within 100 feet gain 1 stack of Nurgle Corruption and 1 stack of Khorne Corruption. In addition, their next attack within 10 seconds will deal additional 7% SAP + 99 ichor damage.`,
      },
      "Deadly Clutch": {
        name: "Deadly Clutch",
        pos: "d9",
        icon: icons["abi_ch_drainingswipe"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "20 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 8% MAP + 92 ichor damage. Deals an additional 50% damage per stack of Plagued, Contaminating Claw, and Rend on the target.`,
      },
      "The Great Plague": {
        name: "The Grand Plague",
        pos: "f9",
        icon: icons["abi_ch_befuddlinggreenfire"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Apply a debuff to target enemy for 2 seconds. Deals 6% SAP + 20 ichor damage every 1 second. At the end of the duration, applies stage 2 of the debuff to up to 6 other enemies within 20 feet. There are 5 stages and each stage can stack up to 10 times on the same target.`,
      },
	  "Favorite Children": {
        name: "Favorite Children",
        pos: "a5",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Double the benefits of Nurgle Corruption on you.`,
      },
	  "Admire the Corrupt": {
        name: "Admire the Corrupt",
        pos: "c5",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Impale will hit 2 additional enemies within 20 feet for 33% of its damage per stack of Blood-marked on the target.`,
      },
	  "Cutting Claw": {
        name: "Cutting Claw",
        pos: "d6",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Tainted Claw now applies a 5 second affliction to target. For the duration, their outgoing healing is decreased by 33%.`,
      },
	  "Festering": {
        name: "Festering",
        pos: "f6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Contaminating Claw and Plagued are now cripples.`,
      },
	  "Rend Asunder": {
        name: "rend Asunder",
        pos: "g7",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 20,
		prereq: "Rend",
		arrows: [
          { dir: "down", from: "g5", to: "g7" },
        ],
        type: "career tactic",
        description: talentText`Rend's Gift effects will now apply to up to 8 other enemies within 30 feet of you.`,
      },
	  "Chaotic Populist": {
        name: "Chaotic Populist",
        pos: "c7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Blissful Coquetry",
		arrows: [
          { dir: "down", from: "c6", to: "c7" },
        ],
        type: "career tactic",
        description: talentText`Blissful Coquetry will now hit up to 8 other enemies within 30 feet of the target.`,
      },
	  "Blessings of Nurgle": {
        name: "Blessings of Nurgle",
        pos: "b8",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Abilities cast in Gift of Pride and Gift of Savagery have a 50% chance to apply a stack of Plagued to the target.`,
      },
	  "Debilitation": {
        name: "Debilitation",
        pos: "e3",
        icon: icons["abi_ch_touchofpalsy"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever you gain a new Gift, up to ${[
          1,
          2,
          3,
          4,
          5,
        ]} enemies within 30 feet of you will gain 1 stack of Reduced Ichor Resistance and 1 stack of Reduced Impact Resistance.`,
      },
	  "Improved Basic Attack": {
        name: "Improved Basic Attack",
        pos: "c4",
        icon: icons["abi_ch_downfall"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Your basic attacks will deal ${[
          75,
          150,
          225,
          300,
          375,
        ]}% additional damage.`,
      },
	  "Wave of Nurgle": {
        name: "Wave of Nurgle",
        pos: "h6",
        icon: icons["abi_ch_dissolvingblast"],
        maxRank: 2,
        reqPoints: 15,
        prereq: "Wave of Chaos",
		arrows: [
          { dir: "right-down", from: "g4", to: "h4" },
          { dir: "right-down-down", from: "h4", to: "h6" }
        ],
        type: "passive",
        description: talentText`Wave of Chaos now deals ichor damage, deals ${[
          5,
          10,
        ]}% more damage, and has a ${[
          50,
          100,
        ]}% chance to always apply Nurgle Corruption to enemies and allies.`,
      },
	  "Plague Paragon": {
        name: "Plague Paragon",
        pos: "e6",
        icon: icons["abi_ch_uncontrollablewarping"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Plagued has a ${[
          15,
          30,
          45,
          60,
          75,
        ]}% chance whenever it ticks to apply a stack of Reduced Fortitude to the target.`,
      },
	  "More Contamination": {
        name: "More Contamination",
        pos: "a7",
        icon: icons["abi_ch_banefulclutch"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Contaminating Claw can now stack up to ${[
          2,
          3,
          4,
          5,
        ]} times on a target.`,
      },
	  "Improved Vigilance": {
        name: "Improved Vigilance",
        pos: "e7",
        icon: icons["abi_vigilance"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Vigilance now only reduces your outgoing damage by ${[
          75,
          60,
          45,
        ]}%.`,
      },
	  "Curse of the Leper": {
        name: "Curse of the Leper",
        pos: "e8",
        icon: icons["abi_ch_tzeentchshallremakeyou"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`You have a ${[
          5,
          10,
          15,
          20,
        ]}% chance per stack of Plagued on the target to make them lose 1 mass for 3 seconds whenever you hit them with an ability.`,
      },
    },
  },
  "Bladesinger": {
    name: "Bladesinger",
    background: backgrounds["mara-slaanesh"],
    icon: icons["archetype_tank"],
    talents: {
      "Break Loose": {
        name: "Break Loose",
        pos: "a8",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Masochist": {
        name: "Masochist",
        pos: "a8",
        icon: icons["rrtac_masochist"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you are attacked while your Guard is active, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Increase your mass by 1.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "What a Rush": {
        name: "What a Rush",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`The action point cost of your skills is reduced by 33% on allies that are lower than 40% health.`,
      },
      "Racial Tactic 1": {
        name: "Racial Tactic 1",
        pos: "a2",
        icon: icons["tac_race_"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Racial Tactic 2": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_race_"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 1": {
        name: "Class Tactic 1",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 2": {
        name: "Class Tactic 2",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Slaanesh Marauders dual wield swords.`,
      },
      "Morale 1 Class": {
        name: "Morale 1 Class",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 2 Spec": {
        name: "Morale 2 Spec",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 3 Race": {
        name: "Morale 3 Race",
        pos: "i7",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 4 Spec": {
        name: "Morale 4 Spec",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Insert tooltip.`,
      },
	  "Hedgehog": {
        name: "Hedgehog",
        pos: "f2",
        icon: icons["morale_hedgehog"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`All groupmates within 100 feet gain 3 stacks of Enhanced Block.`,
      },
      "Champion's Challenge": {
        name: "Champion's Chalenge",
        pos: "g2",
        icon: icons["morale_grapple"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Applies a debuff to target enemy and yourself for 10 seconds. Movement speed is reduced to 0 for the duration.`,
      },
      "Distracting Bellow": {
        name: "Distracting Bellow",
        pos: "h2",
        icon: icons["morale_distractingbellow"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Up to 48 enemies within 30 feet of you receive a debuff. For 10 seconds, they cannot benefit from Cover.`,
      },
      "Immaculate Defense": {
        name: "Immaculate Defense",
        pos: "i2",
        icon: icons["morale_immaculatedefense"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Groupmates within 100 feet gain 25 stacks of a buff for 20 seconds. Each stack grants 3% damage reduction. A stack is removed each time they are attacked by an ability; 4 additional stacks are removed if the ability is single target.`,
      },
      "Specialization Mechanic": {
        name: "Specialization Mechanic",
        pos: "a1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 1": {
        name: "Core Ability 1",
        pos: "b1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 2": {
        name: "Core Ability 2",
        pos: "c1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 3": {
        name: "Core Ability 3",
        pos: "d1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 4": {
        name: "Core Ability 4",
        pos: "e1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 5": {
        name: "Core Ability 5",
        pos: "f1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 6": {
        name: "Core Ability 6",
        pos: "g1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 7": {
        name: "Core Ability 7",
        pos: "h1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 8": {
        name: "Core Ability 8",
        pos: "i1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 1": {
        name: "SA1",
        pos: "a9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 2": {
        name: "SA2",
        pos: "a9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 3": {
        name: "SA3",
        pos: "a9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 4": {
        name: "SA4",
        pos: "a9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 1": {
        name: "Capstone Ability 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 2": {
        name: "Capstone Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 1": {
        name: "T1",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 2": {
        name: "T2",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 3": {
        name: "T3",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 4": {
        name: "T4",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 5": {
        name: "T5",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 6": {
        name: "T6",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 7": {
        name: "T7",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Passive 1": {
        name: "Passive 1",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 2": {
        name: "Passive 2",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 3": {
        name: "Passive 3",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 4": {
        name: "Passive 4",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 5": {
        name: "Passive 5",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 6": {
        name: "Passive 6",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 7": {
        name: "Passive 7",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  
	  
      "blueprint": {
        name: "blueprint",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell career tactic renown tactic passive morale 1234",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  
    },
  },
};