import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/asur"),
);
const icons = requireAll(require.context("../../assets/icons/highelf"));

export const data: TalentData = {
  "Axeman": {
    name: "Axeman",
    background: backgrounds["axeman"],
    icon: icons["archetype_dps"],
    talents: {
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Centuries of Training": {
        name: "centuries of Training",
        pos: "a2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you deal direct damage to an enemy, you have a 33% chance to apply one of three debuffs to them. Effects do not refresh and last 6 seconds.\nDeals 4% MAP + 56 impact damage every second.\nDeals 6% RAP + 80 piercing damage every 2 seconds.\nDeals 10% SAP + 134 spiritual damage every 3 seconds.`,
      },
      "Form Ranks": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, each groupmate within 100 feet that has this tactic will gain 1 stack of purity and a 4 second buff. For the duration, gain 450 penetration and 450 sagacity.`,
      },
      "Feline Grace": {
        name: "Feline Grace",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You and your lion gain 20% movement speed for 4 seconds after using Pounce.`,
      },
      "Animal Within": {
        name: "Animal Within",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You gain 1 Ferocity every 3 seconds if you have no pet active. You gain 6 Ferocity whenever your pet is killed.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specaxe"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Axeman equip two-handed axes.`,
      },
	  "Sever Nerve": {
        name: "Sever Nerve",
        pos: "f2",
        icon: icons["morale_severnerve"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Deals 50% MAP + 400 piercing damage to the target.`,
      },
      "Broad Swings": {
        name: "Broad Swings",
        pos: "g2",
        icon: icons["morale_broadswings"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 10 seconds. Your single target abilities will target two additional enemies within 20 feet in front of you.`,
      },
      "Force of Will": {
        name: "Force of Will",
        pos: "h2",
        icon: icons["morale_forceofwill"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 10 seconds. Action point costs are reduced by 75% for the duration.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "Hunter's Trap": {
        name: "Hunter's Trap",
        pos: "i4",
        icon: icons["abi_he_ensnare"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Applies Rooted and Immovable to target enemy.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nImmovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Even the Odds": {
        name: "Even the Odds",
        pos: "i5",
        icon: icons["abi_dw_face20"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain 75 toughness for each enemy within 30 feet. Stacks up to 10 times and lasts for 15 seconds.`,
      },
      "Wings of Heaven": {
        name: "Wings of Heaven",
        pos: "i7",
        icon: icons["abi_he_wingsofheaven"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Gain a debuff for 5 seconds which reduces your mass by 8. Leap forward and apply Ensnared to up to 9 enemies within 20 feet of where you land.\n\nEnsnared reduces movement speed by 30% for 16 seconds.`,
      },
      "The Wild Hunt": {
        name: "The Wild Hunt",
        pos: "i8",
        icon: icons["abi_he_baitingstrike"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 20 seconds. For the duration, movement speed will be increased by 40% and accuracy will be increased by 100%.`,
      },
      "Ferocity": {
        name: "Ferocity",
        pos: "a1",
        icon: icons["abi_he_maul"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Ferocity stacks up to a maximum of 8. It is generated by pet skills except for the axeman who has some AP skills that generate it.\n\nBleeding is a status effect that lasts 8 seconds and deals 2% MAP + 10 ichor damage every second.`,
      },
      "Hack": {
        name: "Hack",
        pos: "b1",
        icon: icons["abi_he_hack"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 4% MAP + 30 ichor damage to target enemy. Generates 22 action points.`,
      },
      "Blindside": {
        name: "Blindside",
        pos: "c1",
        icon: icons["abi_he_blindside"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "100 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Applies a 21 second cripple to target enemy. Deals 25% MAP + 331 ichor damage every 3 seconds. Generates 1 Ferocity on cast and has a 25% chance to generate 1 Ferocity on tick.`,
      },
      "Sundering Chop": {
        name: "Sundering Chop",
        pos: "d1",
        icon: icons["abi_he_sunderingchop"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 2 Ferocity",
        description: talentText`Deals 37% MAP + 492 ichor damage to target enemy and applies Bleeding.`,
      },
      "Pounce": {
        name: "Pounce",
        pos: "e1",
        icon: icons["abi_he_pounce"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "0.75s cast",
        cooldown: "30s cooldown",
		blue: "Castable While Moving",
        description: talentText`(Movement Skill) You leap forward.`,
      },
      "Cleave Limb": {
        name: "Cleave Limb",
        pos: "f1",
        icon: icons["abi_he_cleavelimb"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Applies Ensnared, Momentum, Bleeding, and a 9 second affliction to target enemy. For the duration, deals 12% + 158 ichor damage every 3 seconds.\n\nEnsnared reduces movement speed by 30% for 16 seconds.\nMomentum prevents the application of Ensnared for 8 seconds.`,
      },
      "Kurnous Bewitchment": {
        name: "Kurnous Bewitchment",
        pos: "g1",
        icon: icons["abi_he_lawofgold"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "75 action points",
        range: "65ft range",
        cast: "3.0s channel",
        cooldown: "30s cooldown",
        blue: "Castable While Moving",
        description: talentText`Caster has their movement speed reduced by 15%. After 2.5 seconds, target enemy is Pulled and Immovable is applied to them.\n\nImmovable prevents application of Rooted, Knockback, and Pull effects for 20 seconds.`,
      },
      "Shattering Blow": {
        name: "Shattering Blow",
        pos: "h1",
        icon: icons["abi_he_shatteringblow"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1 Ferocity",
        description: talentText`Deals 19% MAP + 250 spiritual damage and applies 1 stack of Reduced Ichor Resistance and 1 stack of Reduced Spiritual Resistance to target enemy.`,
      },
      "Vigilance": {
        name: "Vigilance",
        pos: "i1",
        icon: icons["abi_vigilance"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        description: talentText`Your damage reduction is increased by 50% but your outdoing damage is reduced by 90% for 7 seconds.`,
      },
	  "Slashing Blade": {
        name: "Slashing Blade",
        pos: "c4",
        icon: icons["abi_he_slashingblade"],
        maxRank: 1,
        reqPoints: 5,
        type: "skill",
        cost: "75 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 9% MAP + 104 ichor damage to up to 9 enemies within 30 feet of you. Generates 1 Ferocity.`,
      },
	  "Lion Heart": {
        name: "Lion Heart",
        pos: "h5",
        icon: icons["abi_he_lionsfury"],
        maxRank: 1,
        reqPoints: 10,
        type: "skill",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 10% MAP + 145 spiritual damage to target enemy and applies a 6 second affliction to them. For the duration they will take 7% + 98 spiritual damage every 2 seconds. Generates 1 Ferocity.`,
      },
	  "Thin the Herd": {
        name: "Thin the Herd",
        pos: "c6",
        icon: icons["abi_he_thintheherd"],
        maxRank: 1,
        reqPoints: 15,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 2 Ferocity",
        description: talentText`Deals 31% MAP + 430 spiritual damage to target enemy and applies a 10 second affliction. For the duration, their outgoing healing is reduced by 33%.`,
      },
	  "Whirling Axe": {
        name: "Whirling Axe",
        pos: "c8",
        icon: icons["abi_he_whirlingaxe01"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "3.0s channel",
        cooldown: "no cooldown",
        blue: "Costs 2 Ferocity\nCastable While Moving",
        description: talentText`Deals 10% MAP + 132 spiritual damage to up to 9 enemies within 30 feet of you every second.`,
      },
      "Cull the Weak": {
        name: "Cull the Weak",
        pos: "d9",
        icon: icons["abi_he_culltheweak"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "50 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Applies Marked, Bleeding, and a 6 second affliction to target enemy. At the end of the duration, target will take 22% MAP + 288 spiritual damage and you will generate 1 Ferocity.\n\nMarked lasts for 10 second and reduces target's damage reduction by 15% for the duration.`,
      },
      "Echoing Roar": {
        name: "Echoing Roar",
        pos: "f9",
        icon: icons["abi_he_terrifyingroar"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "self",
        cast: "2.0s channel",
        cooldown: "30s cooldown",
        description: talentText`You interrupt up to 48 enemies who do not have Cover from you within 30 feet of you every 0.5 seconds. Whenever you successfully interupt an enemy, you will deal 10% MAP + 50 ichor damage to them and up to 17 other enemies within 20 feet of them.`,
      },
	  "Bleed Out": {
        name: "Bleed Out",
        pos: "a5",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Your Bleeding effect can now stack up to 3 times on a target. In addition, whenever Bleeding expires it has a 20% chance to reapply.`,
      },
	  "Bloodspatter": {
        name: "Bloodspatter",
        pos: "b5",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you hit a Bleeding enemy with Hack, you will apply Bloody Mess to that target and up to 8 other enemies within 15 feet. Bloody Mess stacks up to 8 times and reduces movement speed by 2% for 6 seconds per stack.`,
      },
	  "Blindsided!": {
        name: "Blindsided!",
        pos: "b6",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Blindside will now apply the Bleeding effect to the target and up to 8 enemies within 30 feet.`,
      },
	  "Lion's Fury": {
        name: "Lion's Fury",
        pos: "h6",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 15,
		prereq: "Lion Heart",
		arrows: [
          { dir: "down", from: "h5", to: "h6" },
        ],
        type: "career tactic",
        description: talentText`The effect from Lion Heart now reduces enemy pushback immunity by 50% for the duration.`,
      },
	  "Chop Chop": {
        name: "Chop Chop",
        pos: "a7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Sundering Chop will now attack one other enemy within 20 feet of you.`,
      },
	  "Demolishing Blow": {
        name: "Demolishing Blow",
        pos: "f7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Shattering Blow will now also apply 1 stack of Reduced Armor.`,
      },
	  "Bloodseeker": {
        name: "Bloodseeker",
        pos: "g8",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Slashing Blade and Whirling Axe will deal 33% more damage against Bleeding targets.`,
      },
	  "Split Artery": {
        name: "Split Artery",
        pos: "e3",
        icon: icons["abi_he_festeringwound"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Your Bleeding effects now deal ${[
          50,
          100,
          150,
          200,
          250,
        ]}% additional damage.`,
      },
	  "Improved Hack": {
        name: "Improved Hack",
        pos: "g4",
        icon: icons["abi_he_hack"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Hack will generate ${[
          5,
          10,
          15,
        ]} more action points.`,
      },
	  "Improved Vigilance": {
        name: "Improved Vigilance",
        pos: "e5",
        icon: icons["abi_vigilance"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Vigilance now only reduces your outgoing damage by ${[
          75,
          60,
          45,
          30,
          15,
        ]}%.`,
      },
	  "Hack and Slash": {
        name: "Hack and Slash",
        pos: "g6",
        icon: icons["abi_he_coordinatestrike"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Each time you use Hack, the damage of your next Coordinated Strike, Slashing Blade, or Sundering Chop will be increased by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%. Effect stacks up to 3 times.`,
      },
	  "Practiced Swing": {
        name: "Practiced Swing",
        pos: "e6",
        icon: icons["abi_he_sunderingchop"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`Sundering Chop will cost 3 Ferocity but will deal ${[
          15,
          30,
          45,
          60,
          75,
        ]}% more damage.`,
      },
	  "Improved Pounce": {
        name: "Improved Pounce",
        pos: "d7",
        icon: icons["abi_he_pounce"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Reduce the cooldown on Pounce by ${[
          3,
          6,
          10,
        ]} seconds.`,
      },
	  "Patient Predator": {
        name: "Patient Predator",
        pos: "e7",
        icon: icons["abi_he_trainedtohunt"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Your maximum action points are increased by ${[
          50,
          100,
          150,
          200,
          250,
        ]}.`,
      },
	  "Flurry": {
        name: "Flurry",
        pos: "e8",
        icon: icons["abi_he_whirlingaxe01"],
        maxRank: 4,
        reqPoints: 25,
        prereq: "Whirling Axe",
		arrows: [
          { dir: "right", from: "c8", to: "e8" },
        ],
        type: "passive",
        description: talentText`The tick interval and duration of Whirling Axe are reduced by ${[
          5,
          10,
          15,
          20,
          25,
        ]}%`,
      },
    },
  },
  "Guardsman": {
    name: "Guardsman",
    background: backgrounds["guardsman"],
    icon: icons["archetype_tank"],
    talents: {
      "Break Loose": {
        name: "Break Loose",
        pos: "a8",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Increase your mass by 1.`,
      },
      "Centuries of Training": {
        name: "centuries of Training",
        pos: "a2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you deal direct damage to an enemy, you have a 33% chance to apply one of three debuffs to them. Effects do not refresh and last 6 seconds.\nDeals 4% MAP + 56 impact damage every second.\nDeals 6% RAP + 80 piercing damage every 2 seconds.\nDeals 10% SAP + 134 spiritual damage every 3 seconds.`,
      },
      "Form Ranks": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, each groupmate within 100 feet that has this tactic will gain 1 stack of purity and a 4 second buff. For the duration, gain 450 penetration and 450 sagacity.`,
      },
      "Feline Grace": {
        name: "Feline Grace",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You and your lion gain 20% movement speed for 4 seconds after using Pounce.`,
      },
      "Animal Within": {
        name: "Animal Within",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You gain 1 Ferocity every 3 seconds if you have no pet active. You gain 6 Ferocity whenever your pet is killed.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specaxe"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Guardsman equip two-handed axes.`,
      },
	  "Hedgehog": {
        name: "Hedgehog",
        pos: "f2",
        icon: icons["morale_hedgehog"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`All groupmates within 100 feet gain 3 stacks of Enhanced Block.`,
      },
      "Champion's Challenge": {
        name: "Champion's Chalenge",
        pos: "g2",
        icon: icons["morale_grapple"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Applies a debuff to target enemy and yourself for 10 seconds. Movement speed is reduced to 0 for the duration.`,
      },
      "Distracting Bellow": {
        name: "Distracting Bellow",
        pos: "h2",
        icon: icons["morale_distractingbellow"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Up to 48 enemies within 30 feet of you receive a debuff. For 10 seconds, they cannot benefit from Cover.`,
      },
      "Immaculate Defense": {
        name: "Immaculate Defense",
        pos: "i2",
        icon: icons["morale_immaculatedefense"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Groupmates within 100 feet gain 25 stacks of a buff for 20 seconds. Each stack grants 3% damage reduction. A stack is removed each time they are attacked by an ability; 4 additional stacks are removed if the ability is single target.`,
      },
      "Hunter's Trap": {
        name: "Hunter's Trap",
        pos: "i4",
        icon: icons["abi_he_ensnare"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Applies Rooted and Immovable to target enemy.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nImmovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Even the Odds": {
        name: "Even the Odds",
        pos: "i5",
        icon: icons["abi_dw_face20"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain 75 toughness for each enemy within 30 feet. Stacks up to 10 times and lasts for 15 seconds.`,
      },
      "Wings of Heaven": {
        name: "Wings of Heaven",
        pos: "i7",
        icon: icons["abi_he_wingsofheaven"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Gain a debuff for 5 seconds which reduces your mass by 8. Leap forward and apply Ensnared to up to 9 enemies within 20 feet of where you land.\n\nEnsnared reduces movement speed by 30% for 16 seconds.`,
      },
      "The Wild Hunt": {
        name: "The Wild Hunt",
        pos: "i8",
        icon: icons["abi_he_baitingstrike"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 20 seconds. For the duration, movement speed will be increased by 40% and accuracy will be increased by 100%.`,
      },
      "Ferocity": {
        name: "Ferocity",
        pos: "a1",
        icon: icons["abi_he_maul"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Ferocity stacks up to a maximum of 8. It is generated by pet skills except for the axeman who has some AP skills that generate it.\n\nBleeding is a status effect that lasts 8 seconds and deals 2% MAP + 10 ichor damage every second.`,
      },
      "Hack": {
        name: "Hack",
        pos: "b1",
        icon: icons["abi_he_hack"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 4% MAP + 30 ichor damage to target enemy. Generates 22 action points.`,
      },
      "Summon Champion Lion": {
        name: "Summon Champion Lion",
        pos: "c1",
        icon: icons["abi_he_callwarlion"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "3.0s cast",
        cooldown: "30s cooldown",
        blue: "Castable While Moving",
        description: talentText`Summon a Champion Lion that has 4000 health and all of your stats.`,
      },
      "Maim Command": {
        name: "Maim Command",
        pos: "d1",
        icon: icons["abi_he_fetch"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Requires Pet\nOff the GCD",
        description: talentText`Your lion attacks its target dealing 15% MAP + 204 piercing damage and applies a 5 second ailment. Generates 1 Ferocity. For the duration, their outgoing damage is reduced by 2%.`,
      },
      "Pounce": {
        name: "Pounce",
        pos: "e1",
        icon: icons["abi_he_pounce"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "0.75s cast",
        cooldown: "30s cooldown",
		blue: "Castable While Moving",
        description: talentText`(Movement Skill) You leap forward.`,
      },
      "Sundering Chop": {
        name: "Sundering Chop",
        pos: "f1",
        icon: icons["abi_he_sunderingchop"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 2 Ferocity",
        description: talentText`Deals 37% MAP + 492 ichor damage to target enemy and applies Bleeding.`,
      },
      "Kurnous Bewitchment": {
        name: "Kurnous Bewitchment",
        pos: "g1",
        icon: icons["abi_he_lawofgold"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "75 action points",
        range: "65ft range",
        cast: "3.0s channel",
        cooldown: "30s cooldown",
        blue: "Castable While Moving",
        description: talentText`Caster has their movement speed reduced by 15%. After 2.5 seconds, target enemy is Pulled and Immovable is applied to them.\n\nImmovable prevents application of Rooted, Knockback, and Pull effects for 20 seconds.`,
      },
      "Nature's Bond": {
        name: "Nature's Bond",
        pos: "h1",
        icon: icons["abi_he_naturesbond"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "30s cooldown",
		blue: "Requires Pet",
        description: talentText`Your lion gains a buff for 10 seconds. For the duration, it has 25% increased damage reduction and -25% outgoing damage. In addition, you will restore 6% RP + 66 health to it every 2 seconds.\n\nYou gain a debuff for 10 seconds. For the duratiom, your damage reduction is decreased by 25%.`,
      },
      "Feline Defender": {
        name: "Feline Defender",
        pos: "i1",
        icon: icons["abi_he_felinegrace"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Requires Pet",
        description: talentText`Toggle: Your lion will grant 30% damage reduction to all groupmates within 50 feet of it. This effect deals 750 true damage per second to your lion.\n\nDefender stacks up to 10 on your lion. Each stack prevents one tick of Feline Defender.`,
      },
	  "Slash Command": {
        name: "Slash Command",
        pos: "g4",
        icon: icons["abi_he_clawsweep"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "75 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Requires Pet\nOff the GCD",
        description: talentText`Command your lion to deal 6% MAP + 89 piercing damage to up to 9 enemies within 30 feet of it. Generates 1 Ferocity.`,
      },
	  "Distract": {
        name: "Distract",
        pos: "h5",
        icon: icons["abi_distract"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "40 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Jams the target for the next 3 seconds interupting the next ability cast.`,
      },
	  "Shattering Blow": {
        name: "Shattering Blow",
        pos: "d6",
        icon: icons["abi_he_shatteringblow"],
        maxRank: 1,
        reqPoints: 15,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1 Ferocity",
        description: talentText`Deals 19% MAP + 250 spiritual damage and applies 1 stack of Reduced Ichor Resistance and 1 stack of Reduced Spiritual Resistance to target enemy.`,
      },
	  "Coordinated Strike": {
        name: "Coordinated Strike",
        pos: "c8",
        icon: icons["abi_he_coordinatestrike"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Deal 8% MAP + 87 piercing damage to target enemy. Generates 1 Ferocity. If your lion is within 30 feet, your lion will hit them 3 times as well and you will generate an additional Ferocity.`,
      },
      "Defeaning Roar": {
        name: "Defeaning Roar",
        pos: "d9",
        icon: icons["abi_he_trainedtothreaten"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "no cost",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "45s cooldown",
        blue: "Requires Pet",
        description: talentText`Gives 10 stacks of Defender to your lion.\n\nDefender stacks up to 10 on your lion. Each stack prevents one tick of Feline Defender.`,
      },
      "Echoing Roar": {
        name: "Echoing Roar",
        pos: "f9",
        icon: icons["abi_he_terrifyingroar"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "self",
        cast: "2.0s channel",
        cooldown: "30s cooldown",
        description: talentText`You interrupt up to 48 enemies who do not have Cover from you within 30 feet of you every 0.5 seconds. Whenever you successfully interupt an enemy, you will deal 10% MAP + 50 ichor damage to them and up to 17 other enemies within 20 feet of them.`,
      },
	  "Revenge": {
        name: "Revenge",
        pos: "a5",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Gain 20% outgoing damage and 30% critical chance for 10 seconds whenever your lion dies.`,
      },
	  "Bloodspatter": {
        name: "Bloodspatter",
        pos: "b5",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you hit a Bleeding enemy with Hack, you will apply Bloody Mess to that target and up to 8 other enemies within 15 feet. Bloody Mess stacks up to 8 times and reduces movement speed by 2% for 6 seconds per stack.`,
      },
	  "Close Bond": {
        name: "Close Bond",
        pos: "b6",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Nature's Bond no longer reduces your lion's outgoing damage or your damage reduction. It also now has a 20 second cooldown.`,
      },
	  "Improved Distract": {
        name: "Improved Distract",
        pos: "h6",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Distract",
		arrows: [
          { dir: "down", from: "h5", to: "h6" },
        ],
        type: "career tactic",
        description: talentText`Distract will now work on up to 23 additional enemeies within 20 feet of the target as long as those targets do not have cover.`,
      },
	  "Defense of the Champion": {
        name: "Defense fo the Champion",
        pos: "a7",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Your lion is summoned with 4 stacks of Defender. In addition, it will gain 1 stack every 3 seconds.`,
      },
	  "Demolishing Blow": {
        name: "Demolishing Blow",
        pos: "d7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
		prereq: "Shattering Blow",
		arrows: [
          { dir: "down", from: "d6", to: "d7" },
        ],
        type: "career tactic",
        description: talentText`Shattering Blow will now also apply 1 stack of Reduced Armor.`,
      },
	  "Full-Fledged Lion": {
        name: "Full-Fledged Lion",
        pos: "g8",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Your lion has 2000 more health and 4 more mass.`,
      },
	  "Baiting Strikes": {
        name: "Baiting Strikes",
        pos: "e3",
        icon: icons["abi_he_echoingroar"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Sundering Chop will grant your lion ${[
          "1 stack of Defender.",
          "2 stacks of Defender. Shattering Blow will grant 1 stack of Defender.",
        ]}\n\nDefender stacks up to 10 on your lion. Each stack prevents one tick of Feline Defender.`,
      },
	  "Flashing Claws": {
        name: "Flashing Claws",
        pos: "c4",
        icon: icons["abi_he_fetch"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Maim Command will now reduce outgoing damage by ${[
          4,
          6,
          8,
          10,
        ]}%.`,
      },
	  "Kurnous' Chosen": {
        name: "Kurnous' Chosen",
        pos: "e5",
        icon: icons["abi_he_lionsroar"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Your lion gains an additional ${[
          75,
          150,
        ]}% of your HP4.`,
      },
	  "Tough Hide": {
        name: "Tough Hide",
        pos: "e6",
        icon: icons["abi_he_gutrip"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Your lion gains an additional ${[
          20,
          40,
          60,
          80,
          100,
        ]}% of your armor, hardiness, and fortitude.`,
      },
	  "Improved Hack": {
        name: "Improved Hack",
        pos: "f6",
        icon: icons["abi_he_hack"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`Hack will generate ${[
          5,
          10,
          15,
        ]} more action points.`,
      },
	  "Pack Synergy": {
        name: "Pack Synergy",
        pos: "e7",
        icon: icons["abi_he_submission"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Whenever you are healed, your lion is healed for ${[
          33,
          66,
          100,
        ]}% of the amount if they are within 65 feet.`,
      },
	  "Trained to Protect": {
        name: "Trained to Protect",
        pos: "f7",
        icon: icons["abi_he_felinegrace"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Whenever you are attacked, there is a ${[
          15,
          30,
          45,
        ]}% chance for your lion to gain a stack of Defender.\n\nDefender stacks up to 10 on your lion. Each stack prevents one tick of Feline Defender.`,
      },
	  "Leonine Frenzy": {
        name: "Leonine Frenzy",
        pos: "e8",
        icon: icons["abi_he_charge"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Your lion has ${[
          5,
          14,
          27,
          45,
        ]}% increased movement speed.`,
      },
    },
  },
  "Hunter": {
    name: "Hunter",
    background: backgrounds["hunter"],
    icon: icons["archetype_dps"],
    talents: {
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Centuries of Training": {
        name: "centuries of Training",
        pos: "a2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you deal direct damage to an enemy, you have a 33% chance to apply one of three debuffs to them. Effects do not refresh and last 6 seconds.\nDeals 4% MAP + 56 impact damage every second.\nDeals 6% RAP + 80 piercing damage every 2 seconds.\nDeals 10% SAP + 134 spiritual damage every 3 seconds.`,
      },
      "Form Ranks": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, each groupmate within 100 feet that has this tactic will gain 1 stack of purity and a 4 second buff. For the duration, gain 450 penetration and 450 sagacity.`,
      },
      "Feline Grace": {
        name: "Feline Grace",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You and your lion gain 20% movement speed for 4 seconds after using Pounce.`,
      },
      "Animal Within": {
        name: "Animal Within",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You gain 1 Ferocity every 3 seconds if you have no pet active. You gain 6 Ferocity whenever your pet is killed.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specaxe"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Hunters equip two-handed axes.`,
      },
	  "Sever Nerve": {
        name: "Sever Nerve",
        pos: "f2",
        icon: icons["morale_severnerve"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Deals 50% MAP + 400 piercing damage to the target.`,
      },
      "Broad Swings": {
        name: "Broad Swings",
        pos: "g2",
        icon: icons["morale_broadswings"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 10 seconds. Your single target abilities will target two additional enemies within 20 feet in front of you.`,
      },
      "Force of Will": {
        name: "Force of Will",
        pos: "h2",
        icon: icons["morale_forceofwill"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 10 seconds. Action point costs are reduced by 75% for the duration.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "Hunter's Trap": {
        name: "Hunter's Trap",
        pos: "i4",
        icon: icons["abi_he_ensnare"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Applies Rooted and Immovable to target enemy.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nImmovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Even the Odds": {
        name: "Even the Odds",
        pos: "i5",
        icon: icons["abi_dw_face20"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain 75 toughness for each enemy within 30 feet. Stacks up to 10 times and lasts for 15 seconds.`,
      },
      "Wings of Heaven": {
        name: "Wings of Heaven",
        pos: "i7",
        icon: icons["abi_he_wingsofheaven"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Gain a debuff for 5 seconds which reduces your mass by 8. Leap forward and apply Ensnared to up to 9 enemies within 20 feet of where you land.\n\nEnsnared reduces movement speed by 30% for 16 seconds.`,
      },
      "The Wild Hunt": {
        name: "The Wild Hunt",
        pos: "i8",
        icon: icons["abi_he_baitingstrike"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 20 seconds. For the duration, movement speed will be increased by 40% and accuracy will be increased by 100%.`,
      },
      "Ferocity": {
        name: "Ferocity",
        pos: "a1",
        icon: icons["abi_he_maul"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Ferocity stacks up to a maximum of 8. It is generated by pet skills except for the axeman who has some AP skills that generate it.\n\nBleeding is a status effect that lasts 8 seconds and deals 2% MAP + 10 ichor damage every second.`,
      },
      "Hack": {
        name: "Hack",
        pos: "b1",
        icon: icons["abi_he_hack"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 4% MAP + 30 ichor damage to target enemy. Generates 22 action points.`,
      },
      "Summon War Lion Lion": {
        name: "Summon War Lion Lion",
        pos: "c1",
        icon: icons["abi_he_bite"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "3.0s cast",
        cooldown: "30s cooldown",
        blue: "Castable While Moving",
        description: talentText`Summon a War Lion that has 3000 health and all of your stats.`,
      },
      "Kill Command": {
        name: "Kill Command",
        pos: "d1",
        icon: icons["abi_he_fangandclaw"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "45 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Requires Pet\nOff the GCD",
        description: talentText`Your lion attacks its target dealing 21% MAP + 280 piercing damage. Generates 1 Ferocity.`,
      },
      "Pounce": {
        name: "Pounce",
        pos: "e1",
        icon: icons["abi_he_pounce"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "0.75s cast",
        cooldown: "30s cooldown",
		blue: "Castable While Moving",
        description: talentText`(Movement Skill) You leap forward.`,
      },
      "Sundering Chop": {
        name: "Sundering Chop",
        pos: "f1",
        icon: icons["abi_he_sunderingchop"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 2 Ferocity",
        description: talentText`Deals 37% MAP + 492 ichor damage to target enemy and applies Bleeding.`,
      },
      "Kurnous Bewitchment": {
        name: "Kurnous Bewitchment",
        pos: "g1",
        icon: icons["abi_he_lawofgold"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "75 action points",
        range: "65ft range",
        cast: "3.0s channel",
        cooldown: "30s cooldown",
        blue: "Castable While Moving",
        description: talentText`Caster has their movement speed reduced by 15%. After 2.5 seconds, target enemy is Pulled and Immovable is applied to them.\n\nImmovable prevents application of Rooted, Knockback, and Pull effects for 20 seconds.`,
      },
      "Nature's Bond": {
        name: "Nature's Bond",
        pos: "h1",
        icon: icons["abi_he_naturesbond"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "30s cooldown",
		blue: "Requires Pet",
        description: talentText`Your lion gains a buff for 10 seconds. For the duration, it has 25% increased damage reduction and -25% outgoing damage. In addition, you will restore 6% RP + 66 health to it every 2 seconds.\n\nYou gain a debuff for 10 seconds. For the duratiom, your damage reduction is decreased by 25%.`,
      },
      "Vigilance": {
        name: "Vigilance",
        pos: "i1",
        icon: icons["abi_vigilance"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        description: talentText`Your damage reduction is increased by 50% but your outgoing damage is reduced by 90% for 7 seconds.`,
      },
	  "Slash Command": {
        name: "Slash Command",
        pos: "g4",
        icon: icons["abi_he_clawsweep"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "75 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Requires Pet\nOff the GCD",
        description: talentText`Command your lion to deal 6% MAP + 89 piercing damage to up to 9 enemies within 30 feet of it. Generates 1 Ferocity.`,
      },
	  "Thin the Herd": {
        name: "Thin the Herd",
        pos: "h5",
        icon: icons["abi_he_thintheherd"],
        maxRank: 1,
        reqPoints: 10,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 2 Ferocity",
        description: talentText`Deals 31% MAP + 430 spiritual damage to target enemy and applies a 10 second affliction. For the duration, their outgoing healing is reduced by 33%.`,
      },
	  "Whirling Axe": {
        name: "Whirling Axe",
        pos: "g6",
        icon: icons["abi_he_whirlingaxe01"],
        maxRank: 1,
        reqPoints: 15,
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "3.0s channel",
        cooldown: "no cooldown",
        blue: "Costs 2 Ferocity\nCastable While Moving",
        description: talentText`Deals 10% MAP + 132 spiritual damage to up to 9 enemies within 30 feet of you every second.`,
      },
	  "Coordinated Strike": {
        name: "Coordinated Strike",
        pos: "c8",
        icon: icons["abi_he_coordinatestrike"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Deal 8% MAP + 87 piercing damage to target enemy. Generates 1 Ferocity. If your lion is within 30 feet, your lion will hit them 3 times as well and you will generate an additional Ferocity.`,
      },
      "Pack Assault": {
        name: "Pack Assault",
        pos: "d9",
        icon: icons["abi_he_packassault"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "80 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Requires Pet",
        description: talentText`The next 10 attacks your lion does within 20 seconds will deal an additional 5% MAP + 60 spiritual damage.`,
      },
      "Echoing Roar": {
        name: "Echoing Roar",
        pos: "f9",
        icon: icons["abi_he_terrifyingroar"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "self",
        cast: "2.0s channel",
        cooldown: "30s cooldown",
        description: talentText`You interrupt up to 48 enemies who do not have Cover from you within 30 feet of you every 0.5 seconds. Whenever you successfully interupt an enemy, you will deal 10% MAP + 50 ichor damage to them and up to 17 other enemies within 20 feet of them.`,
      },
	  "Revenge": {
        name: "Revenge",
        pos: "a5",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Gain 20% outgoing damage and 30% critical chance for 10 seconds whenever your lion dies.`,
      },
	  "Bleed Out": {
        name: "Bleed Out",
        pos: "b5",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Your Bleeding effect can now stack up to 3 times on a target. In addition, whenever Bleeding expires it has a 20% chance to reapply.`,
      },
	  "Close Bond": {
        name: "Close Bond",
        pos: "b6",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Nature's Bond no longer reduces your lion's outgoing damage or your damage reduction. It also now has a 20 second cooldown.`,
      },
	  "Unfair Advantage": {
        name: "Unfair Advantage",
        pos: "c6",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Whenever you hit an enemy you are flanking, you will gain a buff for 2 seconds. For the duration, you will gain outgoing damage equal to 100% of your accuracy.`,
      },
	  "Chop Chop": {
        name: "Chop Chop",
        pos: "a7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Sundering Chop will now attack one other enemy within 20 feet of you.`,
      },
	  "Joy of the Hunt": {
        name: "Joy of the Hunt",
        pos: "h7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Whirling Axe",
		arrows: [
          { dir: "right-down", from: "g6", to: "h6" },
          { dir: "right-down-down", from: "h6", to: "h7" }
        ],
        type: "career tactic",
        description: talentText`Slash Command and Whirling Axe now hit up to 24 enemies.`,
      },
	  "Axe and Claw": {
        name: "Axe and Claw",
        pos: "d8",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Coordinated Strike",
		arrows: [
          { dir: "right", from: "c8", to: "d8" },
        ],
        type: "career tactic",
        description: talentText`If your lion is active, the action point cost on Coordinated Strike is reduced by 50%. If your lion is not active, the cooldown on Coordinated Strike is reduced by 50%.`,
      },
	  "Trained to Kill": {
        name: "Trained to Kill",
        pos: "e3",
        icon: icons["abi_he_throatbite"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`You gain ${[
          3,
          6,
          10,
        ]}% increased critical chance while your pet is active. You lose ${[
          9,
          18,
          30,
        ]}% critical chance when it is not.`,
      },
	  "Kurnous' Chosen": {
        name: "Kurnous' Chosen",
        pos: "c4",
        icon: icons["abi_he_lionsroar"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Your lion gains an additional ${[
          75,
          150,
        ]}% of your HP4.`,
      },
	  "Improved Hack": {
        name: "Improved Hack",
        pos: "e5",
        icon: icons["abi_he_hack"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Hack will generate ${[
          5,
          10,
          15,
        ]} more action points.`,
      },
	  "Hack and Slash": {
        name: "Hack and Slash",
        pos: "e6",
        icon: icons["abi_he_coordinatestrike"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Each time you use Hack, the damage of your next Coordinated Strike, Slashing Blade, or Sundering Chop will be increased by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%. Effect stacks up to 3 times.`,
      },
	  "Practiced Swing": {
        name: "Practiced Swing",
        pos: "d6",
        icon: icons["abi_he_sunderingchop"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`Sundering Chop will cost 3 Ferocity but will deal ${[
          15,
          30,
          45,
          60,
          75,
        ]}% more damage.`,
      },
	  "Improved Vigilance": {
        name: "blueprint",
        pos: "b7",
        icon: icons["abi_vigilance"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Vigilance now only reduces your outgoing damage by ${[
          75,
		  60,
          45,
        ]}%.`,
      },
	  "Flurry": {
        name: "Flurry",
        pos: "g7",
        icon: icons["abi_he_whirlingaxe01"],
        maxRank: 3,
        reqPoints: 20,
        prereq: "Whirling Axe",
		arrows: [
          { dir: "down", from: "g6", to: "g7" },
        ],
        type: "passive",
        description: talentText`The tick interval and duration of Whirling Axe are reduced by ${[
          5,
          10,
          15,
          20,
          25,
        ]}%`,
      },
	  "Leonine Frenzy": {
        name: "Leonine Frenzy",
        pos: "e8",
        icon: icons["abi_he_charge"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Your lion has ${[
          5,
          14,
          27,
          45,
        ]}% increased movement speed.`,
      },
    },
  },
};