import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/greenskin"),
);
const icons = requireAll(require.context("../../assets/icons/greenskin"));

export const data: TalentData = {
  "Shroomancer": {
    name: "Shroomancer",
    background: backgrounds["shroomancer"],
    icon: icons["archetype_healer"],
    talents: {
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "What a Rush": {
        name: "What a Rush",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`The action point cost of your skills is reduced by 33% on allies that are lower than 40% health.`,
      },
      "Stop Hittin' Me!": {
        name: "Stop Hittin' Me!",
        pos: "a2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You have 1 less mass. In addition, each time you are attacked you will gain a stack that stacks up to 8 and lasts 6 seconds. Gain 5% movement speed for the duration.`,
      },
      "Waaagh": {
        name: "Waaagh",
        pos: "b2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that have this tactic gain 1 Fightiness, gain 3 Pyschic Energy, lose 1 Cowardice, or lose 1 Paranoia.`,
      },
      "Greenoholic": {
        name: "Greenoholic",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Fungus Beer no longer has a cooldown.`,
      },
      "Extra Special Mushrooms": {
        name: "Extra Special Mushrooms",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You restore 420 + 28% wounds health whenever you use Fungal Beer.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specstaff"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Shroomancers equip staves.`,
      },
	  "Return Life": {
        name: "Return Life",
        pos: "f2",
        icon: icons["morale_returnlife"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Return target groupmate back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Divine Protection": {
        name: "Divine Protection",
        pos: "h2",
        icon: icons["morale_divineprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 15 seconds. They will absorb up to 200% RP + 1500 damage over the duration.`,
      },
      "Alter Fate": {
        name: "Alter Fate",
        pos: "i2",
        icon: icons["morale_alterfate"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Removes all afflictions and cripples from each groupmate within 100ft. Also applies Return Life to each dead groupmate within 100ft.`,
      },
      "Too Smart For Dat": {
        name: "Too Smart For Dat",
        pos: "i4",
        icon: icons["abi_gs_getsmarter"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Reduce your Paranoia by 5.`,
      },
      "Gork Sez Stop": {
        name: "Gork Sez Stop",
        pos: "i5",
        icon: icons["abi_or_hand02"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Apply a 2s debuff to target enemy. Deals 10% SAP + 150 elemental damage to the target every second. The duration of the debuff is refreshed whenever the target moves.`,
      },
      "Ain't Dun Yet": {
        name: "Ain't Dun Yet",
        pos: "i7",
        icon: icons["abi_gs_gimmie"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Gain a buff for 20 seconds. For the duration, every second your Cowardice and Paranoia will lower by 1 and you will gain 20 action points.`,
      },
      "Fist of Gork": {
        name: "Fist of Gork",
        pos: "i8",
        icon: icons["abi_gs_fistsofgork"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Deals 33% SAP + 446 elemental damage to target enemy. Up to 23 enemies within 20 feet of the target also take that damage and are knocked-back.`,
      },
      "Paranoia": {
        name: "Paranoia",
        pos: "a1",
        icon: icons["abi_gs_donthitme"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Paranoia has a base of 0 and a max of 30. Reduced at a rate of 3 per second outside of combat. Paranoia applies a negative effect to the caster at intervals based on amount of current paranoia.\n1 - 5: 1 every 15 seconds.\n6 - 10: 1 every 12 seconds.\n10 - 14: 1 every 10 seconds.\n15 - 19: 1 every 8 seconds.\n20 - 24: 1 every 5 seconds.\n25 - 29: 1 every 3 seconds.\n30 - 30: 1 every second.\n\nThe following are the negative effects that can be applied chosen at random: Gain 1 stack of Reduced Intelliegence, Reduced Willpower, Reduced Initiative, Reduced Agility, Reduced Critical Hit Rating, Reduced Potency, Reduced Accuracy, Reduced Block, Reduced Incoming Healing, or Removes Inevitable and Unstoppable from you.`,
      },
      "Touch of Gork": {
        name: "Touch of Gork",
        pos: "b1",
        icon: icons["abi_or_hand03"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 6% SAP + 133 elemental damage to target enemy. Generates 40 action points.`,
      },
      "Fungus Beer": {
        name: "Fungus Beer",
        pos: "c1",
        icon: icons["itm_ge_slimepurple"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "6s cooldown",
		blue: "Off the GCD",
        description: talentText`Generates 2 Paranoia and one of the negative effects to the caster. Your next spell will be augmented.`,
      },
      "Bigger, Better, an' Greener": {
        name: "Bigger, Better, an' Greener",
        pos: "d1",
        icon: icons["abi_gs_fickskin"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "70 action points",
        range: "150ft range",
        cast: "2.5s cast",
        cooldown: "no cooldown",
        description: talentText`Applies a 12 second enchantment to target ally. For the duration, restore 19% RP + 252 health to them every 3 seconds.\n\nAugmented: Restore 18% RP + 215 health to target on spell cast.`,
      },
      "Summon Mushroom": {
        name: "Summon Mushroom",
        pos: "e1",
        icon: icons["abi_or_symbol03"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Summons a "pet" mushroom. This mushroom will heal allies within 30 feet every 2 seconds for 5% RP + 46.`,
      },
      "Ey! Quit Bleedin'": {
        name: "Ey! Quit Bleedin'",
        pos: "f1",
        icon: icons["abi_gs_eyquitbleedin"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "36 action points",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`Applies a 12 second affliction to target enemy. For the duration, deal 21% SAP + 274 corporeal damage every 3 seconds to them.\n\nAugmented: Deals 12% SAP + 166 elemental damage on cast to target.`,
      },
      "Eeek!": {
        name: "Eeek!",
        pos: "g1",
        icon: icons["abi_gs_eeeek"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Knocks target enemy away from you and applies Immovable to them.\n\nImmovable prevents application of Knockbacks, Pulls, and Roots for 20 seconds.`,
      },
      "Sticky Feetz": {
        name: "Sticky Feetz",
        pos: "h1",
        icon: icons["abi_or_speedyfeet"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Place a 20 foot area on the ground. Allies in the area will have their abilities augmented. Enemies in the area will have their movement speed reduced by 50%.`,
      },
      "RUN AWAY!": {
        name: "RUN AWAY!",
        pos: "i1",
        icon: icons["abi_gs_runaway"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "45s cooldown",
        description: talentText`(Movement Skill) For the next 6 seconds, your movement speed is increased by 25%.`,
      },
	  "Mork'll Fix It": {
        name: "Mork'll Fix It",
        pos: "g4",
        icon: icons["abi_gs_degreenest"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "40 action points",
        range: "150ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`Restore 22% RP + 293 health to target ally.\n\nAugmented: ability is now instant cast.`,
      },
	  "Puff of Poison": {
        name: "Puff of Poison",
        pos: "h5",
        icon: icons["abi_or_mushroom01"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "75 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "6s cooldown",
        blue: "Off the GCD",
        description: talentText`Applies a 9 second affliction to up to 9 enemies within 30 feet of your mushroom. For the duration, deals 5% SAP + 60 corporeal damage every 3 seconds.\n\nAugmented: now deals 7% SAP + 90 corporeal damage every 3 seconds.`,
      },
	  "Blightbloom": {
        name: "Blightbloom",
        pos: "f6",
        icon: icons["abi_or_mushroom02"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "75 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "6s cooldown",
        blue: "Off the GCD",
        description: talentText`Restores 5% RP + 50 health to up to 9 allies within 30 feet of your mushroom.\n\nAugmented: restores 7% RP + 76 health instead.`,
      },
	  "Mycotoxin": {
        name: "Mycotoxin",
        pos: "e8",
        icon: icons["abi_or_melee18"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "100 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Applies 5 stacks of fungal poison to your weapon. Whenever you use a basic attack, you will deal an additional 9% SAP + 114 corporeal damage and remove 1 stack.\n\nAugmented: applies 7 stacks.`,
      },
      "Gather Round": {
        name: "Gather Round",
        pos: "d9",
        icon: icons["abi_or_symbol01"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "75 action points",
        range: "75ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`Restores 11% RP + 153 health to up to 9 allies within a 30 foot area you select.\n\nAugmented: ability is now instant cast.`,
      },
      "Sneaky Waaagh": {
        name: "Sneaky Waaagh",
        pos: "f9",
        icon: icons["abi_gs_windupdawaaagh"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "75ft range",
        cast: "1.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Up to 10 enemies within a 30 foot area you select gain a debuff for 1 second if they do not have cover from you. At the end of the duration, they apply 1 stack of a 6 second debuff to up to 96 enemies within 30 feet of them. Enemies lose 5% damage reduction per stack.`,
      },
	  "Outta Ere!": {
        name: "Outta Ere!",
        pos: "a5",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`The cooldown on RUN AWAY! is reduced by 20 seconds.`,
      },
	  "Spore Pods": {
        name: "Spore Pods",
        pos: "b5",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`If your Summon Mushroom is killed, all groupmates within 100 feet of you gain a buff for 5 second. For the duration, gain 5 adrenaline per second and restore 5% RP + 40 health every second.`,
      },
	  "Fungus Gud For Ya": {
        name: "Fungus Gud For Ya",
        pos: "a6",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Gain 2 mass for 3 seconds whenever you cast Fungal Beer.`,
      },
	  "Lookit What I Did!": {
        name: "Lookit What I Did!",
        pos: "c6",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`The durations of Bigger, Better, an' Greener; Ey! Quit Bleedin'; and Puff of Poison are increased by 6 seconds.`,
      },
	  "Fungal Infestation": {
        name: "Fungal Infestation",
        pos: "a7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Summon Mushroom, Puff of Poison, and Blightbloom now hit up to 24 targets.`,
      },
	  "Pass It On": {
        name: "Pass It On",
        pos: "b7",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Whenever you heal an ally with Bigger, Better, an' Greener or Mork'll Fix It; you will apply a 6 second enchantment to an ally within 50 feet of the target. Absorb up to 21% RP + 280 damage for the duration.`,
      },
	  "Ere We Go": {
        name: "Ere We Go",
        pos: "f8",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Mycotoxin",
		arrows: [
          { dir: "right", from: "e8", to: "f8" },
        ],
        type: "career tactic",
        description: talentText`Mycotoxin now applies to all groupmates within 100 feet of you.`,
      },
	  "Fungral Growth": {
        name: "Fungral Growth",
        pos: "e3",
        icon: icons["abi_gs_stealyerthunder"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever you cast Fungal Beer, a random groupmate within 100 feet will be healed for ${[
          5,
          10,
          15,
          20,
          25,
        ]}% RP.`,
      },
	  "Run Fasta'": {
        name: "Run Fasta'",
        pos: "c4",
        icon: icons["abi_gs_runaway"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`RUN AWAY! will now increase your movement speed by ${[
          30,
          35,
          40,
        ]}%.`,
      },
	  "Bleed Fer Me": {
        name: "Bleed Fer Me",
        pos: "e5",
        icon: icons["abi_gs_eyquitbleedin"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Ey! Quit Bleedin' can now stack up to ${[
          2,
          3,
        ]} times on the same target.`,
      },
	  "I'll Take That": {
        name: "I'll Take That",
        pos: "d6",
        icon: icons["abi_or_figure17"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`Touch of Gork will now heal your defensive target for ${[
          75,
          150,
        ]}% and Mycotoxin will now heal for ${[
          10,
          20,
        ]}% of the damage they deal.`,
      },
	  "Mork Iz Betta!": {
        name: "Mork Iz Betta!",
        pos: "g6",
        icon: icons["abi_or_mob"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Mork'll Fix It",
		arrows: [
          { dir: "down", from: "g4", to: "g6" },
        ],
        type: "passive",
        description: talentText`Mork'll Fix It will heal targets affected with Bigger, Better, and Greener for an additional ${[
          10,
          20,
          30,
          40,
          50,
        ]}%`,
      },
	  "Shroom Git": {
        name: "Shroom Git",
        pos: "e7",
        icon: icons["abi_or_symbol03"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Reduce the cooldown on Summon Mushroom by ${[
          5,
          10,
          15,
        ]} seconds.`,
      },
	  "Mighty Shrooms": {
        name: "Mighty Shrooms",
        pos: "h7",
        icon: icons["abi_or_mushroom03"],
        maxRank: 3,
        reqPoints: 20,
        prereq: "Puff of Poison",
		arrows: [
          { dir: "down", from: "h5", to: "h7" }
        ],
        type: "passive",
        description: talentText`Increases the healing of Blightbloom and the damage of Puff of Poison by ${[
          8,
          16,
          25,
        ]}%.`,
      },
	  "Don' Feel Nuthin'": {
        name: "Don' Feel Nuthin'",
        pos: "d8",
        icon: icons["abi_or_figure08"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Whenever you critically heal someone, you will apply an enchantment on them for 5 seconds. Effect does not refresh. At the end of the duration, target will be healed for 40 + ${[
          8,
          16,
          24,
          32,
        ]}% RP.`,
      },
    },
  },
  "Little Waaagh": {
    name: "Little Waaagh",
    background: backgrounds["little waaagh"],
    icon: icons["archetype_offsupport"],
    talents: {
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 1,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "Stop Hittin' Me!": {
        name: "Stop Hittin' Me!",
        pos: "a2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You have 1 less mass. In addition, each time you are attacked you will gain a stack that stacks up to 8 and lasts 6 seconds. Gain 5% movement speed for the duration.`,
      },
      "Waaagh": {
        name: "Waaagh",
        pos: "b2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that have this tactic gain 1 Fightiness, gain 3 Pyschic Energy, lose 1 Cowardice, or lose 1 Paranoia.`,
      },
      "Greenoholic": {
        name: "Greenoholic",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Fungus Beer no longer has a cooldown.`,
      },
      "Extra Special Mushrooms": {
        name: "Extra Special Mushrooms",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You restore 420 + 28% wounds health whenever you use Fungal Beer.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specstaff"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Little Waaagh equip staves.`,
      },
	  "Return Life": {
        name: "Return Life",
        pos: "f2",
        icon: icons["morale_returnlife"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Return target groupmate back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Divine Protection": {
        name: "Divine Protection",
        pos: "h2",
        icon: icons["morale_divineprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 15 seconds. They will absorb up to 200% RP + 1500 damage over the duration.`,
      },
      "Alter Fate": {
        name: "Alter Fate",
        pos: "i2",
        icon: icons["morale_alterfate"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Removes all afflictions and cripples from each groupmate within 100ft. Also applies Return Life to each dead groupmate within 100ft.`,
      },
      "Too Smart For Dat": {
        name: "Too Smart For Dat",
        pos: "i4",
        icon: icons["abi_gs_getsmarter"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Reduce your Paranoia by 5.`,
      },
      "Gork Sez Stop": {
        name: "Gork Sez Stop",
        pos: "i5",
        icon: icons["abi_or_hand02"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Apply a 2s debuff to target enemy. Deals 10% SAP + 150 elemental damage to the target every second. The duration of the debuff is refreshed whenever the target moves.`,
      },
      "Ain't Dun Yet": {
        name: "Ain't Dun Yet",
        pos: "i7",
        icon: icons["abi_gs_gimmie"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Gain a buff for 20 seconds. For the duration, every second your Cowardice and Paranoia will lower by 1 and you will gain 20 action points.`,
      },
      "Fist of Gork": {
        name: "Fist of Gork",
        pos: "i8",
        icon: icons["abi_gs_fistsofgork"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Deals 33% SAP + 446 elemental damage to target enemy. Up to 23 enemies within 20 feet of the target also take that damage and are knocked-back.`,
      },
      "Paranoia": {
        name: "Paranoia",
        pos: "a1",
        icon: icons["abi_gs_donthitme"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Paranoia has a base of 0 and a max of 30. Reduced at a rate of 3 per second outside of combat. Paranoia applies a negative effect to the caster at intervals based on amount of current paranoia.\n1 - 5: 1 every 15 seconds.\n6 - 10: 1 every 12 seconds.\n10 - 14: 1 every 10 seconds.\n15 - 19: 1 every 8 seconds.\n20 - 24: 1 every 5 seconds.\n25 - 29: 1 every 3 seconds.\n30 - 30: 1 every second.\n\nThe following are the negative effects that can be applied chosen at random: Gain 1 stack of Reduced Intelliegence, Reduced Willpower, Reduced Initiative, Reduced Agility, Reduced Critical Hit Rating, Reduced Potency, Reduced Accuracy, Reduced Block, Reduced Incoming Healing, or Removes Inevitable and Unstoppable from you.`,
      },
      "Touch of Gork": {
        name: "Touch of Gork",
        pos: "b1",
        icon: icons["abi_or_hand03"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 6% SAP + 133 elemental damage to target enemy. Generates 40 action points.`,
      },
      "Fungus Beer": {
        name: "Fungus Beer",
        pos: "c1",
        icon: icons["itm_ge_slimepurple"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "6s cooldown",
		blue: "Off the GCD",
        description: talentText`Generates 2 Paranoia and one of the negative effects to the caster. Your next spell will be augmented.`,
      },
      "Ability 1": {
        name: "Ability 1",
        pos: "d1",
        icon: icons["abi_or_melee14"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "100ft range",
        cast: "1.0s cast",
        cooldown: "no cooldown",
        description: talentText`Deals 14% SAP + 171 elemental damage to target enemy and applies 1 stack of Reduced Toughness.\n\nAugmented: Will apply an additional stack.`,
      },
      "Ey! Quit Bleedin'": {
        name: "Ey! Quit Bleedin'",
        pos: "e1",
        icon: icons["abi_gs_eyquitbleedin"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "36 action points",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`Applies a 12 second affliction to target enemy. For the duration, deal 21% SAP + 274 corporeal damage every 3 seconds to them.\n\nAugmented: Deals 12% SAP + 166 elemental damage on cast to target.`,
      },
      "Ability 2": {
        name: "Ability 2",
        pos: "f1",
        icon: icons["abi_or_wotsdarush"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "25 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Applies 1 stack of Reduced Agility to target enemy.\n\nAugmented: Also applies one stack of Reduced Initiative.`,
      },
      "Eeek!": {
        name: "Eeek!",
        pos: "g1",
        icon: icons["abi_gs_eeeek"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Knocks target enemy away from you and applies Immovable to them.\n\nImmovable prevents application of Knockbacks, Pulls, and Roots for 20 seconds.`,
      },
      "Sticky Feetz": {
        name: "Sticky Feetz",
        pos: "h1",
        icon: icons["abi_or_speedyfeet"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Place a 20 foot area on the ground. Allies in the area will have their abilities augmented. Enemies in the area will have their movement speed reduced by 50%.`,
      },
      "RUN AWAY!": {
        name: "RUN AWAY!",
        pos: "i1",
        icon: icons["abi_gs_runaway"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "45s cooldown",
        description: talentText`(Movement Skill) For the next 6 seconds, your movement speed is increased by 25%.`,
      },
	  "Ability 3": {
        name: "Ability 3",
        pos: "h4",
        icon: icons["abi_ge_zap"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "75 action points",
        range: "75ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`Deals 36% SAP + 485 elemental damage to target enemy. Then will jump to another enemy within 20 feet. Jumps twice.\n\nAugmented: each jump will explode dealing 7% SAP + 95 elemental damage to 1 additional enemy within 20 feet.`,
      },
	  "Ability 4": {
        name: "Ability 4",
        pos: "c5",
        icon: icons["abi_or_shrugitoff"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "45 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Target ally gains 1 stack of Enhanced Penetration and Enhanced Sagacity.\n\nAugmented: will apply to 2 additional groupmates within 100 feet of you.`,
      },
	  "Mycotoxin": {
        name: "Mycotoxin",
        pos: "b6",
        icon: icons["abi_or_melee18"],
        maxRank: 1,
        reqPoints: 15,
        type: "skill",
        cost: "100 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Applies 5 stacks of fungal poison to your weapon. Whenever you use a basic attack, you will deal an additional 9% SAP + 114 corporeal damage and remove 1 stack.\n\nAugmented: applies 7 stacks.`,
      },
	  "Ability 5": {
        name: "Abiltity 5",
        pos: "e8",
        icon: icons["abi_or_figure16"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "50 action points",
        range: "75ft range",
        cast: "2.25s channel",
        cooldown: "10s cooldown",
        description: talentText`Deals 16% SAP + 200 elemental damage to target enemy every 0.75 seconds.\n\nAugmented: removes the cooldown.`,
      },
      "Ability 6": {
        name: "Ability 6",
        pos: "d9",
        icon: icons["abi_or_figure18"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "60 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Applies Marked and an 8 second cripple to target enemy. At the end of the duration, deal 28% SAP + 376 corporeal damage to them.\n\nMarked reduces the target's damage reduction by 15% for 10 seconds.`,
      },
      "Sneaky Waaagh": {
        name: "Sneaky Waaagh",
        pos: "f9",
        icon: icons["abi_gs_windupdawaaagh"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "75ft range",
        cast: "1.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Up to 10 enemies within a 30 foot area you select gain a debuff for 1 second if they do not have cover from you. At the end of the duration, they apply 1 stack of a 6 second debuff to up to 96 enemies within 30 feet of them. Enemies lose 5% damage reduction per stack.`,
      },
	  "Outta Ere!": {
        name: "Outta Ere!",
        pos: "a5",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`The cooldown on RUN AWAY! is reduced by 20 seconds.`,
      },
	  "Tactic 2": {
        name: "Tactic 2",
        pos: "g5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Ey Quit Bleedin will apply 1 stack of Reduced Healing Received as well as Bleeding to the target.\n\nBleeding is a status effect that deals 2% MAP + 10 ichor damage eveyr second.`,
      },
	  "Fungal Hyphae": {
        name: "Fungal Hyphae",
        pos: "d6",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Gain 2 mass for 3 seconds whenever you cast Fungal Beer.`,
      },
	  "Tactic 1": {
        name: "Tactic 1",
        pos: "f6",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Ability 1 and Ability 2 will now hit 2 additional enemies within 20 feet of the primary target.`,
      },
	  "Tactic 3": {
        name: "Tactic 3",
        pos: "a7",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Lose 1 Paranoia every 5 seconds.`,
      },
	  "Ere We Go": {
        name: "Ere We Go",
        pos: "b7",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Mycotoxin",
		arrows: [
          { dir: "down", from: "b6", to: "b7" },
        ],
        type: "career tactic",
        description: talentText`Mycotoxin now applies to all groupmates within 100 feet of you.`,
      },
	  "Tactic 4": {
        name: "Tactic 4",
        pos: "c8",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Sticky Feetz will no longer reduce enemy movement speed. Instead, it will apply Rooted and Immovable to up to 96 enemies in the area on cast.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nImmovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
	  "Passive 1": {
        name: "Passive 1",
        pos: "e3",
        icon: icons["abi_gs_lemmeout"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`You will gain ${[
          3,
          6,
          9,
          12,
        ]} action points whenever you cast Fungal Beer.`,
      },
	  "Bleed Fer Me": {
        name: "Bleed Fer Me",
        pos: "e5",
        icon: icons["abi_gs_eyquitbleedin"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Ey! Quit Bleedin' can now stack up to ${[
          2,
          3,
		  4,
		  5,
		  6,
        ]} times on the same target.`,
      },
	  "Passive 2": {
        name: "Passive 2",
        pos: "e6",
        icon: icons["abi_or_face17"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`Groupmates within 100 feet of you will gain ${[
          3,
          6,
        ]}% outgoing damage for 3 seconds whenever you cast Fungal Beer.`,
      },
	  "Passive 3": {
        name: "Passive 3",
        pos: "h6",
        icon: icons["abi_ge_zap"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Ability 3",
		arrows: [
          { dir: "down", from: "h4", to: "h6" },
        ],
        type: "passive",
        description: talentText`The augmented explosion for Ability 3 will now hit ${[
          2,
          3,
          4,
          5,
          6,
        ]} additional enemies.`,
      },
	  "Passive 5": {
        name: "Passive 5",
        pos: "e7",
        icon: icons["abi_or_face06"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`You always have ${[
          3,
          6,
          9,
        ]}% outgoing damage but also gain 1 Paranoia every 5 seconds.`,
      },
	  "Run Fasta'": {
        name: "Run Fasta'",
        pos: "h7",
        icon: icons["abi_gs_runaway"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`RUN AWAY! will now increase your movement speed by ${[
          30,
          35,
          40,
        ]}%.`,
      },
	  "Passive 6": {
        name: "Passive 6",
        pos: "g8",
        icon: icons["abi_or_figure17"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`You have a ${[
          12.5,
          25,
          37.5,
          50,
        ]}% chance whenever you cast Fungal Beer to cause your next damage ability to dispel 1 enchantment from the target.`,
      },
    },
  },
  "Sneaky Git": {
    name: "Sneaky Git",
    background: backgrounds["stalker"],
    icon: icons["archetype_dps"],
    talents: {
      "Break Loose": {
        name: "Break Loose",
        pos: "a8",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 1,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Stop Hittin' Me!": {
        name: "Stop Hittin' Me!",
        pos: "a2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You have 1 less mass. In addition, each time you are attacked you will gain a stack that stacks up to 8 and lasts 6 seconds. Gain 5% movement speed for the duration.`,
      },
      "Waaagh": {
        name: "Waaagh",
        pos: "b2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that have this tactic gain 1 Fightiness, gain 3 Pyschic Energy, lose 1 Cowardice, or lose 1 Paranoia.`,
      },
      "Greenoholic": {
        name: "Greenoholic",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Fungus Beer no longer has a cooldown.`,
      },
      "Extra Special Mushrooms": {
        name: "Extra Special Mushrooms",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You restore 420 + 28% wounds health whenever you use Fungal Beer.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Sneaky Gitz equip a single dagger.`,
      },
	  "Sever Nerve": {
        name: "Sever Nerve",
        pos: "f2",
        icon: icons["morale_severnerve"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Deals 50% MAP + 400 physical damage to the target.`,
      },
      "Broad Swings": {
        name: "Broad Swings",
        pos: "g2",
        icon: icons["morale_broadswings"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a  buff for 10 seconds. Your single target abilities will target two additional enemies within 15ft in front of you.`,
      },
      "Force of Will": {
        name: "Force of Will",
        pos: "h2",
        icon: icons["morale_forceofwill"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 10 seconds. Action point costs are reduced by 75% for the duration.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "Too Smart For Dat": {
        name: "Too Smart For Dat",
        pos: "i4",
        icon: icons["abi_gs_getsmarter"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Reduce your Paranoia by 5.`,
      },
      "Gork Sez Stop": {
        name: "Gork Sez Stop",
        pos: "i5",
        icon: icons["abi_or_hand02"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Apply a 2s debuff to target enemy. Deals 10% SAP + 150 elemental damage to the target every second. The duration of the debuff is refreshed whenever the target moves.`,
      },
      "Ain't Dun Yet": {
        name: "Ain't Dun Yet",
        pos: "i7",
        icon: icons["abi_gs_gimmie"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Gain a buff for 20 seconds. For the duration, every second your Cowardice and Paranoia will lower by 1 and you will gain 20 action points.`,
      },
      "Fist of Gork": {
        name: "Fist of Gork",
        pos: "i8",
        icon: icons["abi_gs_fistsofgork"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Deals 33% SAP + 446 elemental damage to target enemy. Up to 23 enemies within 20 feet of the target also take that damage and are knocked-back.`,
      },
      "Paranoia": {
        name: "Paranoia",
        pos: "a1",
        icon: icons["abi_gs_donthitme"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Paranoia has a base of 0 and a max of 30. Reduced at a rate of 3 per second outside of combat. Paranoia applies a negative effect to the caster at intervals based on amount of current paranoia.\n1 - 5: 1 every 15 seconds.\n6 - 10: 1 every 12 seconds.\n10 - 14: 1 every 10 seconds.\n15 - 19: 1 every 8 seconds.\n20 - 24: 1 every 5 seconds.\n25 - 29: 1 every 3 seconds.\n30 - 30: 1 every second.\n\nThe following are the negative effects that can be applied chosen at random: Gain 1 stack of Reduced Intelliegence, Reduced Willpower, Reduced Initiative, Reduced Agility, Reduced Critical Hit Rating, Reduced Potency, Reduced Accuracy, Reduced Block, Reduced Incoming Healing, or Removes Inevitable and Unstoppable from you.`,
      },
      "Goblin Basic Attack": {
        name: "Goblin Basic Attack",
        pos: "b1",
        icon: icons["abi_or_melee05"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deal 4% MAP + 30 piercing damage to target enemy. Generates 22 action points.`,
      },
      "Fungus Beer": {
        name: "Fungus Beer",
        pos: "c1",
        icon: icons["itm_ge_slimepurple"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "6s cooldown",
		blue: "Off the GCD",
        description: talentText`Generates 2 Paranoia and one of the negative effects to the caster. Your next spell will be augmented.`,
      },
      "Mycotoxin": {
        name: "Mycotoxin",
        pos: "d1",
        icon: icons["abi_or_melee18"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "100 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Applies 5 stacks of fungal poison to your weapon. Whenever you use a basic attack, you will deal an additional 9% SAP + 114 corporeal damage and remove 1 stack.\n\nAugmented: applies 7 stacks.`,
      },
      "Stalk": {
        name: "Stalk",
        pos: "e1",
        icon: icons["abi_stalk"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "2.5s cast",
        cooldown: "45s cooldown",
        blue: "Castable while Moving",
        description: talentText`(Movement Skill) You become invisible to enemies for up to 5 min. Your action points per second is set to -5, and you will come out of stalk if you reach 0 action points.`,
      },
      "Ey! Quit Bleedin'": {
        name: "Ey! Quit Bleedin'",
        pos: "f1",
        icon: icons["abi_gs_eyquitbleedin"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "36 action points",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`Applies a 12 second affliction to target enemy. For the duration, deal 21% SAP + 274 corporeal damage every 3 seconds to them.\n\nAugmented: Deals 12% SAP + 166 elemental damage on cast to target.`,
      },
      "Eeek!": {
        name: "Eeek!",
        pos: "g1",
        icon: icons["abi_gs_eeeek"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Knocks target enemy away from you and applies Immovable to them.\n\nImmovable prevents application of Knockbacks, Pulls, and Roots for 20 seconds.`,
      },
      "Sticky Feetz": {
        name: "Sticky Feetz",
        pos: "h1",
        icon: icons["abi_or_speedyfeet"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Place a 20 foot area on the ground. Allies in the area will have their abilities augmented. Enemies in the area will have their movement speed reduced by 50%.`,
      },
      "Vigilance": {
        name: "Vigilance",
        pos: "i1",
        icon: icons["abi_vigilance"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        description: talentText`Your damage reduction is increased by 50% but your outgoing damage is reduced by 90% for 7 seconds.`,
      },
	  "Ability 7": {
        name: "Ability 7",
        pos: "h4",
        icon: icons["abi_go_face01"],
        maxRank: 1,
        reqPoints: 5,
        type: "skill",
        cost: "75 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 10% MAP + 130 corporeal damage to up to 9 enemies within 30 feet in front of you.`,
      },
	  "Ability 8": {
        name: "Ability 8",
        pos: "c5",
        icon: icons["abi_or_nofightinback"],
        maxRank: 1,
        reqPoints: 10,
        type: "skill",
        cost: "36 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
		blue: "Disabled by Coward!",
        description: talentText`Deal 21% MAP + 280 elemental damage to target enemy.\n\nAugmented: counts as a basic attack.`,
      },
	  "Ability 9": {
        name: "Ability 9",
        pos: "h6",
        icon: icons["abi_gs_puddleomuck"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Ability 7",
		arrows: [
          { dir: "down", from: "h4", to: "h6" },
        ],
        type: "spell",
        cost: "50 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "12s cooldown",
        description: talentText`Place a 20 foot wide pool around you for 4 seconds. Every second, up to 9 enemies in the pool will gain 1 stack of a 9 second affliction. Every 3 seconds, target takes 5% SAP + 65 corporeal damage.\n\nAugmented: pool lasts for 6 seconds.`,
      },
	  "Ability 1": {
        name: "Ability 1",
        pos: "f8",
        icon: icons["abi_or_melee14"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "40 action points",
        range: "100ft range",
        cast: "1.0s cast",
        cooldown: "no cooldown",
        description: talentText`Deals 14% SAP + 171 elemental damage to target enemy and applies 1 stack of Reduced Toughness.\n\nAugmented: Will apply an additional stack.`,
      },
      "Ability 10": {
        name: "Ability 10",
        pos: "d9",
        icon: icons["abi_gs_gorksbarb"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "100 action points",
        range: "30ft range",
        cast: "1.5s cast",
        cooldown: "no cooldown",
		blue: "Castable while Moving",
        description: talentText`Applies 10 stacks to target enemy. Each time they are hit by an ability, they take 6% SAP + 66 elemental damage and lose a stack.\n\nAugmented: add 4 stacks.`,
      },
      "Sneaky Waaagh": {
        name: "Sneaky Waaagh",
        pos: "f9",
        icon: icons["abi_gs_windupdawaaagh"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "75ft range",
        cast: "1.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Up to 10 enemies within a 30 foot area you select gain a debuff for 1 second if they do not have cover from you. At the end of the duration, they apply 1 stack of a 6 second debuff to up to 96 enemies within 30 feet of them. Enemies lose 5% damage reduction per stack.`,
      },
	  "Unfair Advantage": {
        name: "Unfair Advantage",
        pos: "a5",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you hit an enemy you are flanking, you will gain a buff for 2 seconds. For the duration, you will gain outgoing damage equal to 100% of your accuracy.`,
      },
	  "Tactic 5": {
        name: "Tactic 5",
        pos: "g5",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Ey Quit Bleedin and Ability 1 are now instant cast but deal 50% less damage.`,
      },
	  "Tactic 6": {
        name: "Tactic 6",
        pos: "b6",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`You will gain 5 stacks of Mycotoxin whenever you cast Stalk.`,
      },
	  "Tactic 3": {
        name: "Tactic 3",
        pos: "f6",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Lose 1 Paranoia every 5 seconds.`,
      },
	  "Tactic 4": {
        name: "Tactic 4",
        pos: "b7",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Sticky Feetz will no longer reduce enemy movement speed. Instead, it will apply Rooted and Immovable to up to 96 enemies in the area on cast.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nImmovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
	  "Tactic 8": {
        name: "Tactic 8",
        pos: "h7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Ability 9",
		arrows: [
          { dir: "down", from: "h6", to: "h7" }
        ],
        type: "career tactic",
        description: talentText`Ability 7 and Ability 9 will now hit 24 enemies.`,
      },
	  "Tactic 7": {
        name: "Tactic 7",
        pos: "d8",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`The cooldown on Stalk is reduced by 5 seconds for every 4 Paranoia you had on cast.`,
      },
	  "Passive 10": {
        name: "Passive 10",
        pos: "e3",
        icon: icons["abi_stalk"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`While in Stalk, you lose ${[
          1,
          2,
          3,
          4,
          5,
        ]} Paranoia every 3 seconds.`,
      },
	  "Improved Vigilance": {
        name: "Improved Vigilance",
        pos: "e5",
        icon: icons["abi_vigilance"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Vigilance now only reduces your outgoing damage by ${[
          75,
		  60,
          45,
        ]}%.`,
      },
	  "Passive 7": {
        name: "Passive 7",
        pos: "d6",
        icon: icons["abi_gs_fickskin"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`${[
          "Mycotoxin",
          "Mycotoxin and Ey Quit Bleedin",
        ]} can now be cast in Stalk.`,
      },
	  "Passive 8": {
        name: "Passive 8",
        pos: "e6",
        icon: icons["abi_or_melee18"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Mycotoxin deals ${[
          10,
          20,
          30,
          40,
          50,
        ]}% more damage.`,
      },
	  "Bleed Fer Me": {
        name: "Bleed Fer Me",
        pos: "a7",
        icon: icons["abi_gs_eyquitbleedin"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Ey! Quit Bleedin' can now stack up to ${[
          2,
          3,
		  4,
		  5,
		  6,
        ]} times on the same target.`,
      },
	  "Passive 5": {
        name: "Passive 5",
        pos: "e7",
        icon: icons["abi_or_face06"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`You always have ${[
          3,
          6,
          9,
        ]}% outgoing damage but also gain 1 Paranoia every 5 seconds.`,
      },
	  "Passive 9": {
        name: "Passive 9",
        pos: "e8",
        icon: icons["abi_go_face03"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`You gain ${[
          25,
          50,
          75,
          100,
        ]}% outgoing damage while in Stalk.`,
      },
    },
  },
};