import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/greenskin"),
);
const icons = requireAll(require.context("../../assets/icons/greenskin"));

export const data: TalentData = {
  "Shroomancer": {
    name: "Shroomancer",
    background: backgrounds["shroomancer"],
    icon: icons["archetype_healer"],
    talents: {
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "What a Rush": {
        name: "What a Rush",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`The action point cost of your skills is reduced by 33% on allies that are lower than 40% health.`,
      },
      "Stop Hittin' Me!": {
        name: "Stop Hittin' Me!",
        pos: "a2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You have 1 less mass. In addition, each time you are attacked you will gain a stack that stacks up to 8 and lasts 6 seconds. Gain 5% movement speed for the duration.`,
      },
      "Waaagh": {
        name: "Waaagh",
        pos: "b2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that have this tactic gain 1 Fightiness, gain 3 Pyschic Energy, lose 1 Cowardice, or lose 1 Paranoia.`,
      },
      "Greenoholic": {
        name: "Greenoholic",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Fungus Beer no longer has a cooldown.`,
      },
      "Extra Special Mushrooms": {
        name: "Extra Special Mushrooms",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You restore 420 + 28% wounds health whenever you use Fungal Beer.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specstaff"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Shroomancers equip staves.`,
      },
	  "Return Life": {
        name: "Return Life",
        pos: "f2",
        icon: icons["morale_returnlife"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Return target groupmate back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Divine Protection": {
        name: "Divine Protection",
        pos: "h2",
        icon: icons["morale_divineprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 15 seconds. They will absorb up to 200% RP + 1500 damage over the duration.`,
      },
      "Alter Fate": {
        name: "Alter Fate",
        pos: "i2",
        icon: icons["morale_alterfate"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Removes all afflictions and cripples from each groupmate within 100ft. Also applies Return Life to each dead groupmate within 100ft.`,
      },
      "Too Smart For Dat": {
        name: "Too Smart For Dat",
        pos: "i4",
        icon: icons["abi_gs_getsmarter"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Reduce your Paranoia by 5.`,
      },
      "Gork Sez Stop": {
        name: "Gork Sez Stop",
        pos: "i5",
        icon: icons["abi_or_hand02"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Apply a 2s debuff to target enemy. Deals 10% SAP + 150 elemental damage to the target every second. The duration of the debuff is refreshed whenever the target moves.`,
      },
      "Ain't Dun Yet": {
        name: "Ain't Dun Yet",
        pos: "i7",
        icon: icons["abi_gs_gimmie"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Gain a buff for 20 seconds. For the duration, every second your Cowardice and Paranoia will lower by 1 and you will gain 20 action points.`,
      },
      "Fist of Gork": {
        name: "Fist of Gork",
        pos: "i8",
        icon: icons["abi_gs_fistsofgork"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Deals 33% SAP + 446 elemental damage to target enemy. Up to 23 enemies within 20 feet of the target also take that damage and are knocked-back.`,
      },
      "Paranoia": {
        name: "Paranoia",
        pos: "a1",
        icon: icons["abi_gs_donthitme"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Paranoia has a base of 0 and a max of 30. Reduced at a rate of 3 per second outside of combat. Paranoia applies a negative effect to the caster at intervals based on amount of current paranoia.\n1 - 5: 1 every 15 seconds.\n6 - 10: 1 every 12 seconds.\n10 - 14: 1 every 10 seconds.\n15 - 19: 1 every 8 seconds.\n20 - 24: 1 every 5 seconds.\n25 - 29: 1 every 3 seconds.\n30 - 30: 1 every second.\n\nThe following are the negative effects that can be applied chosen at random: Gain 1 stack of Reduced Intelliegence, Reduced Willpower, Reduced Initiative, Reduced Agility, Reduced Critical Hit Rating, Reduced Potency, Reduced Accuracy, Reduced Block, Reduced Incoming Healing, or Removes Inevitable and Unstoppable from you.`,
      },
      "Touch of Gork": {
        name: "Touch of Gork",
        pos: "b1",
        icon: icons["abi_or_hand03"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 253 elemental damage to target enemy.`,
      },
      "Fungus Beer": {
        name: "Fungus Beer",
        pos: "c1",
        icon: icons["itm_ge_slimepurple"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "6s cooldown",
		blue: "Off the GCD",
        description: talentText`Applies 2 Paranoia and one of the negative effects to the caster. Your next spell will be augmented.`,
      },
      "Bigger, Better, an' Greener": {
        name: "Bigger, Better, an' Greener",
        pos: "d1",
        icon: icons["abi_gs_fickskin"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "70 action points",
        range: "150ft range",
        cast: "2.5s cast",
        cooldown: "no cooldown",
        description: talentText`Applies a 12 second enchantment to target ally. For the duration, restore 19% RP + 252 health to them every 3 seconds.\n\nAugmented: Restore 18% RP + 215 health to target on spell cast.`,
      },
      "Summon Mushroom": {
        name: "Summon Mushroom",
        pos: "e1",
        icon: icons["abi_or_symbol03"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Summons a "pet" mushroom. This mushroom will heal allies within 30 feet every 2 seconds for 5% RP + 46.`,
      },
      "Ey! Quit Bleedin'": {
        name: "Ey! Quit Bleedin'",
        pos: "f1",
        icon: icons["abi_gs_eyquitbleedin"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "36 action points",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`Applies a 12 second affliction to target enemy. For the duration, deal 21% SAP + 274 corporeal damage every 3 seconds to them.\n\nAugmented: Deals 12% SAP + 166 elemental damage on cast to target.`,
      },
      "Eeek!": {
        name: "Eeek!",
        pos: "g1",
        icon: icons["abi_gs_eeeek"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Knocks target enemy away from you and applies Immovable to them.\n\nImmovable prevents application of Knockbacks, Pulls, and Roots for 20 seconds.`,
      },
      "Sticky Feetz": {
        name: "Sticky Feetz",
        pos: "h1",
        icon: icons["abi_or_speedyfeet"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Place a 20 foot area on the ground. Allies in the area will have their abilities augmented. Enemies in the area will have their movement speed reduced by 50%.`,
      },
      "RUN AWAY!": {
        name: "RUN AWAY!",
        pos: "i1",
        icon: icons["abi_gs_runaway"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "45s cooldown",
        description: talentText`(Movement Skill) For the next 6 seconds, your movement speed is increased by 25%.`,
      },
	  "Mork'll Fix It": {
        name: "Mork'll Fix It",
        pos: "g4",
        icon: icons["abi_gs_degreenest"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "40 action points",
        range: "150ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`Restore 22% RP + 293 health to target ally.\n\nAugmented: ability is now instant cast.`,
      },
	  "Puff of Poison": {
        name: "Puff of Poison",
        pos: "h5",
        icon: icons["abi_or_mushroom01"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "75 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "6s cooldown",
        blue: "Off the GCD",
        description: talentText`Applies a 9 second affliction to up to 9 enemies within 30 feet of your mushroom. For the duration, deals 5% SAP + 60 corporeal damage every 3 seconds.\n\nAugmented: now deals 7% SAP + 90 corporeal damage every 3 seconds.`,
      },
	  "Blightbloom": {
        name: "Blightbloom",
        pos: "f6",
        icon: icons["abi_or_mushroom02"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "75 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "6s cooldown",
        blue: "Off the GCD",
        description: talentText`Restores 5% RP + 50 health to up to 9 allies within 30 feet of your mushroom.\n\nAugmented: restores 7% RP + 76 health instead.`,
      },
	  "Mycotoxin": {
        name: "Mycotoxin",
        pos: "e8",
        icon: icons["abi_or_melee18"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "100 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Applies 5 stacks of fungal poison to your weapon. Whenever you use a basic attack, you will deal an additional 9% SAP + 114 corporeal damage and remove 1 stack.`,
      },
      "Gather Round": {
        name: "Gather Round",
        pos: "d9",
        icon: icons["abi_or_symbol01"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "75 action points",
        range: "75ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`Restores 11% RP + 153 health to up to 9 allies within a 30 foot area you select.\n\nAugmented: ability is now instant cast.`,
      },
      "Sneaky Waaagh": {
        name: "Sneaky Waaagh",
        pos: "f9",
        icon: icons["abi_gs_windupdawaaagh"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "75ft range",
        cast: "1.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Up to 10 enemies within a 30 foot area you select gain a debuff for 1 second if they do not have cover from you. At the end of the duration, they apply 1 stack of a 6 second debuff to up to 96 enemies within 30 feet of them. Enemies lose 5% damage reduction per stack.`,
      },
	  "Outta Ere!": {
        name: "Outta Ere!",
        pos: "a5",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`The cooldown on RUN AWAY! is reduced by 20 seconds.`,
      },
	  "Spore Pods": {
        name: "Spore Pods",
        pos: "b5",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`If your Summon Mushroom is killed, all groupmates within 100 feet of you gain a buff for 5 second. For the duration, gain 5 adrenaline per second and restore 5% RP + 40 health every second.`,
      },
	  "Fungal Hyphae": {
        name: "Fungal Hyphae",
        pos: "a6",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Gain 2 mass for 3 seconds whenever you cast Fungal Beer.`,
      },
	  "Lookit What I Did!": {
        name: "Lookit What I Did!",
        pos: "c6",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`The durations of Bigger, Better, an' Greener; Ey! Quit Bleedin'; and Puff of Poison are increased by 6 seconds.`,
      },
	  "Fungal Infestation": {
        name: "Fungal Infestation",
        pos: "a7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Summon Mushroom, Puff of Poison, and Blightbloom now hit up to 24 targets.`,
      },
	  "Pass It On": {
        name: "Pass It On",
        pos: "b7",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Whenever you heal an ally with Bigger, Better, an' Greener or Mork'll Fix It; you will apply a 6 second enchantment to an ally within 50 feet of the target. Absorb up to 21% RP + 280 damage for the duration.`,
      },
	  "Ere We Go": {
        name: "Ere We Go",
        pos: "f8",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Mycotoxin",
		arrows: [
          { dir: "right", from: "e8", to: "f8" },
        ],
        type: "career tactic",
        description: talentText`Mycotoxin now applies to all groupmates within 100 feet of you.`,
      },
	  "Fungal Growth": {
        name: "Fungal Growth",
        pos: "e3",
        icon: icons["abi_gs_stealyerthunder"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever you cast Fungal Beer, a random groupmate within 100 feet will be healed for ${[
          5,
          10,
          15,
          20,
          25,
        ]}% RP.`,
      },
	  "Run Fasta'": {
        name: "Run Fasta'",
        pos: "c4",
        icon: icons["abi_gs_runaway"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`RUN AWAY! will now increase your movement speed by ${[
          30,
          35,
          40,
        ]}%.`,
      },
	  "Bleed Fer Me": {
        name: "Bleed Fer Me",
        pos: "e5",
        icon: icons["abi_gs_eyquitbleedin"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Ey! Quit Bleedin' can now stack up to ${[
          2,
          3,
        ]} times on the same target.`,
      },
	  "I'll Take That": {
        name: "I'll Take That",
        pos: "d6",
        icon: icons["abi_or_figure17"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`Touch of Gork will now heal your defensive target for ${[
          75,
          150,
        ]}% and Mycotoxin will now heal for ${[
          10,
          20,
        ]}% of the damage they deal.`,
      },
	  "Mork Iz Betta!": {
        name: "Mork Iz Betta!",
        pos: "g6",
        icon: icons["abi_or_mob"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Mork'll Fix It",
		arrows: [
          { dir: "down", from: "g4", to: "g6" },
        ],
        type: "passive",
        description: talentText`Mork'll Fix It will heal targets affected with Bigger, Better, and Greener for an additional ${[
          10,
          20,
          30,
          40,
          50,
        ]}%`,
      },
	  "Mushroom Farmer": {
        name: "Mushroom Farmer",
        pos: "e7",
        icon: icons["abi_or_symbol03"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Reduce the cooldown on Summon Mushroom by ${[
          5,
          10,
          15,
        ]} seconds.`,
      },
	  "Mighty Shrooms": {
        name: "Mighty Shrooms",
        pos: "h7",
        icon: icons["abi_or_mushroom03"],
        maxRank: 3,
        reqPoints: 20,
        prereq: "Puff of Poison",
		arrows: [
          { dir: "down", from: "h5", to: "h7" }
        ],
        type: "passive",
        description: talentText`Increases the healing of Blightbloom and the damage of Puff of Poison by ${[
          8,
          16,
          25,
        ]}%.`,
      },
	  "Don' Feel Nuthin'": {
        name: "Don' Feel Nuthin'",
        pos: "d8",
        icon: icons["abi_or_figure08"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Whenever you critically heal someone, you will apply an enchantment on them for 5 seconds. Effect does not refresh. At the end of the duration, target will be healed for 40 + ${[
          8,
          16,
          24,
          32,
        ]}% RP.`,
      },
    },
  },
  "Little Waaagh": {
    name: "Little Waaagh",
    background: backgrounds["little waaagh"],
    icon: icons["archetype_offsupport"],
    talents: {
      "Break Loose": {
        name: "Break Loose",
        pos: "a8",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Masochist": {
        name: "Masochist",
        pos: "a8",
        icon: icons["rrtac_masochist"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you are attacked while your Guard is active, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Increase your mass by 1.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "What a Rush": {
        name: "What a Rush",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`The action point cost of your skills is reduced by 33% on allies that are lower than 40% health.`,
      },
      "Racial Tactic 1": {
        name: "Racial Tactic 1",
        pos: "a2",
        icon: icons["tac_race_"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Racial Tactic 2": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_race_"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 1": {
        name: "Class Tactic 1",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 2": {
        name: "Class Tactic 2",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Specialization is able to equip these weapons.`,
      },
	  "Return Life": {
        name: "Return Life",
        pos: "f2",
        icon: icons["morale_returnlife"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Return target groupmate back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Divine Protection": {
        name: "Divine Protection",
        pos: "h2",
        icon: icons["morale_divineprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 15 seconds. They will absorb up to 200% RP + 1500 damage over the duration.`,
      },
      "Alter Fate": {
        name: "Alter Fate",
        pos: "i2",
        icon: icons["morale_alterfate"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Removes all afflictions and cripples from each groupmate within 100ft. Also applies Return Life to each dead groupmate within 100ft.`,
      },
      "Morale 1 Class": {
        name: "Morale 1 Class",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 2 Spec": {
        name: "Morale 2 Spec",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 3 Race": {
        name: "Morale 3 Race",
        pos: "i7",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 4 Spec": {
        name: "Morale 4 Spec",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Specialization Mechanic": {
        name: "Specialization Mechanic",
        pos: "a1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell career tactic renown tactic passive morale 1234",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 1": {
        name: "Core Ability 1",
        pos: "b1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 2": {
        name: "Core Ability 2",
        pos: "c1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 3": {
        name: "Core Ability 3",
        pos: "d1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 4": {
        name: "Core Ability 4",
        pos: "e1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 5": {
        name: "Core Ability 5",
        pos: "f1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 6": {
        name: "Core Ability 6",
        pos: "g1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 7": {
        name: "Core Ability 7",
        pos: "h1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 8": {
        name: "Core Ability 8",
        pos: "i1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 1": {
        name: "SA1",
        pos: "b4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 2": {
        name: "SA2",
        pos: "c5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 3": {
        name: "SA3",
        pos: "c6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 4": {
        name: "SA4",
        pos: "c8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 1": {
        name: "Capstone Ability 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 2": {
        name: "Capstone Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 1": {
        name: "T1",
        pos: "a5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 2": {
        name: "T2",
        pos: "b5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 3": {
        name: "T3",
        pos: "a6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 4": {
        name: "T4",
        pos: "b6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 5": {
        name: "T5",
        pos: "a7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 6": {
        name: "T6",
        pos: "b7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 7": {
        name: "T7",
        pos: "b8",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Passive 1": {
        name: "Passive 1",
        pos: "e3",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 2": {
        name: "Passive 2",
        pos: "c4",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 5,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 3": {
        name: "Passive 3",
        pos: "e5",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 4": {
        name: "Passive 4",
        pos: "d6",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 5": {
        name: "Passive 5",
        pos: "e6",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 6": {
        name: "Passive 6",
        pos: "d7",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 7": {
        name: "Passive 7",
        pos: "e7",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 8": {
        name: "Passive 8",
        pos: "e8",
        icon: icons["noicon"],
        maxRank: 4,
        reqPoints: 25,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
    },
  },
  "Stalker": {
    name: "Stalker",
    background: backgrounds["stalker"],
    icon: icons["archetype_dps"],
    talents: {
      "Break Loose": {
        name: "Break Loose",
        pos: "a8",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Masochist": {
        name: "Masochist",
        pos: "a8",
        icon: icons["rrtac_masochist"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you are attacked while your Guard is active, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Increase your mass by 1.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "What a Rush": {
        name: "What a Rush",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`The action point cost of your skills is reduced by 33% on allies that are lower than 40% health.`,
      },
      "Racial Tactic 1": {
        name: "Racial Tactic 1",
        pos: "a2",
        icon: icons["tac_race_"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Racial Tactic 2": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_race_"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 1": {
        name: "Class Tactic 1",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 2": {
        name: "Class Tactic 2",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Specialization is able to equip these weapons.`,
      },
	  "Sever Nerve": {
        name: "Sever Nerve",
        pos: "f2",
        icon: icons["morale_severnerve"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Deals 50% MAP + 400 physical damage to the target.`,
      },
      "Broad Swings": {
        name: "Broad Swings",
        pos: "g2",
        icon: icons["morale_broadswings"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a  buff for 10 seconds. Your single target abilities will target two additional enemies within 15ft in front of you.`,
      },
      "Force of Will": {
        name: "Force of Will",
        pos: "h2",
        icon: icons["morale_forceofwill"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 10 seconds. Action point costs are reduced by 75% for the duration.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "Morale 1 Class": {
        name: "Morale 1 Class",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 2 Spec": {
        name: "Morale 2 Spec",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 3 Race": {
        name: "Morale 3 Race",
        pos: "i7",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 4 Spec": {
        name: "Morale 4 Spec",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Specialization Mechanic": {
        name: "Specialization Mechanic",
        pos: "a1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell career tactic renown tactic passive morale 1234",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 1": {
        name: "Core Ability 1",
        pos: "b1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 2": {
        name: "Core Ability 2",
        pos: "c1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 3": {
        name: "Core Ability 3",
        pos: "d1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 4": {
        name: "Core Ability 4",
        pos: "e1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 5": {
        name: "Core Ability 5",
        pos: "f1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 6": {
        name: "Core Ability 6",
        pos: "g1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 7": {
        name: "Core Ability 7",
        pos: "h1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 8": {
        name: "Core Ability 8",
        pos: "i1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 1": {
        name: "SA1",
        pos: "b4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 2": {
        name: "SA2",
        pos: "c5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 3": {
        name: "SA3",
        pos: "c6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 4": {
        name: "SA4",
        pos: "c8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 1": {
        name: "Capstone Ability 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 2": {
        name: "Capstone Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 1": {
        name: "T1",
        pos: "a5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 2": {
        name: "T2",
        pos: "b5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 3": {
        name: "T3",
        pos: "a6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 4": {
        name: "T4",
        pos: "b6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 5": {
        name: "T5",
        pos: "a7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 6": {
        name: "T6",
        pos: "b7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 7": {
        name: "T7",
        pos: "b8",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Passive 1": {
        name: "Passive 1",
        pos: "e3",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 2": {
        name: "Passive 2",
        pos: "c4",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 5,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 3": {
        name: "Passive 3",
        pos: "e5",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 4": {
        name: "Passive 4",
        pos: "d6",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 5": {
        name: "Passive 5",
        pos: "e6",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 6": {
        name: "Passive 6",
        pos: "d7",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 7": {
        name: "Passive 7",
        pos: "e7",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 8": {
        name: "Passive 8",
        pos: "e8",
        icon: icons["noicon"],
        maxRank: 4,
        reqPoints: 25,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
    },
  },
};