import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/asur"),
);
const icons = requireAll(require.context("../../assets/icons/highelf"));

export const data: TalentData = {
  "Shadow Warrior": {
    name: "Shadow Warrior",
    background: backgrounds["shadowwarrior"],
    icon: icons["archetype_dps"],
    talents: {
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 1,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "Centuries of Training": {
        name: "centuries of Training",
        pos: "a2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you deal direct damage to an enemy, you have a 33% chance to apply one of three debuffs to them. Effects do not refresh and last 6 seconds.\nDeals 4% MAP + 56 impact damage every second.\nDeals 6% RAP + 80 piercing damage every 2 seconds.\nDeals 10% SAP + 134 spiritual damage every 3 seconds.`,
      },
      "Form Ranks": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, each groupmate within 100 feet that has this tactic will gain 300 penetration and 300 sagacity for 3 seconds.`,
      },
      "Guerilla Training": {
        name: "Guerilla Training",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You gain one charge of Brutal Assault and 50% AP cost reduction for 5 seconds whenever you change stances.`,
      },
      "Stance Dancer": {
        name: "Stance Dancer",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`The cooldown on your stances is reduced by 7 seconds.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specbow"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Shadow Warriors equip long bows and one-handed swords.`,
      },
      "Lileath's Arrow": {
        name: "Lileath's Arrow",
        pos: "i4",
        icon: icons["abi_he_weightedarrow"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "60ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Knockback target enemy.`,
      },
      "Target Call": {
        name: "Target Call",
        pos: "i5",
        icon: icons["abi_he_felltheweak"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 1 minute that provides a granted ability. Ability is off the GCD and will deal 11% RAP + 130 piercing damage to target enemy that is Marked.`,
      },
      "Wings of Heaven": {
        name: "Wings of Heaven",
        pos: "i7",
        icon: icons["abi_he_wingsofheaven"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Gain a debuff for 5 seconds which reduces your mass by 8. Leap forward and apply Ensnared to up to 9 enemies within 20 feet of where you land.\n\nEnsnared reduces movement speed by 30% for 16 seconds.`,
      },
      "Instill Fear": {
        name: "Instill Fear",
        pos: "i8",
        icon: icons["abi_he_signaloursnipers"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "60ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Applies Marked to up to 96 enemies within a 30 feet area you select if they do not have cover from you.\nMarked reduces the target's damage reduction by 15% for 10 seconds.`,
      },
	  "Disengage": {
        name: "Disengage",
        pos: "f2",
        icon: icons["morale_disengage"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`You knock yourself back away from target enemy.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Explosive Impact": {
        name: "Explosive Impact",
        pos: "h2",
        icon: icons["morale_explosiveimpact"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 10 seconds. Whenever you hit a target with a single-target ability, you will deal 10% RAP + 150 corporeal damage and 10% SAP + 150 elemental damage to up to 24 enemies within 20 feet of the target.`,
      },
      "Unleash the Winds": {
        name: "Unleash the Winds",
        pos: "i2",
        icon: icons["morale_unleashthewinds"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 96 enemies within a 20 feet location you select are knocked straight up into the air.`,
      },
      "Stances": {
        name: "Stances",
        pos: "a1",
        icon: icons["abi_he_scoutstance"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Shadow Warriors have access to 3 controlled stances that have 15 second cooldowns and are off the GCD.\nScout Stance - Gain 60% range.\nSkirmish Stance - All of your abilities are now castable while moving and dispel Marked from the enemies they hit. You lose 2 mass.\nAssault Stance - +15% damage, +1 mass, -40% range, and your attackes refresh Marked on enemies.`,
      },
      "Broadhead Arrow": {
        name: "Broadhead Arrow",
        pos: "b1",
        icon: icons["abi_he_swiftstrike"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "75ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 253 piercing damage to target enemy. You generate 40 action points.`,
      },
      "Eagle Eye": {
        name: "Eagle Eyes",
        pos: "c1",
        icon: icons["abi_he_carefulaim"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "36 action points",
        range: "75ft range",
        cast: "2.25s cast",
        cooldown: "no cooldown",
        description: talentText`Deal 30% RAP + 383 piercing damage to target enemy.`,
      },
      "Brutal Assault": {
        name: "Brutal Assault",
        pos: "d1",
        icon: icons["abi_he_brutalassault"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 37% MAP + 492 impact damage to target enemy, removing 1 charge. Gains 1 charge every 8 seconds with a maximum of 2 charges.`,
      },
      "Marked for Death": {
        name: "Marked for Death",
        pos: "e1",
        icon: icons["abi_he_blindinglight"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Off the GCD",
        description: talentText`Applies Marked to target enemy.\n\nMarked reduces the target's damage reduction by 15% for 10 seconds.`,
      },
      "Tar Arrow": {
        name: "Tar Arrow",
        pos: "f1",
        icon: icons["abi_he_pindown"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "40 action points",
        range: "75ft range",
        cast: "1.0s cast",
        cooldown: "no cooldown",
        description: talentText`Applies Ensnared and Momentum to target enemy.\n\nEnsnared reduces movement speed by 30% for 16 seconds.\nMomentum prevents the application of Ensnared for 8 seconds.`,
      },
      "Counterstrike": {
        name: "Counterstrike",
        pos: "g1",
        icon: icons["abi_he_opportunisticstrike"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "60 action points",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Deals 19% MAP + 250 piercing damage and applies Disarmed and Inevitable to target enemy.\n\nDisarmed prevents the use of skills for 5 seconds.\nInevitable prevents the application of Disarmed and Silenced for 20 seconds.`,
      },
      "Glass Arrow": {
        name: "Glass Arrow",
        pos: "h1",
        icon: icons["abi_he_criticalshot"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "65 action points",
        range: "75ft range",
        cast: "1.25s cast",
        cooldown: "no cooldown",
        description: talentText`Applies an 8 second duration affliction to target enemy. For the duration, their range is reduced by 20% and they take 9% RAP + 114 piercing damage every 2 seconds.`,
      },
      "Smokescreen": {
        name: "Smokescreen",
        pos: "i1",
        icon: icons["abi_smokescreen"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "15s cooldown",
        description: talentText`Target enemy will deal 50% less damage to you for 15 seconds. This effect is removed if you hit the target with an ability.`,
      },
	  "Spiral-Fletched Arrow": {
        name: "Spiral-Fletched Arrow",
        pos: "g4",
        icon: icons["abi_he_spiralfletchedarrow"],
        maxRank: 1,
        reqPoints: 1,
        type: "skill",
        cost: "75 action points",
        range: "75ft range",
        cast: "1.5s cast",
        cooldown: "no cooldown",
        description: talentText`Deals 9% RAP + 108 piercing damage to up to 9 enemies within a 30 foot area you select.`,
      },
	  "Grim Slash": {
        name: "Grim Slash",
        pos: "h5",
        icon: icons["abi_he_grimslash"],
        maxRank: 1,
        reqPoints: 10,
        type: "skill",
        cost: "50 action points",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 23% MAP + 295 piercing damage to target enemy.`,
      },
	  "Flaming Arrow": {
        name: "Flaming Arrow",
        pos: "g6",
        icon: icons["abi_he_shotofcynath"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Spiral-Fletched Arrow",
		arrows: [
          { dir: "down", from: "g4", to: "g6" },
        ],
        type: "skill",
        cost: "90 action points",
        range: "75ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`Deals 15% RAP + 184 impact damage to target enemy and then applies a 12 second affliction to target and up to 8 other enemies within 30 feet of them. For the duration, target takes 7% RAP + 86 impact damage every 3 seconds.`,
      },
	  "Festering Arrow": {
        name: "Festering Arrow",
        pos: "d8",
        icon: icons["abi_he_festeringarrow"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "45 action points",
        range: "75ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        description: talentText`Deals 15% RAP + 191 ichor damage and applies a 6 second affliction to them. For the duration, target takes 15% RAP + 202 ichor damage every 2 seconds.`,
      },
      "Rapid Fire": {
        name: "Rapid Fire",
        pos: "d9",
        icon: icons["abi_he_rapidfire"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "75 action points",
        range: "45ft range",
        cast: "2.5s channel",
        cooldown: "no cooldown",
        description: talentText`Deals 15% RAP + 203 piercing damage to target enemy every 0.5 seconds.`,
      },
      "Penetrating Arrow": {
        name: "Penetrating Arrow",
        pos: "f9",
        icon: icons["abi_he_penetratingarrow"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "150 action points",
        range: "self",
        cast: "2.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Fire an arrow 65 feet in front of you. First enemy hit takes 5% RAP + 50 piercing damage. Each subsequent enemy takes additional damage.`,
      },
	  "Smokebomb": {
        name: "Smokebomb",
        pos: "a5",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Smokescreen will now apply to up to 24 enemies within 30 feet of you.`,
      },
	  "Relentless Assault": {
        name: "Relentless Assault",
        pos: "b5",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Brutal Assault now has a maximum of 4 charges.`,
      },
	  "Blood-Soaked War": {
        name: "Blood-Soaked War",
        pos: "b6",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Reduces the cooldown on Marked for Death by 8 seconds.`,
      },
	  "Shattered Glass": {
        name: "Shattered Glass",
        pos: "h6",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Glass Arrow now reduces range by 40%.`,
      },
	  "Split Arrow": {
        name: "Split Arrow",
        pos: "a7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Eagle Eye now hits 2 additional enemies within 15 feet of the target but it deals 20% less damage.`,
      },
	  "Force Magnifier": {
        name: "Force Magnifier",
        pos: "g7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Flaming Arrow",
		arrows: [
          { dir: "down", from: "g6", to: "g7" },
        ],
        type: "career tactic",
        description: talentText`Spiral-Fletched Arrow and Flaming Arrow will now hit up to 24 enemies.`,
      },
	  "Tactic 7": {
        name: "Tactic 7",
        pos: "e8",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Festering Arrow",
		arrows: [
          { dir: "right", from: "d8", to: "e8" },
        ],
        type: "career tactic",
        description: talentText`Festering Arrow will now cost 75 action points and the initial hit will deal 36% RAP + 490 ichor damage.`,
      },
	  "No Quarter": {
        name: "No Quarter",
        pos: "e3",
        icon: icons["abi_he_thintheherd"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`You deal ${[
          2,
          4,
          6,
          8,
        ]}% increased damage against targets that are Marked.`,
      },
	  "Improved Broadheads": {
        name: "Improved Broadheads",
        pos: "e5",
        icon: icons["abi_he_swiftstrike"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Broadhead Arrow will deal additional damage equal to ${[
          6,
          12,
          18,
          24,
        ]}% RAP.`,
      },
	  "Collateral Damage": {
        name: "Collateral Damage",
        pos: "c6",
        icon: icons["abi_he_flankingshot"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`Whenever you deal direct damage to a Marked target, you will deal ${[
          10,
          20,
        ]}% of that damage to 2 other enemies within 20 feet of them.`,
      },
	  "Improved Eagle Eye": {
        name: "Improved Eagle Eye",
        pos: "e6",
        icon: icons["abi_he_carefulaim"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Eagle Eye has a ${[
          0.1,
          0.2,
          0.3,
          0.4,
          0.5,
        ]} second faster cast time.`,
      },
	  "Ambush": {
        name: "Ambush",
        pos: "c7",
        icon: icons["abi_he_magicalinfusion"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`You deal ${[
          3,
          6,
          9,
        ]}% more damage against enemies above 75% health.`,
      },
	  "Smoldering Arrow": {
        name: "Smoldering Arrow",
        pos: "e7",
        icon: icons["abi_he_pindown"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Tar Arrow will now deal ichor damage equal to ${[
          12,
          24,
          36,
        ]}% + 253. `,
      },
	  "Extended Engagement": {
        name: "Exteneded Engagement",
        pos: "f8",
        icon: icons["abi_he_whirlingpin"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Increase the duration of Glass Arrow by ${[
          2,
          4,
          6,
          8,
        ]} seconds. Increase the duration of Flame Arrow by ${[
          3,
          3,
          6,
          6,
        ]} seconds. Increase the duration of Festering Arrow by ${[
          0,
          2,
          2,
          4,
        ]} seconds.`,
      },
    },
  },
  "Sea Guard": {
    name: "Sea Guard",
    background: backgrounds["seaguard"],
    icon: icons["archetype_offsupport"],
    talents: {
      "Break Loose": {
        name: "Break Loose",
        pos: "a8",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Masochist": {
        name: "Masochist",
        pos: "a8",
        icon: icons["rrtac_masochist"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you are attacked while your Guard is active, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Increase your mass by 1.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "What a Rush": {
        name: "What a Rush",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`The action point cost of your skills is reduced by 33% on allies that are lower than 40% health.`,
      },
      "Racial Tactic 1": {
        name: "Racial Tactic 1",
        pos: "a2",
        icon: icons["tac_race_"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Racial Tactic 2": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_race_"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 1": {
        name: "Class Tactic 1",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 2": {
        name: "Class Tactic 2",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Sea Guards equip one-handed swords, shields, and longbows.`,
      },
      "Morale 1 Class": {
        name: "Morale 1 Class",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 2 Spec": {
        name: "Morale 2 Spec",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 3 Race": {
        name: "Morale 3 Race",
        pos: "i7",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 4 Spec": {
        name: "Morale 4 Spec",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Insert tooltip.`,
      },
	  "Hedgehog": {
        name: "Hedgehog",
        pos: "f2",
        icon: icons["morale_hedgehog"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`All groupmates within 100 feet gain 3 stacks of Enhanced Block.`,
      },
	  "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Distracting Bellow": {
        name: "Distracting Bellow",
        pos: "h2",
        icon: icons["morale_distractingbellow"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Up to 48 enemies within 30 feet of you receive a debuff. For 10 seconds, they cannot benefit from Cover.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "Specialization Mechanic": {
        name: "Specialization Mechanic",
        pos: "a1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 1": {
        name: "Core Ability 1",
        pos: "b1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 2": {
        name: "Core Ability 2",
        pos: "c1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 3": {
        name: "Core Ability 3",
        pos: "d1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 4": {
        name: "Core Ability 4",
        pos: "e1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 5": {
        name: "Core Ability 5",
        pos: "f1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 6": {
        name: "Core Ability 6",
        pos: "g1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 7": {
        name: "Core Ability 7",
        pos: "h1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 8": {
        name: "Core Ability 8",
        pos: "i1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 1": {
        name: "SA1",
        pos: "a9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 2": {
        name: "SA2",
        pos: "a9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 3": {
        name: "SA3",
        pos: "a9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 4": {
        name: "SA4",
        pos: "a9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 1": {
        name: "Capstone Ability 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 2": {
        name: "Capstone Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 1": {
        name: "T1",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 2": {
        name: "T2",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 3": {
        name: "T3",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 4": {
        name: "T4",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 5": {
        name: "T5",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 6": {
        name: "T6",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 7": {
        name: "T7",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Passive 1": {
        name: "Passive 1",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 2": {
        name: "Passive 2",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 3": {
        name: "Passive 3",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 4": {
        name: "Passive 4",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 5": {
        name: "Passive 5",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 6": {
        name: "Passive 6",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 7": {
        name: "Passive 7",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  
	  
      "blueprint": {
        name: "blueprint",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell career tactic renown tactic passive morale 1234",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  
    },
  },
  "Shadow Walker": {
    name: "Shadow Walker",
    background: backgrounds["shadowwalker"],
    icon: icons["archetype_dps"],
    talents: {
      "Break Loose": {
        name: "Break Loose",
        pos: "a8",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Masochist": {
        name: "Masochist",
        pos: "a8",
        icon: icons["rrtac_masochist"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you are attacked while your Guard is active, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Increase your mass by 1.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "What a Rush": {
        name: "What a Rush",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`The action point cost of your skills is reduced by 33% on allies that are lower than 40% health.`,
      },
      "Racial Tactic 1": {
        name: "Racial Tactic 1",
        pos: "a2",
        icon: icons["tac_race_"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Racial Tactic 2": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_race_"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 1": {
        name: "Class Tactic 1",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 2": {
        name: "Class Tactic 2",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Shadow Walkers dual wield one-handed swords and equip longbows`,
      },
      "Morale 1 Class": {
        name: "Morale 1 Class",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 2 Spec": {
        name: "Morale 2 Spec",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 3 Race": {
        name: "Morale 3 Race",
        pos: "i7",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 4 Spec": {
        name: "Morale 4 Spec",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Insert tooltip.`,
      },
	  "Disengage": {
        name: "Disengage",
        pos: "f2",
        icon: icons["morale_disengage"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`You knock yourself back away from target enemy.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Force of Will": {
        name: "Force of Will",
        pos: "h2",
        icon: icons["morale_forceofwill"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 10 seconds. Action point costs are reduced by 75% for the duration.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "Specialization Mechanic": {
        name: "Specialization Mechanic",
        pos: "a1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 1": {
        name: "Core Ability 1",
        pos: "b1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 2": {
        name: "Core Ability 2",
        pos: "c1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 3": {
        name: "Core Ability 3",
        pos: "d1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 4": {
        name: "Core Ability 4",
        pos: "e1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 5": {
        name: "Core Ability 5",
        pos: "f1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 6": {
        name: "Core Ability 6",
        pos: "g1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 7": {
        name: "Core Ability 7",
        pos: "h1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 8": {
        name: "Core Ability 8",
        pos: "i1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 1": {
        name: "SA1",
        pos: "a9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 2": {
        name: "SA2",
        pos: "a9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 3": {
        name: "SA3",
        pos: "a9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 4": {
        name: "SA4",
        pos: "a9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 1": {
        name: "Capstone Ability 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 2": {
        name: "Capstone Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 1": {
        name: "T1",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 2": {
        name: "T2",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 3": {
        name: "T3",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 4": {
        name: "T4",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 5": {
        name: "T5",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 6": {
        name: "T6",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 7": {
        name: "T7",
        pos: "b9",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Passive 1": {
        name: "Passive 1",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 2": {
        name: "Passive 2",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 3": {
        name: "Passive 3",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 4": {
        name: "Passive 4",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 5": {
        name: "Passive 5",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 6": {
        name: "Passive 6",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 7": {
        name: "Passive 7",
        pos: "c9",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  
	  
      "blueprint": {
        name: "blueprint",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell career tactic renown tactic passive morale 1234",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  
    },
  },
};