import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/greenskin"),
);
const icons = requireAll(require.context("../../assets/icons/greenskin"));

export const data: TalentData = {
  "Big Un": {
    name: "Big Un",
    background: backgrounds["big un"],
    icon: icons["archetype_dps"],
    talents: {
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 1,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 1,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "I'm Da Biggest": {
        name: "I'm Da Biggest",
        pos: "a2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Gain 500 + 25% wounds maximum health.`,
      },
      "Waaagh": {
        name: "Waaagh",
        pos: "b2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that have this tactic gain 1 Fightiness, gain 3 Pyschic Energy, lose 1 Cowardice, or lose 1 Paranoia.`,
      },
      "Longa and Stronga": {
        name: "Longa and Stronga",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`The maximum amount of Psychic Energy you can hold is increased to 250.`,
      },
      "Keep It Comin'": {
        name: "Keep It Comin'",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Generate 3 Psychic Energy per second.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specdualwield"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Big Uns dual wield swords.`,
      },
	  "Sever Nerve": {
        name: "Sever Nerve",
        pos: "f2",
        icon: icons["morale_severnerve"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Deals 50% MAP + 400 piercing damage to the target.`,
      },
      "Broad Swings": {
        name: "Broad Swings",
        pos: "g2",
        icon: icons["morale_broadswings"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 10 seconds. Your single target abilities will target two additional enemies within 20 feet in front of you.`,
      },
      "Force of Will": {
        name: "Force of Will",
        pos: "h2",
        icon: icons["morale_forceofwill"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 10 seconds. Action point costs are reduced by 75% for the duration.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "Hunter's Trap": {
        name: "Hunter's Trap",
        pos: "i4",
        icon: icons["abi_he_ensnare"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Applies Rooted and Immovable to target enemy.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nImmovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Relentless": {
        name: "Relentless",
        pos: "i5",
        icon: icons["abi_or_tantrum"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Gain a buff for 15 seconds. Convert 20 action points into 30 psychic energy every second. This effect is dispelled if you run out of action points.`,
      },
      "Puddle O' Muck": {
        name: "Puddle O' Muck",
        pos: "i7",
        icon: icons["abi_gs_puddleomuck"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Up to 12 enemies within 30 feet of you gain Ensnared.\n\nEnsnared reduces your movement speed by 30% for 16 seconds.`,
      },
      "Gork iz 'Ere": {
        name: "Gork iz 'Ere",
        pos: "i8",
        icon: icons["abi_or_waaagh"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Gork w'll krump n' bash their 'eads for ya! For 30 seconds you gain 10 Fightiness and 20 Psychic Energy per second, 100% outgoing damage, 50% damage reduction, and 1000 HP4. You'll die at the end of the duration and gain Forlorn.`,
      },
      "Psychic Energy": {
        name: "Psychic Energy",
        pos: "a1",
        icon: icons["abi_or_figure10"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Psychic Energy has a base of 0 and a maximum of 200. You generate 5 psychic energy anytime a groupmate within 100 feet uses a basic attack.`,
      },
      "Clobber": {
        name: "Clobber",
        pos: "b1",
        icon: icons["abi_gs_yernothin"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 4% MAP + 30 piercing damage to target enemy. Generates 22 action points.`,
      },
      "Slasha": {
        name: "Slasha",
        pos: "c1",
        icon: icons["abi_or_melee11"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "36 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 21% MAP + 280 piercing damage to target enemy.`,
      },
      "Supa Chop": {
        name: "Supa Chop",
        pos: "d1",
        icon: icons["abi_or_supachop"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 50 Psychic Energy",
        description: talentText`Deals 33% MAP + 450 piercing damage to target enemy.`,
      },
      "Charge": {
        name: "Charge",
        pos: "e1",
        icon: icons["abi_charge"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "30s cooldown",
        description: talentText`(Movement Skill) For the next 8 seconds, your movement speed is increased by 40%.`,
      },
      "Chop Fasta": {
        name: "Chop Fasta",
        pos: "f1",
        icon: icons["abi_or_melee09"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 18% MAP + 234 piercing damage to target enemy and up to 2 other enemies within 20 feet of them.`,
      },
      "Sit Down!": {
        name: "Sit Down!",
        pos: "g1",
        icon: icons["abi_or_sitdown"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Applies Knocked-down and Unstoppable to target enemy.\n\nKnocked-down prevents all control of your character for 3 seconds.\nUnstoppable prevents application of Knocked-down and Staggered for 30 seconds.`,
      },
      "Bring Da Pain": {
        name: "Bring Da Pain",
        pos: "h1",
        icon: icons["abi_or_tiredalready"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 50 Psychic Energy",
        description: talentText`Applies a 6 second ailment to target enemy. Deals 32% SAP + 443 indirect, impact damage to them at the end of the duration.`,
      },
      "Vigilance": {
        name: "Vigilance",
        pos: "i1",
        icon: icons["abi_vigilance"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        description: talentText`All damage you take is reduced by 50% but all damage you deal is reduced by 90% for 7 seconds.`,
      },
	  "Lotsa Choppin'": {
        name: "Lotsa Choppin'",
        pos: "g4",
        icon: icons["abi_or_wildswing"],
        maxRank: 1,
        reqPoints: 5,
        type: "skill",
        cost: "75 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 10% MAP + 127 piercing damage to up to 9 enemies within 30 feet in front of you.`,
      },
	  "Quit Yer Yappin'": {
        name: "Quit Yer Yappin'",
        pos: "c5",
        icon: icons["abi_or_throatslasha"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Costs 30 Psychic Energy",
        description: talentText`Applies Silenced and Inevitable to target enemy.\n\nSilenced prevents the use fo spells for 5 seconds.\nInevitable prevents the application of Disarmed and Silenced for 20 seconds.`,
      },
	  "Wild Choppin'": {
        name: "Wild Choppin'",
        pos: "g6",
        icon: icons["abi_or_melee02"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Lotsa Choppin'",
		arrows: [
          { dir: "down", from: "g4", to: "g6" },
        ],
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 75 Psychic Energy",
        description: talentText`Deals 12% MAP + 171 piercing damage to up to 9 enemies within 30 feet of you.`,
      },
	  "Bleed 'Em Out": {
        name: "Bleed 'Em Out",
        pos: "d8",
        icon: icons["abi_or_bleedemout"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "50 action points",
        range: "8ft range",
        cast: "3.0s channel",
        cooldown: "no cooldown",
        blue: "Castable While Moving",
        description: talentText`Applies one stack of a 6 second ailment to target enemy every second with a maximum of 4 stacks. For the duration, deals 8% MAP + 101 ichor damage every 3 seconds.`,
      },
      "Hurtin' Time": {
        name: "Hurtin' Time",
        pos: "d9",
        icon: icons["abi_or_combo02"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Off the GCD",
        description: talentText`Gain a buff for 60 seconds. For the duration, you have +20% outgoing damage but you will lose 20 Psychic Energy every second. This effect will be dispelled if you run out of Psychic Energy.`,
      },
      "Waaagh!": {
        name: "Waaagh!",
        pos: "f9",
        icon: icons["abi_gs_waaagh"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "150 action points",
        range: "self",
        cast: "2.0s channel",
        cooldown: "30s cooldown",
        description: talentText`You interrupt up to 48 enemies who do not have Cover from you within 30 feet every 0.5 seconds. Whenever you successfully interrupt an enemy, you will deal 10% MAP + 50 ichor damage to them and up to 17 other enemies within 20 feet of them.`,
      },
	  "Dat Tickles": {
        name: "Dat Tickles",
        pos: "a5",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you spend Psychic Energy, you will gain a 5 second enchantment. Absorb up to 15% RP + 204 damage for the duration.`,
      },
	  "Unfair Advantage": {
        name: "Unfair Advantage",
        pos: "h5",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you hit an enemy you are flanking, you will gain a buff for 2 seconds. For the duration, you will gain outgoing damage equal to 100% of your accuracy.`,
      },
	  "Wot Rules?": {
        name: "Wot Rules?",
        pos: "b6",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Chop Fasta now counts as a basic attack.`,
      },
	  "No More Helpin'": {
        name: "No More Helpin'",
        pos: "f6",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Bring Da Pain now applies a -33% outgoing healing debuff.`,
      },
	  "Furious Choppin'": {
        name: "Furious Choppin'",
        pos: "a7",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Chop Fasta will deal 50% additional damage to a target that has casted an active Guard effect.`,
      },
	  "Extra Choppin'": {
        name: "Extra Choppin'",
        pos: "h7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Wild Choppin'",
		arrows: [
          { dir: "right-down", from: "g6", to: "h6" },
          { dir: "right-down-down", from: "h6", to: "h7" }
        ],
        type: "career tactic",
        description: talentText`Lotsa Choppin' and Wild Choppin' will now hit up to 24 enemies.`,
      },
	  "Yer All Bleedin' Now": {
        name: "Yer All Bleedin' Now",
        pos: "e8",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Bleed 'Em Out",
		arrows: [
          { dir: "right", from: "d8", to: "e8" },
        ],
        type: "career tactic",
        description: talentText`Bleed 'Em Out will now hit an additional enemy within 20 feet of the target.`,
      },
	  "Long Lasta": {
        name: "Long Lasta",
        pos: "e3",
        icon: icons["abi_or_figure10"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever you use a basic attack, you will gain ${[
          3,
          6,
          9,
          12,
		  15,
        ]}% outgoing damage for 4 seconds.`,
      },
	  "Shrug It Off": {
        name: "Shrug It Off",
        pos: "c4",
        icon: icons["abi_or_figure12"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Gain ${[
          1,
          2,
          3,
          4,
          5,
        ]} Psychic energy whenever you are hit by an enemy ability.`,
      },
	  "Improved Vigilance": {
        name: "Improved Vigilance",
        pos: "d6",
        icon: icons["abi_vigilance"],
        maxRank: 3,
        reqPoints: 15,
        type: "passive",
        description: talentText`Vigilance now only reduces your outgoing damage by ${[
          75,
		  60,
          45,
        ]}%.`,
      },
	  "Reckless Gamble": {
        name: "Reckless Gamble",
        pos: "e6",
        icon: icons["abi_or_melee15"],
        maxRank: 4,
        reqPoints: 15,
        type: "passive",
        description: talentText`Each time you deal direct damage to an enemy, you will deal ${[
          4,
          8,
          12,
          16,
          20,
        ]}% MAP indirect, ichor damage to them as well. You will deal half this amount to yourself.`,
      },
	  "Extra Crit": {
        name: "Extra Crit",
        pos: "b7",
        icon: icons["abi_extracrit"],
        maxRank: 4,
        reqPoints: 20,
        type: "passive",
        description: talentText`Your chance to critically hit is increased by ${[
          2,
		  4,
          6,
		  8,
        ]}%.`,
      },
	  "Improved Wild Choppin'": {
        name: "Improved Wild Choppin'",
        pos: "g7",
        icon: icons["abi_or_melee02"],
        maxRank: 3,
        reqPoints: 20,
        prereq: "Wild Choppin'",
		arrows: [
          { dir: "down", from: "g6", to: "g7" },
        ],
        type: "passive",
        description: talentText`Wild Choppin' will deal ${[
          5,
          10,
          15,
        ]}% more damage.`,
      },
	  "Don' Hate Da' Choppa": {
        name: "Don' Hate Da' Choppa",
        pos: "f8",
        icon: icons["abi_or_blood01"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Whenever you critically hit an enemy, you will apply a 3 second affliction to them which cannot refresh. At the end of the duration, you will deal 40 + ${[
          6,
          12,
          18,
          24,
        ]}% MAP indirect, impact damage to them. In addition, your potency is reduced by ${[
          15,
          30,
          45,
          60,
        ]}%`,
      },
    },
  },
  "Arrer Boy": {
    name: "Arrer Boy",
    background: backgrounds["arrer boy"],
    icon: icons["archetype_offsupport"],
    talents: {
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 1,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "I'm Da Biggest": {
        name: "I'm Da Biggest",
        pos: "a2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Gain 500 + 25% wounds maximum health.`,
      },
      "Waaagh": {
        name: "Waaagh",
        pos: "b2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that have this tactic gain 1 Fightiness, gain 3 Pyschic Energy, lose 1 Cowardice, or lose 1 Paranoia.`,
      },
      "Longa and Stronga": {
        name: "Longa and Stronga",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`The maximum amount of Psychic Energy you can hold is increased to 250.`,
      },
      "Keep It Comin'": {
        name: "Keep It Comin'",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Generate 3 Psychic Energy per second.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specbow"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Arrer Boyz equip one-handed swords and bows.`,
      },
	  "Disengage": {
        name: "Disengage",
        pos: "f2",
        icon: icons["morale_disengage"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`You knock yourself back away from target enemy.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Explosive Impact": {
        name: "Explosive Impact",
        pos: "h2",
        icon: icons["morale_explosiveimpact"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 10 seconds. Whenever you hit a target with a single-target ability, you will deal 10% RAP + 150 corporeal damage and 10% SAP + 150 elemental damage to up to 24 enemies within 20ft of the target.`,
      },
      "Unleash the Winds": {
        name: "Unleash the Winds",
        pos: "i2",
        icon: icons["morale_unleashthewinds"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 96 enemies within a 30 feet location you select are knocked straight up into the air.`,
      },
      "Hunter's Trap": {
        name: "Hunter's Trap",
        pos: "i4",
        icon: icons["abi_he_ensnare"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Applies Rooted and Immovable to target enemy.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nImmovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Relentless": {
        name: "Relentless",
        pos: "i5",
        icon: icons["abi_or_tantrum"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Gain a buff for 15 seconds. Convert 20 action points into 30 psychic energy every second. This effect is dispelled if you run out of action points.`,
      },
      "Puddle O' Muck": {
        name: "Puddle O' Muck",
        pos: "i7",
        icon: icons["abi_gs_puddleomuck"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Up to 12 enemies within 30 feet of you gain Ensnared.\n\nEnsnared reduces your movement speed by 30% for 16 seconds.`,
      },
      "Gork iz 'Ere": {
        name: "Gork iz 'Ere",
        pos: "i8",
        icon: icons["abi_or_waaagh"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Gork w'll krump n' bash their 'eads for ya! For 30 seconds you gain 10 Fightiness and 20 Psychic Energy per second, 100% outgoing damage, 50% damage reduction, and 1000 HP4. You'll die at the end of the duration and gain Forlorn.`,
      },
      "Psychic Energy": {
        name: "Psychic Energy",
        pos: "a1",
        icon: icons["abi_or_figure10"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Psychic Energy has a base of 0 and a maximum of 200. You generate 5 psychic energy anytime a groupmate within 100 feet uses a basic attack.`,
      },
      "Shoot 'Em": {
        name: "Shoot 'Em",
        pos: "b1",
        icon: icons["abi_ge_shoot"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 6% RAP + 133 piercing damage to target enemy. Generates 40 action points.`,
      },
      "Plink": {
        name: "Plink",
        pos: "c1",
        icon: icons["abi_or_plink"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "36 action points",
        range: "100ft range",
        cast: "2.25s cast",
        cooldown: "no cooldown",
        description: talentText`Deals 37% RAP + 484 piercing damage to target enemy.`,
      },
      "Supa Chop": {
        name: "Supa Chop",
        pos: "d1",
        icon: icons["abi_or_supachop"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 50 Psychic Energy",
        description: talentText`Deals 33% MAP + 450 piercing damage to target enemy.`,
      },
      "Go For Da Soft Spot": {
        name: "Go For Da Soft Spot",
        pos: "e1",
        icon: icons["abi_gs_whatarmor"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "100ft range",
        cast: "3.0s channel",
        cooldown: "10s cooldown",
        description: talentText`Deals 10% RAP + 148 piercing damage to target enemy every second and apply 1 stack of Reduced Agility, Dodge, or Block.`,
      },
      "Wear Em Down": {
        name: "Wear Em Down",
        pos: "f1",
        icon: icons["abi_or_yerallbleedinnow"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 40 Psychic Energy",
        description: talentText`Applies a 21 second ailment to target enemy stacking up to 5 times. For the duration, deals 9% MAP + 135 indirect, ichor damage every 3 seconds.`,
      },
      "Drop That!": {
        name: "Drop That!",
        pos: "g1",
        icon: icons["abi_gs_dropthat"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "45 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Applies Disarmed and Inevitable to the target.\n\nDisarmed prevents the use of skills for 5 seconds.\nInevitable prevents the application of Disarmed and Silenced for 20 seconds.`,
      },
      "Don' Wana Live Foreva": {
        name: "Don' Wana Live Foreva",
        pos: "h1",
        icon: icons["abi_or_range02"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "100ft range",
        cast: "1.5s cast",
        cooldown: "no cooldown",
        description: talentText`Deals 15% RAP + 214 piercing damage to target enemy, applies 1 stack of Reduced Outgoing Healing, and applies a 5 second affliction. For the duration, target has 33% slower cast times.`,
      },
      "Vigilance": {
        name: "Vigilance",
        pos: "i1",
        icon: icons["abi_vigilance"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        description: talentText`Your damage reduction is increased by 50% but your outgoing damage is reduced by 90% for 7 seconds.`,
      },
	  "Shrapnel Arrer": {
        name: "Shrapnel Arrer",
        pos: "h4",
        icon: icons["abi_gs_shrapnelarrer"],
        maxRank: 1,
        reqPoints: 5,
        type: "skill",
        cost: "60 action points",
        range: "100ft range",
        cast: "1.5s cast",
        cooldown: "no cooldown",
        description: talentText`Applies a 10 second ailment to up to 9 enemies within a 30 foot area you select. For the duration, deals 4% RAP + 44 indirect, ichor damage every 2 seconds.`,
      },
	  "Quit Yer Yappin'": {
        name: "Quit Yer Yappin'",
        pos: "e5",
        icon: icons["abi_or_throatslasha"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Costs 30 Psychic Energy",
        description: talentText`Applies Silenced and Inevitable to target enemy.\n\nSilenced prevents the use of spells for 5 seconds.\nInevitable prevents the application of Disarmed and Silenced for 20 seconds.`,
      },
	  "Wild Choppin'": {
        name: "Wild Choppin'",
        pos: "c6",
        icon: icons["abi_or_melee02"],
        maxRank: 1,
        reqPoints: 15,
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 75 Psychic Energy",
        description: talentText`Deals 12% MAP + 170 piercing damage to up to 9 enemies within 30 feet of you.`,
      },
	  "Abuse Em": {
        name: "Abuse Em",
        pos: "d8",
        icon: icons["abi_or_range01"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "65 action points",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "15s cooldown",
        description: talentText`Applies 3 stacks of Reduced Armor and a 15 second ailment to target enemy. For the duration, deals 16% RAP + 226 indirect, ichor damage every 3 seconds.`,
      },
      "Da Big Arrer": {
        name: "Da Big Arrer",
        pos: "d9",
        icon: icons["abi_or_range03"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "65 action points",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "15s cooldown",
        description: talentText`Deals 91% RAP + 1210 piercing damage to target enemy.`,
      },
      "Penetrating Arrow": {
        name: "Penetrating Arrow",
        pos: "f9",
        icon: icons["abi_he_penetratingarrow"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "150 action points",
        range: "self",
        cast: "2.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Fire an arrow 65 feet in front of you. First enemy hit takes 5% RAP + 50 piercing damage. Each subsequent enemy takes additional damage.`,
      },
	  "Dat Tickles": {
        name: "Dat Tickles",
        pos: "a5",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you spend Psychic Energy, you will gain a 5 second enchantment. Absorb up to 15% RP + 204 damage for the duration.`,
      },
	  "Unfair Advantage": {
        name: "Unfair Advantage",
        pos: "g5",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you hit an enemy you are flanking, you will gain a buff for 2 seconds. For the duration, you will gain outgoing damage equal to 100% of your accuracy.`,
      },
	  "Aimin' Quickly": {
        name: "Aimin' Quickly",
        pos: "f6",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Plink has a 0.75 second faster cast time.`,
      },
	  "Biggest and Strongest": {
        name: "Biggest and Strongest",
        pos: "g6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Vigilance now increases outgoing damage by 20% instead of its original effects.`,
      },
	  "You Got Nuffin": {
        name: "You Got Nuffin",
        pos: "a7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Go For Da Soft Spot and Don Wana Live Foreva now hit up to 8 additional enemies within 20 feet of the target, but will deal 66% less damage.`,
      },
	  "Heavy Metal": {
        name: "Heavy Metal",
        pos: "h7",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 20,
		prereq: "Shrapnel Arrer",
		arrows: [
          { dir: "down", from: "h4", to: "h7" },
        ],
        type: "career tactic",
        description: talentText`Shrapnel Arrer now reduces Outgoing Damage and Outgoing Healing by 5%; and Pushback Immunity by 33%.`,
      },
	  "Finish Em Fasta": {
        name: "Finish Em Fasta",
        pos: "f8",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Supa Chop, Wear Em Down, and Wild Choppin' now apply stacks of Reduced Piercing Resistance to their target.`,
      },
	  "Red Goes Fasta": {
        name: "Red Goes Fasta",
        pos: "e3",
        icon: icons["abi_or_range04"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Your range and cast times are reduced by ${[
          5,
          10,
          15,
          20,
          25,
        ]}%.`,
      },
	  "Bigga and Harda": {
        name: "Bigga and Harda",
        pos: "b4",
        icon: icons["abi_gs_arreromork"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Your ranged attacks deal 50% more damage but have an additional 30% chance to miss.`,
      },
	  "Bring It On": {
        name: "Bring It On",
        pos: "b5",
        icon: icons["abi_gs_arreromork"],
        maxRank: 2,
        reqPoints: 10,
        prereq: "Bigga and Harda",
		arrows: [
          { dir: "down", from: "b4", to: "b5" },
        ],
        type: "passive",
        description: talentText`Whenever you spend Psychic Energy, you will gain ${[
          10,
          20,
        ]}% range and accuracy for 10 seconds.`,
      },
	  "Go Fasta": {
        name: "Go Fasta",
        pos: "d6",
        icon: icons["abi_gs_runnshoot"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`You gain ${[
          2,
          5,
        ]}% movement speed for 10 seconds whenever you spend Psychic Energy. Stacks up to 5 times.`,
      },
	  "Improved Basic Attack": {
        name: "Improved Basic Attack",
        pos: "e6",
        icon: icons["abi_ge_shoot"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Your basic attacks deal ${[
          50,
          100,
          150,
          200,
          250,
        ]}% additional damage.`,
      },
	  "Improved Wild Choppin'": {
        name: "Improved Wild Choppin'",
        pos: "c7",
        icon: icons["abi_or_melee02"],
        maxRank: 3,
        reqPoints: 20,
        prereq: "Wild Choppin'",
		arrows: [
          { dir: "down", from: "c6", to: "c7" },
        ],
        type: "passive",
        description: talentText`Wild Choppin' will deal ${[
          5,
          10,
          15,
        ]}% more damage.`,
      },
	  "Ladz, Ladz, Ladz": {
        name: "Passive 5",
        pos: "e7",
        icon: icons["abi_gs_quityersquabbin"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Your outgoing damage is reduced by ${[
          6,
          12,
          20,
        ]}%. Whenever you use an ability, all groupmates within 100 feet will gain half the amount of outgoing damage for 3 seconds.`,
      },
	  "Use Them": {
        name: "Use Them",
        pos: "e8",
        icon: icons["abi_or_figure10"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Your action point costs are reduced by ${[
          2,
          6,
          12,
          20,
        ]}%. Whenever you spend Psychic Energy, you will double this benefit for 10 seconds.`,
      },
    },
  },
  "Big Waaagh": {
    name: "Big Waaagh",
    background: backgrounds["big waaagh"],
    icon: icons["archetype_dps"],
    talents: {
	  "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 1,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "I'm Da Biggest": {
        name: "I'm Da Biggest",
        pos: "a2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Gain 500 + 25% wounds maximum health.`,
      },
      "Waaagh": {
        name: "Waaagh",
        pos: "b2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that have this tactic gain 1 Fightiness, gain 3 Pyschic Energy, lose 1 Cowardice, or lose 1 Paranoia.`,
      },
      "Longa and Stronga": {
        name: "Longa and Stronga",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`The maximum amount of Psychic Energy you can hold is increased to 250.`,
      },
      "Keep It Comin'": {
        name: "Keep It Comin'",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Generate 3 Psychic Energy per second.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specstaff"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Big Waaagh equip Staves.`,
      },
	  "Return Life": {
        name: "Return Life",
        pos: "f2",
        icon: icons["morale_returnlife"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Return target groupmate back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Divine Protection": {
        name: "Divine Protection",
        pos: "h2",
        icon: icons["morale_divineprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 15 seconds. They will absorb up to 200% RP + 1500 damage over the duration.`,
      },
      "Alter Fate": {
        name: "Alter Fate",
        pos: "i2",
        icon: icons["morale_alterfate"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Removes all ailments and cripples from each groupmate within 100 feet. Also applies Return Life to each dead groupmate within 100 feet.`,
      },
      "Melt Armor": {
        name: "Melt Armor",
        pos: "i4",
        icon: icons["morale_melt"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Target enemy gains 4 stacks of Reduced Armor.`,
      },
      "Relentless": {
        name: "Relentless",
        pos: "i5",
        icon: icons["abi_or_tantrum"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Gain a buff for 15 seconds. Convert 20 action points into 30 psychic energy every second. This effect is dispelled if you run out of action points.`,
      },
      "Puddle O' Muck": {
        name: "Puddle O' Muck",
        pos: "i7",
        icon: icons["abi_gs_puddleomuck"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Up to 12 enemies within 30 feet of you gain Ensnared.\n\nEnsnared reduces your movement speed by 30% for 16 seconds.`,
      },
      "Gork iz 'Ere": {
        name: "Gork iz 'Ere",
        pos: "i8",
        icon: icons["abi_or_waaagh"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Gork w'll krump n' bash their 'eads for ya! For 30 seconds you gain 10 Fightiness and 20 Psychic Energy per second, 100% outgoing damage, 50% damage reduction, and 1000 HP4. You'll die at the end of the duration and gain Forlorn.`,
      },
      "Psychic Energy": {
        name: "Psychic Energy",
        pos: "a1",
        icon: icons["abi_or_figure10"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Psychic Energy has a base of 0 and a maximum of 200. You generate 5 psychic energy anytime a groupmate within 100 feet uses a basic attack.`,
      },
      "Clobber": {
        name: "Clobber",
        pos: "b1",
        icon: icons["abi_gs_yernothin"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 4% MAP + 30 piercing damage to target enemy. Generates 22 action points.`,
      },
      "Slasha": {
        name: "Slasha",
        pos: "c1",
        icon: icons["abi_or_melee11"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "36 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 21% MAP + 280 piercing damage to target enemy.`,
      },
      "Gaze of Mork": {
        name: "Gaze of Mork",
        pos: "d1",
        icon: icons["abi_or_melee06"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "75ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 50 Psychic Energy",
        description: talentText`Deals 57% SAP + 767 impact damage to target enemy.`,
      },
      "Bring Da Pain": {
        name: "Bring Da Pain",
        pos: "e1",
        icon: icons["abi_or_tiredalready"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 50 Psychic Energy",
        description: talentText`Applies a 6 second ailment to target enemy. Deals 32% SAP + 443 indirect, impact damage to them at the end of the duration.`,
      },
      "Chop Fasta": {
        name: "Chop Fasta",
        pos: "f1",
        icon: icons["abi_or_melee09"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 18% MAP + 234 piercing damage to target enemy and up to 2 other enemies within 20 feet of them.`,
      },
      "Quit Yer Yappin'": {
        name: "Quit Yer Yappin'",
        pos: "g1",
        icon: icons["abi_or_throatslasha"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Costs 30 Psychic Energy",
        description: talentText`Applies Silenced and Inevitable to target enemy.\n\nSilenced prevents the use fo spells for 5 seconds.\nInevitable prevents the application of Disarmed and Silenced for 20 seconds.`,
      },
      "Wear Em Down": {
        name: "Wer Em Down",
        pos: "h1",
        icon: icons["abi_or_yerallbleedinnow"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 40 Psychic Energy",
        description: talentText`Applies a 21 second ailment to target enemy stacking up to 5 times. For the duration, deals 9% MAP + 135 indirect, ichor damage every 3 seconds.`,
      },
      "Vigilance": {
        name: "Vigilance",
        pos: "i1",
        icon: icons["abi_vigilance"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        description: talentText`Your damage reduction is increased by 50% but your outgoing damage is reduced by 90% for 7 seconds.`,
      },
	  "Breath of Mork": {
        name: "Breath of Mork",
        pos: "g4",
        icon: icons["abi_ge_zap"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "75 action points",
        range: "75ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`Deals 36% SAP + 485 elemental damage to target enemy. Then will jump to another enemy within 20 feet. Jumps twice.\n\nAugmented: each jump will explode dealing 7% SAP + 95 elemental damage to 1 additional enemy within 20 feet.`,
      },
	  "Tired Already?": {
        name: "Tired Already?",
        pos: "c5",
        icon: icons["abi_gs_getemlads"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "5s cooldown",
        blue: "Costs 35 Psychic Energy",
        description: talentText`Deals 17% SAP + 211 impact damage to target enemy and slows their movement by 25% for 1 second.`,
      },
	  "Wild Choppin'": {
        name: "Wild Choppin'",
        pos: "f6",
        icon: icons["abi_or_melee02"],
        maxRank: 1,
        reqPoints: 15,
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 75 Psychic Energy",
        description: talentText`Deals 12% MAP + 170 piercing damage to up to 9 enemies within 30 feet of you.`,
      },
	  "Fists of Gork": {
        name: "Fists of Gork",
        pos: "b8",
        icon: icons["abi_gs_bunchowaaagh"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "no cost",
        range: "75ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 75 Psychic Energy",
        description: talentText`Deals 32% SAP + 426 impact damage to target enemy every second.`,
      },
      "Really Green": {
        name: "Really Green",
        pos: "d9",
        icon: icons["abi_or_figure22"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "25s cooldown",
        description: talentText`Generates 150 Psychic Energy.`,
      },
      "Waaagh!": {
        name: "Waagh!",
        pos: "f9",
        icon: icons["abi_gs_waaagh"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "150 action points",
        range: "self",
        cast: "2.0s channel",
        cooldown: "30s cooldown",
        description: talentText`You interrupt up to 48 enemies who do not have Cover from you within 30 feet every 0.5 seconds. Whenever you successfully interrupt an enemy, you will deal 10% MAP + 50 ichor damage to them and up to 17 other enemies within 20 feet of them.`,
      },
	  "Cripple Em": {
        name: "Cripple Em",
        pos: "a5",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Bring Da Pain and Wear Em Down are now cripples.`,
      },
	  "Fightin' Betta": {
        name: "Fightin' Betta",
        pos: "b5",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you hit with a melee attack, your next Gaze of Mork cast within 8 seconds will deal 33% more damage.`,
      },
	  "Biggest and Strongest": {
        name: "Biggest and Strongest",
        pos: "a6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Vigilance now increases outgoing damage by 20% instead of its original effects.`,
      },
	  "No More Helpin'": {
        name: "No More Helpin'",
        pos: "b6",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Bring Da Pain now applies a -33% outgoing healing debuff.`,
      },
	  "Extra Choppin'": {
        name: "Extra Choppin'",
        pos: "b7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Lotsa Choppin' and Wild Choppin' will now hit up to 24 enemies.`,
      },
	  "Big Breath": {
        name: "Big Breath",
        pos: "g7",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Breath of Mork",
		arrows: [
          { dir: "down", from: "g4", to: "g7" },
        ],
        type: "career tactic",
        description: talentText`If you have 30 or more Psychic Energy, Breath of Mork will be augmented and cost 30 Psychic Energy.`,
      },
	  "Blast Em Fasta": {
        name: "Blast Em Fasta",
        pos: "h8",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`The cast time of Gaze of Mork is reduced by 1.7 seconds. You will lose 20% movement for 2 seconds after casting it.`,
      },
	  "Great Green Nemesis": {
        name: "Great Green Nemesis",
        pos: "e3",
        icon: icons["abi_or_figure10"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Gain ${[
          1,
          2,
          3,
          4,
          5,
        ]} Psychic Energy every 2 seconds.`,
      },
	  "Improved Gaze of Mork": {
        name: "Improved Gaze of Mork",
        pos: "c4",
        icon: icons["abi_or_melee06"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`The cast time of Gaze of Mork is reduced by ${[
          0.1,
          0.2,
          0.3,
          0.4,
          0.5,
        ]} seconds.`,
      },
	  "Wots Da Rush": {
        name: "Wots Da Rush",
        pos: "c6",
        icon: icons["abi_gs_getemlads"],
        maxRank: 2,
        reqPoints: 15,
        prereq: "Tired Already?",
		arrows: [
          { dir: "down", from: "c5", to: "c6" },
        ],
        type: "passive",
        description: talentText`The effect of Tired Already? now lasts ${[
          2,
          3,
        ]} seconds.`,
      },
	  "Explosive Breath": {
        name: "Explosive Breath",
        pos: "h6",
        icon: icons["abi_ge_zap"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Breath of Mork",
		arrows: [
          { dir: "right-down", from: "g4", to: "h4" },
          { dir: "right-down-down", from: "h4", to: "h6" }
        ],
        type: "passive",
        description: talentText`The augmented explosion for Breath of Mork will now hit ${[
          2,
          3,
          4,
          5,
          6,
        ]} additional enemies.`,
      },
	  "Yer Gettin Soft": {
        name: "Yer Getting Soft",
        pos: "d7",
        icon: icons["abi_or_yerallbleedinnow"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Wear Em Down will now cost 0 Psychic Energy and 55 action points. Also deals ${[
          0,
          10,
          25,
        ]}% additional damage.`,
      },
	  "Improved Wild Choppin'": {
        name: "Improved Wild Choppin'",
        pos: "f7",
        icon: icons["abi_or_melee02"],
        maxRank: 3,
        reqPoints: 20,
        prereq: "Wild Choppin'",
		arrows: [
          { dir: "down", from: "f6", to: "f7" },
        ],
        type: "passive",
        description: talentText`Wild Choppin' will deal ${[
          5,
          10,
          15,
        ]}% more damage.`,
      },
	  "Imposin Presence": {
        name: "Imposing Presence",
        pos: "e8",
        icon: icons["abi_gs_dachallenge"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Your spells deal ${[
          3,
          8,
          15,
          25,
        ]}% additional damage against enemies above 80% health, and your skills deal ${[
          3,
          8,
          15,
          25,
        ]}% additional damage against enemies below 40% health.`,
      },
    },
  },
};