import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/greenskin"),
);
const icons = requireAll(require.context("../../assets/icons/greenskin"));

export const data: TalentData = {
  "Fighta": {
    name: "Fighta",
    background: backgrounds["fighta"],
    icon: icons["archetype_tank"],
    talents: {
      "Masochist": {
        name: "Masochist",
        pos: "a8",
        icon: icons["rrtac_masochist"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you are attacked while your Guard is active, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Increase your mass by 1.`,
      },
      "I'm Da Biggest": {
        name: "I'm Da Biggest",
        pos: "a2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Gain 500 + 25% wounds maximum health.`,
      },
      "Waaagh": {
        name: "Waaagh",
        pos: "b2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that have this tactic gain 1 Fightiness, gain 3 Pyschic Energy, lose 1 Cowardice, or lose 1 Paranoia.`,
      },
      "Lookin' For Opp'tunity": {
        name: "Lookin' For Opp'tunity",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Clobberin' Time now costs 5 less Fightiness.`,
      },
      "Guud at Big Choppin'": {
        name: "Guud at Big Choppin'",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You will now retain 0.5 times your block chance while under the effects of Clobberin' Time.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Fightas equip swords, shields, and two-handed axes.`,
      },
	  "Hedgehog": {
        name: "Hedgehog",
        pos: "f2",
        icon: icons["morale_hedgehog"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`All groupmates within 100ft gain 3 stacks of Enhanced Block.`,
      },
      "Champion's Challenge": {
        name: "Champion's Chalenge",
        pos: "g2",
        icon: icons["morale_grapple"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Applies a debuff to target enemy and yourself for 10 seconds. Movement speed is reduced to 0 for the duration.`,
      },
      "Distracting Bellow": {
        name: "Distracting Bellow",
        pos: "h2",
        icon: icons["morale_distractingbellow"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Up to 48 enemies within 30ft of you receive a debuff. For 10 seconds, they cannot benefit from Cover.`,
      },
      "Immaculate Defense": {
        name: "Immaculate Defense",
        pos: "i2",
        icon: icons["morale_immaculatedefense"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Groupmates within 100ft gain 25 stacks of a buff for 20 seconds. Each stack grants 3% damage reduction. A stack is removed each time they are attacked by an ability; 4 additional stacks are removed if the ability is single target.`,
      },
      "No Choppin' Me": {
        name: "No Choppin' Me",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "5.0s channel",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`You gain 100% block chance.`,
      },
      "Save Da Runts": {
        name: "Save Da Runts",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Jump to target groupmates and apply 5 stacks of Savin' Me Hide to them.\n\nSavin' Me Hide lasts 10 seconds and stacks up to 10 times. For the duration, gain 100% block chance and lose 1 stack each time you block.`,
      },
      "Puddle O' Muck": {
        name: "Puddle O' Muck",
        pos: "i7",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Up to 12 enemies within 30 feet of you gain Ensnared.\n\nEnsnared reduces your movement speed by 30% for 16 seconds.`,
      },
      "Gork Smash": {
        name: "Gork Smash",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`You gain a buff for 30 seconds. For the duration, gain 10 Fightiness per second, 100% outgoing damage, 50% damage reduction, and 1000 HP4. You die at the end of the duration and gain Forlorn.`,
      },
      "Fightiness": {
        name: "Fightiness",
        pos: "a1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Fightiness has a base of 0 and a max of 30. You lose 1 Fightiness anytime you are hit by an ability that you do not block.`,
      },
      "Clobber": {
        name: "Clobber",
        pos: "b1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 110 piercing damage to target enemy. Generates 22 action points.`,
      },
      "Clobberin' Time": {
        name: "Clobberin' Time",
        pos: "c1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Off the GCD\nCosts 25 Fightiness",
        description: talentText`Gain a buff for 10 seconds. For the duration, you cannot block and will lose access to certain skills, but will enable your two-handed axe skills.`,
      },
      "Right in Da Jibblies": {
        name: "Right in Da Jibblies",
        pos: "d1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "36 action points",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled by Clobberin' Time",
        description: talentText`Deals 21% MAP + 280 impact damage to target enemy. Generates 1 Fightiness.`,
      },
      "Guard": {
        name: "Guard",
        pos: "e1",
        icon: icons["abi_guard"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Applies Guard to target groupmate. While you are within 30 feet of them, they will gain 50% of your armor, resistances, and block. You will lose these stats for the duration and for 5 seconds after the effect is broken.`,
      },
      "Skull Thumper": {
        name: "Skull Thumper",
        pos: "f1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Requires Clobberin' Time",
        description: talentText`Deals X% MAP + Y impact damage to target enemy and apply 1 stack of Reduced Block to them.`,
      },
      "Buh-Bye": {
        name: "Buh-Bye",
        pos: "g1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Disabled by Clobberin' Time",
        description: talentText`Knocks the enemy away and applies Immovable to them.\n\nImmovable prevents the application of Knockbacks, Pulls, and the Rooted status for 20 seconds.`,
      },
      "Trip 'Em Up": {
        name: "Trip 'Em Up",
        pos: "h1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled by Clobberin' Time",
        description: talentText`Deals 17% MAP + 227 impact damage and applies Ensnared and Momentum to target enemy.\n\nEnsanred reduced movement speed by 30% for 16 seconds.\nMomentum prevents the application of Ensnared for 8 seconds.`,
      },
      "Can't Hit Me": {
        name: "Can't Hit Me",
        pos: "i1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Gain a blessing for 8 seconds. For the duration, your block chance is increased by 50%.`,
      },
	  "Big Swing": {
        name: "big Swing",
        pos: "b4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        type: "skill",
        cost: "60 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Requires Clobberin' Time",
        description: talentText`Deals X% MAP + Y impact damage to up to 9 enemies within 30 feet in front of you.`,
      },
	  "Distract": {
        name: "Distract",
        pos: "g5",
        icon: icons["abi_distract"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "40 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Jams the target for the next 3 seconds interupting the next ability cast.`,
      },
	  "Follow Me Lead": {
        name: "Follow Me Lead",
        pos: "c6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "60 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`All groupmates within 100 feet of you gain an enchantment for 5 seconds. For the duration they will gain 5 action points per second and 5 adrenaline per second.`,
      },
	  "Big Slash": {
        name: "Big Slash",
        pos: "c8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "80 action points",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Requires Clobberin' Time",
        description: talentText`Knocks away up to 9 enemies within 20 feet target enemy and applies Immovable to them. Apply an ailment to target enemy for 10 seconds. For the duration, their outgoing damage is decreased by 15%.`,
      },
      "We'z Bigger": {
        name: "We'z Bigger",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "75 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "30s cooldown",
        description: talentText`Removes Ensnared, Rooted, Silenced, Disarmed, Knocked-down, and Staggered from all groupmates within 100 feet of you.`,
      },
      "Waaagh!": {
        name: "Waagh!",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "150 action points",
        range: "self",
        cast: "2.0s channel",
        cooldown: "30s cooldown",
        description: talentText`You interrupt up to 48 enemies who do not have Cover from you within 30 feet every 0.5 seconds. Whenever you successfully interrupt an enemy, you will deal 10% MAP + 50 ichor damage to them and up to 17 other enemies within 20 feet of them.`,
      },
	  "Leg Breaka": {
        name: "Leg Breaka",
        pos: "a5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Trip 'Em Up will now hit up to 2 other enemies within 20 feet.`,
      },
	  "Keep It Goin'": {
        name: "Keep It Goin'",
        pos: "c5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Buh-Bye, Trip 'Em Up, and Distract now generates 1 Fightiness.`,
      },
	  "Big Brawlin'": {
        name: "Big Brawlin'",
        pos: "e6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Skull Thumper now applies 1 stack of Reduced Fortitude and 1 stack of Reduced Agility to the target.`,
      },
	  "Improved Distract": {
        name: "Improved Distract",
        pos: "g6",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Distract",
		arrows: [
          { dir: "down", from: "g5", to: "g6" },
        ],
        type: "career tactic",
        description: talentText`Distract will now work on up to 23 additional enemies within 20 feet of the target as long as those targets do not have Cover from you.`,
      },
	  "You'z See Me Block Dat?!": {
        name: "You'z See Me Block Dat?!",
        pos: "a7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Whenever you block an attack, you will deal X% MAP + Y impact damage to up to 9 enemies within 30 feet of you and gain 1 Fightiness. This effect cannot happen more than once every 2 seconds.`,
      },
	  "Tactic 6": {
        name: "T6",
        pos: "b7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Big Swing",
		arrows: [
          { dir: "down", from: "b4", to: "b7" },
        ],
        type: "career tactic",
        description: talentText`Big Swing will now grant 1 stack of Enhanced Strength to all groupmates within 100 feet of you.`,
      },
	  "Good Wif Shield": {
        name: "Good Wif Shield",
        pos: "g8",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Whenever you block an attack, you will gain 15% damage reduction for 5 seconds. Big Swing will now cost 10 less action points.`,
      },
	  "Passive 1": {
        name: "Passive 1",
        pos: "e3",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 2": {
        name: "Passive 2",
        pos: "c4",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 5,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 3": {
        name: "Passive 3",
        pos: "e5",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 4": {
        name: "Passive 4",
        pos: "d6",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 5": {
        name: "Passive 5",
        pos: "e6",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 6": {
        name: "Passive 6",
        pos: "d7",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 7": {
        name: "Passive 7",
        pos: "e7",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 8": {
        name: "Passive 8",
        pos: "e8",
        icon: icons["noicon"],
        maxRank: 4,
        reqPoints: 25,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
    },
  },
  "Warboss": {
    name: "Warboss",
    background: backgrounds["warboss"],
    icon: icons["archetype_defsupport"],
    talents: {
      "Break Loose": {
        name: "Break Loose",
        pos: "a8",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Masochist": {
        name: "Masochist",
        pos: "a8",
        icon: icons["rrtac_masochist"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you are attacked while your Guard is active, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Increase your mass by 1.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "What a Rush": {
        name: "What a Rush",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`The action point cost of your skills is reduced by 33% on allies that are lower than 40% health.`,
      },
      "Racial Tactic 1": {
        name: "Racial Tactic 1",
        pos: "a2",
        icon: icons["tac_race_"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Racial Tactic 2": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_race_"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 1": {
        name: "Class Tactic 1",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 2": {
        name: "Class Tactic 2",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Specialization is able to equip these weapons.`,
      },
	  "Hedgehog": {
        name: "Hedgehog",
        pos: "f2",
        icon: icons["morale_hedgehog"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`All groupmates within 100ft gain 3 stacks of Enhanced Block.`,
      },
      "Champion's Challenge": {
        name: "Champion's Chalenge",
        pos: "g2",
        icon: icons["morale_grapple"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Applies a debuff to target enemy and yourself for 10 seconds. Movement speed is reduced to 0 for the duration.`,
      },
      "Distracting Bellow": {
        name: "Distracting Bellow",
        pos: "h2",
        icon: icons["morale_distractingbellow"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Up to 48 enemies within 30ft of you receive a debuff. For 10 seconds, they cannot benefit from Cover.`,
      },
      "Immaculate Defense": {
        name: "Immaculate Defense",
        pos: "i2",
        icon: icons["morale_immaculatedefense"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Groupmates within 100ft gain 25 stacks of a buff for 20 seconds. Each stack grants 3% damage reduction. A stack is removed each time they are attacked by an ability; 4 additional stacks are removed if the ability is single target.`,
      },
      "Morale 1 Class": {
        name: "Morale 1 Class",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 2 Spec": {
        name: "Morale 2 Spec",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 3 Race": {
        name: "Morale 3 Race",
        pos: "i7",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 4 Spec": {
        name: "Morale 4 Spec",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Specialization Mechanic": {
        name: "Specialization Mechanic",
        pos: "a1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell career tactic renown tactic passive morale 1234",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 1": {
        name: "Core Ability 1",
        pos: "b1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 2": {
        name: "Core Ability 2",
        pos: "c1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 3": {
        name: "Core Ability 3",
        pos: "d1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 4": {
        name: "Core Ability 4",
        pos: "e1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 5": {
        name: "Core Ability 5",
        pos: "f1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 6": {
        name: "Core Ability 6",
        pos: "g1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 7": {
        name: "Core Ability 7",
        pos: "h1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 8": {
        name: "Core Ability 8",
        pos: "i1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 1": {
        name: "SA1",
        pos: "b4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 2": {
        name: "SA2",
        pos: "c5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 3": {
        name: "SA3",
        pos: "c6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 4": {
        name: "SA4",
        pos: "c8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 1": {
        name: "Capstone Ability 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 2": {
        name: "Capstone Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 1": {
        name: "T1",
        pos: "a5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 2": {
        name: "T2",
        pos: "b5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 3": {
        name: "T3",
        pos: "a6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 4": {
        name: "T4",
        pos: "b6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 5": {
        name: "T5",
        pos: "a7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 6": {
        name: "T6",
        pos: "b7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 7": {
        name: "T7",
        pos: "b8",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Passive 1": {
        name: "Passive 1",
        pos: "e3",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 2": {
        name: "Passive 2",
        pos: "c4",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 5,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 3": {
        name: "Passive 3",
        pos: "e5",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 4": {
        name: "Passive 4",
        pos: "d6",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 5": {
        name: "Passive 5",
        pos: "e6",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 6": {
        name: "Passive 6",
        pos: "d7",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 7": {
        name: "Passive 7",
        pos: "e7",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 8": {
        name: "Passive 8",
        pos: "e8",
        icon: icons["noicon"],
        maxRank: 4,
        reqPoints: 25,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
    },
  },
  "Butcha": {
    name: "Butcha",
    background: backgrounds["butcha"],
    icon: icons["archetype_dps"],
    talents: {
      "Break Loose": {
        name: "Break Loose",
        pos: "a8",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Masochist": {
        name: "Masochist",
        pos: "a8",
        icon: icons["rrtac_masochist"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you are attacked while your Guard is active, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Increase your mass by 1.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "What a Rush": {
        name: "What a Rush",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`The action point cost of your skills is reduced by 33% on allies that are lower than 40% health.`,
      },
      "Racial Tactic 1": {
        name: "Racial Tactic 1",
        pos: "a2",
        icon: icons["tac_race_"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Racial Tactic 2": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_race_"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 1": {
        name: "Class Tactic 1",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 2": {
        name: "Class Tactic 2",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Specialization is able to equip these weapons.`,
      },
	  "Sever Nerve": {
        name: "Sever Nerve",
        pos: "f2",
        icon: icons["morale_severnerve"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Deals 50% MAP + 400 physical damage to the target.`,
      },
      "Broad Swings": {
        name: "Broad Swings",
        pos: "g2",
        icon: icons["morale_broadswings"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a  buff for 10 seconds. Your single target abilities will target two additional enemies within 15ft in front of you.`,
      },
      "Force of Will": {
        name: "Force of Will",
        pos: "h2",
        icon: icons["morale_forceofwill"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 10 seconds. Action point costs are reduced by 75% for the duration.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "Morale 1 Class": {
        name: "Morale 1 Class",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 2 Spec": {
        name: "Morale 2 Spec",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 3 Race": {
        name: "Morale 3 Race",
        pos: "i7",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 4 Spec": {
        name: "Morale 4 Spec",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Specialization Mechanic": {
        name: "Specialization Mechanic",
        pos: "a1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell career tactic renown tactic passive morale 1234",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 1": {
        name: "Core Ability 1",
        pos: "b1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 2": {
        name: "Core Ability 2",
        pos: "c1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 3": {
        name: "Core Ability 3",
        pos: "d1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 4": {
        name: "Core Ability 4",
        pos: "e1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 5": {
        name: "Core Ability 5",
        pos: "f1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 6": {
        name: "Core Ability 6",
        pos: "g1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 7": {
        name: "Core Ability 7",
        pos: "h1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 8": {
        name: "Core Ability 8",
        pos: "i1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 1": {
        name: "SA1",
        pos: "b4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 2": {
        name: "SA2",
        pos: "c5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 3": {
        name: "SA3",
        pos: "c6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 4": {
        name: "SA4",
        pos: "c8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 1": {
        name: "Capstone Ability 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 2": {
        name: "Capstone Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 1": {
        name: "T1",
        pos: "a5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 2": {
        name: "T2",
        pos: "b5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 3": {
        name: "T3",
        pos: "a6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 4": {
        name: "T4",
        pos: "b6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 5": {
        name: "T5",
        pos: "a7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 6": {
        name: "T6",
        pos: "b7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 7": {
        name: "T7",
        pos: "b8",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Passive 1": {
        name: "Passive 1",
        pos: "e3",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 2": {
        name: "Passive 2",
        pos: "c4",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 5,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 3": {
        name: "Passive 3",
        pos: "e5",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 4": {
        name: "Passive 4",
        pos: "d6",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 5": {
        name: "Passive 5",
        pos: "e6",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 6": {
        name: "Passive 6",
        pos: "d7",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 7": {
        name: "Passive 7",
        pos: "e7",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 8": {
        name: "Passive 8",
        pos: "e8",
        icon: icons["noicon"],
        maxRank: 4,
        reqPoints: 25,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
    },
  },
};