import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/greenskin"),
);
const icons = requireAll(require.context("../../assets/icons/greenskin"));

export const data: TalentData = {
  "Fighta": {
    name: "Fighta",
    background: backgrounds["fighta"],
    icon: icons["archetype_tank"],
    talents: {
      "Masochist": {
        name: "Masochist",
        pos: "a8",
        icon: icons["rrtac_masochist"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you are attacked while your Guard is active, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Increase your mass by 1.`,
      },
      "I'm Da Biggest": {
        name: "I'm Da Biggest",
        pos: "a2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Gain 500 + 25% wounds maximum health.`,
      },
      "Waaagh": {
        name: "Waaagh",
        pos: "b2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Da Waaagh calls, whenever you use a basic attack, all groupmates within 100 feet that have this tactic gain 1 Fightiness, gain 3 Pyschic Energy, lose 1 Cowardice, or lose 1 Paranoia.`,
      },
      "Scrappin' Time": {
        name: "Scrappin' Time ",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Fightin'is gettin' guud, Clobberin' Time now costs 5 less Fightiness.`,
      },
      "Guud at Big Choppin'": {
        name: "Guud at Big Choppin'",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Nothin' like a big scrap! You will now retain 0.5 times your block chance while under the effects of Clobberin' Time.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specexpertshield"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Anyfin' that chopz and bashes gits iz useful. Fightas equip swords, shields, and two-handed axes.`,
      },
	  "Hedgehog": {
        name: "Hedgehog",
        pos: "f2",
        icon: icons["morale_hedgehog"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`All groupmates within 100ft gain 3 stacks of Enhanced Block.`,
      },
      "Champion's Challenge": {
        name: "Champion's Chalenge",
        pos: "g2",
        icon: icons["morale_grapple"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Applies a debuff to target enemy and yourself for 10 seconds. Movement speed is reduced to 0 for the duration.`,
      },
      "Distracting Bellow": {
        name: "Distracting Bellow",
        pos: "h2",
        icon: icons["morale_distractingbellow"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Up to 48 enemies within 30ft of you receive a debuff. For 10 seconds, they cannot benefit from Cover.`,
      },
      "Immaculate Defense": {
        name: "Immaculate Defense",
        pos: "i2",
        icon: icons["morale_immaculatedefense"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Groupmates within 100ft gain 25 stacks of a buff for 20 seconds. Each stack grants 3% damage reduction. A stack is removed each time they are attacked by an ability; 4 additional stacks are removed if the ability is single target.`,
      },
      "No Choppin' Me": {
        name: "No Choppin' Me",
        pos: "i4",
        icon: icons["abi_gs_canthitme"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "5.0s channel",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`You gain 100% block chance.`,
      },
      "Save Da Runts": {
        name: "Save Da Runts",
        pos: "i5",
        icon: icons["abi_gs_savedarunts"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Jump to target groupmates and apply 5 stacks of Savin' Me Hide to them.\n\nSavin' Me Hide lasts 10 seconds and stacks up to 10 times. For the duration, gain 100% block chance and lose 1 stack each time you block.`,
      },
      "Puddle O' Muck": {
        name: "Puddle O' Muck",
        pos: "i7",
        icon: icons["abi_gs_puddleomuck"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Up to 12 enemies within 30 feet of you gain Ensnared.\n\nEnsnared reduces your movement speed by 30% for 16 seconds.`,
      },
      "Gork iz 'Ere": {
        name: "Gork iz 'Ere",
        pos: "i8",
        icon: icons["abi_or_waaagh"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Gork w'll krump n' bash their 'eads for ya! For 30 seconds you gain 10 Fightiness per second, 100% outgoing damage, 50% damage reduction, and 1000 HP4. You'll die at the end of the duration and gain Forlorn.`,
      },
      "Fightiness": {
        name: "Fightiness",
        pos: "a1",
        icon: icons["abi_or_figure14"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Fightiness has a base of 0 and a max of 30. You lose 1 Fightiness any time you are hit by an ability that you do not block.`,
      },
      "Clobber": {
        name: "Clobber",
        pos: "b1",
        icon: icons["abi_gs_yernothin"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) A guud clobber, deals 4% MAP + 30 piercing damage to target enemy. Generates 22 action points.`,
      },
      "Clobberin' Time": {
        name: "Clobberin' Time",
        pos: "c1",
        icon: icons["abi_or_armor01"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Off the GCD\nCosts 25 Fightiness",
        description: talentText`You want to fight harder than ever! For 10 seconds you cannot block and will lose access to certain skills, but will enable your two-handed axe skills.`,
      },
      "Right in Da Jibblies": {
        name: "Right in Da Jibblies",
        pos: "d1",
        icon: icons["abi_or_crotch01"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "20 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled by Clobberin' Time",
        description: talentText`Wuts' fightin dirty? a scrap is a scrap. You deal 15% MAP + 204 impact damage to target enemy. Generates 2 Fightiness.`,
      },
      "Guard": {
        name: "Guard",
        pos: "e1",
        icon: icons["abi_guard"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Applies Guard to target groupmate. While you are within 30 feet of them, they will gain 50% of your armor, resistances, and block. You will lose these stats for the duration and for 5 seconds after the effect is broken.`,
      },
      "Skull Thumper": {
        name: "Skull Thumper",
        pos: "f1",
        icon: icons["abi_gs_eadbutt"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Requires Clobberin' Time",
        description: talentText`A smash to the 'ead that deals 26% MAP + 348 impact damage to target enemy and apply 1 stack of Reduced Block to them.`,
      },
      "Outta' My Way": {
        name: "Outta' My Way",
        pos: "g1",
        icon: icons["abi_gs_walkitoff"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Disabled by Clobberin' Time",
        description: talentText`A guud bash of your shield knocks the enemy away and applies Immovable to them.\n\nImmovable prevents the application of Knockbacks, Pulls, and the Rooted status for 20 seconds.`,
      },
      "Knowhere ta' Go": {
        name: "Knowhere ta' Go",
        pos: "h1",
        icon: icons["abi_or_foot03"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled by Clobberin' Time",
        description: talentText`You swipe at their legs dealing 17% MAP + 227 impact damage and applies Ensnared and Momentum to target enemy.\n\nEnsanred reduced movement speed by 30% for 16 seconds.\nMomentum prevents the application of Ensnared for 8 seconds.`,
      },
      "Can't Hit Me": {
        name: "Can't Hit Me",
        pos: "i1",
        icon: icons["abi_or_shield01"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Shield up and gain a blessing for 8 seconds. Your block chance is increased by 50%.`,
      },
	  "Big Swing": {
        name: "Big Swing",
        pos: "b4",
        icon: icons["abi_gs_bigswing"],
        maxRank: 1,
        reqPoints: 5,
        type: "skill",
        cost: "60 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Requires Clobberin' Time",
        description: talentText`A maddening swing deals 10% MAP + 126 impact damage to up to 9 enemies within 30 feet in front of you.`,
      },
	  "Distract": {
        name: "Distract",
        pos: "g5",
        icon: icons["abi_distract"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "40 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Jams the target for the next 3 seconds interupting the next ability cast.`,
      },
	  "Follow Me Lead": {
        name: "Follow Me Lead",
        pos: "c6",
        icon: icons["abi_gs_followmelead"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "60 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`All groupmates within 100 feet of you gain an enchantment for 5 seconds. For the duration they will gain 5 action points per second and 5 adrenaline per second.`,
      },
	  "Big Scrappin": {
        name: "Big Scrappin",
        pos: "c8",
        icon: icons["abi_gs_dabigun"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "80 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Requires Clobberin' Time",
        description: talentText`Knocks away up to 9 enemies within 20 feet target enemy and applies Immovable to them. Apply an ailment to target enemy for 10 seconds. For the duration, their outgoing damage is decreased by 15%.\n\nImmovable prevents the application of Knockbacks, Pulls, and the Rooted status for 20 seconds.`,
      },
      "We'z Bigger": {
        name: "We'z Bigger",
        pos: "d9",
        icon: icons["abi_gs_wezbigger"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "75 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "30s cooldown",
        description: talentText`Removes Ensnared, Rooted, Silenced, Disarmed, Knocked-down, and Staggered from all groupmates within 100 feet of you.`,
      },
      "Waaagh!": {
        name: "Waagh!",
        pos: "f9",
        icon: icons["abi_gs_waaagh"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "150 action points",
        range: "self",
        cast: "2.0s channel",
        cooldown: "30s cooldown",
        description: talentText`A rampaging bellow that interrupts up to 48 enemies who do not have Cover from you within 30 feet every 0.5 seconds. Whenever you successfully interrupt an enemy, you will deal 10% MAP + 50 ichor damage to them and up to 17 other enemies within 20 feet of them.`,
      },
	  "Leg Breaka": {
        name: "Leg Breaka",
        pos: "a5",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Why not a stop to all ther' gits? Knowhere ta' Go will now hit up to 2 other enemies within 20 feet.`,
      },
	  "Keep It Goin'": {
        name: "Keep It Goin'",
        pos: "c5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Outta My Way, Knowhere ta Go, and Distract now generates 1 Fightiness.`,
      },
	  "Big Brawlin'": {
        name: "Big Brawlin'",
        pos: "e6",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Skull Thumper now applies 1 stack of Reduced Fortitude and 1 stack of Reduced Agility to the target.`,
      },
	  "Improved Distract": {
        name: "Improved Distract",
        pos: "g6",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Distract",
		arrows: [
          { dir: "down", from: "g5", to: "g6" },
        ],
        type: "career tactic",
        description: talentText`Distract will now work on up to 23 additional enemies within 20 feet of the target as long as those targets do not have Cover from you.`,
      },
	  "You'z See Me Block Dat?!": {
        name: "You'z See Me Block Dat?!",
        pos: "a7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Whenever you block an attack, you will deal 6% MAP + 90 impact damage to up to 9 enemies within 30 feet of you and gain 1 Fightiness. This effect cannot happen more than once every 2 seconds.`,
      },
	  "'Ead Bashers": {
        name: "'Ead Bashers",
        pos: "b7",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Big Swing",
		arrows: [
          { dir: "down", from: "b4", to: "b7" },
        ],
        type: "career tactic",
        description: talentText`Big Swing will now grant 1 stack of Enhanced Strength to all groupmates within 100 feet of you.`,
      },
	  "Good Wif Shield": {
        name: "Good Wif Shield",
        pos: "g8",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Whenever you block an attack, you will gain 15% damage reduction for 5 seconds. Big Swing will now cost 10 less action points.`,
      },
	  "Krump 'em": {
        name: "Krump 'em",
        pos: "e3",
        icon: icons["abi_or_figure14"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`You have a ${[
          33,
          66,
          100,
        ]}% chance to gain an extra Fightiness whenever you gain Fightiness.`,
      },
	  "Improved Block": {
        name: "Improved Block",
        pos: "h4",
        icon: icons["skl_specexpertshield"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increase your chance to block by ${[
          3,
          6,
          9,
          12,
          15,
        ]}%.`,
      },
	  "Engage": {
        name: "Engage",
        pos: "d6",
        icon: icons["abi_engage"],
        maxRank: 3,
        reqPoints: 15,
        type: "passive",
        description: talentText`Enemies that you deal direct damage to will have their outgoing damage reduced by ${[
          2,
          4,
          6,
        ]}% for 5 seconds.`,
      },
	  "Savin' Me Hide": {
        name: "Savin' Me Hide",
        pos: "f6",
        icon: icons["abi_or_face19"],
        maxRank: 4,
        reqPoints: 15,
        type: "passive",
        description: talentText`Whenever you cast Can't Hit Me, you will gain ${[
          2,
          4,
          6,
          8,
        ]} stacks of Savin' Me Hide.\n\nSavin' Me Hide lasts 10 seconds and stacks up to 10 times. For the duration, gain 100% block chance and lose 1 stack each time you block.`,
      },
	  "Hold the Line": {
        name: "Hold the Line",
        pos: "e7",
        icon: icons["abi_cover"],
        maxRank: 1,
        reqPoints: 20,
        type: "passive",
        description: talentText`Groupmates within 50 feet behind you have Cover from all enemies up to 100 feet in front of you.\n\nCover reduces the damage of area of effect attacks by 25% in addition to providing immunity to some effects.`,
      },
	  "Band Together": {
        name: "Band Together",
        pos: "h7",
        icon: icons["abi_bandtogether"],
        maxRank: 5,
        reqPoints: 20,
        type: "passive",
        description: talentText`Groupmates within 30 feet of you will have their damage reduction increased by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%. This effect is supressed for 5 seconds whenever you are hit by a single-target ability.`,
      },
	  "Stop Muckin' About": {
        name: "Stop Muckin' About",
        pos: "e8",
        icon: icons["abi_or_figure04"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Whenever you cast Clobberin' Time, each groupmate within 65 feet of you will gain ${[
          1,
          2,
          3,
          4,
          5,
        ]} stacks of Savin' Me Hide.\n\nSavin' Me Hide lasts 10 seconds and stacks up to 10 times. For the duration, gain 100% block chance and lose 1 stack each time you block.`,
      },
    },
  },
  "Shotcalla": {
    name: "Shotcalla",
    background: backgrounds["warboss"],
    icon: icons["archetype_defsupport"],
    talents: {
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Increase your mass by 1.`,
      },
      "I'm Da Biggest": {
        name: "I'm Da Biggest",
        pos: "a2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Gain 500 + 25% wounds maximum health.`,
      },
      "Waaagh": {
        name: "Waaagh",
        pos: "b2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Da Waaagh calls, whenever you use a basic attack, all groupmates within 100 feet that have this tactic gain 1 Fightiness, gain 3 Pyschic Energy, lose 1 Cowardice, or lose 1 Paranoia.`,
      },
      "Scrappin' Time": {
        name: "Scrappin' Time ",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Fightin'is gettin' guud, Clobberin' Time now costs 5 less Fightiness.`,
      },
      "Guud at Big Choppin'": {
        name: "Guud at Big Choppin'",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Nothin' like a big scrap! You will now retain 0.5 times your block chance while under the effects of Clobberin' Time.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specexpertshield"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Shotcallas equip one-handed axes, shields, and two-handed axes.`,
      },
	  "Hedgehog": {
        name: "Hedgehog",
        pos: "f2",
        icon: icons["morale_hedgehog"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`All groupmates within 100ft gain 3 stacks of Enhanced Block.`,
      },
      "Champion's Challenge": {
        name: "Champion's Chalenge",
        pos: "g2",
        icon: icons["morale_grapple"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Applies a debuff to target enemy and yourself for 10 seconds. Movement speed is reduced to 0 for the duration.`,
      },
      "Distracting Bellow": {
        name: "Distracting Bellow",
        pos: "h2",
        icon: icons["morale_distractingbellow"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Up to 48 enemies within 30ft of you receive a debuff. For 10 seconds, they cannot benefit from Cover.`,
      },
      "Immaculate Defense": {
        name: "Immaculate Defense",
        pos: "i2",
        icon: icons["morale_immaculatedefense"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Groupmates within 100ft gain 25 stacks of a buff for 20 seconds. Each stack grants 3% damage reduction. A stack is removed each time they are attacked by an ability; 4 additional stacks are removed if the ability is single target.`,
      },
      "No Choppin' Me": {
        name: "No Choppin' Me",
        pos: "i4",
        icon: icons["abi_gs_canthitme"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "5.0s channel",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`You gain 100% block chance.`,
      },
      "Save Da Runts": {
        name: "Save Da Runts",
        pos: "i5",
        icon: icons["abi_gs_savedarunts"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Jump to target groupmates and apply 5 stacks of Savin' Me Hide to them.\n\nSavin' Me Hide lasts 10 seconds and stacks up to 10 times. For the duration, gain 100% block chance and lose 1 stack each time you block.`,
      },
      "Puddle O' Muck": {
        name: "Puddle O' Muck",
        pos: "i7",
        icon: icons["abi_gs_puddleomuck"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Up to 12 enemies within 30 feet of you gain Ensnared.\n\nEnsnared reduces your movement speed by 30% for 16 seconds.`,
      },
      "Gork iz 'Ere": {
        name: "Gork iz 'Ere",
        pos: "i8",
        icon: icons["abi_or_waaagh"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Gork w'll krump n' bash their 'eads for ya! For 30 seconds you gain 10 Fightiness per second, 100% outgoing damage, 50% damage reduction, and 1000 HP4. You'll die at the end of the duration and gain Forlorn.`,
      },
      "Fightiness": {
        name: "Fightiness",
        pos: "a1",
        icon: icons["abi_or_figure14"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Fightiness has a base of 0 and a max of 30. You lose 1 Fightiness any time you are hit by an ability that you do not block.`,
      },
      "Clobber": {
        name: "Clobber",
        pos: "b1",
        icon: icons["abi_gs_yernothin"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) A guud clobber, deals 4% MAP + 30 piercing damage to target enemy. Generates 22 action points.`,
      },
      "Clobberin' Time": {
        name: "Clobberin' Time",
        pos: "c1",
        icon: icons["abi_or_armor01"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Off the GCD\nCosts 25 Fightiness",
        description: talentText`You want to fight harder than ever! For 10 seconds you cannot block and will lose access to certain skills, but will enable your two-handed axe skills.`,
      },
      "Right in Da Jibblies": {
        name: "Right in Da Jibblies",
        pos: "d1",
        icon: icons["abi_or_crotch01"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "20 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled by Clobberin' Time",
        description: talentText`Wuts' fightin dirty? a scrap is a scrap. You deal 15% MAP + 204 impact damage to target enemy. Generates 2 Fightiness.`,
      },
      "Ability 1": {
        name: "Ability 1",
        pos: "e1",
        icon: icons["abi_gs_tuffernnails"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "6s cooldown",
        description: talentText`Target enemy gains 1 stack of Reduced Ballstic Skill, Reduced Intelligence, and Reduced Strength. Generates 2 Fightiness.`,
      },
      "Skull Thumper": {
        name: "Skull Thumper",
        pos: "f1",
        icon: icons["abi_gs_eadbutt"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Requires Clobberin' Time",
        description: talentText`A smash to the 'ead that deals 26% MAP + 348 impact damage to target enemy and apply 1 stack of Reduced Block to them.`,
      },
      "Outta' My Way": {
        name: "Outta' My Way",
        pos: "g1",
        icon: icons["abi_gs_walkitoff"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Disabled by Clobberin' Time",
        description: talentText`A guud bash of your shield knocks the enemy away and applies Immovable to them.\n\nImmovable prevents the application of Knockbacks, Pulls, and the Rooted status for 20 seconds.`,
      },
      "Knowhere ta' Go": {
        name: "Knowhere ta' Go",
        pos: "h1",
        icon: icons["abi_or_foot03"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled by Clobberin' Time",
        description: talentText`You swipe at their legs dealing 17% MAP + 227 impact damage and applies Ensnared and Momentum to target enemy.\n\nEnsanred reduced movement speed by 30% for 16 seconds.\nMomentum prevents the application of Ensnared for 8 seconds.`,
      },
      "Can't Hit Me": {
        name: "Can't Hit Me",
        pos: "i1",
        icon: icons["abi_or_shield01"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Shield up and gain a blessing for 8 seconds. Your block chance is increased by 50%.`,
      },
	  "Big Swing": {
        name: "Big Swing",
        pos: "h4",
        icon: icons["abi_gs_bigswing"],
        maxRank: 1,
        reqPoints: 5,
        type: "skill",
        cost: "60 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Requires Clobberin' Time",
        description: talentText`A maddening swing deals 10% MAP + 126 impact damage to up to 9 enemies within 30 feet in front of you.`,
      },
	  "Ability 2": {
        name: "Ability 2",
        pos: "g5",
        icon: icons["abi_gs_whereyougoing"],
        maxRank: 1,
        reqPoints: 10,
        type: "skill",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        blue: "Requires Clobberin' Time",
        description: talentText`Deals 15% MAP + 204 piercing damage to target enemy and applies Knocked-down and Unstoppable to them.\n\nKnocked-down prevents all control of your character for 3 seconds.\nUnstoppable prevents application of Knocked-down and Staggered for 30 seconds.`,
      },
	  "Follow Me Lead": {
        name: "Follow Me Lead",
        pos: "c6",
        icon: icons["abi_gs_followmelead"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "60 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`All groupmates within 100 feet of you gain an enchantment for 5 seconds. For the duration they will gain 5 action points per second and 5 adrenaline per second.`,
      },
	  "Big Scrappin": {
        name: "Big Scrappin",
        pos: "c8",
        icon: icons["abi_gs_dabigun"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "80 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Requires Clobberin' Time",
        description: talentText`Knocks away up to 9 enemies within 20 feet target enemy and applies Immovable to them. Apply an ailment to target enemy for 10 seconds. For the duration, their outgoing damage is decreased by 15%.\n\nImmovable prevents the application of Knockbacks, Pulls, and the Rooted status for 20 seconds.`,
      },
      "Ability 3": {
        name: "Ability 3",
        pos: "d9",
        icon: icons["abi_gs_canttouchus"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled by Clobberin' Time",
        description: talentText`Deal 15% MAP + 204 piercing damage to target enemy. Your defensive target gains 1 stack of Savin' Me Hide and a 5 second enchantment. For the duration, target absorbs up to 14% RP + 166 damage. Generates 1 Fightiness.`,
      },
      "Waaagh!": {
        name: "Waagh!",
        pos: "f9",
        icon: icons["abi_gs_waaagh"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "150 action points",
        range: "self",
        cast: "2.0s channel",
        cooldown: "30s cooldown",
        description: talentText`A rampaging bellow that interrupts up to 48 enemies who do not have Cover from you within 30 feet every 0.5 seconds. Whenever you successfully interrupt an enemy, you will deal 10% MAP + 50 ichor damage to them and up to 17 other enemies within 20 feet of them.`,
      },
	  "Keep It Goin'": {
        name: "Keep It Goin'",
        pos: "a5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Outta My Way, Knowhere ta Go, and Distract now generates 1 Fightiness.`,
      },
	  "Tactic 2": {
        name: "Tactic 2",
        pos: "c5",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`When you cast Ability 1 or Follow Me Lead, all groupmates within 100 feet gain 1 stack of Savin' Me Hide.`,
      },
	  "Big Brawlin'": {
        name: "Big Brawlin'",
        pos: "e6",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Skull Thumper now applies 1 stack of Reduced Fortitude and 1 stack of Reduced Agility to the target.`,
      },
	  "Tactic 1": {
        name: "Tactic 1",
        pos: "b6",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Ability 1 will now apply to up to 8 other enemies within 30 feet of you.`,
      },
	  "You'z See Me Block Dat?!": {
        name: "You'z See Me Block Dat?!",
        pos: "a7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Whenever you block an attack, you will deal 6% MAP + 90 impact damage to up to 9 enemies within 30 feet of you and gain 1 Fightiness. This effect cannot happen more than once every 2 seconds.`,
      },
	  "'Ead Bashers": {
        name: "'Ead Bashers",
        pos: "h7",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Big Swing",
		arrows: [
          { dir: "down", from: "h4", to: "h7" },
        ],
        type: "career tactic",
        description: talentText`Big Swing will now grant 1 stack of Enhanced Strength to all groupmates within 100 feet of you.`,
      },
	  "Good Wif Shield": {
        name: "Good Wif Shield",
        pos: "g8",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Whenever you block an attack, you will gain 15% damage reduction for 5 seconds. Big Swing will now cost 10 less action points.`,
      },
	  "Passive 1": {
        name: "Passive 1",
        pos: "e3",
        icon: icons["abi_or_face19"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever you gain Fightiness, apply 1 stack of Savin' Me Hide to up to ${[
          1,
          2,
          3,
          4,
          5,
        ]} groupmates within 100 feet of you.`,
      },
	  "Passive 2": {
        name: "Passive 2",
        pos: "b4",
        icon: icons["abi_gs_followmelead"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Ability 1 and Follow Me Lead cost ${[
          4,
          8,
          12,
          16,
          20,
        ]} less action points.`,
      },
	  "Passive 3": {
        name: "Passive 3",
        pos: "d6",
        icon: icons["abi_gs_yernothin"],
        maxRank: 3,
        reqPoints: 15,
        type: "passive",
        description: talentText`Clobber has a ${[
          33,
          66,
          100,
        ]}% chance to generate 1 Fightiness.`,
      },
	  "Savin' Me Hide": {
        name: "Savin' Me Hide",
        pos: "f6",
        icon: icons["abi_or_face19"],
        maxRank: 4,
        reqPoints: 15,
        type: "passive",
        description: talentText`Whenever you cast Can't Hit Me, you will gain ${[
          2,
          4,
          6,
          8,
        ]} stacks of Savin' Me Hide.\n\nSavin' Me Hide lasts 10 seconds and stacks up to 10 times. For the duration, gain 100% block chance and lose 1 stack each time you block.`,
      },
	  "Hold the Line": {
        name: "Hold the Line",
        pos: "b7",
        icon: icons["abi_cover"],
        maxRank: 1,
        reqPoints: 20,
        type: "passive",
        description: talentText`Groupmates within 50 feet behind you have Cover from all enemies up to 100 feet in front of you.\n\nCover reduces the damage of area of effect attacks by 25% in addition to providing immunity to some effects.`,
      },
	  "Band Together": {
        name: "Band Together",
        pos: "e7",
        icon: icons["abi_bandtogether"],
        maxRank: 5,
        reqPoints: 20,
        type: "passive",
        description: talentText`Groupmates within 30 feet of you will have their damage reduction increased by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%. This effect is supressed for 5 seconds whenever you are hit by a single-target ability.`,
      },
	  "Passive 4": {
        name: "Passive 4",
        pos: "e8",
        icon: icons["abi_gs_stealyerthunder"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Savin' Me Hide has a ${[
          15,
          30,
          45,
          60,
        ]}% chance to apply 1 stack of Enhanced Piercing, Impact, or Ichor Resistance each time the target blocks.`,
      },
    },
  },
  "Butcha": {
    name: "Butcha",
    background: backgrounds["butcha"],
    icon: icons["archetype_dps"],
    talents: {
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 1,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Increase your mass by 1.`,
      },
      "I'm Da Biggest": {
        name: "I'm Da Biggest",
        pos: "a2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Gain 500 + 25% wounds maximum health.`,
      },
      "Waaagh": {
        name: "Waaagh",
        pos: "b2",
        icon: icons["tac_race_green"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Da Waaagh calls, whenever you use a basic attack, all groupmates within 100 feet that have this tactic gain 1 Fightiness, gain 3 Pyschic Energy, lose 1 Cowardice, or lose 1 Paranoia.`,
      },
      "Scrappin' Time": {
        name: "Scrappin' Time ",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Fightin'is gettin' guud, Clobberin' Time now costs 5 less Fightiness.`,
      },
      "Guud at Big Choppin'": {
        name: "Guud at Big Choppin'",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Nothin' like a big scrap! You will now retain 0.5 times your block chance while under the effects of Clobberin' Time.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specaxe"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Butchas dual wield one-handed axes and have a two-handed axe.`,
      },
	  "Sever Nerve": {
        name: "Sever Nerve",
        pos: "f2",
        icon: icons["morale_severnerve"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Deals 50% MAP + 400 physical damage to the target.`,
      },
      "Broad Swings": {
        name: "Broad Swings",
        pos: "g2",
        icon: icons["morale_broadswings"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a  buff for 10 seconds. Your single target abilities will target two additional enemies within 15ft in front of you.`,
      },
      "Force of Will": {
        name: "Force of Will",
        pos: "h2",
        icon: icons["morale_forceofwill"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 10 seconds. Action point costs are reduced by 75% for the duration.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "Morale 1 Class": {
        name: "Morale 1 Class",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 2 Spec": {
        name: "Morale 2 Spec",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Puddle O' Muck": {
        name: "Puddle O' Muck",
        pos: "i7",
        icon: icons["abi_gs_puddleomuck"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Up to 12 enemies within 30 feet of you gain Ensnared.\n\nEnsnared reduces your movement speed by 30% for 16 seconds.`,
      },
      "Gork iz 'Ere": {
        name: "Gork iz 'Ere",
        pos: "i8",
        icon: icons["abi_or_waaagh"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Gork w'll krump n' bash their 'eads for ya! For 30 seconds you gain 10 Fightiness per second, 100% outgoing damage, 50% damage reduction, and 1000 HP4. You'll die at the end of the duration and gain Forlorn.`,
      },
      "Fightiness": {
        name: "Fightiness",
        pos: "a1",
        icon: icons["abi_or_figure14"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Fightiness has a base of 0 and a max of 30. You lose 1 Fightiness any time you are hit by an ability that you do not block.`,
      },
      "Clobber": {
        name: "Clobber",
        pos: "b1",
        icon: icons["abi_gs_yernothin"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) A guud clobber, deals 4% MAP + 30 piercing damage to target enemy. Generates 22 action points.`,
      },
      "Clobberin' Time": {
        name: "Clobberin' Time",
        pos: "c1",
        icon: icons["abi_or_armor01"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Off the GCD\nCosts 25 Fightiness",
        description: talentText`You want to fight harder than ever! For 10 seconds you cannot block and will lose access to certain skills, but will enable your two-handed axe skills.`,
      },
      "Right in Da Jibblies": {
        name: "Right in Da Jibblies",
        pos: "d1",
        icon: icons["abi_or_crotch01"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "20 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled by Clobberin' Time",
        description: talentText`Wuts' fightin dirty? a scrap is a scrap. You deal 15% MAP + 204 impact damage to target enemy. Generates 2 Fightiness.`,
      },
      "Skull Thumper": {
        name: "Skull Thumper",
        pos: "e1",
        icon: icons["abi_gs_eadbutt"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Requires Clobberin' Time",
        description: talentText`A smash to the 'ead that deals 26% MAP + 348 impact damage to target enemy and apply 1 stack of Reduced Block to them.`,
      },
      "Ability 4": {
        name: "Ability 4",
        pos: "f1",
        icon: icons["abi_or_figure13"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "25 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "6s cooldown",
        description: talentText`Target ally gains 1 stack of Enhanced Critical Chance.`,
      },
      "Ability 2": {
        name: "Ability 2",
        pos: "g1",
        icon: icons["abi_gs_whereyougoing"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        blue: "Requires Clobberin' Time",
        description: talentText`Deals 15% MAP + 204 piercing damage to target enemy and applies Knocked-down and Unstoppable to them.\n\nKnocked-down prevents all control of your character for 3 seconds.\nUnstoppable prevents application of Knocked-down and Staggered for 30 seconds.`,
      },
      "Ability 5": {
        name: "Ability 5",
        pos: "h1",
        icon: icons["abi_or_melee19"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled by Clobberin' Time",
        description: talentText`Applies a 10 second affliction to target enemy. Every 2 seconds, deals 9% MAP + 126 ichor damage and applies Bleeding.\n\nBleeding is a status effect that lasts for 8 seconds and deals 2% MAP + 10 ichor damage every second.`,
      },
      "Can't Hit Me": {
        name: "Can't Hit Me",
        pos: "i1",
        icon: icons["abi_or_shield01"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Shield up and gain a blessing for 8 seconds. Your block chance is increased by 50%.`,
      },
	  "Big Swing": {
        name: "Big Swing",
        pos: "h4",
        icon: icons["abi_gs_bigswing"],
        maxRank: 1,
        reqPoints: 5,
        type: "skill",
        cost: "60 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Requires Clobberin' Time",
        description: talentText`A maddening swing deals 10% MAP + 126 impact damage to up to 9 enemies within 30 feet in front of you.`,
      },
	  "Ability 6": {
        name: "Ability 6",
        pos: "c5",
        icon: icons["abi_or_melee13"],
        maxRank: 1,
        reqPoints: 10,
        type: "skill",
        cost: "30 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Requires Clobberin' Time",
        description: talentText`Applies a 6 second affliction to target enemy. At the end of the duration, deals 25% MAP + 312 ichor damage to target.`,
      },
	  "Chop Fasta": {
        name: "Chop Fasta",
        pos: "e6",
        icon: icons["abi_or_melee09"],
        maxRank: 1,
        reqPoints: 15,
        type: "skill",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
		blue: "Disabled by Clobberin' Time",
        description: talentText`Deals 18% MAP + 222 piercing damage to target enemy and up to 2 other enemies within 20 feet of them.`,
      },
	  "Ability 7": {
        name: "Ability 7",
        pos: "e8",
        icon: icons["abi_or_melee08"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Disabled by Clobberin' Time",
        description: talentText`Applies 5 stacks of a 10 second ailment to target enemy. Each time the enemy is hit by an ability, they take 5% MAP + 73 piercing damage and lose a stack.`,
      },
      "Ability 8": {
        name: "Ability 8",
        pos: "d9",
        icon: icons["abi_or_furiouschoppin"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "60 action points",
        range: "8ft range",
        cast: "2.5s channel",
        cooldown: "no cooldown",
        blue: "Requires Clobberin' Time\nCastable While Moving",
        description: talentText`Deals 13% MAP + 182 piercing damage every 0.5 seconds to target enemy.`,
      },
      "Waaagh!": {
        name: "Waagh!",
        pos: "f9",
        icon: icons["abi_gs_waaagh"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "150 action points",
        range: "self",
        cast: "2.0s channel",
        cooldown: "30s cooldown",
        description: talentText`A rampaging bellow that interrupts up to 48 enemies who do not have Cover from you within 30 feet every 0.5 seconds. Whenever you successfully interrupt an enemy, you will deal 10% MAP + 50 ichor damage to them and up to 17 other enemies within 20 feet of them.`,
      },
	  "Bleed Out": {
        name: "Bleed Out",
        pos: "a5",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Your Bleeding effect can now stack up to 3 times on a target. In addition, whenever Bleedign expires it has a 20% chance to reapply.`,
      },
	  "Tactic 7": {
        name: "Tactic 7",
        pos: "b5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`You gain 50% of your block chance as accuracy while in Clobberin' Time.`,
      },
	  "Tactic 3": {
        name: "Tactic 3",
        pos: "d6",
        icon: icons["tac_spec_1"],
        maxRank: 3,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Ability 4 will also apply 1 stack of Enhanced Weaponskill. In addition, it now always applies to you in addition to your target.`,
      },
	  "Tactic 4": {
        name: "Tactic 4",
        pos: "f6",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Ability 2 will now apply Marked to the target.\n\nMarked reduces the target's damage reduction by 15% for 10 seconds.`,
      },
	  "Tactic 5": {
        name: "Tactic 5",
        pos: "e7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Chop Fasta",
		arrows: [
          { dir: "down", from: "e6", to: "e7" },
        ],
        type: "career tactic",
        description: talentText`Chop Fasta and Big Swing will now hit up to 24 enemies. Chop Fasta will now deal 50% less damage.`,
      },
	  "Big Brawlin'": {
        name: "Big Brawlin'",
        pos: "a7",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Skull Thumper now applies 1 stack of Reduced Fortitude and 1 stack of Reduced Agility to the target.`,
      },
	  "Tactic 6": {
        name: "Tactic 6",
        pos: "g8",
        icon: icons["tac_spec_1"],
        maxRank: 5,
        reqPoints: 25,
        prereq: "Ability 7",
		arrows: [
          { dir: "right", from: "e8", to: "g8" },
        ],
        type: "career tactic",
        description: talentText`Ability 7 now applies 10 stacks.`,
      },
	  "Passive 5": {
        name: "Passive 5",
        pos: "e3",
        icon: icons["abi_gs_eadbutt"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`You have a ${[
          12.5,
          25,
          37.5,
          50,
        ]}% chance when hit to not lose Fightiness.`,
      },
	  "Improved Basic Attack": {
        name: "Improved Basic Attack",
        pos: "b4",
        icon: icons["abi_or_melee15"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Your basic attack will deal ${[
          75,
          150,
          225,
          300,
          375,
        ]}% additional damage.`,
      },
	  "Passive 6": {
        name: "Passive 6",
        pos: "e5",
        icon: icons["abi_or_melee19"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Ability 5 has a ${[
          50,
          100,
        ]}% chance to hit an additional target within 20 feet.`,
      },
	  "Passive 7": {
        name: "Passive 7",
        pos: "c6",
        icon: icons["abi_or_melee13"],
        maxRank: 4,
        reqPoints: 15,
        prereq: "Ability 6",
		arrows: [
          { dir: "down", from: "c5", to: "c6" },
        ],
        type: "passive",
        description: talentText`Ability 6 deals ${[
          5,
          10,
          15,
          20,
        ]}% more damage.`,
      },
	  "Passive 3": {
        name: "Passive 3",
        pos: "g6",
        icon: icons["abi_gs_yernothin"],
        maxRank: 3,
        reqPoints: 15,
        type: "passive",
        description: talentText`Clobber has a ${[
          33,
          66,
          100,
        ]}% chance to generate 1 Fightiness.`,
      },
	  "Passive 9": {
        name: "Passive 9",
        pos: "b7",
        icon: icons["abi_or_throatslasha"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`${[
          "Ability 5",
          "Ability 5 and Ability 6",
          "Abilty 5, Ability 6, and Ability 7",
        ]} now classify as a cripple.`,
      },
	  "Passive 8": {
        name: "Passive 8",
        pos: "h7",
        icon: icons["abi_gs_bigswing"],
        maxRank: 3,
        reqPoints: 20,
        prereq: "Big Swing",
		arrows: [
          { dir: "down", from: "h4", to: "h7" },
        ],
        type: "passive",
        description: talentText`Big Swing deals ${[
          5,
          10,
          15,
        ]}% more damage.`,
      },
	  "Passive 10": {
        name: "Passive 10",
        pos: "c8",
        icon: icons["abi_or_armor01"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Whenever you activate Clobberin' Time, you will gain ${[
          10,
          20,
          35,
          50,
        ]}% outgoing damage for 4 seconds.`,
      },
    },
  },
};