import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/druchii"),
);
const icons = requireAll(require.context("../../assets/icons/darkelf"));

export const data: TalentData = {
  "Dominator of Ulgu": {
    name: "Dominator of Ulgu",
    background: backgrounds["ulgu"],
    icon: icons["archetype_dps"],
    talents: {
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 1,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 1,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "Alignment of Naggaroth": {
        name: "Alignment of Naggaroth",
        pos: "a2",
        icon: icons["tac_race_delf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that have this tactic will gain 670 critical hit rating for 4 seconds.`,
      },
      "Bathing in Blood": {
        name: "Bathing in Blood",
        pos: "b2",
        icon: icons["tac_race_delf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You are healed for 7% of all damage you deal.`,
      },
      "Empowered Dhar": {
        name: "Empowered Dhar",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you hit an enemy with an augmented spell, you will dispel one enchantment from them.`,
      },
      "Tapping the Dark": {
        name: "Tapping the Dark",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Reduces the cast time of Doombolt by 1 second.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specstaff"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Dominators of Ulgu equip staves.`,
      },
      "Hunter's Trap": {
        name: "Hunter's Trap",
        pos: "i4",
        icon: icons["abi_he_ensnare"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Applies Rooted and Immovable to target enemy.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nImmovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Shroud of Darkness": {
        name: "Shroud of Darkness",
        pos: "i5",
        icon: icons["abi_de_darkstarcloak"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Target ally gains a buff for 5 seconds. Each second, they will gain 1 stack of Enhanced Piercing Resistance, Enhanced Impact Resistance, Enhanced Ichor Resistance, Enhanced Corporeal Resistance, Enhanced Elemental Resistance, and Enhanced Spiritual Resistance.`,
      },
      "Murderous Prowess": {
        name: "Murderous Prowess",
        pos: "i7",
        icon: icons["abi_de_gripofanger"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain 50% critical hit chance and accuracy for 20 seconds.`,
      },
      "Winter's Frost": {
        name: "Winter's Frost",
        pos: "i8",
        icon: icons["abi_de_shadowspike"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 24 enemies within a 20 foot area you select become Rooted, Silenced, and Disarmed.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nSilenced prevents the use of spells for 5 seconds.\nDisarmed prevents the use of skills for 5 seconds.`,
      },
	  "Disengage": {
        name: "Disengage",
        pos: "f2",
        icon: icons["morale_disengage"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`You knock yourself back away from target enemy.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Explosive Impact": {
        name: "Explosive Impact",
        pos: "h2",
        icon: icons["morale_explosiveimpact"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 10 seconds. Whenever you hit a target with a single-target ability, you will deal 10% RAP + 150 corporeal damage and 10% SAP + 150 elemental damage to up to 24 enemies within 20ft of the target.`,
      },
      "Unleash the Winds": {
        name: "Unleash the Winds",
        pos: "i2",
        icon: icons["morale_unleashthewinds"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 96 enemies within a 20ft location you select are knocked straight up into the air.`,
      },
      "Winds of Magic": {
        name: "Winds of Magic",
        pos: "a1",
        icon: icons["abi_he_stormofcronos"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Every 3 seconds, you will gain 1 stack of a wind of magic at random (Shadow, Beast, and Death) stacking up to a maximum of 3. Whenever you cast a spell of that lore of magic, it will consume one stack, if present, and augment the spell.\n\nYou have access to a no cost, no cooldown toggle ability which prevents you from using winds of magic while active.`,
      },
      "Bladewind": {
        name: "Bladewind",
        pos: "b1",
        icon: icons["abi_de_chillwind"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 6% SAP + 133 spiritual damage to target enemy. Generates 40 action points.`,
      },
      "Doombolt": {
        name: "Doombolt",
        pos: "c1",
        icon: icons["abi_de_doombolt"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "36 action points",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        description: talentText`Deals 55% SAP + 744 spiritual damage to target enemy.`,
      },
      "Word of Pain": {
        name: "Word of Pain",
        pos: "d1",
        icon: icons["abi_de_dreadaspect"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Applies an affliction to target enemy for 10 seconds. At the end of the duration, target will take 23% SAP + 311 spiritual damage.`,
      },
      "Gloom": {
        name: "Gloom",
        pos: "e1",
        icon: icons["abi_de_gloomburst"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "65 action points",
        range: "100ft range",
        cast: "1.5s cast",
        cooldown: "no cooldown",
        blue: "Lore of Shadow",
        description: talentText`Deals 27% SAP + 371 spiritual damage to target enemy.\n\nAugmented: ability is now instant cast.`,
      },
      "Curse of Anraheir": {
        name: "Curse of Anraheir",
        pos: "f1",
        icon: icons["abi_de_disastrouscascade"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "100ft range",
        cast: "1.0s cast",
        cooldown: "no cooldown",
        blue: "Lore of Beast",
        description: talentText`Deals 10% SAP + 145 corporeal damage to target enemy and applies 1 stack of Reduced Strength.\n\nAugmented: applies 1 stack of Reduced Toughness and Reduced Corporeal Resistance.`,
      },
      "Choking Shadows": {
        name: "Choking Shadows",
        pos: "g1",
        icon: icons["abi_de_chokingfury"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "45 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Lore of Shadow",
        description: talentText`Applies Silenced and Inevitable to target enemy.\n\nAugmented: Applies Ensnared and Momentum as well.\n\nSilenced prevents the use of spells for 5 seconds.\nInevitable prevents the application of Disarmed and Silenced for 20 seconds.\nEnsnared reduces movement speed by 30% for 16 seconds.\nMomentum prevents the application of Ensnared for 8 seconds.`,
      },
      "Soul Harvest": {
        name: "Soul Harvest",
        pos: "h1",
        icon: icons["abi_de_absorbvitality"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "1.75s cast",
        cooldown: "no cooldown",
        blue: "Lore of Death",
        description: talentText`Applies an affliction to target enemy for 15 seconds. Every 3 seconds, the target will take 12% SAP + 175 spiritual damage and your defensive target will be healed for 100% of the damage dealt.\n\nAugmented: ability is now instant cast and applies a blessing.`,
      },
      "Boar's Hide": {
        name: "Boar's Hide",
        pos: "i1",
        icon: icons["abi_de_shroudingdarkness"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "40s cooldown",
        blue: "Lore of Beast",
        description: talentText`Your damage reduction is increased by 50% and your cast times are increased by 33% for 4 seconds.\n\nAugmented: cooldown is reduced to 20 seconds.`,
      },
	  "Ashes and Dust": {
        name: "Ashes and Dust",
        pos: "h4",
        icon: icons["abi_de_shatteredshadows"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "75 action points",
        range: "100ft range",
        cast: "2.5s cast",
        cooldown: "no cooldown",
        blue: "Lore of Death",
        description: talentText`Deals 18% SAP + 240 spiritual damage to up to 9 enemies within a 30 foot area you select.\n\nAugmented: cast time is reduced by 1.5 seconds.`,
      },
	  "Mockery of Death": {
        name: "Mockery of Death",
        pos: "a5",
        icon: icons["abi_de_gloomofnight"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "1.5s cast",
        cooldown: "no cooldown",
        blue: "Lore of Death",
        description: talentText`Applies an ailment to target enemy for 10 seconds. Whenever the target is healed, you will deal 9% SAP + 128 spiritual damage to the healer.\n\nAugmented: effect is now a cripple and will deal 25% damage to target as well.`,
      },
	  "Pit of Shades": {
        name: "Pit of Shades",
        pos: "b6",
        icon: icons["abi_de_pitofshades"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "75 action points",
        range: "100ft range",
        cast: "6.0s channel",
        cooldown: "no cooldown",
        blue: "Lore of Shadow",
        description: talentText`Every second, deals 6% SAP + 67 spiritual damage to up to 9 enemies within a 20 foot area you select.\n\nAugmented: tick interval is now every 0.66 seconds.`,
      },
	  "Arnzipal's Black Horror": {
        name: "Arnzipal's Black Horror",
        pos: "h8",
        icon: icons["abi_de_blackhorror"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "40 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Applies an enchantment to target ally for 15 seconds. Whenever they are attacked, you will deal 7% SAP + 89 corporeal damage to the attacker.`,
      },
      "Shadow Bolt": {
        name: "Shadow Bolt",
        pos: "d9",
        icon: icons["abi_de_cataclysmicdarkness"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "60 action points",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Lore of Shadow",
        description: talentText`Deals 38% SAP + 506 spiritual damage to target enemy and 2 additional enemies within 20 feet.\n\nAugmented: Deals an additional 22% SAP + 305 spiritual damage instead.`,
      },
      "Power of Darkness": {
        name: "Power of Darkness",
        pos: "f9",
        icon: icons["abi_de_echoofpower"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "65ft range",
        cast: "3.0s channel",
        cooldown: "30s cooldown",
        description: talentText`Every 0.5 seconds, deals 5% SAP + 50 spiritual damage to up to 48 enemies within a 30 foot area you select. Each time you strike an enemy you will gain a stack of a buff that grants 10% outgoing damage per stack up to a maximum of 100 stacks that lasts 1 second. Will not hit enemies who have Cover from you.`,
      },
	  "Neverending Agony": {
        name: "Neverending Agony",
        pos: "b5",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Mockery of Death",
		arrows: [
          { dir: "right", from: "a5", to: "b5" },
        ],
        type: "career tactic",
        description: talentText`Mockery of Death now applies a -33% outgoing healing debuff.`,
      },
	  "Vision of Domination": {
        name: "Vision of Domination",
        pos: "g5",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Word of Pain is now a cripple with a 6 second duration.`,
      },
	  "Doom and Gloom": {
        name: "Doom and Gloom",
        pos: "d6",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Gloom applies a cripple to target for 4 seconds. Whenever they take damage from Doombolt or Shadow Bolt, up to 2 additional enemies within 20 feet will take Gloom damage.`,
      },
	  "Grip of Fear": {
        name: "Grip of Fear",
        pos: "f6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Curse of Anraheir's augmented effect now applies to up to 23 additional enemies within 30 feet of the target.`,
      },
	  "Echo of Power": {
        name: "Echo of Power",
        pos: "a7",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Whenever you augment a Lore of Shadow spell, you will gain 12% critical chance for 5 seconds.`,
      },
	  "Shadow of Disaster": {
        name: "Shadow of Disaster",
        pos: "c7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Pit of Shades",
		arrows: [
          { dir: "right-down", from: "b6", to: "c6" },
          { dir: "right-down-down", from: "c6", to: "c7" }
        ],
        type: "career tactic",
        description: talentText`Pit of Shades and Ashes and Dust will now hit up to 24 enemies.`,
      },
	  "Master of Ulgu": {
        name: "Master of Ulgu",
        pos: "b8",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Every 5 seconds, you generate 1 Wind of Shadow.`,
      },
	  "Embodiment of Ulgu": {
        name: "Embodiment of Ulgu",
        pos: "e3",
        icon: icons["abi_de_gripoffear"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever you augment a Lore of Shadow spell, you will gain ${[
          3,
          6,
          9,
          12,
          15,
        ]}% dodge for 5 seconds.`,
      },
	  "Improved Boar's Hide": {
        name: "Improved Boar's Hide",
        pos: "b4",
        icon: icons["abi_de_shroudingdarkness"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Boar's hide now lasts ${[
          5,
          6,
          7,
          8,
        ]} seconds.`,
      },
	  "Improved Bladewind": {
        name: "Improved Bladewind",
        pos: "e5",
        icon: icons["abi_de_chillwind"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Bladewind will now generate ${[
          46,
          52,
          58,
          64,
        ]} action points.`,
      },
	  "Improved Ashes and Dust": {
        name: "Improved Ashes and Dust",
        pos: "h6",
        icon: icons["abi_de_shatteredshadows"],
        maxRank: 2,
        reqPoints: 15,
        prereq: "Ashes and Dust",
		arrows: [
          { dir: "down", from: "h4", to: "h6" },
        ],
        type: "passive",
        description: talentText`Ashes and Dust will now deal ${[
          5,
          10,
        ]}% more damage.`,
      },
	  "Improved Word of Pain": {
        name: "Passive 4",
        pos: "e6",
        icon: icons["abi_de_dreadaspect"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Word of Pain will now deal ${[
          5,
          10,
          15,
          20,
          25,
        ]}% more damage.`,
      },
	  "Swift Passing": {
        name: "Swift Passing",
        pos: "e7",
        icon: icons["noicon"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`You deal ${[
          5,
          10,
          15,
        ]}% more damage against enemies under 40% health.`,
      },
	  "Extra Crit": {
        name: "Extra Crit",
        pos: "g7",
        icon: icons["abi_extracrit"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Your chance to critically hit is increased by ${[
          2,
          4,
		  6,
        ]}%.`,
	  },
	  "Horn of Andar": {
        name: "Horn of Andar",
        pos: "e8",
        icon: icons["abi_de_recklessgathering"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Whenever you critically hit with a single-target ability, you have a ${[
          10,
          30,
          60,
          100,
        ]}% chance to gain 1 stack of Enhanced Potency.`,
      },
    },
  },
  "Dominator of Ghur": {
    name: "Dominator of Ghur",
    background: backgrounds["ghur"],
    icon: icons["archetype_offsupport"],
    talents: {
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 1,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "What a Rush": {
        name: "What a Rush",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`The action point cost of your skills is reduced by 33% on allies that are lower than 40% health.`,
      },
      "Alignment of Naggaroth": {
        name: "Alignment of Naggaroth",
        pos: "a2",
        icon: icons["tac_race_delf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that have this tactic will gain 670 critical hit rating for 4 seconds.`,
      },
      "Bathing in Blood": {
        name: "Bathing in Blood",
        pos: "b2",
        icon: icons["tac_race_delf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You are healed for 7% of all damage you deal.`,
      },
      "Empowered Dhar": {
        name: "Empowered Dhar",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you hit an enemy with an augmented spell, you will dispel one enchantment from them.`,
      },
      "Tapping the Dark": {
        name: "Tapping the Dark",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Reduces the cast time of Doombolt by 1 second.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specpolearm"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Adepts of Ghur equip two-handed spears.`,
      },
      "Hunter's Trap": {
        name: "Hunter's Trap",
        pos: "i4",
        icon: icons["abi_he_ensnare"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Applies Rooted and Immovable to target enemy.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nImmovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Shroud of Darkness": {
        name: "Shroud of Darkness",
        pos: "i5",
        icon: icons["abi_de_darkstarcloak"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Target ally gains a buff for 5 seconds. Each second, they will gain 1 stack of Enhanced Piercing Resistance, Enhanced Impact Resistance, Enhanced Ichor Resistance, Enhanced Corporeal Resistance, Enhanced Elemental Resistance, and Enhanced Spiritual Resistance.`,
      },
      "Murderous Prowess": {
        name: "Murderous Prowess",
        pos: "i7",
        icon: icons["abi_de_gripofanger"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain 50% critical hit chance and accuracy for 20 seconds.`,
      },
      "Winter's Frost": {
        name: "Winter's Frost",
        pos: "i8",
        icon: icons["abi_de_shadowspike"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 24 enemies within a 20 foot area you select become Rooted, Silenced, and Disarmed.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nSilenced prevents the use of spells for 5 seconds.\nDisarmed prevents the use of skills for 5 seconds.`,
      },
	  "Disengage": {
        name: "Disengage",
        pos: "f2",
        icon: icons["morale_disengage"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`You knock yourself back away from target enemy.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Explosive Impact": {
        name: "Explosive Impact",
        pos: "h2",
        icon: icons["morale_explosiveimpact"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 10 seconds. Whenever you hit a target with a single-target ability, you will deal 10% RAP + 150 corporeal damage and 10% SAP + 150 elemental damage to up to 24 enemies within 20ft of the target.`,
      },
      "Unleash the Winds": {
        name: "Unleash the Winds",
        pos: "i2",
        icon: icons["morale_unleashthewinds"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 96 enemies within a 20ft location you select are knocked straight up into the air.`,
      },
      "Winds of Magic": {
        name: "Winds of Magic",
        pos: "a1",
        icon: icons["abi_he_stormofcronos"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Every 3 seconds, you will gain 1 stack of a wind of magic at random (Shadow, Beast, and Death) stacking up to a maximum of 3. Whenever you cast a spell of that lore of magic, it will consume one stack, if present, and augment the spell.\n\nYou have access to a no cost, no cooldown toggle ability which prevents you from using winds of magic while active.`,
      },
      "Bladewind": {
        name: "Bladewind",
        pos: "b1",
        icon: icons["abi_de_chillwind"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 6% SAP + 133 spiritual damage to target enemy. Generates 40 action points.`,
      },
      "Doombolt": {
        name: "Doombolt",
        pos: "c1",
        icon: icons["abi_de_doombolt"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "36 action points",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        description: talentText`Deals 55% SAP + 744 spiritual damage to target enemy.`,
      },
      "Curse of Anraheir": {
        name: "Curse of Anraheir",
        pos: "d1",
        icon: icons["abi_de_disastrouscascade"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "100ft range",
        cast: "1.0s cast",
        cooldown: "no cooldown",
        blue: "Lore of Beast",
        description: talentText`Deals 10% SAP + 145 corporeal damage to target enemy and applies 1 stack of Reduced Strength.\n\nAugmented: applies 1 stack of Reduced Toughness and Reduced Corporeal Resistance.`,
      },
      "Word of Pain": {
        name: "Word of Pain",
        pos: "e1",
        icon: icons["abi_de_dreadaspect"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Applies an affliction to target enemy for 10 seconds. At the end of the duration, target will take 23% SAP + 311 spiritual damage.`,
      },
      "Mockery of Death": {
        name: "Mockery of Death",
        pos: "f1",
        icon: icons["abi_de_gloomofnight"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "1.5s cast",
        cooldown: "no cooldown",
        blue: "Lore of Death",
        description: talentText`Applies an ailment to target enemy for 10 seconds. Whenever the target is healed, you will deal 9% SAP + 128 spiritual damage to the healer.\n\nAugmented: effect is now a cripple and will deal 25% damage to target as well.`,
      },
      "Choking Shadows": {
        name: "Choking Shadows",
        pos: "g1",
        icon: icons["abi_de_chokingfury"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "45 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Lore of Shadow",
        description: talentText`Applies Silenced and Inevitable to target enemy.\n\nAugmented: Applies Ensnared and Momentum as well.\n\nSilenced prevents the use of spells for 5 seconds.\nInevitable prevents the application of Disarmed and Silenced for 20 seconds.\nEnsnared reduces movement speed by 30% for 16 seconds.\nMomentum prevents the application of Ensnared for 8 seconds.`,
      },
      "Gloom": {
        name: "Gloom",
        pos: "h1",
        icon: icons["abi_de_gloomburst"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "65 action points",
        range: "100ft range",
        cast: "1.5s cast",
        cooldown: "no cooldown",
        blue: "Lore of Shadow",
        description: talentText`Deals 27% SAP + 371 spiritual damage to target enemy.\n\nAugmented: ability is now instant cast.`,
      },
      "Pann's Impenetrable Pelt": {
        name: "Pann's Impenetrable Pelt",
        pos: "i1",
        icon: icons["abi_de_whirlinglaceration"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "30 action points",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Lore of Beasts",
        description: talentText`Applies 1 stack of Enhanced Piercing Resistance, 1 stack of Enhanced Ichor Resistance, 1 stack of Enhanced Block, and 1 stack of Reduced Impact Resistance to target ally.\n\nAugmented: applies an 8 second enchantment as well. For the duration, target's damage reduction is increased by 20%.`,
      },
	  "Ashes and Dust": {
        name: "Ashes and Dust",
        pos: "g4",
        icon: icons["abi_de_shatteredshadows"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "75 action points",
        range: "100ft range",
        cast: "2.5s cast",
        cooldown: "no cooldown",
        blue: "Lore of Death",
        description: talentText`Deals 18% SAP + 240 spiritual damage to up to 9 enemies within a 30 foot area you select.\n\nAugmented: cast time is reduced by 1.5 seconds.`,
      },
	  "Arnzipal's Black Horror": {
        name: "Arnzipal's Black Horror",
        pos: "c5",
        icon: icons["abi_de_blackhorror"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "40 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Applies an enchantment to target ally for 15 seconds. Whenever they are attacked, you will deal 7% SAP + 89 corporeal damage to the attacker.`,
      },
	  "Bestial Surge": {
        name: "Bestial Surge",
        pos: "h6",
        icon: icons["abi_de_impendingdoom"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "50 action points",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Lore of Beasts",
        description: talentText`Applies a 10 second enchantment to target ally. For the duration, their penetration is increased by 750, their sagacity is increased by 750, and their AP regen is increased by 2.\n\nAugmented: effect now lasts 15 seconds.`,
      },
	  "Okkham's Mindrazor": {
        name: "Okkham's Mindrazor",
        pos: "c8",
        icon: icons["abi_de_surgingpain"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "30 action points",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Lore of Shadow",
        description: talentText`Applies a 30 second blessing to target ally. For the duration, whenever they deal direct damage to an enemy, they will deal an additional 10% SAP + 121 indirect, spiritual damage to the target.\n\nAugmented: the effect now lasts 45 seconds.`,
      },
      "Transformation of Kadon": {
        name: "Transformation of Kadon",
        pos: "d9",
        icon: icons["abi_de_overwhelmingdread"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "45s cooldown",
        blue: "Lore of Beast",
        description: talentText`This ability consumes all Winds of Beast and grants 5 stacks plus 5 additional per Wind of Beast consumed. You become a beast as long as you have stacks. You lose 2 stacks every second, and gain 1 stack every time you use an ability.\n\nWhile transformed you have 2.0s faster cast times, you gain 40 toughness per stack, and you gain 1 Wind of Beast every second. Your range will be reduced by 75% and all of your abilities now scale with MAP instead of SAP.`,
      },
      "Power of Darkness": {
        name: "Power of Darkness",
        pos: "f9",
        icon: icons["abi_de_echoofpower"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "65ft range",
        cast: "3.0s channel",
        cooldown: "30s cooldown",
        description: talentText`Every 0.5 seconds, deals 5% SAP + 50 spiritual damage to up to 48 enemies within a 30 foot area you select. Each time you strike an enemy you will gain a stack of a buff that grants 10% outgoing damage per stack up to a maximum of 100 stacks that lasts 1 second. Will not hit enemies who have Cover from you.`,
      },
	  "Amber Spear": {
        name: "Amber Spear",
        pos: "a5",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Doombolt now deals corporeal damage and applies 1 stack of Reduced Armor and 1 stack of Reduced Block to the target.`,
      },
	  "Grip of Fear": {
        name: "Grip of Fear",
        pos: "g5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Curse of Anraheir's augmented effect now applies to up to 23 additional enemies within 30 feet of the target.`,
      },
	  "Neverending Agony": {
        name: "Neverending Agony",
        pos: "b6",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Mockery of Death now applies a -33% outgoing healing debuff.`,
      },
	  "Eyes of Truth": {
        name: "Eyes of Truth",
        pos: "e6",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`You can see players under Stalk and your abilities will dispel Stalk from enemies hit.`,
      },
	  "Fate of Doom": {
        name: "Fate of Doom",
        pos: "a7",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Whenever you deal direct damage to enemies, if they die within 3 seconds, they will have Forlorn.`,
      },
	  "Amber Talons": {
        name: "Amber Talons",
        pos: "h7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Bestial Surge",
		arrows: [
          { dir: "down", from: "h6", to: "h7" },
        ],
        type: "career tactic",
        description: talentText`Bestial Surge will now apply to all groupmates within 150 when cast but it now has a 20 second cooldown.`,
      },
	  "Master of Ghur": {
        name: "Master of Ghur",
        pos: "g8",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Every 5 seconds, you generate 1 Wind of Beast.`,
      },
	  "Wings of the Falcon": {
        name: "Wings of the Falcon",
        pos: "e3",
        icon: icons["abi_de_consumeresolve"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever you augment a Lore of Beast spell, you will gain ${[
          6,
          12,
          18,
          24,
        ]}% movement speed for 5 seconds.`,
      },
	  "Embodiment of Ghur": {
        name: "Embodiment of Ghur",
        pos: "c4",
        icon: icons["abi_de_consumestrength"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Whenever you cast Pann's Impenetrable Pelt, it will always apply to you as well.`,
      },
	  "Improved Bladewind": {
        name: "Improved Bladewind",
        pos: "e5",
        icon: icons["abi_de_chillwind"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Bladewind will now generate ${[
          46,
          52,
          58,
          64,
        ]} action points.`,
      },
	  "Amber Trance": {
        name: "Amber Trance",
        pos: "d6",
        icon: icons["abi_de_fleetfooted"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`Gloom will now apply Staggered and Unstoppable to target enemy. This effect can only happen once every ${[
          60,
          30,
        ]} seconds.\n\nStaggered prevents all control of the character for 9 seconds unless attacked.\nUnstoppable prevents application og Knocked-down and staggered for 30 seconds.`,
      },
	  "Vengeful Hood": {
        name: "Vengeful Hood",
        pos: "f6",
        icon: icons["abi_de_windwovenshell"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`There is a ${[
          10,
          20,
          30,
          40,
          50,
        ]}% chance whenever an enemy hits you with a skill (not spells/abilities), that they will also take damage from that skill.`,
      },
	  "Extra Crit": {
        name: "Extra Crit",
        pos: "b7",
        icon: icons["abi_extracrit"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Your chance to critically hit is increased by ${[
          2,
          4,
		  6,
        ]}%.`,
	  },
	  "Flock of Doom": {
        name: "Flock of Doom",
        pos: "e7",
        icon: icons["abi_de_shadesofdeath"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`You deal ${[
          "3% SAP + 42",
          "6% SAP + 84",
          "9% SAP + 126",
        ]} corporeal damage to up to 9 enemies within 10 feet of you every 2 seconds.`,
      },
	  "The Beast Unleashed": {
        name: "The Beast Unleashed",
        pos: "e8",
        icon: icons["abi_de_cripplingterror"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Whenever you augment any spell, you will gain ${[
          1,
          2,
          3,
          4,
          5,
        ]} of 4 effects.\n\n1 stack of Enhanced Strength\n1 stack of Enhanced Agility\n750 armor for 5 seconds\n+1 mass for 5 seconds`,
      },
    },
  },
  "Dominator of Shyish": {
    name: "Dominator fo Shyish",
    background: backgrounds["shyish"],
    icon: icons["archetype_healer"],
    talents: {
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "What a Rush": {
        name: "What a Rush",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`The action point cost of your skills is reduced by 33% on allies that are lower than 40% health.`,
      },
      "Alignment of Naggaroth": {
        name: "Alignment of Naggaroth",
        pos: "a2",
        icon: icons["tac_race_delf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that have this tactic will gain 670 critical hit rating for 4 seconds.`,
      },
      "Bathing in Blood": {
        name: "Bathing in Blood",
        pos: "b2",
        icon: icons["tac_race_delf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You are healed for 7% of all damage you deal.`,
      },
      "Empowered Dhar": {
        name: "Empowered Dhar",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you hit an enemy with an augmented spell, you will dispel one enchantment from them.`,
      },
      "Tapping the Dark": {
        name: "Tapping the Dark",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Reduces the cast time of Doombolt by 1 second.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specstaff"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Dominators of Shyish equip staves.`,
      },
      "Hunter's Trap": {
        name: "Hunter's Trap",
        pos: "i4",
        icon: icons["abi_he_ensnare"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Applies Rooted and Immovable to target enemy.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nImmovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Shroud of Darkness": {
        name: "Shroud of Darkness",
        pos: "i5",
        icon: icons["abi_de_darkstarcloak"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Target ally gains a buff for 5 seconds. Each second, they will gain 1 stack of Enhanced Piercing Resistance, Enhanced Impact Resistance, Enhanced Ichor Resistance, Enhanced Corporeal Resistance, Enhanced Elemental Resistance, and Enhanced Spiritual Resistance.`,
      },
      "Murderous Prowess": {
        name: "Murderous Prowess",
        pos: "i7",
        icon: icons["abi_de_gripofanger"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain 50% critical hit chance and accuracy for 20 seconds.`,
      },
      "Winter's Frost": {
        name: "Winter's Frost",
        pos: "i8",
        icon: icons["abi_de_shadowspike"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 24 enemies within a 20 foot area you select become Rooted, Silenced, and Disarmed.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nSilenced prevents the use of spells for 5 seconds.\nDisarmed prevents the use of skills for 5 seconds.`,
      },
	  "Return Life": {
        name: "Return Life",
        pos: "f2",
        icon: icons["morale_returnlife"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Return target groupmate back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Divine Protection": {
        name: "Divine Protection",
        pos: "h2",
        icon: icons["morale_divineprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 15 seconds. They will absorb up to 200% RP + 1500 damage over the duration.`,
      },
      "Alter Fate": {
        name: "Alter Fate",
        pos: "i2",
        icon: icons["morale_alterfate"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Removes all afflictions and cripples from each groupmate within 100ft. Also applies Return Life to each dead groupmate within 100ft.`,
      },
      "Winds of Magic": {
        name: "Winds of Magic",
        pos: "a1",
        icon: icons["abi_he_stormofcronos"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Every 3 seconds, you will gain 1 stack of a wind of magic at random (Shadow, Beast, and Death) stacking up to a maximum of 3. Whenever you cast a spell of that lore of magic, it will consume one stack, if present, and augment the spell.\n\nYou have access to a no cost, no cooldown toggle ability which prevents you from using winds of magic while active.`,
      },
      "Bladewind": {
        name: "Bladewind",
        pos: "b1",
        icon: icons["abi_de_chillwind"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 6% SAP + 133 spiritual damage to target enemy. Generates 40 action points.`,
      },
      "Doombolt": {
        name: "Doombolt",
        pos: "c1",
        icon: icons["abi_de_doombolt"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "36 action points",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        description: talentText`Deals 55% SAP + 744 spiritual damage to target enemy.`,
      },
      "Morr's Peace": {
        name: "Morr's Peace",
        pos: "d1",
        icon: icons["abi_de_bestowvitality"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "45 action points",
        range: "150ft range",
        cast: "1.75s cast",
        cooldown: "no cooldown",
        blue: "Lore of Death",
        description: talentText`Restore 13% RP + 179 health to target groupmate and apply Aspect of the Dreadknight to them.\n\nAugmented: Restore an additional 10% RP + 131 health to target.\n\nAspect of the Dreadknight lasts for 15 seconds. Whenever you deal direct damage, groupmates within 150 feet of you with this buff are healed for 8% of the damage you deal.`,
      },
      "Word of Pain": {
        name: "Word of Pain",
        pos: "e1",
        icon: icons["abi_de_dreadaspect"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Applies an affliction to target enemy for 10 seconds. At the end of the duration, target will take 23% SAP + 311 spiritual damage.`,
      },
      "Arnzipal's Black Horror": {
        name: "Arnzipal's Black Horror",
        pos: "f1",
        icon: icons["abi_de_blackhorror"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Applies an enchantment to target ally for 15 seconds. Whenever they are attacked, you will deal 7% SAP + 89 corporeal damage to the attacker.`,
      },
      "Choking Shadows": {
        name: "Choking Shadows",
        pos: "g1",
        icon: icons["abi_de_chokingfury"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "45 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Lore of Shadow",
        description: talentText`Applies Silenced and Inevitable to target enemy.\n\nAugmented: Applies Ensnared and Momentum as well.\n\nSilenced prevents the use of spells for 5 seconds.\nInevitable prevents the application of Disarmed and Silenced for 20 seconds.\nEnsnared reduces movement speed by 30% for 16 seconds.\nMomentum prevents the application of Ensnared for 8 seconds.`,
      },
      "Soul Harvest": {
        name: "Soul Harvest",
        pos: "h1",
        icon: icons["abi_de_absorbvitality"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "1.75s cast",
        cooldown: "no cooldown",
        blue: "Lore of Death",
        description: talentText`Applies an affliction to target enemy for 15 seconds. Every 3 seconds, the target will take 12% SAP + 175 spiritual damage and your defensive target will be healed for 100% of the damage dealt.\n\nAugmented: ability is now instant cast and applies a blessing.`,
      },
      "Boar's Hide": {
        name: "Boar's Hide",
        pos: "i1",
        icon: icons["abi_de_shroudingdarkness"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "40s cooldown",
        blue: "Lore of Beast",
        description: talentText`Your damage reduction is increased by 50% and your cast times are increased by 33% for 4 seconds.\n\nAugmented: cooldown is reduced to 20 seconds.`,
      },
	  "Curse of Anraheir": {
        name: "Curse of Anraheir",
        pos: "g4",
        icon: icons["abi_de_disastrouscascade"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "40 action points",
        range: "100ft range",
        cast: "1.0s cast",
        cooldown: "no cooldown",
        blue: "Lore of Beast",
        description: talentText`Deals 10% SAP + 145 corporeal damage to target enemy and applies 1 stack of Reduced Strength.\n\nAugmented: applies 1 stack of Reduced Toughness and Reduced Corporeal Resistance.`,
      },
	  "Okkham's Mindrazor": {
        name: "Okkham's Mindrazor",
        pos: "h5",
        icon: icons["abi_de_surgingpain"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "30 action points",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Lore of Shadow",
        description: talentText`Applies a 30 second blessing to target ally. For the duration, whenever they deal direct damage to an enemy, they will deal an additional 10% SAP + 121 indirect, spiritual damage to the target.\n\nAugmented: the effect now lasts 45 seconds.`,
      },
	  "Mockery of Death": {
        name: "Mockery of Death",
        pos: "e6",
        icon: icons["abi_de_gloomofnight"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "1.5s cast",
        cooldown: "no cooldown",
        blue: "Lore of Death",
        description: talentText`Applies an ailment to target enemy for 10 seconds. Whenever the target is healed, you will deal 9% SAP + 128 spiritual damage to the healer.\n\nAugmented: effect is now a cripple and will deal 25% damage to target as well.`,
      },
	  "Pann's Impenetrable Pelt": {
        name: "Pann's Impenetrable Pelt",
        pos: "f8",
        icon: icons["abi_de_whirlinglaceration"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "30 action points",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Lore of Beasts",
        description: talentText`Applies 1 stack of Enhanced Piercing Resistance, 1 stack of Enhanced Ichor Resistance, 1 stack of Enhanced Block, and 1 stack of Reduced Impact Resistance to target ally.\n\nAugmented: applies an 8 second enchantment as well. For the duration, target's damage reduction is increased by 20%.`,
      },
      "Amanrath": {
        name: "Amanrath",
        pos: "d9",
        icon: icons["abi_de_bloodoffering"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "100 action points",
        range: "100ft range",
        cast: "3.0s channel",
        cooldown: "30s cooldown",
        blue: "Lore of Death",
        description: talentText`Deal 28% SAP + 382 spiritual damage to target enemy every second.\n\nAugmented: applys Aspect of the Dreadknight to all groupmates within 150 feet.\n\nAspect of the Dreadknight lasts for 15 seconds. Whenever you deal direct damage, groupmates within 150 feet of you with this buff are healed for 8% of the damage you deal.`,
      },
      "Power of Darkness": {
        name: "Power of Darkness",
        pos: "f9",
        icon: icons["abi_de_echoofpower"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "65ft range",
        cast: "3.0s channel",
        cooldown: "30s cooldown",
        description: talentText`Every 0.5 seconds, deals 5% SAP + 50 spiritual damage to up to 48 enemies within a 30 foot area you select. Each time you strike an enemy you will gain a stack of a buff that grants 10% outgoing damage per stack up to a maximum of 100 stacks that lasts 1 second. Will not hit enemies who have Cover from you.`,
      },
	  "Vision of Domination": {
        name: "Vision of Domination",
        pos: "a5",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Word of Pain is now a cripple with a 6 second duration.`,
      },
	  "Grief's End": {
        name: "Grief's End",
        pos: "b5",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever a groupmate lands a killing blow, you will gain 5 adrenaline regen for 8 seconds. Whenever a groupmate dies, you will gain 25 adrenaline regen for 8 seconds.`,
      },
	  "Eyes of Truth": {
        name: "Eyes of Truth",
        pos: "b6",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`You can see players under Stalk and your abilities will dispel Stalk from enemies hit.`,
      },
	  "Finger of Life": {
        name: "Finger of Life",
        pos: "h6",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Okkham's Mindrazor",
		arrows: [
          { dir: "down", from: "h5", to: "h6" },
        ],
        type: "career tactic",
        description: talentText`Okkham's Mindrazor will now heal the buff holder for 75% of the damage it deals.`,
      },
	  "Fate of Bjuna": {
        name: "Fate of Bjuna",
        pos: "a7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Soul Harvest deals 50% additional damage but no longer has innate lifetap.`,
      },
	  "Purple Pall of Shyish": {
        name: "Purple Pall of Shyish",
        pos: "e7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Whenever you augment a Lore of Death spell, you will gain a blessing for 8 seconds. For the duration, absorb up to 11% RP + 149 damage.`,
      },
	  "Master of Shyish": {
        name: "Master of Shyish",
        pos: "g8",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Every 5 seconds, you generate 1 Wind of Death.`,
      },
	  "Embodiment of Shyish": {
        name: "Embodiment of Shyish",
        pos: "e3",
        icon: icons["abi_de_consumeessence"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever you augment a Lore of Death spell, you will gain ${[
          3,
          6,
        ]} adrenaline regen for 5 seconds.`,
      },
	  "Aspect of the Dreadknight": {
        name: "Aspect of the Dreadknight",
        pos: "c4",
        icon: icons["abi_de_daemonicchill"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Aspect of the Dreadknight will now heal for ${[
          16,
          24,
          32,
          40,
        ]}% of the damage dealt.`,
      },
	  "Improved Bladewind": {
        name: "Improved Bladewind",
        pos: "e5",
        icon: icons["abi_de_chillwind"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Bladewind will now generate ${[
          46,
          52,
          58,
          64,
        ]} action points.`,
      },
	  "Improved Boar's Hide": {
        name: "Improved Boar's Hide",
        pos: "d6",
        icon: icons["abi_de_shroudingdarkness"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`Boar's hide now lasts ${[
          5,
          6,
          7,
          8,
        ]} seconds.`,
      },
	  "Acceptance of Fate": {
        name: "Acceptance of Fate",
        pos: "f6",
        icon: icons["abi_de_bestowvitality"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Morr's Peace will have a ${[
          0.1,
          0.2,
          0.3,
          0.4,
          0.5,
        ]} faster cast time.`,
      },
	  "Blessing of Asuryan": {
        name: "Blessing of Asuryan",
        pos: "c7",
        icon: icons["abi_he_lawofage"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Gain ${[
          25,
          50,
          75,
          100,
        ]}% pushback immunity.`,
      },
	  "Final Words": {
        name: "Final Words",
        pos: "g7",
        icon: icons["abi_de_consumewill"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`You have ${[
          3,
          6,
          10,
        ]}% outgoing damage and outgoing healing against targets with 40% or less health.`,
      },
	  "Spirit Leech": {
        name: "Spirit Leech",
        pos: "e8",
        icon: icons["abi_de_handofruin"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Doombolt and Word of Pain now deal ${[
          8,
          16,
          24,
          32,
        ]}% less damage but will heal your defensive target for ${[
          15,
          45,
          90,
          150,
        ]}% of the damage dealt.`,
      },
    },
  },
};