import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/druchii"),
);
const icons = requireAll(require.context("../../assets/icons/darkelf"));

export const data: TalentData = {
  "Blackguard": {
    name: "Blackguard",
    background: backgrounds["blackguard"],
    icon: icons["archetype_defsupport"],
    talents: {
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Increase your mass by 1.`,
      },
      "Alignment of Naggaroth": {
        name: "Alignment of Naggaroth",
        pos: "a2",
        icon: icons["tac_race_delf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that have this tactic will gain 670 critical hit rating for 4 seconds.`,
      },
      "Bathing in Blood": {
        name: "Bathing in Blood",
        pos: "b2",
        icon: icons["tac_race_delf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You are healed for 7% of all damage you deal.`,
      },
      "Thirst for Death": {
        name: "thirst for Death",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Critical hits generate 5 additional hatred. This effect can only happen once every second.`,
      },
      "Driven by Hate": {
        name: "Driven by Hate",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Abilities which spend hatred will generate 125 action points for you. Hateful Strike no longer generates action points.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specpolearm"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Blackguards equip two-handed polearms.`,
      },
      "Choking Fury": {
        name: "Choking Fury",
        pos: "i4",
        icon: icons["abi_de_chokingfury"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Applies Silenced and Inevitable to target.\n\nSilenced prevents use of spells for 5 seconds.\nInevitable prevents application of Disarmed and Silenced.`,
      },
      "Filled With Fury": {
        name: "Filled With Fury",
        pos: "i5",
        icon: icons["abi_de_drivenbyhate"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Generates 100 hatred.`,
      },
      "Murderous Prowess": {
        name: "Murderous Prowess",
        pos: "i7",
        icon: icons["abi_de_gripofanger"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain 50% critical hit chance and accuracy for 20 seconds.`,
      },
      "Furious Howl": {
        name: "Furious Howl",
        pos: "i8",
        icon: icons["abi_de_furioushowl"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Applies Silenced to up to 48 enemies within 30 feet.`,
      },
	  "Hedgehog": {
        name: "Hedgehog",
        pos: "f2",
        icon: icons["morale_hedgehog"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`All groupmates within 100ft gain 3 stacks of Enhanced Block.`,
      },
      "Champion's Challenge": {
        name: "Champion's Chalenge",
        pos: "g2",
        icon: icons["morale_grapple"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Applies a debuff to target enemy and yourself for 10 seconds. Movement speed is reduced to 0 for the duration.`,
      },
      "Distracting Bellow": {
        name: "Distracting Bellow",
        pos: "h2",
        icon: icons["morale_distractingbellow"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Up to 48 enemies within 30ft of you receive a debuff. For 10 seconds, they cannot benefit from Cover.`,
      },
      "Immaculate Defense": {
        name: "Immaculate Defense",
        pos: "i2",
        icon: icons["morale_immaculatedefense"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Groupmates within 100ft gain 25 stacks of a buff for 20 seconds. Each stack grants 3% damage reduction. A stack is removed each time they are attacked by an ability; 4 additional stacks are removed if the ability is single target.`,
      },
      "Hatred": {
        name: "Hatred",
        pos: "a1",
        icon: icons["abi_de_drivenbyhate"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Hatred goes up to 100. You generate 5 Hatred whenever you use an ability. You lose 3 Hatred whenever you are attacked (1s ICD).`,
      },
      "Hateful Strike": {
        name: "Hateful Strike",
        pos: "b1",
        icon: icons["abi_de_brutalsmash"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 110 piercing damage to target enemy. Generates 22 action points.`,
      },
      "Bolstering Anger": {
        name: "Bolstering Anger",
        pos: "c1",
        icon: icons["abi_de_noneshallpass"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 35 Hatred",
        description: talentText`Groupmates within 100 feet of you gain a blessing for 8 seconds. For the duration, they will have their block chance increased by 35%.\n\nGroupmates within 100 feet of you gain an enchantment for 60 seconds. For the duration, they will gain 1 stack of Enhanced Toughness every 10 seconds.`,
      },
      "Pitiless Strike": {
        name: "Pitiless Strike",
        pos: "d1",
        icon: icons["abi_de_pitilessstrike"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "36 action points",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 21% MAP + 280 piercing damage to target enemy.`,
      },
      "Banish Weakness": {
        name: "Banish Weakness",
        pos: "e1",
        icon: icons["abi_de_shatterenchantment"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "45 action points",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 15% MAP + 204 piercing damage to target enemy. Dispels one affliction from your defensive target if they are within 100 feet.`,
      },
      "Mind Killer": {
        name: "Mind Killer",
        pos: "f1",
        icon: icons["abi_de_mindkiller"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 15% MAP + 204 impact damage to target enemy and applies one stack of Reduced Intelligence and Reduced Willpower.`,
      },
      "Spiteful Slam": {
        name: "Spiteful Slam",
        pos: "g1",
        icon: icons["abi_de_crushingspite"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "60 action points",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Applies Knocked-down and Unstoppable to target enemy.\n\nKnocked-down prevents all control of your character for 3 seconds.\nUnstopppable prevents application of Knocked-down and Staggered for 30 seconds.`,
      },
      "Crushing Anger": {
        name: "Crushing Anger",
        pos: "h1",
        icon: icons["abi_de_banishweakness"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 35 Hatred",
        description: talentText`Groupmates within 100 feet of you gain a blessing for 8 seconds. For the duration, they will have their critical hit chance increased by 15%.\n\nGroupmates within 100 feet of you gain an enchantment for 60 seconds. For the duration, they will gain 1 stack of Enhanced Strength every 10 seconds.`,
      },
      "Vigilance": {
        name: "Vigilance",
        pos: "i1",
        icon: icons["abi_vigilance"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        description: talentText`Your damage reduction is increased by 50%, but your outgoing damage is reduced by 90% for 7 seconds.`,
      },
	  "Wave of Scorn": {
        name: "Wave of Scorn",
        pos: "h4",
        icon: icons["abi_de_crushinganger"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 35 Hatred",
        description: talentText`Groupmates within 100 feet of you gain a blessing for 8 seconds. For the duration they will deal 5% MAP + 8 impact damage every time they attack an enemy.\n\nAll groupmates within 100 feet gain an enchantment for 60 seconds. Every 3 seconds, up to 6 enemies within 30 feet will take 4% MAP + 39 indirect impact damage.`,
      },
	  "Distract": {
        name: "Distract",
        pos: "g5",
        icon: icons["abi_distract"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "40 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Jams the target for the next 3 seconds interupting the next ability cast.`,
      },
	  "Hate Flows Through You": {
        name: "Hate Flows Through You",
        pos: "h6",
        icon: icons["abi_de_armorofeternalservitude"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 35 Hatred",
        description: talentText`Groupmates within 100 feet of you gain a blessing for 8 seconds. For the duration, they will have their healing received increased by 20%.\n\nGroupmates within 100 feet of you gain an enchantment for 60 seconds. For the duration, they will gain 1 stack of Enhanced Willpower every 10 seconds.`,
      },
	  "Exile": {
        name: "Exile",
        pos: "e8",
        icon: icons["abi_de_awaycretins"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "50 action points",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Knocks the enemy away and applies Immovable to them.\n\nImmovable prevents application of Knockbacks, Pulls, and Rooted for 20 seconds.`,
      },
      "Get Down Mr. Malekith": {
        name: "Get Down Mr. Malekith",
        pos: "d9",
        icon: icons["abi_de_bolsteringanger"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 35 Hatred",
        description: talentText`Groupmates within 100 feet of you gain a blessing for 8 seconds. For the duration, they will have their corporeal, elemental, and spiritual resistances increased by 700.\n\nGroupmates within 100 feet of you gain an enchantment for 60 seconds. For the duration, they will gain 1 stack of Enhanced Hardiness every 10 seconds.`,
      },
      "Chains of Hatred": {
        name: "Chains of Hatred",
        pos: "f9",
        icon: icons["abi_de_groundslam"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "self",
        cast: "1.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Up to 48 enemies within 30 feet of you have their movement speed reduced by 90% for 4 seconds. Does not effect targets that have Cover from you.`,
      },
	  "Shielded by Hate": {
        name: "Shielded by Hate",
        pos: "a5",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Every 3 seconds, you will gain 800 block rating for every 30 Hatred that you have for 3 seconds.`,
      },
	  "Malekith's Bulwark": {
        name: "Malekith's Bulwark",
        pos: "b5",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`You gain 1250 corporeal, elemental, and spiritual resistance but lose 10% healing received.`,
      },
	  "Soul Killer": {
        name: "Soul Killer",
        pos: "b6",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Mind Killer will now apply a 5 second affliction to target. For the duration, their outgoing healing is reduced by 33%.`,
      },
	  "Improved Distract": {
        name: "Improved Distract",
        pos: "g6",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 15,
		prereq: "Distract",
		arrows: [
          { dir: "down", from: "g5", to: "g6" },
        ],
        type: "career tactic",
        description: talentText`Distract will now work on up to 23 additional enemies within 20 feet of the target as long as those targets do not have Cover from you.`,
      },
	  "Disperse the Weak": {
        name: "Disperse the Weak",
        pos: "a7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Banish Weakness will no longer deal damage, but now will dispel one enchantment from the enemy. In addition, you will dispel 1 cripple from your defensive target.`,
      },
	  "Endless Pursuit": {
        name: "Endless Pursuit",
        pos: "b7",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Whenever you take magic damage, you apply a stack of Bloody Mess to the enemy who dealt it. Bloody Mess stacks up to 8 times and reduces movement speed by 2% for 6 seconds per stack.`,
      },
	  "Intrusive Strikes": {
        name: "Intrusive Strikes",
        pos: "d8",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Pitiless Strike will now deal 28% less damage but it will always interrupt the enemy.`,
      },
	  "Focus Past Pain": {
        name: "Focus Past Pain",
        pos: "e3",
        icon: icons["abi_de_drivenbyhate"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Reduces the amount of Hatred lost whenever you are attacked by ${[
          1,
          2,
          3,
          4,
          5,
        ]}.`,
      },
	  "Feeding on Pain": {
        name: "Feeding on Pain",
        pos: "b4",
        icon: icons["abi_de_umbralstrikes"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Restore ${[
          2,
          4,
          6,
          8,
        ]}% of your health each time you use Hateful Strike.`,
      },
	  "Improved Hateful Strike": {
        name: "Improved Hateful Strike",
        pos: "e5",
        icon: icons["abi_de_brutalsmash"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Hateful Strike now deals additional damage equal to ${[
          4,
          8,
        ]}% MAP.`,
      },
	  "Engage": {
        name: "Engage",
        pos: "c6",
        icon: icons["abi_engage"],
        maxRank: 3,
        reqPoints: 15,
        type: "passive",
        description: talentText`Enemies that you deal direct damage to will have their outgoing damage reduced by ${[
          2,
          4,
          6,
          8,
          10,
        ]}% for 5 seconds.`,
      },
	  "Passive 4": {
        name: "Passive 4",
        pos: "e6",
        icon: icons["abi_de_shroudingdarkness"],
        maxRank: 4,
        reqPoints: 15,
        type: "passive",
        description: talentText`Whenever you spend Hatred, up to ${[
          1,
          2,
          3,
          4,
          5,
        ]} groupmates within 100 feet of you will gain 1 stack of either Enhanced Corporeal, Elemental, or Spiritual Resistance.`,
      },
	  "Passive 5": {
        name: "Passive 5",
        pos: "e7",
        icon: icons["abi_de_shroudingdarkness"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Passive 4",
		arrows: [
          { dir: "down", from: "e6", to: "e7" },
        ],
        type: "passive",
        description: talentText`Passive 4 will now apply 2 stacks.`,
      },
	  "Band Together": {
        name: "Band Together",
        pos: "h7",
        icon: icons["abi_bandtogether"],
        maxRank: 5,
        reqPoints: 20,
        type: "passive",
        description: talentText`Groupmates within 30 feet of you have their damage reduction increased by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%. This effect is suppressed for 5 seconds whenever you are hit by a single-target ability.`,
      },
	  "Clamor for Hatred": {
        name: "Clamor for Hatred",
        pos: "f8",
        icon: icons["abi_rushofcommand"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`You generate ${[
          1,
          2,
          3,
          4,
        ]} adrenaline per second for each enchantment effect from Hatred spenders you cast that are active on you.`,
      },
    },
  },
  "Dread Knight": {
    name: "Dread Knight",
    background: backgrounds["dreadknight"],
    icon: icons["archetype_tank"],
    talents: {
      "Break Loose": {
        name: "Break Loose",
        pos: "a8",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Masochist": {
        name: "Masochist",
        pos: "a8",
        icon: icons["rrtac_masochist"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you are attacked while your Guard is active, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Increase your mass by 1.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "What a Rush": {
        name: "What a Rush",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`The action point cost of your skills is reduced by 33% on allies that are lower than 40% health.`,
      },
      "Racial Tactic 1": {
        name: "Racial Tactic 1",
        pos: "a2",
        icon: icons["tac_arche"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Racial Tactic 2": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_arche"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 1": {
        name: "Class Tactic 1",
        pos: "c2",
        icon: icons["tac_arche"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 2": {
        name: "Class Tactic 2",
        pos: "d2",
        icon: icons["tac_arche"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Specialization is able to equip these weapons.`,
      },
      "Morale 1 Class": {
        name: "Morale 1 Class",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 2 Spec": {
        name: "Morale 2 Spec",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 3 Race": {
        name: "Morale 3 Race",
        pos: "i7",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 4 Spec": {
        name: "Morale 4 Spec",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Insert tooltip.`,
      },
	  "Hedgehog": {
        name: "Hedgehog",
        pos: "f2",
        icon: icons["morale_hedgehog"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`All groupmates within 100ft gain 3 stacks of Enhanced Block.`,
      },
      "Champion's Challenge": {
        name: "Champion's Chalenge",
        pos: "g2",
        icon: icons["morale_grapple"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Applies a debuff to target enemy and yourself for 10 seconds. Movement speed is reduced to 0 for the duration.`,
      },
      "Distracting Bellow": {
        name: "Distracting Bellow",
        pos: "h2",
        icon: icons["morale_distractingbellow"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Up to 48 enemies within 30ft of you receive a debuff. For 10 seconds, they cannot benefit from Cover.`,
      },
      "Immaculate Defense": {
        name: "Immaculate Defense",
        pos: "i2",
        icon: icons["morale_immaculatedefense"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Groupmates within 100ft gain 25 stacks of a buff for 20 seconds. Each stack grants 3% damage reduction. A stack is removed each time they are attacked by an ability; 4 additional stacks are removed if the ability is single target.`,
      },
      "Specialization Mechanic": {
        name: "Specialization Mechanic",
        pos: "a1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell career tactic renown tactic passive morale 1234",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 1": {
        name: "Core Ability 1",
        pos: "b1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 2": {
        name: "Core Ability 2",
        pos: "c1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 3": {
        name: "Core Ability 3",
        pos: "d1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 4": {
        name: "Core Ability 4",
        pos: "e1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 5": {
        name: "Core Ability 5",
        pos: "f1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 6": {
        name: "Core Ability 6",
        pos: "g1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 7": {
        name: "Core Ability 7",
        pos: "h1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 8": {
        name: "Core Ability 8",
        pos: "i1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Special Ability 1": {
        name: "SA1",
        pos: "b4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 2": {
        name: "SA2",
        pos: "c5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 3": {
        name: "SA3",
        pos: "c6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 4": {
        name: "SA4",
        pos: "c8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 1": {
        name: "Capstone Ability 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 2": {
        name: "Capstone Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 1": {
        name: "T1",
        pos: "a5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 2": {
        name: "T2",
        pos: "b5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 3": {
        name: "T3",
        pos: "a6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 4": {
        name: "T4",
        pos: "b6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 5": {
        name: "T5",
        pos: "a7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 6": {
        name: "T6",
        pos: "b7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 7": {
        name: "T7",
        pos: "b8",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Passive 1": {
        name: "Passive 1",
        pos: "e3",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 2": {
        name: "Passive 2",
        pos: "c4",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 5,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 3": {
        name: "Passive 3",
        pos: "e5",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 4": {
        name: "Passive 4",
        pos: "d6",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 5": {
        name: "Passive 5",
        pos: "e6",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 6": {
        name: "Passive 6",
        pos: "d7",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 7": {
        name: "Passive 7",
        pos: "e7",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 8": {
        name: "Passive 8",
        pos: "e8",
        icon: icons["noicon"],
        maxRank: 4,
        reqPoints: 25,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
    },
  },
  "Corsair": {
    name: "Corsair",
    background: backgrounds["corsair"],
    icon: icons["archetype_offsupport"],
    talents: {
      "Break Loose": {
        name: "Break Loose",
        pos: "a8",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Masochist": {
        name: "Masochist",
        pos: "a8",
        icon: icons["rrtac_masochist"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you are attacked while your Guard is active, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 5,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Increase your mass by 1.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "What a Rush": {
        name: "What a Rush",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`The action point cost of your skills is reduced by 33% on allies that are lower than 40% health.`,
      },
      "Racial Tactic 1": {
        name: "Racial Tactic 1",
        pos: "a2",
        icon: icons["tac_arche"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Racial Tactic 2": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_arche"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 1": {
        name: "Class Tactic 1",
        pos: "c2",
        icon: icons["tac_arche"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Class Tactic 2": {
        name: "Class Tactic 2",
        pos: "d2",
        icon: icons["tac_arche"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Text of tactic.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Specialization is able to equip these weapons.`,
      },
      "Morale 1 Class": {
        name: "Morale 1 Class",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 2 Spec": {
        name: "Morale 2 Spec",
        pos: "i5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 3 Race": {
        name: "Morale 3 Race",
        pos: "i7",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Insert tooltip.`,
      },
      "Morale 4 Spec": {
        name: "Morale 4 Spec",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Insert tooltip.`,
      },
	  "Hedgehog": {
        name: "Hedgehog",
        pos: "f2",
        icon: icons["morale_hedgehog"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`All groupmates within 100ft gain 3 stacks of Enhanced Block.`,
      },
      "Champion's Challenge": {
        name: "Champion's Chalenge",
        pos: "g2",
        icon: icons["morale_grapple"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Applies a debuff to target enemy and yourself for 10 seconds. Movement speed is reduced to 0 for the duration.`,
      },
      "Force of Will": {
        name: "Force of Will",
        pos: "h2",
        icon: icons["morale_forceofwill"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 10 seconds. Action point costs are reduced by 75% for the duration.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "Specialization Mechanic": {
        name: "Specialization Mechanic",
        pos: "a1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell career tactic renown tactic passive morale 1234",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 1": {
        name: "Core Ability 1",
        pos: "b1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 2": {
        name: "Core Ability 2",
        pos: "c1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 3": {
        name: "Core Ability 3",
        pos: "d1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 4": {
        name: "Core Ability 4",
        pos: "e1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 5": {
        name: "Core Ability 5",
        pos: "f1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 6": {
        name: "Core Ability 6",
        pos: "g1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 7": {
        name: "Core Ability 7",
        pos: "h1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Core Ability 8": {
        name: "Core Ability 8",
        pos: "i1",
        icon: icons["noicon"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability skill spell passive",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Special Ability 1": {
        name: "SA1",
        pos: "b4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 2": {
        name: "SA2",
        pos: "c5",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 3": {
        name: "SA3",
        pos: "c6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Special Ability 4": {
        name: "SA4",
        pos: "c8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 1": {
        name: "Capstone Ability 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
      "Capstone Ability 2": {
        name: "Capstone Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 30,
        type: "ability skill spell",
        cost: "50 action points no cost",
        range: "7.5ft range self",
        cast: "2.0s instant cast",
        cooldown: "10s no cooldown",
        blue: "blue text",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 1": {
        name: "T1",
        pos: "a5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 2": {
        name: "T2",
        pos: "b5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 3": {
        name: "T3",
        pos: "a6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 4": {
        name: "T4",
        pos: "b6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 5": {
        name: "T5",
        pos: "a7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 6": {
        name: "T6",
        pos: "b7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Tactic 7": {
        name: "T7",
        pos: "b8",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "career tactic",
        description: talentText`Insert tooltip.`,
      },
	  "Passive 1": {
        name: "Passive 1",
        pos: "e3",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 0,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 2": {
        name: "Passive 2",
        pos: "c4",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 5,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 3": {
        name: "Passive 3",
        pos: "e5",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 10,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 4": {
        name: "Passive 4",
        pos: "d6",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 5": {
        name: "Passive 5",
        pos: "e6",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 15,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 6": {
        name: "Passive 6",
        pos: "d7",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 7": {
        name: "Passive 7",
        pos: "e7",
        icon: icons["noicon"],
        maxRank: 5,
        reqPoints: 20,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
	  "Passive 8": {
        name: "Passive 8",
        pos: "e8",
        icon: icons["noicon"],
        maxRank: 4,
        reqPoints: 25,
        prereq: "Wounds",
		arrows: [
          { dir: "right-down", from: "e6", to: "f6" },
          { dir: "right-down-down", from: "f6", to: "f8" }
        ],
        type: "passive",
        description: talentText`Insert tooltip. ${[
          1,
          2,
          3,
          4,
          5,
        ]}`,
      },
    },
  },
};