import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/asur"),
);
const icons = requireAll(require.context("../../assets/icons/highelf"));

export const data: TalentData = {
  "Adept of Ghyran": {
    name: "Adept of Ghyran",
    background: backgrounds["ghyran"],
    icon: icons["archetype_healer"],
    talents: {
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 1,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "What a Rush": {
        name: "What a Rush",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`The action point cost of your skills is reduced by 33% on allies that are lower than 40% health.`,
      },
      "Centuries of Training": {
        name: "centuries of Training",
        pos: "a2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you deal direct damage to an enemy, you have a 33% chance to apply one of three debuffs to them. Effects do not refresh and last 6 seconds.\nDeals 4% MAP + 56 impact damage every second.\nDeals 6% RAP + 80 piercing damage every 2 seconds.\nDeals 10% SAP + 134 spiritual damage every 3 seconds.`,
      },
      "Form Ranks": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, each groupmate within 100 feet that has this tactic will gain 1 stack of purity and a 4 second buff. For the duration, gain 450 penetration and 450 sagacity.`,
      },
      "Drain Magic": {
        name: "Drain Magic",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you hit an enemy with an augmented spell, you will dispel one enchantment from them.`,
      },
      "Run Between Worlds": {
        name: "Run Between Worlds",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Walk Between Worlds will no longer increase your cast times and will increase your movement speed by 25% for the duration.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specstaff"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Adepts of Ghyran equip staves.`,
      },
      "Radiant Gaze": {
        name: "Radiant Gaze",
        pos: "i4",
        icon: icons["abi_he_radiantglaze"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Target enemy gains 3 stacks of Reduced Corporeal Resistance, Reduced Elemental Resistance, and Reduced Spiritual Resistance.`,
      },
      "Net of Amyntok": {
        name: "Net of Amyntok",
        pos: "i5",
        icon: icons["abi_de_webofshadows"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Target gains a debuff for 5 seconds. For the duration, their movement speed is decreased by 75% and their mass is increased by 3.`,
      },
      "Wings of Heaven": {
        name: "Wings of Heaven",
        pos: "i7",
        icon: icons["abi_he_wingsofheaven"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Gain a debuff for 5 seconds which reduces your mass by 8. Leap forward and apply Ensnared to up to 9 enemies within 20 feet of where you land.\n\nEnsnared reduces movement speed by 30% for 16 seconds.`,
      },
      "Winter's Frost": {
        name: "Winter's Frost",
        pos: "i8",
        icon: icons["abi_de_shadowspike"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 24 enemies within a 20 foot area you select become Rooted, Silenced, and Disarmed.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nSilenced prevents the use of spells for 5 seconds.\nDisarmed prevents the use of skills for 5 seconds.`,
      },
	  "Return Life": {
        name: "Return Life",
        pos: "f2",
        icon: icons["morale_returnlife"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Return target groupmate back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Divine Protection": {
        name: "Divine Protection",
        pos: "h2",
        icon: icons["morale_divineprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 15 seconds. They will absorb up to 120% RP + 1600 damage over the duration.`,
      },
      "Alter Fate": {
        name: "Alter Fate",
        pos: "i2",
        icon: icons["morale_alterfate"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Removes all afflictions and cripples from each groupmate within 100 feet. Also applies Return Life to each dead groupmate within 100 feet.`,
      },
      "Winds of Magic": {
        name: "Winds of Magic",
        pos: "a1",
        icon: icons["abi_he_stormofcronos"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Every 3 seconds, you will gain 1 stack of a wind of magic at random (Life, Light, and Heavens) stacking up to a maximum of 3. Whenever you cast a spell of that lore of magic, it will consume one stack, if present, and augment the spell.\n\nYou have access to a no cost, no cooldown toggle ability which prevents you from using winds of magic while active.`,
      },
      "Radiant Lance": {
        name: "Radiant Lance",
        pos: "b1",
        icon: icons["abi_he_radiantlance"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 6% SAP + 133 elemental damage to target enemy. You generate 40 action points.`,
      },
      "Regrowth": {
        name: "Regrowth",
        pos: "c1",
        icon: icons["abi_he_lambentaura"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "150ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        blue: "Lore of Life",
        description: talentText`Heal target ally for 22% RP + 283.\n\nAugmented: Apply a 21 second enchantment to the target. For the duration, target is healed for 7% RP + 100 every 3 seconds.`,
      },
	  "Shield of Saphery": {
        name: "Shield of Saphery",
        pos: "d1",
        icon: icons["abi_he_shieldofsphery"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "80 action points",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Target ally gains an enchantment for 8 seconds. They will absorb 20% RP + 259 damage over the duration.`,
      },
	  "Lightning Bolt": {
        name: "Lightning Bolt",
        pos: "e1",
        icon: icons["abi_ch_zap"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "36 action points",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        blue: "Lore of Heavens",
        description: talentText`Deals 19% SAP + 258 elemental damage to target enemy and applies 1 stack of Reduced Elemental Resistance to them.\n\nAugmented: Deals 11% SAP + 155 corporeal damage to target and 1 stack of Reduced Corporeal Resistance.`,
      },
	  "Courage of Aenarion": {
        name: "Courage of Aenarion",
        pos: "f1",
        icon: icons["abi_he_mistressofthemarsh"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Place a 20 foot wide area on the ground. Allies in the area will have their abilities augmented. Enemies in the area will have their movement speed reduced by 50%.`,
      },
      "Abulla's Snare": {
        name: "Abulla's Snare",
        pos: "g1",
        icon: icons["abi_he_windsprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        blue: "Lore of Light",
        description: talentText`Applies Rooted, Immovable, and 3 stacks of Purity to target enemy.\n\nAugmented: Will now also apply to up to 8 other enemies within 30 feet of you.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nImmovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Awakening the Woods": {
        name: "Awakening the Woods",
        pos: "h1",
        icon: icons["itm_em_tornclawspaw"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "20 action points",
        range: "150ft range",
        cast: "1.0s cast",
        cooldown: "no cooldown",
        blue: "Lore of Life",
        description: talentText`Applys a Seed of Life to target ally.\n\nAugmented: Causes all of your Seed of Life stacks on the target to bloom at once.\n\nSeed of Life lasts for 1 minute and stacks up to 10 times. Whenever the target is critically hit by an enemy, a stack will bloom restoring 6% RP + 82 health.`,
      },
      "Walk Between Worlds": {
        name: "Walk Between Worlds",
        pos: "i1",
        icon: icons["abi_he_walkbetweenworlds"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        description: talentText`Your damage reduction is increased by 50% and your cast times are increased by 33% for 7 seconds.`,
      },
	  "Cleansing Light": {
        name: "Cleansing Light",
        pos: "b4",
        icon: icons["abi_he_cleansinglight"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "30 action points",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Lore of Light",
        description: talentText`Dispel 1 affliction from target ally and applies 1 stack of Purity.\n\nAugmented: Also dispel 1 cripple and apply another stack of Purity.`,
      },
	  "Star Tide's Ebb": {
        name: "Star Tide's Ebb",
        pos: "e5",
        icon: icons["abi_he_distractingshot"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "40 action points",
        range: "100ft range",
        cast: "1.0s cast",
        cooldown: "12s cooldown",
        blue: "Lore of Heavens",
        description: talentText`Applies an affliction to target enemy for 12 seconds. For the duration, target's cast times are increased by 33%.\n\nAugmented: The effect becomes a cripple and also increases their cooldowns by 33%.`,
      },
	  "Barkskin": {
        name: "Barkskin",
        pos: "f6",
        icon: icons["abi_he_skinofstone"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "30 action points",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Lore of Life",
        description: talentText`Applies 1 stack of Enhanced Piercing Resistance, Enhanced Impact Resistance, Enhanced Corporeal Resiatance, Enhanced Fortitude, Reduced Agility, and Reduced Elemental Resistance to target ally.\n\nAugmented: Applies an enchantment for 8 seconds. For the duration their damage reduction is increased by 20%.`,
      },
	  "Urannon's Thunderbolt": {
        name: "Urannon's Thunderbolt",
        pos: "e8",
        icon: icons["abi_dw_explosion02"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "75 action points",
        range: "100ft range",
        cast: "2.5s cast",
        cooldown: "no cooldown",
        blue: "Lore of Heavens",
        description: talentText`Deals 18% SAP + 240 elemental damage to up to 9 enemies within a 20 foot area you select.\n\nAugmented: Reduce the cast time by 1.5 seconds.`,
      },
      "Storm of Renewal": {
        name: "Storm of Renewal",
        pos: "d9",
        icon: icons["abi_he_rainlord02"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "100 action points",
        range: "self",
        cast: "3.0s cast",
        cooldown: "15s cooldown",
        blue: "Lore of Life",
        description: talentText`Applies a 15 second enchantment on all groupmates within 100 feet of you. For the duration they will be healed for 13% RP + 166 every 3 seconds.\n\nAugmented: Also applies to up to 4 allies within 20 feet of each groupmate.`,
      },
      "Flames of the Phoenix": {
        name: "Flames of Phoenix",
        pos: "f9",
        icon: icons["abi_he_flamesofthephoenix"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "100ft range",
        cast: "3.0s channel",
        cooldown: "30s cooldown",
        description: talentText`Deals 10% SAP + 50 elemental damage every 0.5 seconds to up to 48 enemies within a 30 foot area you select. Each time an enemy is hit by this ability they gain a stack that increases damage they take from this ability by 25% for 1 second. This ability deals no damage to targets that have cover from you.`,
      },
	  "Earthblood": {
        name: "Earthblood",
        pos: "a5",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`If you have been standing still for 3 seconds, gain 3 AP regen and 720 HP4 until you move.`,
      },
	  "Apotheosis": {
        name: "Apothesosis",
        pos: "b5",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 10,
		prereq: "Cleansing Light",
		arrows: [
          { dir: "down", from: "b4", to: "b5" },
        ],
        type: "career tactic",
        description: talentText`Cleansing Light will now apply a 9 second enchantment to the target, stacking up to 3 times. For the duration, they will be healed for 3% RP + 50 every 3 seconds.`,
      },
	  "Eyes of Truth": {
        name: "Eyes of Truth",
        pos: "b6",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`You can see players under Stalk and your abilities will dispel Stalk from enemies hit.`,
      },
	  "Starshine": {
        name: "Starshine",
        pos: "e6",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Star Tide's Ebb",
		arrows: [
          { dir: "down", from: "e5", to: "e6" },
        ],
        type: "career tactic",
        description: talentText`Star Tide's Ebb no longer has a cooldown but the duration is decreased to 8 seconds.`,
      },
	  "Living Seeds": {
        name: "Living Seeds",
        pos: "a7",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`The healing over time effect of Regrowth and Seeds of Life can now critically heal.`,
      },
	  "Curse of Thorns": {
        name: "Curse of Thorns",
        pos: "f7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Barkskin",
		arrows: [
          { dir: "down", from: "f6", to: "f7" },
        ],
        type: "career tactic",
        description: talentText`Enemies that attack allies affected by your Barkskin, Fortune's Renewal, and Regrowth effects will take 12% SAP + 147 corporeal damage.`,
      },
	  "Master of Ghyran": {
        name: "Master of Ghyran",
        pos: "c8",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Every 5 seconds you generate 1 Wind of Life.`,
      },
      "Vital Growth": {
        name: "blueprint",
        pos: "e3",
        icon: icons["itm_em_woodlog"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever you augment a spell, your defensive target will gain ${[
          1,
          2,
		  3,
        ]} stacks of Seed of Life.\n\nSeed of Life lasts for 1 minute and stacks up to 10 times. Whenever the target is critically hit by an enemy, a stack will bloom restoring 6% RP + 82 health.`,
      },
	  "Radiant Return": {
        name: "Radiant Return",
        pos: "h4",
        icon: icons["abi_he_radiantlance"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Radiant Lance will now generate ${[
          46,
          52,
          58,
        ]} action points.`,
      },
	  "Drain Life": {
        name: "Drain Life",
        pos: "h5",
        icon: icons["abi_he_balanceessence"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Radiant Lance will heal your defensive target for ${[
          150,
          300,
        ]}% of the damage dealt.`,
      },
	  "Nature's Splendor": {
        name: "Nature's Splendor",
        pos: "d6",
        icon: icons["itm_he_shadowthorn"],
        maxRank: 3,
        reqPoints: 15,
        type: "passive",
        description: talentText`Whenever you augment a spell, all groupmates within 100 feet of you gain ${[
          1,
          2,
          3,
        ]} AP regen for 3 seconds.`,
      },
	  "Cloak of Dain": {
        name: "Cloak of Dain",
        pos: "h6",
        icon: icons["abi_he_shieldofsphery"],
        maxRank: 4,
        reqPoints: 15,
        type: "passive",
        description: talentText`Shield of Saphery absorbs ${[
          10,
          20,
          30,
          40,
          50,
        ]}% more damage.`,
      },
	  "Rampant Growth I": {
        name: "Rampant Growth I",
        pos: "c7",
        icon: icons["abi_he_lambentaura"],
        maxRank: 2,
        reqPoints: 20,
        type: "passive",
        description: talentText`Regrowth's direct heal is ${[
          10,
          25,
        ]}% more effective on targets that have Regrowth's over time effect.`,
      },
	  "Rampant Growth III": {
        name: "Rampant Growth III",
        pos: "d7",
        icon: icons["abi_he_lambentaura"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Rampant Growth I",
		arrows: [
          { dir: "right", from: "c7", to: "d7" },
        ],
        type: "passive",
        description: talentText`Regrowth's effect is now a blessing.`,
      },
	  "Rampant Growth V": {
        name: "Rampant Growth V",
        pos: "e7",
        icon: icons["abi_he_lambentaura"],
        maxRank: 2,
        reqPoints: 20,
        prereq: "Rampant Growth III",
		arrows: [
          { dir: "right", from: "d7", to: "e7" },
        ],
        type: "passive",
        description: talentText`Regrowth will now apply the over time effect to ${[
          1,
          2,
          3,
          4,
          5,
        ]} other allies within 30 feet of the target.`,
      },
	  "Aspect of the Forest": {
        name: "Aspect of the Forest",
        pos: "g7",
        icon: icons["itm_em_blightthorn"],
        maxRank: 1,
        reqPoints: 20,
		prereq: "Barkskin",
		arrows: [
          { dir: "right-down", from: "f6", to: "g6" },
          { dir: "right-down-down", from: "g6", to: "g7" }
        ],
        type: "passive",
        description: talentText`Whenever you augment Barkskin, you also will gain the enchantment effect.`,
      },
	  "Abundance": {
        name: "Abundance",
        pos: "g8",
        icon: icons["abi_he_giftoflife"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Whenever you critically heal someone, you will apply an enchantment on them for 5 seconds. Effect does not refresh. At the end of the duration, target will restore ${[
          "3% RP + 56",
          "7% RP + 92",
          "10% RP + 148",
          "14% RP + 184",
        ]} health.`,
      },
    },
  },
  "Adept of Azyr": {
    name: "Adept of Azyr",
    background: backgrounds["azyr"],
    icon: icons["archetype_offsupport"],
    talents: {
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 1,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 1,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 1,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "Centuries of Training": {
        name: "centuries of Training",
        pos: "a2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you deal direct damage to an enemy, you have a 33% chance to apply one of three debuffs to them. Effects do not refresh and last 6 seconds.\nDeals 4% MAP + 56 impact damage every second.\nDeals 6% RAP + 80 piercing damage every 2 seconds.\nDeals 10% SAP + 134 spiritual damage every 3 seconds.`,
      },
      "Form Ranks": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, each groupmate within 100 feet that has this tactic will gain 1 stack of purity and a 4 second buff. For the duration, gain 450 penetration and 450 sagacity.`,
      },
      "Drain Magic": {
        name: "Drain Magic",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you hit an enemy with an augmented spell, you will dispel one enchantment from them.`,
      },
      "Run Between Worlds": {
        name: "Run Between Worlds",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Walk Between Worlds will no longer increase your cast times and will increase your movement speed by 25% for the duration.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specsword"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Adepts of Ayzr use one-handed swords.`,
      },
      "Radiant Gaze": {
        name: "Radiant Gaze",
        pos: "i4",
        icon: icons["abi_he_radiantglaze"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Target enemy gains 3 stacks of Reduced Corporeal Resistance, Reduced Elemental Resistance, and Reduced Spiritual Resistance.`,
      },
      "Net of Amyntok": {
        name: "Net of Amyntok",
        pos: "i5",
        icon: icons["abi_de_webofshadows"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Target gains a debuff for 5 seconds. For the duration, their movement speed is decreased by 75% and their mass is increased by 3.`,
      },
      "Wings of Heaven": {
        name: "Wings of Heaven",
        pos: "i7",
        icon: icons["abi_he_wingsofheaven"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Gain a debuff for 5 seconds which reduces your mass by 8. Leap forward and apply Ensnared to up to 9 enemies within 20 feet of where you land.\n\nEnsnared reduces movement speed by 30% for 16 seconds.`,
      },
      "Winter's Frost": {
        name: "Winter's Frost",
        pos: "i8",
        icon: icons["abi_de_shadowspike"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 24 enemies within a 20 foot area you select become Rooted, Silenced, and Disarmed.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nSilenced prevents the use of spells for 5 seconds.\nDisarmed prevents the use of skills for 5 seconds.`,
      },
      "Return Life": {
        name: "Return Life",
        pos: "f2",
        icon: icons["morale_returnlife"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Return target groupmate back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Divine Protection": {
        name: "Divine Protection",
        pos: "h2",
        icon: icons["morale_divineprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 15 seconds. They will absorb up to 120% RP + 1600 damage over the duration.`,
      },
      "Alter Fate": {
        name: "Alter Fate",
        pos: "i2",
        icon: icons["morale_alterfate"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Removes all afflictions and cripples from each groupmate within 100 feet. Also applies Return Life to each dead groupmate within 100 feet.`,
      },
      "Winds of Magic": {
        name: "Winds of Magic",
        pos: "a1",
        icon: icons["abi_he_stormofcronos"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Every 3 seconds, you will gain 1 stack of a wind of magic at random (Life, Light, and Heavens) stacking up to a maximum of 3. Whenever you cast a spell of that lore of magic, it will consume one stack, if present, and augment the spell.\n\nYou have access to a no cost, no cooldown toggle ability which prevents you from using winds of magic while active.`,
      },
      "Radiant Lance": {
        name: "Radiant Lance",
        pos: "b1",
        icon: icons["abi_he_radiantlance"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 6% SAP + 133 elemental damage to target enemy. You generate 40 action points.`,
      },
	  "Lightning Bolt": {
        name: "Lightning Bolt",
        pos: "c1",
        icon: icons["abi_ch_zap"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "36 action points",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        blue: "Lore of Heavens",
        description: talentText`Deals 19% SAP + 258 elemental damage to target enemy and applies 1 stack of Reduced Elemental Resistance to them.\n\nAugmented: Deals 11% SAP + 155 corporeal damage to target and 1 stack of Reduced Corporeal Resistance.`,
      },
      "Deadlock": {
        name: "Deadlock",
        pos: "d1",
        icon: icons["abi_he_mindlash"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "45 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Applies Silenced and Inevitable to target enemy.\n\nSilenced prevents the use of spells for 5 seconds.\nInevitable prevents the application of Disarmed and Silenced for 20 seconds.`,
      },
      "Summer Heat": {
        name: "Summer Heat",
        pos: "e1",
        icon: icons["abi_he_searingtouch"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "60 action points",
        range: "100ft range",
        cast: "2.5s cast",
        cooldown: "no cooldown",
        blue: "Lore of Life",
        description: talentText`Applies a 12s ailment to target enemy. For the duration, target takes 20% SAP + 271 corporeal damage every 2 seconds.\n\nAugmented: Reduce the cast time by 1.5 seconds.`,
      },
      "Courage of Aenarion": {
        name: "Courage of Aenarion",
        pos: "f1",
        icon: icons["abi_he_mistressofthemarsh"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Place a 20 foot wide area on the ground. Allies in the area will have their abilities augmented. Enemies in the area will have their movement speed reduced by 50%.`,
      },
      "Abulla's Snare": {
        name: "Abulla's Snare",
        pos: "g1",
        icon: icons["abi_he_windsprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        blue: "Lore of Light",
        description: talentText`Applies Rooted, Immovable, and 3 stacks of Purity to target enemy.\n\nAugmented: Will now also apply to up to 8 other enemies within 30 feet of you.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nImmovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Fortune's Renewal": {
        name: "Fortune's Renewal",
        pos: "h1",
        icon: icons["abi_he_portentoffar"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "30 action points",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Lore of Heavens",
        description: talentText`Applies a 12 second enchantment to target ally. For the duration, their critical hit rate is increased by 15%.\n\nAugmented: applies to up to 5 other allies within 30 feet of target.`,
      },
      "Walk Between Worlds": {
        name: "Walk Between Worlds",
        pos: "i1",
        icon: icons["abi_he_walkbetweenworlds"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        description: talentText`Your damage reduction is increased by 50% and your cast times are increased by 33% for 7 seconds.`,
      },
	  "Barkskin": {
        name: "Barkskin",
        pos: "c4",
        icon: icons["abi_he_skinofstone"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "30 action points",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Lore of Life",
        description: talentText`Applies 1 stack of Enhanced Piercing Resistance, Enhanced Impact Resistance, Enhanced Corporeal Resiatance, Enhanced Fortitude, Reduced Agility, and Reduced Elemental Resistance to target ally.\n\nAugmented: Applies an enchantment for 8 seconds. For the duration their damage reduction is increased by 20%.`,
      },
	  "Cleansing Light": {
        name: "Cleansing Light",
        pos: "c5",
        icon: icons["abi_he_cleansinglight"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "30 action points",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Lore of Light",
        description: talentText`Dispel 1 affliction from target ally and applies 1 stack of Purity.\n\nAugmented: Also dispel 1 cripple and apply another stack of Purity.`,
      },
	  "Urannon's Thunderbolt": {
        name: "Urannon's Thunderbolt",
        pos: "h6",
        icon: icons["abi_dw_explosion02"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "75 action points",
        range: "100ft range",
        cast: "2.5s cast",
        cooldown: "no cooldown",
        blue: "Lore of Heavens",
        description: talentText`Deals 18% SAP + 240 elemental damage to up to 9 enemies within a 20 foot area you select.\n\nAugmented: Reduce the cast time by 1.5 seconds.`,
      },
	  "Brilliance": {
        name: "Briliance",
        pos: "g8",
        icon: icons["abi_he_cleansingflare"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "1.5s cast",
        cooldown: "no cooldown",
        blue: "Lore of Light",
        description: talentText`Deals 4% SAP + 51 spiritual damage, applies 1 stack of Reduced Accuracy, applies 1 stack of Reduced Dodge, and applies 1 stack of Purity to target and up to 8 enemies within 30 feet of them.\n\nAugmented: Deals an additional 4% SAP + 51 spiritual damage.`,
      },
      "First Portent of Amul": {
        name: "First Portent of Amul",
        pos: "d9",
        icon: icons["abi_he_lawofconductivity"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "40 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "15s cooldown",
        blue: "Lore of Heavens",
        description: talentText`Applies 1 stack of a 10 second buff to all groupmates within 100 feet of you. Their next attack will deal double damage.\n\nAugmented: applies 2 stacks.`,
      },
      "Flames of the Phoenix": {
        name: "Flames of Phoenix",
        pos: "f9",
        icon: icons["abi_he_flamesofthephoenix"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "100ft range",
        cast: "3.0s channel",
        cooldown: "30s cooldown",
        description: talentText`Deals 10% SAP + 50 elemental damage every 0.5 seconds to up to 48 enemies within a 30 foot area you select. Each time an enemy is hit by this ability they gain a stack that increases damage they take from this ability by 25% for 1 second. This ability deals no damage to targets that have cover from you.`,
      },
	  "Improved Omens": {
        name: "Improved Omens",
        pos: "e5",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Fortune's Renewal will now also always target you. When augmented, it will apply around you as well.`,
      },
	  "Arc Blast": {
        name: "Arc Blast",
        pos: "h5",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 10,
        prereq: "Shocked",
		arrows: [
          { dir: "right-down", from: "g4", to: "h4" },
          { dir: "right-down-down", from: "h4", to: "h5" }
        ],
        type: "career tactic",
        description: talentText`Whenever you apply Shocked to a target, you will also apply 1 stack of Reduced Hardiness and 1 stack of Reduced Fortitude to them.`,
      },
	  "Eyes of Truth": {
        name: "Eyes of Truth",
        pos: "d6",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`You can see players under Stalk and your abilities will dispel Stalk from enemies hit.`,
      },
	  "Split Lightning": {
        name: "Split Lightning",
        pos: "f6",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Lightning Bolt will now hit 2 additional enemies within 30 feet of the primary target but will deal 20% less damage.`,
      },
	  "Curse of Thorns": {
        name: "Curse of Thorns",
        pos: "e7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Enemies that attack allies affected by your Barkskin, Fortune's Renewal, and Regrowth effects will take 12% SAP + 147 corporeal damage.`,
      },
	  "Fate of Doom": {
        name: "Fate of Doom",
        pos: "g7",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Whenever you deal direct damage to enemies, if they die within 3 seconds, they will have Forlorn.`,
      },
	  "Master of Azyr": {
        name: "Master of Azyr",
        pos: "f8",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Every 5 seconds you generate 1 Wind of Heavens.`,
      },
	  "Signs in the Sky": {
        name: "Signs in the Sky",
        pos: "e3",
        icon: icons["abi_he_rainlord"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever you augment a spell, you will gain a stack of a 15 second buff, maximum 3 stacks.\n\nWhenever you cast Lightning Bolt or Urannon's Thunderbolt, consume all stacks to deal an additional ${[
          3,
          6,
          9,
          12,
        ]}% damage per stack.`,
      },
	  "Shocked": {
        name: "Shocked",
        pos: "g4",
        icon: icons["abi_he_furyofasuryan"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Whenever you critically hit an enemy, apply Shocked to them.\n\nShocked lasts for 10 seconds. Each time the target is hit by Lightning Bolt or Urannon's Thunderbolt, the target will take 4% SAP + 30 indirect elemental damage and refresh the duration of Shocked.`,
      },
	  "Radiant Return": {
        name: "Radiant Return",
        pos: "e6",
        icon: icons["abi_he_radiantlance"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`Radiant Lance will now generate ${[
          46,
          52,
          58,
        ]} action points.`,
      },
	  "Chain Lightning": {
        name: "Chain Lightning",
        pos: "g5",
        icon: icons["abi_he_furyofasuryan"],
        maxRank: 3,
        reqPoints: 10,
        prereq: "Shocked",
		arrows: [
          { dir: "down", from: "g4", to: "g5" },
        ],
        type: "passive",
        description: talentText`Whenever your Shocked status effects deal damage, it will now deal damage to ${[
          1,
          2,
          3,
          4,
          5,
        ]} additional enemies within 30 feet.`,
      },
	  "Improved Lightning Bolt": {
        name: "Improved Lightning Bolt",
        pos: "g6",
        icon: icons["abi_ch_zap"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`The cast time of Lightning Bolt is reduced by ${[
          0.1,
          0.2,
          0.3,
          0.4,
          0.5,
        ]} seconds.`,
      },
	  "Blessing of Asuryan": {
        name: "Blessing of Asuryan",
        pos: "f7",
        icon: icons["abi_he_lawofage"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Gain ${[
          25,
          50,
          75,
          100,
        ]}% pushback immunity.`,
      },
	  "Lightning Storm": {
        name: "Lightning Storm",
        pos: "h7",
        icon: icons["abi_dw_explosion02"],
        maxRank: 3,
        reqPoints: 20,
        prereq: "Urannon's Thunderbolt",
		arrows: [
          { dir: "down", from: "h6", to: "h7" },
        ],
        type: "passive",
        description: talentText`Whenever you augment Lightning Bolt or Urannon's Thunderbolt, it will apply a 2 second debuff to targets hit. At the end of the duration, the target will take ${[
          "2% SAP + 27",
          "4% SAP + 54",
          "6% SAP + 81",
        ]} spiritual damage. This effect can critically hit and triggers Shocked.`,
      },
	  "Aftershock": {
        name: "Aftershock",
        pos: "h8",
        icon: icons["abi_he_whirlingdervish"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Whenever you critically hit an enemy, you will apply a 5 second ailment to them that cannot refresh. At the end of the duration, target will take ${[
          "1% SAP + 15",
          "3% SAP + 45",
          "6% SAP + 90",
          "10% SAP + 150",
        ]} indirect elemental damage.`,
      },
    },
  },
  "Adept of Hysh": {
    name: "Adept of Hysh",
    background: backgrounds["hysh"],
    icon: icons["archetype_healer"],
    talents: {
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 1,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "What a Rush": {
        name: "What a Rush",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`The action point cost of your skills is reduced by 33% on allies that are lower than 40% health.`,
      },
      "Centuries of Training": {
        name: "centuries of Training",
        pos: "a2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you deal direct damage to an enemy, you have a 33% chance to apply one of three debuffs to them. Effects do not refresh and last 6 seconds.\nDeals 4% MAP + 56 impact damage every second.\nDeals 6% RAP + 80 piercing damage every 2 seconds.\nDeals 10% SAP + 134 spiritual damage every 3 seconds.`,
      },
      "Form Ranks": {
        name: "Racial Tactic 2",
        pos: "b2",
        icon: icons["tac_race_helf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, each groupmate within 100 feet that has this tactic will gain 1 stack of purity and a 4 second buff. For the duration, gain 450 penetration and 450 sagacity.`,
      },
      "Drain Magic": {
        name: "Drain Magic",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you hit an enemy with an augmented spell, you will dispel one enchantment from them.`,
      },
      "Run Between Worlds": {
        name: "Run Between Worlds",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Walk Between Worlds will no longer increase your cast times and will increase your movement speed by 25% for the duration.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specstaff"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Adepts of Hysh equip staves.`,
      },
      "Radiant Gaze": {
        name: "Radiant Gaze",
        pos: "i4",
        icon: icons["abi_he_radiantglaze"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Target enemy gains 3 stacks of Reduced Corporeal Resistance, Reduced Elemental Resistance, and Reduced Spiritual Resistance.`,
      },
      "Net of Amyntok": {
        name: "Net of Amyntok",
        pos: "i5",
        icon: icons["abi_de_webofshadows"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Target gains a debuff for 5 seconds. For the duration, their movement speed is decreased by 75% and their mass is increased by 3.`,
      },
      "Wings of Heaven": {
        name: "Wings of Heaven",
        pos: "i7",
        icon: icons["abi_he_wingsofheaven"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Gain a debuff for 5 seconds which reduces your mass by 8. Leap forward and apply Ensnared to up to 9 enemies within 20 feet of where you land.\n\nEnsnared reduces movement speed by 30% for 16 seconds.`,
      },
      "Winter's Frost": {
        name: "Winter's Frost",
        pos: "i8",
        icon: icons["abi_de_shadowspike"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 24 enemies within a 20 foot area you select become Rooted, Silenced, and Disarmed.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nSilenced prevents the use of spells for 5 seconds.\nDisarmed prevents the use of skills for 5 seconds.`,
      },
      "Return Life": {
        name: "Return Life",
        pos: "f2",
        icon: icons["morale_returnlife"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Return target groupmate back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Divine Protection": {
        name: "Divine Protection",
        pos: "h2",
        icon: icons["morale_divineprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 15 seconds. They will absorb up to 120% RP + 1600 damage over the duration.`,
      },
      "Alter Fate": {
        name: "Alter Fate",
        pos: "i2",
        icon: icons["morale_alterfate"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Removes all afflictions and cripples from each groupmate within 100 feet. Also applies Return Life to each dead groupmate within 100 feet.`,
      },
      "Winds of Magic": {
        name: "Winds of Magic",
        pos: "a1",
        icon: icons["abi_he_stormofcronos"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Every 3 seconds, you will gain 1 stack of a wind of magic at random (Life, Light, and Heavens) stacking up to a maximum of 3. Whenever you cast a spell of that lore of magic, it will consume one stack, if present, and augment the spell.\n\nYou have access to a no cost, no cooldown toggle ability which prevents you from using winds of magic while active.`,
      },
      "Radiant Lance": {
        name: "Radiant Lance",
        pos: "b1",
        icon: icons["abi_he_radiantlance"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 6% SAP + 133 elemental damage to target enemy. You generate 40 action points.`,
      },
      "Boon of Hysh": {
        name: "Boon of Hysh",
        pos: "c1",
        icon: icons["abi_he_boonofhyshr"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "60 action points",
        range: "150ft range",
        cast: "2.5s cast",
        cooldown: "10s cooldown",
        blue: "Lore of Light",
        description: talentText`Restores 37% RP + 483 health to target ally.\n\nAugmented: restores an additional 22% RP + 280 health to the target.`,
      },
      "Lightning Bolt": {
        name: "Lightning Bolt",
        pos: "d1",
        icon: icons["abi_ch_zap"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "36 action points",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        blue: "Lore of Heavens",
        description: talentText`Deals 19% SAP + 258 elemental damage to target enemy and applies 1 stack of Reduced Elemental Resistance to them.\n\nAugmented: Deals 11% SAP + 155 corporeal damage to target and 1 stack of Reduced Corporeal Resistance.`,
      },
      "Regrowth": {
        name: "Regrowth",
        pos: "e1",
        icon: icons["abi_he_lambentaura"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "150ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        blue: "Lore of Life",
        description: talentText`Heal target ally for 22% RP + 283.\n\nAugmented: Apply a 21 second enchantment to the target. For the duration, target is healed for 7% RP + 100 every 3 seconds.`,
      },
      "Courage of Aenarion": {
        name: "Courage of Aenarion",
        pos: "f1",
        icon: icons["abi_he_mistressofthemarsh"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Place a 20 foot wide area on the ground. Allies in the area will have their abilities augmented. Enemies in the area will have their movement speed reduced by 50%.`,
      },
      "Deadlock": {
        name: "Deadlock",
        pos: "g1",
        icon: icons["abi_he_mindlash"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "45 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Applies Silenced and Inevitable to target enemy.\n\nSilenced prevents the use of spells for 5 seconds.\nInevitable prevents the application of Disarmed and Silenced for 20 seconds.`,
      },
      "Cleansing Light": {
        name: "Cleansing Light",
        pos: "h1",
        icon: icons["abi_he_cleansinglight"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "30 action points",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Lore of Light",
        description: talentText`Dispel 1 affliction from target ally and applies 1 stack of Purity.\n\nAugmented: Also dispel 1 cripple and apply another stack of Purity.`,
      },
      "Walk Between Worlds": {
        name: "Walk Between Worlds",
        pos: "i1",
        icon: icons["abi_he_walkbetweenworlds"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        description: talentText`Your damage reduction is increased by 50% and your cast times are increased by 33% for 7 seconds.`,
      },
	  "Star Tide's Ebb": {
        name: "Star Tide's Ebb",
        pos: "h4",
        icon: icons["abi_he_distractingshot"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "40 action points",
        range: "100ft range",
        cast: "1.0s cast",
        cooldown: "12s cooldown",
        blue: "Lore of Heavens",
        description: talentText`Applies an affliction to target enemy for 12 seconds. For the duration, target's cast times are increased by 33%.\n\nAugmented: The effect becomes a cripple and also increases their cooldowns by 33%.`,
      },
	  "Summer Heat": {
        name: "Summer Heat",
        pos: "c5",
        icon: icons["abi_he_searingtouch"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "60 action points",
        range: "100ft range",
        cast: "2.5s cast",
        cooldown: "no cooldown",
        blue: "Lore of Life",
        description: talentText`Applies a 12s ailment to target enemy. For the duration, target takes 20% SAP + 271 corporeal damage every 2 seconds.\n\nAugmented: Reduce the cast time by 1.5 seconds.`,
      },
	  "Brilliance": {
        name: "Briliance",
        pos: "g6",
        icon: icons["abi_he_cleansingflare"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "1.5s cast",
        cooldown: "no cooldown",
        blue: "Lore of Light",
        description: talentText`Deals 4% SAP + 51 spiritual damage, applies 1 stack of Reduced Accuracy, applies 1 stack of Reduced Dodge, and applies 1 stack of Purity to target and up to 8 enemies within 30 feet of them.\n\nAugmented: Deals an additional 4% SAP + 51 spiritual damage.`,
      },
	  "Barkskin": {
        name: "Barkskin",
        pos: "e8",
        icon: icons["abi_he_skinofstone"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "30 action points",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Lore of Life",
        description: talentText`Applies 1 stack of Enhanced Piercing Resistance, Enhanced Impact Resistance, Enhanced Corporeal Resiatance, Enhanced Fortitude, Reduced Agility, and Reduced Elemental Resistance to target ally.\n\nAugmented: Applies an enchantment for 8 seconds. For the duration their damage reduction is increased by 20%.`,
      },
	  "Healing Energy": {
        name: "Healing Energy",
        pos: "d9",
        icon: icons["abi_he_healingenergy"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "20 action points",
        range: "150ft range",
        cast: "1.5s cast",
        cooldown: "no cooldown",
        blue: "Lore of Light\nCastable While Moving",
        description: talentText`Restore 7% RP + 87 health and apply 1 stack of Purity to target ally.\n\nAugmented: Restore an additional 6% RP + 66 health.`,
      },
      "Flames of the Phoenix": {
        name: "Flames of Phoenix",
        pos: "f9",
        icon: icons["abi_he_flamesofthephoenix"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "100ft range",
        cast: "3.0s channel",
        cooldown: "30s cooldown",
        description: talentText`Deals 10% SAP + 50 elemental damage every 0.5 seconds to up to 48 enemies within a 30 foot area you select. Each time an enemy is hit by this ability they gain a stack that increases damage they take from this ability by 25% for 1 second. This ability deals no damage to targets that have cover from you.`,
      },
	  "Apotheosis": {
        name: "Apothesosis",
        pos: "a5",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Cleansing Light will now apply a 9 second enchantment to the target, stacking up to 3 times. For the duration, they will be healed for 3% RP + 50 every 3 seconds.`,
      },
	  "Pha's Protection": {
        name: "Pha's Protection",
        pos: "g5",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Your outgoing healing is reduced by 10%.\n\nWhenever you cast Radiant Lance or Healing Energy, your defensive target is blessed for 10 seconds if they are a groupmate and within 150 feet of you.\n\nYour heals are 35% more effective against targets with Pha's Protection.`,
      },
	  "Daemonbane": {
        name: "daemonbane",
        pos: "b6",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Whenever you deal direct damage against an enemy that has any chaos corruption, you will deal 33% additional damage. In addition, for the next 6 seconds, your outgoing healing will be increased by 10%.`,
      },
	  "Starshine": {
        name: "Starshine",
        pos: "h6",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Star Tide's Ebb",
		arrows: [
          { dir: "down", from: "h4", to: "h6" },
        ],
        type: "career tactic",
        description: talentText`Star Tide's Ebb no longer has a cooldown but the duration is decreased to 8 seconds.`,
      },
	  "Shallya's Blessing": {
        name: "Shallya's Blessing",
        pos: "a7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Boon of Hysh will now heal all groupmates within 100 feet of you when cast, but will heal for 60% less.`,
      },
	  "Bolt of Illumination": {
        name: "Bolt of Illumination",
        pos: "g7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Brilliance",
		arrows: [
          { dir: "down", from: "g6", to: "g7" },
        ],
        type: "career tactic",
        description: talentText`Brilliance will now deals its damage 4 times to the target and apply 4 stacks of each of its effects. The ability no longer affects targets beyond the primary.`,
      },
	  "Master of Hysh": {
        name: "Master of Hysh",
        pos: "f8",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Every 5 seconds you generate 1 Wind of Light.`,
      },
	  "Lightbloom": {
        name: "Lightbloom",
        pos: "e3",
        icon: icons["abi_he_blessingofisha"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever you augment a spell, ${[
          1,
          2,
          3,
          4,
          5,
        ]} groupmates within 100 feet of you gain a stack of Purity.`,
      },
	  "Blessing of Asuryan": {
        name: "Blessing of Asuryan",
        pos: "b4",
        icon: icons["abi_he_lawofage"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Gain ${[
          25,
          50,
          75,
          100,
        ]}% pushback immunity.`,
      },
	  "Enlightenment": {
        name: "Enlightenment",
        pos: "e5",
        icon: icons["abi_he_embodimentofminaith"],
        maxRank: 1,
        reqPoints: 10,
        type: "passive",
        description: talentText`You have 2% increased damage reduction from an enemy per stack of Purity they have.`,
      },
	  "Drain Life": {
        name: "Drain Life",
        pos: "c6",
        icon: icons["abi_he_balanceessence"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`Radiant Lance will heal your defensive target for ${[
          150,
          300,
        ]}% of the damage dealt.`,
      },
	  "Speed of Light": {
        name: "Speed of Light",
        pos: "e6",
        icon: icons["abi_he_boonofhyshr"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Reduce the cooldown on Boon of Hysh by ${[
          1,
          2,
          3,
          4,
          5,
        ]} seconds.`,
      },
	  "Inspiration": {
        name: "Inspiration",
        pos: "c7",
        icon: icons["abi_he_lawofgold"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Whenever you heal a target with Boon of Hysh or Healing Energy, their AP regen will be increased by ${[
          1,
          3,
          5,
        ]} for 3 seconds.`,
      },
	  "Shimmering Cloak": {
        name: "Shimmering Cloak",
        pos: "e7",
        icon: icons["abi_he_walkbetweenworlds"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Reduce the cooldown on Walk Between Worlds by ${[
          5,
          10,
          15,
        ]} seconds.`,
      },
	  "Purifying Lights": {
        name: "Purifying Lights",
        pos: "g8",
        icon: icons["abi_he_magicalinfusion"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`You have ${[
          1,
          2,
          3,
          5,
        ]}% outgoing damage and healing against any target (ally or enemy) per stack of Purity on them.`,
      },
    },
  },
};
