import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/dwarf"),
);
const icons = requireAll(require.context("../../assets/icons/dwarf"));

export const data: TalentData = {
  "Rifleman": {
    name: "Rifleman",
    background: backgrounds["rifleman"],
    icon: icons["archetype_dps"],
    talents: {
      "Motivated": {
        name: "Motivated",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "b2",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 5 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 20 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "b4",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "b6",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a6",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a8",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Increases your mass by 1.`,
      },
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a9",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "b5",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases your Agility by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "b7",
        icon: icons["stat_bal"],
        maxRank: 4,
        reqPoints: 30,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "b3",
        icon: icons["stat_ini"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e7",
        icon: icons["stat_int"],
        maxRank: 2,
        reqPoints: 30,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "h7",
        icon: icons["stat_str"],
        maxRank: 4,
        reqPoints: 30,
        description: talentText`Increases your Strength by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "e5",
        icon: icons["stat_tou"],
        maxRank: 4,
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "h3",
        icon: icons["stat_wil"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "h5",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "e3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Disengage": {
        name: "Disengage",
        pos: "i2",
        icon: icons["morale_disengage"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`level 1\n30ft range\n360 adrenaline\ninstant cast\nability\n\nYou knock yourself back away from target enemy.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "i4",
        icon: icons["morale_focusedmind"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`level 2\n720 adrenaline\ninstant cast\nability\n\nFor the next 15 seconds, your abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Explosive Impact": {
        name: "Explosive Impact",
        pos: "i6",
        icon: icons["morale_explosiveimpact"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`level 3\n1800 adrenaline\ninstant cast\nability\n\nFor the next 10 seconds, whenever you hit a target with a single-target ability, you will deal 20% RAP + 150 corporeal damage and 20% SAP + 150 elemental damage to up to 24 enemies within 20ft of the target.`,
      },
      "Unleash the Winds": {
        name: "Unleash the Winds",
        pos: "i8",
        icon: icons["morale_unleashthewinds"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 4\n100ft range\n3600 adrenaline\ninstant cast\nability\n\nUp to 96 enemies within a 20ft location are knocked straight up into the air.`,
      },
      "Morale 3 Race": {
        name: "Morale 3r",
        pos: "b8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 3\n100ft range\n1800 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 1 Class": {
        name: "Morale 1c",
        pos: "h2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`level 1\n100ft range\n360 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 2 Class": {
        name: "Morale 2c",
        pos: "h4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`level 2\n100ft range\n720 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "h6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`level 1\n100ft range\n360 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "h8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 2\n100ft range\n720 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`level 4\n100ft range\n3600 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Your range is increased by 20%.`,
      "Race Tactic 1": {
        name: "Archetype Tactic",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`placeholder atm`,
      },
      "Race Tactic 2": {
        name: "Race Tactic 2",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`placeholder atm`,
      },
      "Power Ability 1": {
        name: "Power Aility 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Power Ability 2": {
        name: "Power Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`100ft range\n100 AP\n2.0s cast\n5.0s CD\nability\n\nDescription`,
      },
      "Wounds II": {
        name: "Wounds II",
        pos: "f8",
        icon: icons["stat_wou"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wounds",
        arrows: [{ dir: "down", from: "f7", to: "f8" }],
        description: talentText`100ft range\n50 AP\n2.0s cast\n5.0s CD\nabilityskillspell\n\nDescription`,
      },
    },
  },
  "Grenadier": {
    name: "Grenadier",
    background: backgrounds["grenadier"],
    icon: icons["archetype_dps"],
      "Motivated": {
        name: "Motivated",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "b2",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 5 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 20 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "b4",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "b6",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a6",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a8",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Increases your mass by 1.`,
      },
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a9",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "b5",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases your Agility by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "b7",
        icon: icons["stat_bal"],
        maxRank: 4,
        reqPoints: 30,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "b3",
        icon: icons["stat_ini"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e7",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "h7",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Strength by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "e5",
        icon: icons["stat_tou"],
        maxRank: 4,
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "h3",
        icon: icons["stat_wil"],
        maxRank: 4,
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "h5",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "e3",
        icon: icons["stat_ws"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Disengage": {
        name: "Disengage",
        pos: "i2",
        icon: icons["morale_disengage"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`level 1\n30ft range\n360 adrenaline\ninstant cast\nability\n\nYou knock yourself back away from target enemy.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "i4",
        icon: icons["morale_focusedmind"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`level 2\n720 adrenaline\ninstant cast\nability\n\nFor the next 15 seconds, your abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Explosive Impact": {
        name: "Explosive Impact",
        pos: "i6",
        icon: icons["morale_explosiveimpact"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`level 3\n1800 adrenaline\ninstant cast\nability\n\nFor the next 10 seconds, whenever you hit a target with a single-target ability, you will deal 20% RAP + 150 corporeal damage and 20% SAP + 150 elemental damage to up to 24 enemies within 20ft of the target.`,
      },
      "Unleash the Winds": {
        name: "Unleash the Winds",
        pos: "i8",
        icon: icons["morale_unleashthewinds"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 4\n100ft range\n3600 adrenaline\ninstant cast\nability\n\nUp to 96 enemies within a 20ft location are knocked straight up into the air.`,
      },
      "Morale 3 Race": {
        name: "Morale 3r",
        pos: "b8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 3\n100ft range\n1800 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 1 Class": {
        name: "Morale 1c",
        pos: "h2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`level 1\n100ft range\n360 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 2 Class": {
        name: "Morale 2c",
        pos: "h4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`level 2\n100ft range\n720 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "h6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`level 1\n100ft range\n360 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "h8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 2\n100ft range\n720 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`level 4\n100ft range\n3600 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Your range is increased by 20%.`,
      },
      "Race Tactic 1": {
        name: "Archetype Tactic",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`placeholder atm`,
      },
      "Race Tactic 2": {
        name: "Race Tactic 2",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`placeholder atm`,
      },
      "Power Ability 1": {
        name: "Power Aility 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Power Ability 2": {
        name: "Power Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`100ft range\n100 AP\n2.0s cast\n5.0s CD\nability\n\nDescription`,
      },
      "Wounds II": {
        name: "Wounds II",
        pos: "f8",
        icon: icons["stat_wou"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wounds",
        arrows: [{ dir: "down", from: "f7", to: "f8" }],
        description: talentText`100ft range\n50 AP\n2.0s cast\n5.0s CD\nabilityskillspell\n\nDescription`,
      },
    },
  },
  "Tinkerer": {
    name: "Tinkerer",
    background: backgrounds["tinkerer"],
    icon: icons["archetype_tank"],
    talents: {
      "Motivated": {
        name: "Motivated",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "b2",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 5 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 20 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "b4",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "b6",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a6",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a8",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Increases your mass by 1.`,
      },
      "Loved By All": {
        name: "Loved By All",
        pos: "a9",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`You always have Unstoppable. Your mass is decreased by 2.`,
      },
      "Agility": {
        name: "Agility",
        pos: "b5",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases your Agility by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "b7",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 30,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "b3",
        icon: icons["stat_ini"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e7",
        icon: icons["stat_int"],
        maxRank: 2,
        reqPoints: 30,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "h7",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Strength by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "e5",
        icon: icons["stat_tou"],
        maxRank: 5,
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "h3",
        icon: icons["stat_wil"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "h5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "e3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Hedgehog": {
        name: "Hedgehog",
        pos: "i2",
        icon: icons["morale_hedgehog"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`level 1\n360 adrenaline\ninstant cast\nability\n\nAll groupmates within 100 ft gain 3 stacks of Enhanced Block.`,
      },
      "Champion's Challenge": {
        name: "Champion's Chalenge",
        pos: "i4",
        icon: icons["morale_grapple"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`level 2\nmelee range\n720 adrenaline\ninstant cast\nability\n\nTarget enemy and yourself have your movement speed reduced to 0 for 10 seconds.`,
      },
      "Distracting Bellow": {
        name: "Distracting Bellow",
        pos: "i6",
        icon: icons["morale_distractingbellow"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`level 3\n1800 adrenaline\ninstant cast\nability\n\nUp to 48 enemies within 30ft of you receive a tier3 debuff. For 10 seconds, they cannot benefit from Cover.`,
      },
      "Immaculate Defense": {
        name: "Immaculate Defense",
        pos: "i8",
        icon: icons["morale_immaculatedefense"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 4\n3600 adrenaline\ninstant cast\nability\n\nGroupmates within 100ft gain 25 stacks of a tier3 buff for 20 seconds. Each stack grants 3% damage reduction. A stack is removed each time they are attacked by an ability; 4 additional stacks are removed if the ability is single target.`,
      },
      "Morale 3 Race": {
        name: "Morale 3r",
        pos: "b8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 3\n100ft range\n1800 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 1 Class": {
        name: "Morale 1c",
        pos: "h2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`level 1\n100ft range\n360 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 2 Class": {
        name: "Morale 2c",
        pos: "h4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`level 2\n100ft range\n720 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "h6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`level 1\n100ft range\n360 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "h8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 2\n100ft range\n720 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`level 4\n100ft range\n3600 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Increase your mass by 1.`,
      },
      "Race Tactic 1": {
        name: "Archetype Tactic",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`placeholder atm`,
      },
      "Race Tactic 2": {
        name: "Race Tactic 2",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`placeholder atm`,
      },
      "Power Ability 1": {
        name: "Power Aility 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Power Ability 2": {
        name: "Power Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`100ft range\n100 AP\n2.0s cast\n5.0s CD\nability\n\nDescription`,
      },
      "Wounds II": {
        name: "Wounds II",
        pos: "f8",
        icon: icons["stat_wou"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wounds",
        arrows: [{ dir: "down", from: "f7", to: "f8" }],
        description: talentText`100ft range\n50 AP\n2.0s cast\n5.0s CD\nabilityskillspell\n\nDescription`,
      },
    },
  },
};
