import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/dwarf"),
);
const icons = requireAll(require.context("../../assets/icons/dwarf"));

export const data: TalentData = {
  "Rifleman": {
    name: "Rifleman",
    background: backgrounds["rifleman"],
    icon: icons["archetype_dps"],
    talents: {
      "Motivated": {
        name: "Motivated",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "b2",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 5 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 20 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "b4",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "b6",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a6",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a8",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Increases your mass by 1.`,
      },
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a9",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "b5",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases your Agility by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "b7",
        icon: icons["stat_bal"],
        maxRank: 4,
        reqPoints: 30,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "b3",
        icon: icons["stat_ini"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e7",
        icon: icons["stat_int"],
        maxRank: 2,
        reqPoints: 30,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "h7",
        icon: icons["stat_str"],
        maxRank: 4,
        reqPoints: 30,
        description: talentText`Increases your Strength by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "e5",
        icon: icons["stat_tou"],
        maxRank: 4,
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "h3",
        icon: icons["stat_wil"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "h5",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "e3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Disengage": {
        name: "Disengage",
        pos: "i2",
        icon: icons["morale_disengage"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`level 1\n30ft range\n360 adrenaline\ninstant cast\nability\n\nYou knock yourself back away from target enemy.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "i4",
        icon: icons["morale_focusedmind"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`level 2\n720 adrenaline\ninstant cast\nability\n\nFor the next 15 seconds, your abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Explosive Impact": {
        name: "Explosive Impact",
        pos: "i6",
        icon: icons["morale_explosiveimpact"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`level 3\n1800 adrenaline\ninstant cast\nability\n\nFor the next 10 seconds, whenever you hit a target with a single-target ability, you will deal 20% RAP + 150 corporeal damage and 20% SAP + 150 elemental damage to up to 24 enemies within 20ft of the target.`,
      },
      "Unleash the Winds": {
        name: "Unleash the Winds",
        pos: "i8",
        icon: icons["morale_unleashthewinds"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 4\n100ft range\n3600 adrenaline\ninstant cast\nability\n\nUp to 96 enemies within a 20ft location are knocked straight up into the air.`,
      },
      "Mountain Spirit": {
        name: "Mountain Spirit",
        pos: "b8",
        icon: icons["morale_mountainspirit"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 3\n1800 adrenaline\ninstant cast\nability\n\nAll groupmates within 100ft of you gain 1000 armor, 500 corporeal resistance, and 500 elemental resistance.`,
      },
      "Cannon Smash": {
        name: "Cannon Smash",
        pos: "h2",
        icon: icons["morale_cannonsmash"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`level 1\n100ft range\n360 adrenaline\ninstant cast\nability\n\nDeals 30% RAP + 300 physical damage to the target and applies 3 stacks of Reduced Armor.`,
      },
      "Autoloader": {
        name: "Autoloader",
        pos: "h4",
        icon: icons["morale_autoloader"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`level 2\n100ft range\n720 adrenaline\ninstant cast\nability\n\nFor the next 8 seconds, your skills do not consume bullets or grenades.`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "h6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`level 1\n100ft range\n360 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "h8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 2\n100ft range\n720 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`level 4\n100ft range\n3600 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Your range is increased by 20%.`,
      },
      "Ancestral Inheritance": {
        name: "Archetype Tactic",
        pos: "a1",
        icon: icons["tac_race_dwarf"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`You are immune to effects that apply Reduced Armor.`,
      },
      "Stoutness of Stone": {
        name: "Race Tactic 2",
        pos: "i1",
        icon: icons["tac_race_dwarf"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Your mass is increased by 1.`,
      },
      "Craft Munitions": {
        name: "Craft Munitions",
        pos: "b1",
        icon: icons["abi_craft"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`50 AP\n3.0s cast\nskill\n\nYou generate 1 bullet, 1 grenade, and 1 kit. Can be cast while moving and has 0% pushback immunity.`,
      },
      "Contraband Munitions": {
        name: "Contraband Munitions",
        pos: "c1",
        icon: icons["tac_class_2"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Craft Munitions",
        arrows: [{ dir: "right", from: "b1", to: "c1" }],
        description: talentText`Craft Munitions now costs 75 AP and a 1.0s cast time.`,
      },
      "Gun Blast": {
        name: "Gun Blast",
        pos: "d1",
        icon: icons["abi_gunblast"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`125ft range\n1 bullet\n2.5s cast\nskill\n\nDeals %50 RAP + 500 physical damage to target.`,
      },
      "Improved Gun Blast": {
        name: "Improved Gunbast",
        pos: "d2",
        icon: icons["abi_gunblast"],
        maxRank: 2,
        reqPoints: 5,
        prereq: "Gun Blast",
        arrows: [{ dir: "down", from: "d1", to: "d2" }],
        description: talentText`Reduces the cast time of Gun Blast by ${[
          0.25,
          0.5,
        ]}seconds.`,
      },
      "Hollow Points": {
        name: "Hollow Points",
        pos: "d4",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Improved Gun Blast",
        arrows: [{ dir: "down", from: "d2", to: "d4" }],
        description: talentText`Gun Blast will now deal 50% RAP physical damage after 5 seconds but the initial hit will always be blocked.`,
      },
      "Concussion Grenade": {
        name: "Concussion Grenade",
        pos: "e1",
        icon: icons["abi_concussiong"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`65ft range\n1 grenade\ninstant cast\nskill\n\nKnocks the target away from you and applies Immovable to them\n\nImmovable prevents application of Rooted and the target from being Knocked Back or Pulled for 20 seconds.`,
      },
      "Incendiary Round": {
        name: "Incendiary Round",
        pos: "f1",
        icon: icons["abi_incendiaryround"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`125ft range\n1 bullet\ninstant cast\nskill\n\nApplies a tier1 debuff to the target that deals 30% RAP + 60 corporeal damage every 3 seconds over 15 seconds.`,
      },
      "Signal Flare": {
        name: "Signal Flare",
        pos: "f4",
        icon: icons["abi_signalflare"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Incendiary Round",
        arrows: [{ dir: "down", from: "f1", to: "f4" }],
        description: talentText`125ft range\n1 bullet\ninstant cast\nskill\n\nApplies a tier2 debuff to target enemy that deals 12.5% RAP + 70 physical damage every 3 seconds over 21 seconds.`,
      },
      "Coordinated Fire": {
        name: "Coordinated Fire",
        pos: "f8",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Signal Flare",
        arrows: [{ dir: "down", from: "f4", to: "f8" }],
        description: talentText`Coordinated Fire now has a 12 second duration and cooldown. It will now cause the target to take 15% increased damage for the duration.`,
      },
      "Gun Turret": {
        name: "Gun Turret",
        pos: "g1",
        icon: icons["abi_gunturret"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`2 kit\ninstant cast\nskill\n\n(Deployment)Summon a gun turret at your feet that will attack enemies within 125ft of it. It will give you 1 bullet every 2 seconds if you are within 20ft of it.\n\nYou can only have one Deployment skill active.`,
      },
      "Self Destruct": {
        name: "Self Destruct",
        pos: "g2",
        icon: icons["abi_selfdestruct"],
        maxRank: 1,
        reqPoints: 5,
        prereq: "Gun Turret",
        arrows: [{ dir: "down", from: "g1", to: "g2" }],
        description: talentText`1 kit\ninstant cast\n45s CD\nspell\n\nDestroy your Deployment device to apply Knocked-down and Unstoppable to up to 6 enemies within 20ft of it.\n\nKnocked-down prevents all control of your character for 3 seconds. Unstoppable prevents application of Knocked-down or Staggered for 30 seconds.`,
      },
      "Ammo Pack": {
        name: "Ammo Pack",
        pos: "h1",
        icon: icons["abi_ammopack"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`30ft range\n1 kit\ninstant cast\nability\n\nGives 100 action points to target groupmate.`,
      },
      "Recycle": {
        name: "Recycle",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You have a 33% chance to recover any bullet, grenade, or kit you spend.`,
      },
      "Thousand Meter Stare": {
        name: "Thousand Meter Stare",
        pos: "e2",
        icon: icons["abi_detaunt"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`150ft range\ninstant cast\n15.0s CD\nability\n\nReduces the damage target does to you by 50% for 15 seconds. Effect will be removed if you hit the opponent with an ability.`,
      },
      "Fire Bomb": {
        name: "Fire Bomb",
        pos: "c4",
        icon: icons["abi_firebomb"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`65ft range\n1 grenade\ninstant cast\nskill\n\nDeals 10% RAP + 100 corporeal damage to up to 3 enemies within a 20ft area.`,
      },
      "Extra Powder": {
        name: "Extra Powder",
        pos: "c6",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Fire Bomb",
        arrows: [{ dir: "down", from: "c4", to: "c6" }],
        description: talentText`Fire Bomb will now hit up to 12 enemies.`,
      },
      "Phosphorous Shell": {
        name: "Phosphorous Shell",
        pos: "g4",
        icon: icons["abi_pshell"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`125ft range\n1 bullet\n1.0s cast\nskill\n\nDeals 18% RAP + 180 corporeal damage to the target. Then it applies a tier1 debuff for 12 seconds to the target and up to 2 enemies within 20ft of them that deals 30% RAP + 15 corporeal damage every 3 seconds.`,
      },
      "White Phosphorous Bomb": {
        name: "White Phosphorous Bomb",
        pos: "g8",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Phosphorous Shell",
        arrows: [{ dir: "down", from: "g4", to: "g8" }],
        description: talentText`The secondary effect will now hit up to 11 enemies.`,
      },
      "Pierce Defenses": {
        name: "Pierce Defenses",
        pos: "d6",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`Whenever a target dodges or blocks an ability that uses bullets, they will take 1 stack of Reduced Armor and 1 stack of Reduced Corporeal Resistance.`,
      },
      "Trench Fighting": {
        name: "Trench Fighting",
        pos: "g6",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`Your single target abilities will deal 15% more damage when you are under 50ft away from them, but deal 5% less damage otherwise.`,
      },
      "Crack Shot": {
        name: "Crack Shot",
        pos: "c8",
        icon: icons["abi_crackshot"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`125ft range\n1 bullet\ninstant cast\n10s CD\nskill\n\nDeals 160 physical damage to the target and applies Diarmed and Inevitable.\n\nDisarmed prevents the use of skills for 5 seconds. Inevitable prevents the application of Disarmed and Silenced effects.`,
      },
      "Improved Crack Shot": {
        name: "Improved Crack Shot",
        pos: "d8",
        icon: icons["abi_crackshot"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Crackshot",
        arrows: [{ dir: "right", from: "c8", to: "d8" }],
        description: talentText`Crack Shot now deals an additional 37% RAP physical damage.`,
      },
      "Depleted Runic Rounds": {
        name: "Depleted Runic Rounds",
        pos: "e8",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Every ability that uses bullets will deal an additional 10% RAP corporeal damage.`,
      },
      "Snipe": {
        name: "Snipe",
        pos: "d9",
        icon: icons["abi_snipe"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`150ft range\n1 bullet\n3.0s cast\nskill\n\nDeals 70% RAP + 400 physical damage to the target. Applies 1 stack of Reduced Dodge.`,
      },
      "Focused Fire": {
        name: "Focused Fire",
        pos: "f9",
        icon: icons["abi_focusedfire"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`100ft range\n4 bullets\n3.0s channel\nskill\n\nDeals 20% RAP + 125 physical damage four times over the channel.`,
      },
    },
  },
  "Grenadier": {
    name: "Grenadier",
    background: backgrounds["grenadier"],
    icon: icons["archetype_dps"],
    talents: {
      "Motivated": {
        name: "Motivated",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "b2",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 5 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 20 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "b4",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "b6",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a6",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a8",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Increases your mass by 1.`,
      },
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a9",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "b5",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases your Agility by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "b7",
        icon: icons["stat_bal"],
        maxRank: 4,
        reqPoints: 30,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "b3",
        icon: icons["stat_ini"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e7",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "h7",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Strength by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "e5",
        icon: icons["stat_tou"],
        maxRank: 4,
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "h3",
        icon: icons["stat_wil"],
        maxRank: 4,
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "h5",
        icon: icons["stat_wou"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "e3",
        icon: icons["stat_ws"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Disengage": {
        name: "Disengage",
        pos: "i2",
        icon: icons["morale_disengage"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`level 1\n30ft range\n360 adrenaline\ninstant cast\nability\n\nYou knock yourself back away from target enemy.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "i4",
        icon: icons["morale_focusedmind"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`level 2\n720 adrenaline\ninstant cast\nability\n\nFor the next 15 seconds, your abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Explosive Impact": {
        name: "Explosive Impact",
        pos: "i6",
        icon: icons["morale_explosiveimpact"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`level 3\n1800 adrenaline\ninstant cast\nability\n\nFor the next 10 seconds, whenever you hit a target with a single-target ability, you will deal 20% RAP + 150 corporeal damage and 20% SAP + 150 elemental damage to up to 24 enemies within 20ft of the target.`,
      },
      "Unleash the Winds": {
        name: "Unleash the Winds",
        pos: "i8",
        icon: icons["morale_unleashthewinds"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 4\n100ft range\n3600 adrenaline\ninstant cast\nability\n\nUp to 96 enemies within a 20ft location are knocked straight up into the air.`,
      },
      "Mountain Spirit": {
        name: "Mountain Spirit",
        pos: "b8",
        icon: icons["morale_mountainspirit"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 3\n1800 adrenaline\ninstant cast\nability\n\nAll groupmates within 100ft of you gain 1000 armor, 500 corporeal resistance, and 500 elemental resistance.`,
      },
      "Cannon Smash": {
        name: "Cannon Smash",
        pos: "h2",
        icon: icons["morale_cannonsmash"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`level 1\n100ft range\n360 adrenaline\ninstant cast\nability\n\nDeals 30% RAP + 300 physical damage to the target and applies 3 stacks of Reduced Armor.`,
      },
      "Autoloader": {
        name: "Autoloader",
        pos: "h4",
        icon: icons["morale_autoloader"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`level 2\n100ft range\n720 adrenaline\ninstant cast\nability\n\nFor the next 8 seconds, your skills do not consume bullets or grenades.`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "h6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`level 1\n100ft range\n360 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "h8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 2\n100ft range\n720 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`level 4\n100ft range\n3600 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Your range is increased by 20%.`,
      },
      "Race Tactic 1": {
        name: "Archetype Tactic",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`placeholder atm`,
      },
      "Race Tactic 2": {
        name: "Race Tactic 2",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`placeholder atm`,
      },
      "Power Ability 1": {
        name: "Power Aility 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Power Ability 2": {
        name: "Power Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`100ft range\n100 AP\n2.0s cast\n5.0s CD\nability\n\nDescription`,
      },
      "Wounds II": {
        name: "Wounds II",
        pos: "f8",
        icon: icons["stat_wou"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wounds",
        arrows: [{ dir: "down", from: "f7", to: "f8" }],
        description: talentText`100ft range\n50 AP\n2.0s cast\n5.0s CD\nabilityskillspell\n\nDescription`,
      },
    },
  },
  "Tinkerer": {
    name: "Tinkerer",
    background: backgrounds["tinkerer"],
    icon: icons["archetype_tank"],
    talents: {
      "Motivated": {
        name: "Motivated",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "b2",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 5 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 20 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "b4",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "b6",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a6",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a8",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Increases your mass by 1.`,
      },
      "Loved By All": {
        name: "Loved By All",
        pos: "a9",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`You always have Unstoppable. Your mass is decreased by 2.`,
      },
      "Agility": {
        name: "Agility",
        pos: "b5",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases your Agility by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "b7",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 30,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "b3",
        icon: icons["stat_ini"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e7",
        icon: icons["stat_int"],
        maxRank: 2,
        reqPoints: 30,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "h7",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Strength by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "e5",
        icon: icons["stat_tou"],
        maxRank: 5,
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "h3",
        icon: icons["stat_wil"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "h5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "e3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Hedgehog": {
        name: "Hedgehog",
        pos: "i2",
        icon: icons["morale_hedgehog"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`level 1\n360 adrenaline\ninstant cast\nability\n\nAll groupmates within 100 ft gain 3 stacks of Enhanced Block.`,
      },
      "Champion's Challenge": {
        name: "Champion's Chalenge",
        pos: "i4",
        icon: icons["morale_grapple"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`level 2\nmelee range\n720 adrenaline\ninstant cast\nability\n\nTarget enemy and yourself have your movement speed reduced to 0 for 10 seconds.`,
      },
      "Distracting Bellow": {
        name: "Distracting Bellow",
        pos: "i6",
        icon: icons["morale_distractingbellow"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`level 3\n1800 adrenaline\ninstant cast\nability\n\nUp to 48 enemies within 30ft of you receive a tier3 debuff. For 10 seconds, they cannot benefit from Cover.`,
      },
      "Immaculate Defense": {
        name: "Immaculate Defense",
        pos: "i8",
        icon: icons["morale_immaculatedefense"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 4\n3600 adrenaline\ninstant cast\nability\n\nGroupmates within 100ft gain 25 stacks of a tier3 buff for 20 seconds. Each stack grants 3% damage reduction. A stack is removed each time they are attacked by an ability; 4 additional stacks are removed if the ability is single target.`,
      },
      "Mountain Spirit": {
        name: "Mountain Spirit",
        pos: "b8",
        icon: icons["morale_mountainspirit"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 3\n1800 adrenaline\ninstant cast\nability\n\nAll groupmates within 100ft of you gain 1000 armor, 500 corporeal resistance, and 500 elemental resistance.`,
      },
      "Cannon Smash": {
        name: "Cannon Smash",
        pos: "h2",
        icon: icons["morale_cannonsmash"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`level 1\n100ft range\n360 adrenaline\ninstant cast\nability\n\nDeals 30% RAP + 300 physical damage to the target and applies 3 stacks of Reduced Armor.`,
      },
      "Autoloader": {
        name: "Autoloader",
        pos: "h4",
        icon: icons["morale_autoloader"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`level 2\n100ft range\n720 adrenaline\ninstant cast\nability\n\nFor the next 8 seconds, your skills do not consume bullets or grenades.`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "h6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`level 1\n100ft range\n360 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "h8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`level 2\n100ft range\n720 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`level 4\n100ft range\n3600 adrenaline\ninstant cast\nability\n\nDescription`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Increase your mass by 1.`,
      },
      "Race Tactic 1": {
        name: "Archetype Tactic",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`placeholder atm`,
      },
      "Race Tactic 2": {
        name: "Race Tactic 2",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`placeholder atm`,
      },
      "Power Ability 1": {
        name: "Power Aility 1",
        pos: "d9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Power Ability 2": {
        name: "Power Ability 2",
        pos: "f9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`100ft range\n100 AP\n2.0s cast\n5.0s CD\nability\n\nDescription`,
      },
      "Wounds II": {
        name: "Wounds II",
        pos: "f8",
        icon: icons["stat_wou"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wounds",
        arrows: [{ dir: "down", from: "f7", to: "f8" }],
        description: talentText`100ft range\n50 AP\n2.0s cast\n5.0s CD\nabilityskillspell\n\nDescription`,
      },
    },
  },
};
