import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/chaos"),
);
const icons = requireAll(require.context("../../assets/icons/chaos"));

export const data: TalentData = {
  "Soulflayer": {
    name: "Soulflayer",
    background: backgrounds["magus-slaanesh"],
    icon: icons["archetype_dps"],
    talents: {
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "Follower of Chaos": {
        name: "Follower of Chaos",
        pos: "a2",
        icon: icons["tac_race_chaos"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You are immune to the negative effects of corruption.`,
      },
      "Bleed Corruption": {
        name: "Bleed Corruption",
        pos: "b2",
        icon: icons["tac_race_chaos"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you are hit by an enemy ability, apply a random corruption to them.`,
      },
      "Iron Will": {
        name: "Iron Will",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You lose 3 Insanity every second.`,
      },
      "Infernal Flesh": {
        name: "Infernal Flesh",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Your daemons are twice as hard to kill.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specstaff"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Soulflayers equip staves.`,
      },
      "Daemonic Maw": {
        name: "Daemonic Maw",
        pos: "i4",
        icon: icons["abi_ch_demonicmaw"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Deals 30% SAP + 300 spiritual damage to the target and applies 2 stacks of Reduced Armor.`,
      },
      "Bless the Unholy Seeker": {
        name: "Bless the Unholy Seeker",
        pos: "i5",
        icon: icons["abi_ch_exchangevitality"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Summons a Daemonette of Slaanesh.`,
      },
      "Winds of Insanity": {
        name: "Winds of Insanity",
        pos: "i7",
        icon: icons["abi_ch_windblock"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "3.0s channel",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`For the duration you lose 3 mass. Every second up to 12 enemies within 20 feet of you are knocked back.`,
      },
      "Greater Daemon Summon": {
        name: "Greater Daemon Summon",
        pos: "i8",
        icon: icons["abi_ch_firewyrmoftzeentch"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Summons an uncontrolled greater daemon based on your current highest corruption level.\n\nSlaanesh - Keeper of Secrets\nNurgle - Plaguefather\nTzeentch - Firewyrm\nKhorne - Bloodthirster`,
      },
	  "Disengage": {
        name: "Disengage",
        pos: "f2",
        icon: icons["morale_disengage"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`You knock yourself back away from target enemy.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Explosive Impact": {
        name: "Explosive Impact",
        pos: "h2",
        icon: icons["morale_explosiveimpact"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 10 seconds. Whenever you hit a target with a single-target ability, you will deal 10% RAP + 150 corporeal damage and 10% SAP + 150 elemental damage to up to 24 enemies within 20 feet of the target.`,
      },
      "Unleash the Winds": {
        name: "Unleash the Winds",
        pos: "i2",
        icon: icons["morale_unleashthewinds"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 96 enemies within a 20 feet location you select are knocked straight up into the air.`,
      },
      "Insanity": {
        name: "Insanity",
        pos: "a1",
        icon: icons["abi_ch_ritualoflunacy"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Your spells generate insanity as you get magic directly from the Chaos Gods. Insanity has a maximum of 100.\n\nAt 60 insanity, you have Slaanesh Fanaticism.\nAt 70 insanity, you have Nurgle Fanatacism.\nAt 90 insanity, you have Tzeentch Fanatacism.`,
      },
      "Rend Winds": {
        name: "Rend Winds",
        pos: "b1",
        icon: icons["abi_ch_rendwinds"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
		blue: "Generates 3 Insanity",
        description: talentText`(Basic Attack) Deals 6% SAP + 133 elemental damage to target enemy. Generates 40 action points.`,
      },
      "Flickering Red Fire": {
        name: "Flickering Red Fire",
        pos: "c1",
        icon: icons["abi_ch_flingredfire"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "60 action points",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
		blue: "Generates 18 Insanity",
        description: talentText`Deals 74% SAP + 996 elemental damage to target enemy. Applies 1 stack of Slaanesh Corruption to target and caster.\n\nSlaanesh Fanatacism: you will also deal the damage to yourself.`,
      },
      "Summon Daemonette": {
        name: "Summon Daemonette",
        pos: "d1",
        icon: icons["abi_ch_exchangevitality"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "30s cooldown",
		blue: "Generates 12 Insanity",
        description: talentText`Summons a daemon of Slaanesh and bind them to the summoning circle. The Daemonette will deal 110 elemental damage to enemies within 100 feet of it, and will apply 1 Slaanesh Corruption to you if you are within 30 feet of it. You may only have one daemon active.`,
      },
      "Glamour of Slaanesh": {
        name: "Glamour of Slaanesh",
        pos: "e1",
        icon: icons["abi_ch_ritualofexsanguination"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Generates 6 Insanity\nOff the GCD",
        description: talentText`Your daemon will deal 14% SAP + 206 elemental damage to your target and applies 1 stack of Reduced Elemental Resistance. Generates 6 Insanity.`,
      },
      "Gift of Flesh": {
        name: "Infernal Flesh",
        pos: "f1",
        icon: icons["abi_ch_gleanmagic"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
		blue: "Off the GCD",
        description: talentText`Deals 1200 true damage to your daemon in order to reduce your Insanity by 18.`,
      },
      "Tzeentch's Grasp": {
        name: "Tzeentch's Grasp",
        pos: "g1",
        icon: icons["abi_ch_tzeentchsgrip"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Applies Rooted and Immovable to target enemy.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nImmovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Bolt of Change": {
        name: "Bolt of Change",
        pos: "h1",
        icon: icons["abi_ch_boltofchange"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "100ft range",
        cast: "1.5s instant cast",
        cooldown: "no cooldown",
		blue: "Generates 9 Insanity",
        description: talentText`Deals 23% SAP + 305 spiritual damage to target enemy. Applies Tzeentch Corruption to target and caster.\n\nTzeentch Fanatacism: the ability has a 50% chance to hit a random target within 20 feet of the original for 25% additional damage instead of the original target.`,
      },
      "Smokescreen": {
        name: "Smokescreen",
        pos: "i1",
        icon: icons["abi_em_smokescreen"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "15s cooldown",
        description: talentText`Target enemy will deal 50% less damage to you for 15 seconds. This effect is removed if you hit the target with an ability.`,
      },
	  "Firestorm": {
        name: "Firestorm",
        pos: "b4",
        icon: icons["abi_ch_tzeentchsfirestorm"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "75 action points",
        range: "100ft range",
        cast: "3.0s channel",
        cooldown: "no cooldown",
		blue: "Generates 22 Insanity",
        description: talentText`Deals 7% SAP + 80 elemental damage per second to up to 9 enemies within a 20 foot area you select.\n\nSlaanesh Fanaticism: Increase the action point cost by 25.\nNurgle Fanaticism: Increase the channel time and tick interval by 20%.\nTzeentch Fanaticism: reduces your damage reduction by 100% for the channel duration.`,
      },
	  "Withered Soul": {
        name: "Withered Soul",
        pos: "c5",
        icon: icons["abi_ch_eruption"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
		blue: "Generates 7 Insanity",
        description: talentText`Applies 1 stack of Nurgle Corruption to target and caster. Applies a 15 second ailment to target. For the duration, target will take 11% SAP + 137 corporeal damage every 3 seconds.\n\nNurgle Fanaticsm: Has a 50% chance to also apply a 15 second blessing to target. For the duration, target will restore 7% RP + 92 health every 3 seconds.`,
      },
	  "Eternal Pleasure": {
        name: "Eternal Pleasure",
        pos: "h6",
        icon: icons["abi_ch_flameoftzeentch"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "40 action points",
        range: "100ft range",
        cast: "3.0s channel",
        cooldown: "no cooldown",
		blue: "Generates 12 Insanity",
        description: talentText`Deals 14% SAP + 190 elemental damage to target every second. Applies 1 Slaanesh Corruption to target and caster every second.\n\nSlaanesh Fanaticism: your damage reduction is reduced by 50% for the duration of the channel.`,
      },
	  "Surge of Insanity": {
        name: "Surge of Insanity",
        pos: "b8",
        icon: icons["abi_ch_waveofhorror"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Off the GCD",
        description: talentText`Consume all Slaanesh Corruption on yourself. Your next 2 spells cast will be 10% faster per Slaanesh Corruption consumed.`,
      },
      "Conduit of Chaos": {
        name: "Conduit of Chaos",
        pos: "d9",
        icon: icons["abi_ch_potionoofpaindenied"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        blue: "Off the GCD",
        description: talentText`Kills your daemon and places it on cooldown. For the next 15 seconds, you gain 1000 sagacity and 10000 potency.`,
      },
      "The Great Decadence": {
        name: "The Great Decadence",
        pos: "f9",
        icon: icons["abi_ch_graspingdarkness"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "self",
        cast: "1.0s cast",
        cooldown: "30s cooldown",
        description: talentText`You apply Staggered and Unstoppable to up to 48 enemies within 30 feet in front of you. This effect does not apply to targets that have Cover from you.\n\nStaggered prevents all control of your character for 9 seconds or until you are attacked.\nUnstoppable prevents application of Kockdown and Staggered effects.`,
      },
	  "Rapturous Bliss": {
        name: "Rapturous Bliss",
        pos: "a5",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Double the effects of Slaanesh Corruption on you.`,
      },
	  "Allure of Slaanesh": {
        name: "Allure of Slaanesh",
        pos: "g5",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`As long as you are within 30 feet of your daemon, you will gain 15% dodge and 50% pushback immunity, but you will lose 25% movement speed.`,
      },
	  "Perils of the Warp": {
        name: "Perils of the Warp",
        pos: "b6",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Firestorm",
		arrows: [
          { dir: "down", from: "b4", to: "b6" },
        ],
        type: "career tactic",
        description: talentText`Firestorm, Seed of Chaos, and Spore Diffusion will now damage to up to 24 enemies.`,
      },
	  "Shine Twice": {
        name: "Shine Twice",
        pos: "e6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Flickering Red Fire will deal damage to an additional target within 20 feet of the primary target.`,
      },
	  "Daemonic Withering": {
        name: "Daemonic Withering",
        pos: "c7",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Withered Soul",
		arrows: [
          { dir: "down", from: "c5", to: "c7" },
        ],
        type: "career tactic",
        description: talentText`Withered Soul now has a 10 second cooldown and applies Marked to the target. Marked is a debuff that lasts for 10 seconds that reduces target's damage reduction by 15%.`,
      },
	  "Labored Pleasure": {
        name: "Labored Pleasure",
        pos: "h8",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Eternal Pleasure",
		arrows: [
          { dir: "down", from: "h6", to: "h8" },
        ],
        type: "career tactic",
        description: talentText`Eternal Pleasure will reduce the target's movement speed by 33% for the duration of the channel.`,
      },
	  "Daemonic Infestation": {
        name: "Daemonic Infestation",
        pos: "g7",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`The cooldown of your Summons is now 15 seconds. The cooldowns of Glamour of Slaanesh, Spore Diffusion, and Piercing Scream are now 5 seconds.`,
      },
	  "Sacred Number of Slaanesh": {
        name: "Passive 1",
        pos: "e3",
        icon: icons["abi_ch_powervortex"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increase the threshold before Slaanesh Fanatacism is applied by ${[
          6,
          12,
          18,
          24,
        ]}.`,
      },
	  "Strengthen Thrall": {
        name: "Strengthen Thrall",
        pos: "h4",
        icon: icons["abi_ch_strengthenthrall"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Your daemon gains ${[
          300,
          600,
          900,
          1200,
          1500,
        ]} HP4.`,
      },
	  "Improved Basic Attack": {
        name: "Improved Basic Attack",
        pos: "e5",
        icon: icons["abi_ch_rendwinds"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Your basic attacks will deal ${[
          50,
          100,
          150,
          200,
          250,
        ]}% additional damage.`,
      },
	  "Change and Adoration": {
        name: "Change and Adoration",
        pos: "d6",
        icon: icons["abi_ch_boltofchange"],
        maxRank: 2,
        reqPoints: 15,
        description: talentText`Bolt of Change will now apply ${[
          1,
          1,
        ]} stack of Slaanesh Corruption and ${[
          1,
          2,
        ]} stacks of Tzeentch Corruption.`,
      },
	  "Improved Flickering Red Fire": {
        name: "Improved Flickering Red Fire",
        pos: "f6",
        icon: icons["abi_ch_flingredfire"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Reduces the cast time of Flickering Red Fire by ${[
          0.1,
          0.2,
          0.3,
          0.4,
          0.5,
        ]} seconds.`,
      },
	  "Improved Firestorm": {
        name: "Improved Firestorm",
        pos: "b7",
        icon: icons["abi_ch_tzeentchsfirestorm"],
        maxRank: 3,
        reqPoints: 20,
        prereq: "Perils of the Warp",
		arrows: [
          { dir: "down", from: "b6", to: "b7" },
        ],
        type: "passive",
        description: talentText`Increase the damage of Firestorm by ${[
          5,
          10,
          15,
        ]}%.`,
      },
	  "Extra Crit": {
        name: "Extra Crit",
        pos: "e7",
        icon: icons["abi_extracrit"],
        maxRank: 5,
        reqPoints: 20,
        type: "passive",
        description: talentText`Increase your chance to critically hit by ${[
          1,
          2,
          3,
          4,
          5,
        ]}.`,
      },
      "Seeking Affluence": {
        name: "Seeking Affluence",
        pos: "e8",
        icon: icons["abi_ch_ritualoflunacy"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Reduce the Insanity generation of all abilities by ${[
          1,
          2,
          3,
          4,
          5,
        ]}.`,
      },
    },
  },
  "Doomweaver": {
    name: "Doomweaver",
    background: backgrounds["magus-tzeentch"],
    icon: icons["archetype_defsupport"],
    talents: {
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Increase your mass by 1.`,
      },
      "Follower of Chaos": {
        name: "Follower of Chaos",
        pos: "a2",
        icon: icons["tac_race_chaos"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You are immune to the negative effects of corruption.`,
      },
      "Bleed Corruption": {
        name: "Bleed Corruption",
        pos: "b2",
        icon: icons["tac_race_chaos"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you are hit by an enemy ability, apply a random corruption to them.`,
      },
      "Iron Will": {
        name: "Iron Will",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You lose 3 Insanity every second.`,
      },
      "Infernal Flesh": {
        name: "Infernal Flesh",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Your daemons are twice as hard to kill.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specstaff"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Doomweaves equip staves.`,
      },
      "Daemonic Maw": {
        name: "Daemonic Maw",
        pos: "i4",
        icon: icons["abi_ch_demonicmaw"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Deals 30% SAP + 300 spiritual damage to the target and applies 2 stacks of Reduced Armor.`,
      },
      "Night of Madness": {
        name: "Night of Madness",
        pos: "i5",
        icon: icons["abi_ch_instability"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Summons a Pink Horror of Tzeentch.`,
      },
      "Winds of Insanity": {
        name: "Winds of Insanity",
        pos: "i7",
        icon: icons["abi_ch_windblock"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "3.0s channel",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`For the duration you lose 3 mass. Every second up to 12 enemies within 20 feet of you are knocked back.`,
      },
      "Greater Daemon Summon": {
        name: "Greater Daemon Summon",
        pos: "i8",
        icon: icons["abi_ch_firewyrmoftzeentch"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Summons an uncontrolled greater daemon based on your current highest corruption level.\n\nSlaanesh - Keeper of Secrets\nNurgle - Plaguefather\nTzeentch - Firewyrm\nKhorne - Bloodthirster`,
      },
	  "Return Life": {
        name: "Return Life",
        pos: "f2",
        icon: icons["morale_returnlife"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Return target groupmate back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Divine Protection": {
        name: "Divine Protection",
        pos: "h2",
        icon: icons["morale_divineprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 15 seconds. They will absorb up to 120% RP + 1600 damage over the duration.`,
      },
      "Alter Fate": {
        name: "Alter Fate",
        pos: "i2",
        icon: icons["morale_alterfate"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Removes all afflictions and cripples from each groupmate within 100 feet. Also applies Return Life to each dead groupmate within 100ft.`,
      },
      "Insanity": {
        name: "Insanity",
        pos: "a1",
        icon: icons["abi_ch_ritualoflunacy"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Your spells generate insanity as you get magic directly from the Chaos Gods. Insanity has a maximum of 100.\n\nAt 60 insanity, you have Slaanesh Fanaticism.\nAt 70 insanity, you have Nurgle Fanatacism.\nAt 90 insanity, you have Tzeentch Fanatacism.`,
      },
      "Rend Winds": {
        name: "Rend Winds",
        pos: "b1",
        icon: icons["abi_ch_rendwinds"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
		blue: "Generates 3 Insanity",
        description: talentText`(Basic Attack) Deals 6% SAP + 133 elemental damage to target enemy. Generates 40 action points.`,
      },
      "Bolt of Change": {
        name: "Bolt of Change",
        pos: "c1",
        icon: icons["abi_ch_boltofchange"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "100ft range",
        cast: "1.5s instant cast",
        cooldown: "no cooldown",
		blue: "Generates 9 Insanity",
        description: talentText`Deals 23% SAP + 305 spiritual damage to target enemy. Applies Tzeentch Corruption to target and caster.\n\nTzeentch Fanatacism: the ability has a 50% chance to hit a random target within 20 feet of the original for 25% additional damage instead of the original target.`,
      },
      "Summon Pink Horror": {
        name: "Summon Pink Horror",
        pos: "d1",
        icon: icons["abi_ch_instability"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "30s cooldown",
        blue: "Generates 18 Insanity",
        description: talentText`Summons a Pink Horror which will run after enemies attaching them in melee for 4% MAP + 30 spiritual damage. Removes 1 Insanity whenever it deals damage. You may only have 1 daemon active.`,
      },
      "Piercing Scream": {
        name: "Piercing Scream",
        pos: "e1",
        icon: icons["abi_ch_warpingenergy"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Generates 9 Insanity\nOff the GCD",
        description: talentText`Commands your Pink Horror to deal 6% SAP + 89 spiritual damage to up to 9 enemies within 30 feet of it and apply 1 stack of Tzeentch Corruption to them.`,
      },
      "Flickering Red Fire": {
        name: "Flickering Red Fire",
        pos: "f1",
        icon: icons["abi_ch_flingredfire"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "60 action points",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
		blue: "Generates 18 Insanity",
        description: talentText`Deals 74% SAP + 996 elemental damage to target enemy. Applies 1 stack of Slaanesh Corruption to target and caster.\n\nSlaanesh Fanatacism: you will also deal the damage to yourself.`,
      },
      "Tzeentch's Grasp": {
        name: "Tzeentch's Grasp",
        pos: "g1",
        icon: icons["abi_ch_tzeentchsgrip"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Applies Rooted and Immovable to target enemy.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nImmovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Withered Soul": {
        name: "Withered Soul",
        pos: "h1",
        icon: icons["abi_ch_eruption"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
		blue: "Generates 7 Insanity",
        description: talentText`Applies 1 stack of Nurgle Corruption to target and caster. Applies a 15 second affliction to target. For the duration, target will take 11% SAP + 137 corporeal damage every 3 seconds.\n\nNurgle Fanaticsm: Has a 50% chance to also apply a 15 second blessing to target. For the duration, target will restore 7% RP + 92 health every 3 seconds.`,
      },
      "Smokescreen": {
        name: "Smokescreen",
        pos: "i1",
        icon: icons["abi_em_smokescreen"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "15s cooldown",
        description: talentText`Target enemy will deal 50% less damage to you for 15 seconds. This effect is removed if you hit the target with an ability.`,
      },
	  "Firestorm": {
        name: "Firestorm",
        pos: "b4",
        icon: icons["abi_ch_tzeentchsfirestorm"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "75 action points",
        range: "100ft range",
        cast: "3.0s channel",
        cooldown: "no cooldown",
		blue: "Generates 22 Insanity",
        description: talentText`Deals 7% SAP + 80 elemental damage per second to up to 9 enemies within a 20 foot area you select.\n\nSlaanesh Fanaticism: Increase the action point cost by 25.\nNurgle Fanaticism: Increase the channel time and tick interval by 20%.\nTzeentch Fanaticism: reduces your damage reduction by 100% for the channel duration.`,
      },
	  "Tzeentch's Reflection": {
        name: "Tzeentch's Reflection",
        pos: "h5",
        icon: icons["abi_ch_theftofwords"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Applies 1 stack of Tzeentch Corruption, Silenced, and Inevitable to target enemy.\n\nSilenced prevents the use of spells for 5 seconds.\nInevitable prevents the application of Disarmed and Silenced for 20 seconds.`,
      },
	  "Chaos Unleashed": {
        name: "Chaos Unleashed",
        pos: "e6",
        icon: icons["abi_ch_unstablepower"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "40 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "45s cooldown",
        description: talentText`Destroy your Pink Horror to apply Knocked-down and Unstoppable to up to 6 enemies within 20 feet of it.\n\nKnocked-down prevents all control of your character for 3 seconds.\nUnstoppable prevents application of Knocked-down or Staggered for 30 seconds.`,
      },
	  "Flames of Fate": {
        name: "Flames of Fate",
        pos: "e8",
        icon: icons["abi_ch_flamesoffate"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        blue: "Generates 18 Insanity",
        description: talentText`Fires a Bolt of Change at target and applies a 8 second cripple to them. For the duration, target loses 1 mass.`,
      },
      "Chaotic Rift": {
        name: "Chaotic Rift",
        pos: "d9",
        icon: icons["abi_ch_tzeentchsreversal"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "50 action points",
        range: "self",
        cast: "1.0s cast",
        cooldown: "60s cooldown",
        description: talentText`Pulls up to 9 enemies within 65 feet of you and applies Ensnared, Momentum, and Immovable to them.\n\nEnsnared reduces movement speed by 30% for 16 seconds.\nMomentum prevents the application of Ensnared for 8 seconds.\nImmovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "The Great Change": {
        name: "The Great Change",
        pos: "f9",
        icon: icons["abi_ch_riteofresilence"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "self",
        cast: "1.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Deals 13% SAP + 186 spiritual damage to up to 48 enemies within 30 feet in front of you. For each target hit that did not have Cover, all groupmates within 150 feet gain a stack. The stacks heal for 6% RP + 8 each at the end of their 3 second duration.`,
      },
	  "Champion of Change": {
        name: "Champion of Change",
        pos: "a5",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Double the benefits of Tzeentch Corruption on you.`,
      },
	  "Glimpse of Chaos": {
        name: "Glimpse of Chaos",
        pos: "b5",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Withered Soul now applies its blessing to your defensive target.`,
      },
	  "Fire of Change": {
        name: "Fire of Change",
        pos: "b6",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Bolt of Change will dispel 1 enchantment from the target.`,
      },
	  "Unending Horrors": {
        name: "Unending Horrors",
        pos: "h6",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Whenever your Pink Horror dies, two uncontrollable Blue Horrors are spawned which last up to 20 seconds.`,
      },
	  "Daemonic Infestation": {
        name: "Daemonic Infestation",
        pos: "a7",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`The cooldown of your Summons is now 15 seconds. The cooldowns of Glamour of Slaanesh, Spore Diffusion, and Piercing Scream are now 5 seconds.`,
      },
	  "Surging Power": {
        name: "Surging Power",
        pos: "e7",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Whenever you cast Flickering Red Fire on a target, you next Bolt of Change on that target will apply Knocked-down and Unstoppable to target enemy.\n\nKnocked-down prevents all control of your character for 3 seconds.\nUnstoppable prevents application of Knocked-down and Staggered for 30 seconds.`,
      },
	  "Chaotic Attunement": {
        name: "Chaotic Attunement",
        pos: "d8",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Bolt of Change deals 30% less damage. It will now hit up to 2 other targets within 20 feet of the primary target unless you have Tzeentch Fanatacism.`,
      },
	  "Sacred Number of Tzeentch": {
        name: "Sacred Number of Tzzentch",
        pos: "e3",
        icon: icons["abi_ch_discordantturbulence"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever you use an ability, you will gain a stack for 30 seconds. Whenever you reach 9, they will be dispelled, you lose ${[
          20,
          60,
        ]} insanity, and your next Bolt of Change applies 5 stacks of Reduced Intelligence to the target.`,
      },
	  "Mutating Blue Fire": {
        name: "Mutating Blue Fire",
        pos: "c4",
        icon: icons["abi_ch_despairingblackfire"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Flickering Red Fire no longer deals direct damage and has a 2.0s cast time. Instead it applies a ${[
          6,
          12,
          18,
          24,
          30,
        ]} second affliction to target. For the duration, target takes 25% SAP + 330 spiritual damage every 3 seconds.`,
      },
	  "Infernal Blast": {
        name: "Infernal Blast",
        pos: "g4",
        icon: icons["abi_ch_inevitablechanging"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Rend Winds is now instant cast but generates 7 Insanity.`,
      },
	  "Strengthen Thrall": {
        name: "Strengthen Thrall",
        pos: "d6",
        icon: icons["abi_ch_strengthenthrall"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`Your daemon gains ${[
          300,
          600,
          900,
          1200,
          1500,
        ]} HP4.`,
      },
	  "Horrifying Changes": {
        name: "Horrifying Changes",
        pos: "f6",
        icon: icons["abi_ch_flamesofchange"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Whenever your Pink Horror deals damage to an enemy, it has a ${[
          10,
          20,
          30,
          40,
          50,
        ]}% chance to apply 1 stack of Reduced Initiative, Reduced Agility, Reduced Critical Hit Rating, or Reduced Potency if the target has Withered Soul or Mutating Blue Fire is on the target. This chance is doubled if both are on the target.`,
      },
	  "Scriveners of Insanity": {
        name: "Scriveners of Insanity",
        pos: "c7",
        icon: icons["abi_ch_boltofchange"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Reduces the cast time of Bolt of Change by ${[
          0.1,
          0.2,
          0.3,
        ]} seconds.`,
      },
	  "Iridescent Touch": {
        name: "Iridescent Touch",
        pos: "g7",
        icon: icons["abi_ch_markoftzeentchsrebirth"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Withered Soul's affliction now reduces the targets AP regen by ${[
          2,
          4,
          6,
        ]}.`,
      },
	  "Arsenal of Insanity": {
        name: "Arsenal of Insanity",
        pos: "f8",
        icon: icons["abi_ch_devastatingindigofire"],
        maxRank: 4,
		prereq: "Flames of Fate",
		arrows: [
          { dir: "right", from: "e8", to: "f8" },
        ],
        reqPoints: 25,
        type: "passive",
        description: talentText`Flames of Fate now applies ${[
          "-1 mass and -50% pushback immunity",
          "-1 mass, 50% pushback immunity, and -33% outgoing healing",
          "-2 mass, 50% pushback immunity, and -33% outgoing healing",
		  "-2 mass, 50% pushback immunity, and -33% outgoing healing. It is now a debuff instead of a cripple",
        ]}.`,
      },
    },
  },
  "Poxbringer": {
    name: "Poxbringer",
    background: backgrounds["magus-nurgle"],
    icon: icons["archetype_dps"],
    talents: {
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Follower of Chaos": {
        name: "Follower of Chaos",
        pos: "a2",
        icon: icons["tac_race_chaos"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You are immune to the negative effects of corruption.`,
      },
      "Bleed Corruption": {
        name: "Bleed Corruption",
        pos: "b2",
        icon: icons["tac_race_chaos"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you are hit by an enemy ability, apply a random corruption to them.`,
      },
      "Iron Will": {
        name: "Iron Will",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You lose 3 Insanity every second.`,
      },
      "Infernal Flesh": {
        name: "Infernal Flesh",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Your daemons are twice as hard to kill.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specstaff"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Poxbringers equip staves.`,
      },
      "Daemonic Maw": {
        name: "Daemonic Maw",
        pos: "i4",
        icon: icons["abi_ch_demonicmaw"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Deals 30% SAP + 300 spiritual damage to the target and applies 2 stacks of Reduced Armor.`,
      },
      "Revel in Malady": {
        name: "Revel in Malady",
        pos: "i5",
        icon: icons["abi_ch_chaoticontamination"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Summons a Nurgling of Nurgle.`,
      },
      "Winds of Insanity": {
        name: "Winds of Insanity",
        pos: "i7",
        icon: icons["abi_ch_windblock"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "3.0s channel",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`For the duration you lose 3 mass. Every second up to 12 enemies within 20 feet of you are knocked back.`,
      },
      "Greater Daemon Summon": {
        name: "Greater Daemon Summon",
        pos: "i8",
        icon: icons["abi_ch_firewyrmoftzeentch"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Summons an uncontrolled greater daemon based on your current highest corruption level.\n\nSlaanesh - Keeper of Secrets\nNurgle - Plaguefather\nTzeentch - Firewyrm\nKhorne - Bloodthirster`,
      },
	  "Disengage": {
        name: "Disengage",
        pos: "f2",
        icon: icons["morale_disengage"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`You knock yourself back away from target enemy.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Explosive Impact": {
        name: "Explosive Impact",
        pos: "h2",
        icon: icons["morale_explosiveimpact"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 10 seconds. Whenever you hit a target with a single-target ability, you will deal 10% RAP + 150 corporeal damage and 10% SAP + 150 elemental damage to up to 24 enemies within 20 feet of the target.`,
      },
      "Unleash the Winds": {
        name: "Unleash the Winds",
        pos: "i2",
        icon: icons["morale_unleashthewinds"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Up to 96 enemies within a 20 feet location you select are knocked straight up into the air.`,
      },
      "Insanity": {
        name: "Insanity",
        pos: "a1",
        icon: icons["abi_ch_ritualoflunacy"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Your spells generate insanity as you get magic directly from the Chaos Gods. Insanity has a maximum of 100.\n\nAt 60 insanity, you have Slaanesh Fanaticism.\nAt 70 insanity, you have Nurgle Fanatacism.\nAt 90 insanity, you have Tzeentch Fanatacism.`,
      },
      "Rend Winds": {
        name: "Rend Winds",
        pos: "b1",
        icon: icons["abi_ch_rendwinds"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
		blue: "Generates 3 Insanity",
        description: talentText`(Basic Attack) Deals 6% SAP + 133 elemental damage to target enemy. Generates 40 action points.`,
      },
      "Pestilent Growth": {
        name: "Pestilent Growth",
        pos: "c1",
        icon: icons["abi_ch_aegisofyellowfire"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "30 action points",
        range: "65ft range",
        cast: "2.0s cast",
        cooldown: "no cooldown",
        blue: "Generates 7 Insanity\nCastable While Moving",
        description: talentText`Deals 10% SAP + 121 corporeal damage to target enemy and applies a 9 second affliction to them that stacks up to 5 times. Apples 1 stack of Nurgle Corruption to target and caster. For the duration, target takes 4% SAP + 58 corporeal damage every 3 seconds.\n\nNurgle Fanatacism: Applies 2 stacks to target enemy, 5 stacks to up to 2 allies within 30 feet of the target, and 5 stacks to yourself.`,
      },
      "Summon Nurgling": {
        name: "Summon Nurgling",
        pos: "d1",
        icon: icons["abi_ch_chaoticontamination"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "30s cooldown",
        blue: "Generates 14 Insanity",
        description: talentText`Summons a Nurgling which will run after enemies attacking them in melee for 4% MAP + 30 corporeal damage. You may only have 1 daemon active.`,
      },
      "Spore Diffusion": {
        name: "Spore Diffusion",
        pos: "e1",
        icon: icons["abi_ch_dissolvingmist"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        blue: "Generates 7 Insanity\nOff the GCD",
        description: talentText`Commands your Nurgling to apply 1 stack of Nurgle Corruption and a 6 second affliction to up to 3 enemies within 30 feet of it. For the duration, target takes 9% MAP + 127 corporeal damage every 3 seconds.`,
      },
      "Withered Soul": {
        name: "Withered Soul",
        pos: "f1",
        icon: icons["abi_ch_eruption"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "100ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
		blue: "Generates 7 Insanity",
        description: talentText`Applies 1 stack of Nurgle Corruption to target and caster. Applies a 15 second affliction to target. For the duration, target will take 11% SAP + 137 corporeal damage every 3 seconds.\n\nNurgle Fanaticsm: Has a 50% chance to also apply a 15 second blessing to target. For the duration, target will restore 7% RP + 92 health every 3 seconds.`,
      },
      "Tzeentch's Grasp": {
        name: "Tzeentch's Grasp",
        pos: "g1",
        icon: icons["abi_ch_tzeentchsgrip"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Applies Rooted and Immovable to target enemy.\n\nRooted reduces target movement speed to 0 for 5 seconds.\nImmovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Bolt of Change": {
        name: "Bolt of Change",
        pos: "h1",
        icon: icons["abi_ch_boltofchange"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "40 action points",
        range: "100ft range",
        cast: "1.5s instant cast",
        cooldown: "no cooldown",
		blue: "Generates 9 Insanity",
        description: talentText`Deals 23% SAP + 305 spiritual damage to target enemy. Applies Tzeentch Corruption to target and caster.\n\nTzeentch Fanatacism: the ability has a 50% chance to hit a random target within 20 feet of the original for 25% additional damage instead of the original target.`,
      },
      "Smokescreen": {
        name: "Smokescreen",
        pos: "i1",
        icon: icons["abi_em_smokescreen"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "15s cooldown",
        description: talentText`Target enemy will deal 50% less damage to you for 15 seconds. This effect is removed if you hit the target with an ability.`,
      },
	  "Firestorm": {
        name: "Firestorm",
        pos: "b4",
        icon: icons["abi_ch_tzeentchsfirestorm"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "75 action points",
        range: "100ft range",
        cast: "3.0s channel",
        cooldown: "no cooldown",
		blue: "Generates 22 Insanity",
        description: talentText`Deals 7% SAP + 80 elemental damage per second to up to 9 enemies within a 20 foot area you select.\n\nSlaanesh Fanaticism: Increase the action point cost by 25.\nNurgle Fanaticism: Increase the channel time and tick interval by 20%.\nTzeentch Fanaticism: reduces your damage reduction by 100% for the channel duration.`,
      },
	  "Eternal Pleasure": {
        name: "Eternal Pleasure",
        pos: "c5",
        icon: icons["abi_ch_flameoftzeentch"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "40 action points",
        range: "100ft range",
        cast: "3.0s channel",
        cooldown: "no cooldown",
		blue: "Generates 12 Insanity",
        description: talentText`Deals 14% SAP + 190 elemental damage to target every second. Applies 1 Slaanesh Corruption to target and caster every second.\n\nSlaanesh Fanaticism: your damage reduction is reduced by 50% for the duration of the channel.`,
      },
	  "Speckled Hide": {
        name: "Speckled Hide",
        pos: "e6",
        icon: icons["abi_ch_demonspittle"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "60 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "6s cooldown",
        blue: "Generates 7 Insanity\nOff the GCD",
        description: talentText`Commands your Nurgling to apply 2 stacks of Nurgle Corruption and a 12 second affliction to target enemy. For the duration, target takes 9% MAP + 133 corporeal damage every 2 seconds.`,
      },
	  "Seed of Chaos": {
        name: "Seed of Chaos",
        pos: "e8",
        icon: icons["abi_ch_seedofchaos"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "80 action points",
        range: "65ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Generates 7 Insanity",
        description: talentText`Applies a 10 second cripple to target enemy. For the duration, target takes 7% SAP + 78 corporeal damage every 2 seconds. At the end of the duration, explodes dealing 12% SAP + 144 corporeal damage to up to 3 enemies within 30 feet.\n\nNurgle Fanatacism: you will apply a seed in yourself that cannot be dispelled or refreshed; and deals double damage. The explosion will hit allies and/or enemies.`,
      },
      "Nurgle's Visitation": {
        name: "Nurgle's Visitation",
        pos: "d9",
        icon: icons["abi_ch_demonicconsumption"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "20 action points",
        range: "65ft range",
        cast: "1.0s cast",
        cooldown: "15s cooldown",
        blue: "Generates 21 Insanity",
        description: talentText`Deals 6% SAP + 81 corporeal damage to target enemy. Will attack the target again for each stack of Pestilent Growth, Spore Diffusion, Withered Soul, Speckled Hide, and Seed of Chaos on the target. Up to a maximum of 7 hits.\n\nNurgle Fanatacism: instead, will restore 50% RP + 250 health to the target and caster applying 10 stacks of Nurgle Corruption to both.`,
      },
      "The Great Plague": {
        name: "The Grand Plague",
        pos: "f9",
        icon: icons["abi_ch_befuddlinggreenfire"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "100ft range",
        cast: "2.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Apply a debuff to target enemy for 2 seconds. Deals 6% SAP + 20 ichor damage every 1 second. At the end of the duration, applies stage 2 of the debuff to up to 6 other enemies within 20 feet. There are 5 stages and each stage can stack up to 10 times on the same target.`,
      },
	  "Favorite Children": {
        name: "Favorite Children",
        pos: "a5",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Double the benefits of Nurgle Corruption on you.`,
      },
	  "Fleshy Growths": {
        name: "Fleshy Growths",
        pos: "g5",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Your Nurglings have 30% increased movement speed and are healed for 100% of healing you receive.`,
      },
	  "Perils of the Warp": {
        name: "Perils of the Warp",
        pos: "b6",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Firestorm",
		arrows: [
          { dir: "down", from: "b4", to: "b6" },
        ],
        type: "career tactic",
        description: talentText`Firestorm, Seed of Chaos, and Spore Diffusion will now damage to up to 24 enemies.`,
      },
	  "Fire of Change": {
        name: "Fire of Change",
        pos: "h6",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Bolt of Change will dispel 1 enchantment from the target.`,
      },
	  "Daemonic Withering": {
        name: "Daemonic Withering",
        pos: "a7",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Withered Soul now has a 10 second cooldown and applies Marked to the target. Marked is a debuff that lasts for 10 seconds that reduces target's damage reduction by 15%.`,
      },
	  "Daemonic Infestation": {
        name: "Daemonic Infestation",
        pos: "h7",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`The cooldown of your Summons is now 15 seconds. The cooldowns of Glamour of Slaanesh, Spore Diffusion, and Piercing Scream are now 5 seconds.`,
      },
	  "Highly Infectious": {
        name: "Highly Infectious",
        pos: "d8",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Whenever you apply Nurgle Corruption, you also apply 1 stack of Reduced Corporeal Resistance.`,
      },
	  "Sacred Number of Nurgle": {
        name: "Sacred Number of Nurgle",
        pos: "e3",
        icon: icons["abi_ch_plunderingpower"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever Pestilent Growth, Spore Diffusion, Withered Soul, or Speckled Hide deal damage, you will gain a stack of Nurgle's Favor. Whenever you reach 7 stacks, they will be dispelled and you will lose ${[
          5,
          10,
          15,
          20,
        ]} Insanity.`,
      },
	  "Improved Basic Attack": {
        name: "Improved Basic Attack",
        pos: "c4",
        icon: icons["abi_ch_rendwinds"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Your basic attacks will deal ${[
          50,
          100,
          150,
          200,
          250,
        ]}% additional damage.`,
      },
	  "Infernal Blast": {
        name: "Infernal Blast",
        pos: "e5",
        icon: icons["abi_ch_inevitablechanging"],
        maxRank: 1,
        reqPoints: 10,
        type: "passive",
        description: talentText`Rend Winds is now instant cast but generates 7 Insanity.`,
      },
	  "Strengthen Thrall": {
        name: "Strengthen Thrall",
        pos: "d6",
        icon: icons["abi_ch_strengthenthrall"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`Your daemon gains ${[
          300,
          600,
          900,
          1200,
          1500,
        ]} HP4.`,
      },
	  "Decay and Change": {
        name: "Decay and Change",
        pos: "f6",
        icon: icons["abi_ch_indigofireofchange"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Whenever you cast Pestilent Growth, you have a ${[
          10,
          20,
          30,
          40,
          50,
        ]}% chance to make your next Bolt of Change cast within 5 seconds instant cast.`,
      },
	  "Contagious Horde": {
        name: "Contagious Horde",
        pos: "e7",
        icon: icons["abi_ch_pandemonium"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`${[
          "Pestilent Growth is now a cripple",
          "Pestilent Growth and Withered Soul are now cripples",
          "Pestilent Growth, Withered Soul, and Spore Diffusion are now cripples",
        ]}.`,
      },
	  "Improved Firestorm": {
        name: "Improved Firestorm",
        pos: "b7",
        icon: icons["abi_ch_tzeentchsfirestorm"],
        maxRank: 3,
        reqPoints: 20,
        prereq: "Perils of the Warp",
		arrows: [
          { dir: "down", from: "b6", to: "b7" },
        ],
        type: "passive",
        description: talentText`Increase the damage of Firestorm by ${[
          5,
          10,
          15,
        ]}%.`,
      },
	  "Weight of Plague": {
        name: "Weight of Plague",
        pos: "f8",
        icon: icons["abi_ch_denyvitality"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Pestilent Growth, Spore Diffusion, and Withered Soul now reduce target movement speed by ${[
          1,
          2,
          3,
          5,
        ]}% each.`,
      },
    },
  },
};