import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/empire"),
);
const icons = requireAll(require.context("../../assets/icons/empire"));

export const data: TalentData = {
  "Silver Hammer": {
    name: "Silver Hammer",
    background: backgrounds["silverhammer"],
    icon: icons["archetype_healer"],
    talents: {
      "Loved By All": {
        name: "Loved By All",
        pos: "a8",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`You always have Immovable. Your mass is decreased by 2.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 1,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Emperor's Ward": {
        name: "Emperor's Ward",
        pos: "a2",
        icon: icons["tac_race_empire"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet of you with this tactic gain a 20% wounds + 300 absorb for 3 seconds.`,
      },
      "Sigmar's Favored": {
        name: "Sigmar's Favored",
        pos: "b2",
        icon: icons["tac_race_empire"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you receive a direct heal, you will also be healed for 120 + 8% wounds.`,
      },
      "Charged Fury": {
        name: "Charged Fury",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Any ability that generates Righteous Fury will generate 10 more.`,
      },
      "Fueled Fury": {
        name: "Fueled Fury",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you are hit by an ability, you will gain 10 Righteous Fury.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specadvancedshield"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Silver Hammer equips one-handed hammers and shields.`,
      },
	  "Return Life": {
        name: "Return Life",
        pos: "f2",
        icon: icons["morale_returnlife"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Return target groupmate back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Divine Protection": {
        name: "Divine Protection",
        pos: "h2",
        icon: icons["morale_divineprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 15 seconds. They will absorb up to 200% RP + 1500 damage over the duration.`,
      },
      "Alter Fate": {
        name: "Alter Fate",
        pos: "i2",
        icon: icons["morale_alterfate"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Removes all afflictions and cripples from each groupmate within 100 feet. Also applies Return Life to each dead groupmate within 100ft.`,
      },
      "Leading the Prayer": {
        name: "Leading the Prayer",
        pos: "i4",
        icon: icons["morale_leadingtheprayer"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Applies Shield of Faith with the augmented modifer to all groupmates within 100 feet.`,
      },
      "Hammer Time": {
        name: "Hammer Time",
        pos: "i5",
        icon: icons["morale_hammertime"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Gain 250 Righteous Fury.`,
      },
      "Emperor's Champion": {
        name: "Emperor's Champion",
        pos: "i7",
        icon: icons["morale_empchamp"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 20 seconds. For the duration, You gain 250 ballistic skill, 250 intelligence, and 250 strength.`,
      },
      "Avatar of Sigmar": {
        name: "Avatar of Sigmar",
        pos: "i8",
        icon: icons["abi_avatarofsigmar"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Cleanses all Chaos Corruption from up to 96 allies and 96 enemies within 30 feet of you. You gain a buff for 30 seconds. For the duration, you generate 10 Righteous Fury per second, your outgoing damage is increased by 75%, your healing done is increased by 75%, and your HP4 is increased by 1000. At the end of the duration, you die and gain Forlorn.`,
      },
      "Shield of Faith": {
        name: "Shield of Faith",
        pos: "a1",
        icon: icons["abi_shieldoffaith"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Righteous Fury has a maximum value of 250.\n\nShield of Faith absorbs up to 6% RP + 80 damage over 5 seconds. When Augmented, it will absorb 75% more and apply 1 stack of Enhanced Dodge.`,
      },
	  "Judgement": {
        name: "Judgement",
        pos: "b1",
        icon: icons["abi_judgement"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 3% SAP + 34 spiritual damage to target enemy. You generate 22 action points.`,
      },
      "Twin-Tailed Blow": {
        name: "Twin-Tailed Blow",
        pos: "c1",
        icon: icons["abi_twintailedblow"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 11% MAP + 156 spiritual damage to target enemy. Your defensive target will be healed for 150% of the damage dealt and applies Shield of Faith to groupmates within 75 feet. Generates 30 Righteous Fury.`,
      },
      "Divine Light": {
        name: "Divine Light",
        pos: "d1",
        icon: icons["abi_divinelight"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 60 Righteous Fury",
        description: talentText`Target ally gains 1 stack of Purity and a 5 second blessing that absorbs up to 27% RP + 342 damage.`,
      },
      "Prayer of Devotion": {
        name: "Prayer of Devotion",
        pos: "e1",
        icon: icons["abi_devotion"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 30 Righteous Fury",
        description: talentText`Target groupmate gains 1 stack of Purity, Shield of Faith, and an enchantment for 60 seconds that heals the target for 6% RP + 85 each time they use an ability.`,
      },
      "Wrath": {
        name: "Wrath",
        pos: "f1",
        icon: icons["abi_wrath"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "36 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 21% MAP + 280 impact damage to target enemy. Generates 25 Righteous Fury.\n\nAugmented: Deals 25% more damage.`,
      },
      "Vow of Silence": {
        name: "Vow of Silence",
        pos: "g1",
        icon: icons["abi_vowofsilence"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "30 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Applies Silenced and Inevitable to the target.\n\nSilenced prevents the use of spells for 5 seconds.\nInevitable prevents the application of Disarmed and Silenced for 20 seconds.\n\nAugmented: now has an 80 foot range.`,
      },
      "Divine Assault": {
        name: "Divine Assault",
        pos: "h1",
        icon: icons["abi_divineassault"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "3.0s channel",
        cooldown: "no cooldown",
        blue: "Costs 80 Righteous Fury",
        description: talentText`Deals 20% MAP + 275 spiritual damage to target enemy every second. Your defensive target will be healed for 150% of the damage you dealt if they were within 75 feet.`,
      },
      "Vigilance": {
        name: "Vigilance",
        pos: "i1",
        icon: icons["abi_vigilance"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        description: talentText`Your damage reduction is increased by 50% but your outdoing damage is reduced by 90% for 7 seconds.`,
      },
	  "Healing Hand": {
        name: "Healing Hand",
        pos: "g4",
        icon: icons["abi_healinghand"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 25 Righteous Fury",
        description: talentText`Applies an enchantment to target ally that heals for 6% RP + 65 every 3 seconds for 15 seconds.`,
      },
	  "Radiance": {
        name: "Radiance",
        pos: "h5",
        icon: icons["abi_radiance"],
        maxRank: 1,
        reqPoints: 10,
        type: "skill",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 19% MAP + 250 impact damage to target enemy. Your defensive target gains 1 stack of Enhanced Block if they are within 75ft. Generates 30 Righteous Fury.`,
      },
	  "Spirit of the Heldenhammer": {
        name: "Spirit of the Heldenhammer",
        pos: "c6",
        icon: icons["abi_spiritofh"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Applies a buff to target ally that heals them for 28% of your wounds + 420 every second for 5 seconds. Applies a debuff to you that deals 28% of your wounds + 420 true damage every second and reduces your healing received by 100% for 5 seconds.`,
      },
	  "Repel": {
        name: "Repel",
        pos: "h8",
        icon: icons["abi_repel"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Knocks the enemy away and applies Immovable to them.\n\nImmovable prevents application of Knockbacks, Pulls, and the Rooted status for 20 seconds.`,
      },
      "Sigmar's Shield": {
        name: "Sigmar's Shield",
        pos: "d9",
        icon: icons["abi_sigmarsshield"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "7s cooldown",
        blue: "Costs 100 Righteous Fury",
        description: talentText`Applies a blessing to target ally for 7 seconds. Each time they are attacked, they will gain a Shield of Faith and 1 stack of a buff. Buff stacks up to 10 times, lasts 3 seconds, and heals the target for 5% RP + 25 per stack at the end of the duration.`,
      },
      "Martyr's Blessing": {
        name: "Martyr's Blessing",
        pos: "f9",
        icon: icons["abi_martyrsblessing"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "self",
        cast: "1.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Deals 13% SAP + 186 spiritual damage to up to 48 enemies within 30 feet in front of you. For each target hit that did not have Cover, all groupmates within 150 feet gain a stack. The stacks heal for 6% RP + 8 each at the end of their 3 second duration.`,
      },
	  "Exalted Defenses": {
        name: "Exalted Defenses",
        pos: "a5",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you block or dodge, you will gain 1 stack of Enhanced Willpower.`,
      },
	  "Sanctity": {
        name: "Sanctity",
        pos: "b5",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Prayers now apply to all groupmates within 150 feet when cast, but now only last 15 seconds.`,
      },
	  "Unberogen Creed": {
        name: "Unberogen Creed",
        pos: "b6",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Twin-Tailed Blow and Radiance now have a 32 foot range.`,
      },
	  "Lay on Hands": {
        name: "Lay on Hands",
        pos: "g6",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Healing Hand",
        arrows: [{ dir: "down", from: "g4", to: "g6" }],
        type: "career tactic",
        description: talentText`The range of Healing Hand is reduced to 75 feet but it now heals for 40% more.`,
      },
	  "Preserving Light": {
        name: "Preserving Light",
        pos: "a7",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Divine Light now has a 15 second duration and Shield of Faith now has a 7 second duration.`,
      },
	  "Moved by the Spirit": {
        name: "Moved by the Spirit",
        pos: "c7",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Spirit of the Heldenhammer",
        arrows: [{ dir: "down", from: "c6", to: "c7" }],
        type: "career tactic",
        description: talentText`Spirit of the Heldenhammer now has a 30 second cooldown, but you and the target will gain 30% movement speed for 5 seconds.`,
      },
	  "Leading the Charge": {
        name: "Leading the Charge",
        pos: "b8",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Divine Assault, Radiance, and Word of Damnation will always apply their effects to you in addition to your defensive target.`,
      },
	  "Stronger Faith": {
        name: "Stronger Faith",
        pos: "e3",
        icon: icons["abi_shieldoffaith"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Shield of Faith now absorbs ${[
          20,
          40,
          60,
        ]}% more damage.`,
      },
	  "Improved Twin-Tailed Blow": {
        name: "Improved Twin-Tailed Blow",
        pos: "b3",
        icon: icons["abi_twintailedblow"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Twin-Tailed Blow will deal ${[
          10,
          20,
        ]}% additional damage.`,
      },
	  "Improved Vigilance": {
        name: "Improved Vigilance",
        pos: "e5",
        icon: icons["abi_vigilance"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Vigilance now only reduces your outgoing damage by ${[
          75,
          60,
          45,
        ]}%.`,
      },
	  "Improved Block": {
        name: "Improved Block",
        pos: "e6",
        icon: icons["skl_specexpertshield"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Your chance to block is increased by ${[
          3,
          6,
          9,
		  12,
		  15,
        ]}%.`,
      },
	  "Improved Lifetaps": {
        name: "Improved Lifetaps",
        pos: "h6",
        icon: icons["abi_blaze"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`Twin-Tailed Blow and Divine Assault now heal your defensive target for an additional ${[
          10,
          25,
        ]}% of the damage dealt.`,
      },
	  "Righteous Wrath": {
        name: "Righteous Wrath",
        pos: "d7",
        icon: icons["abi_wrath"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Wrath will now generate ${[
          3,
          6,
          10,
        ]} more Righteous Fury.`,
      },
	  "Circle of Friends": {
        name: "Circle of Friends",
        pos: "f7",
        icon: icons["abi_circleoffriends"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Whenever you spend Righteous Fury, up to 9 allies within 30 feet of you gain ${[
          "4% RP + 20",
          "8% RP + 40",
          "12% RP + 60",
        ]} health.`,
      },
      "Divine Intervention": {
        name: "Divine Intervention",
        pos: "e8",
        icon: icons["abi_intervention"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Whenever you are effected by knocked-down, disarmed, silenced, or rooted effects; you will gain ${[
          8,
          16,
          24,
          32,
        ]}% damage reduction for 3 seconds.`,
      },
	  
    },
  },
  "Anvil and Torch": {
    name: "Anvil and Torch",
    background: backgrounds["anvilandtorch"],
    icon: icons["archetype_defsupport"],
    talents: {
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a8",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your range is increased by 20%.`,
      },
      "Emperor's Ward": {
        name: "Emperor's Ward",
        pos: "a2",
        icon: icons["tac_race_empire"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet of you with this tactic gain a 20% wounds + 300 absorb for 3 seconds.`,
      },
      "Sigmar's Favored": {
        name: "Sigmar's Favored",
        pos: "b2",
        icon: icons["tac_race_empire"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you receive a direct heal, you will also be healed for 120 + 8% wounds.`,
      },
      "Charged Fury": {
        name: "Charged Fury",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Any ability that generates Righteous Fury will generate 10 more.`,
      },
      "Fueled Fury": {
        name: "Fueled Fury",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you are hit by an ability, you will gain 10 Righteous Fury.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["em_book_1h_t1_01"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Silver and Torch equip one-handed hammers and tomes.`,
      },
	  "Return Life": {
        name: "Return Life",
        pos: "f2",
        icon: icons["morale_returnlife"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "100ft range",
        cast: "3.0s cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Return target groupmate back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn.`,
      },
      "Focused Mind": {
        name: "Focused Mind",
        pos: "g2",
        icon: icons["morale_focusedmind"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 15 seconds. Abilities will have 50% faster cast time and you will have 100% pushback immunity.`,
      },
      "Divine Protection": {
        name: "Divine Protection",
        pos: "h2",
        icon: icons["morale_divineprotection"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 15 seconds. They will absorb up to 200% RP + 1500 damage over the duration.`,
      },
      "Alter Fate": {
        name: "Alter Fate",
        pos: "i2",
        icon: icons["morale_alterfate"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Removes all afflictions and cripples from each groupmate within 100ft. Also applies Return Life to each dead groupmate within 100ft.`,
      },
      "Leading the Prayer": {
        name: "Leading the Prayer",
        pos: "i4",
        icon: icons["morale_leadingtheprayer"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Applies Shield of Faith with the augmented modifer to all groupmates within 100 feet.`,
      },
      "Hammer Time": {
        name: "Hammer Time",
        pos: "i5",
        icon: icons["morale_hammertime"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Gain 250 Righteous Fury.`,
      },
      "Emperor's Champion": {
        name: "Emperor's Champion",
        pos: "i7",
        icon: icons["morale_empchamp"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 20 seconds. For the duration, You gain 250 ballistic skill, 250 intelligence, and 250 strength.`,
      },
      "Avatar of Sigmar": {
        name: "Avatar of Sigmar",
        pos: "i8",
        icon: icons["abi_avatarofsigmar"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Cleanses all Chaos Corruption from up to 96 allies and 96 enemies within 30 feet of you. You gain a buff for 30 seconds. For the duration, you generate 10 Righteous Fury per second, your outgoing damage is increased by 75%, your healing done is increased by 75%, and your HP4 is increased by 1000. At the end of the duration, you die and gain Forlorn.`,
      },
	  "Shield of Faith": {
        name: "Shield of Faith",
        pos: "a1",
        icon: icons["abi_shieldoffaith"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Righteous Fury has a maximum value of 250.\n\nShield of Faith absorbs up to 6% RP + 80 damage over 5 seconds. When Augmented, it will absorb 75% more and apply 1 stack of Enhanced Dodge.`,
      },
	  "Judgement": {
        name: "Judgement",
        pos: "b1",
        icon: icons["abi_judgement"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 3% SAP + 34 spiritual damage to target enemy. You generate 22 action points.`,
      },
      "Penance": {
        name: "Penance",
        pos: "c1",
        icon: icons["abi_em_divineaegis"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "50 action points",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Dispels 1 ailment from target ally and applies a Shield of Faith to them. Generates 10 Righteous Fury.`,
      },
      "Divine Light": {
        name: "Divine Light",
        pos: "d1",
        icon: icons["abi_divinelight"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 60 Righteous Fury",
        description: talentText`Target ally gains 1 stack of Purity and a 5 second blessing that absorbs up to 27% RP + 342 damage.`,
      },
      "Healing Hand": {
        name: "Healing Hand",
        pos: "e1",
        icon: icons["abi_healinghand"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 25 Righteous Fury",
        description: talentText`Applies an enchantment to target ally that heals for 6% RP + 65 every 3 seconds for 15 seconds.`,
      },
      "Prayer of Immaculate Flesh": {
        name: "Prayer of Immaculate Flesh",
        pos: "f1",
        icon: icons["abi_em_divinegaze"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 30 Righteous Fury",
        description: talentText`Target groupmate gains 1 stack of Purity, Shield of Faith, and an enchantment for 60 seconds. For the duration, whenever target uses an ability, they will gain 1 stack of Enhanced Piercing Resistance, Enhanced Impact Resistance, or Enhanced Ichor Resistance.`,
      },
      "Vow of Silence": {
        name: "Vow of Silence",
        pos: "g1",
        icon: icons["abi_vowofsilence"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "30 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Applies Silenced and Inevitable to the target.\n\nSilenced prevents the use of spells for 5 seconds.\nInevitable prevents the application of Disarmed and Silenced for 20 seconds.\n\nAugmented: now has an 80 foot range.`,
      },
      "Prayer of Absolution": {
        name: "Prayer of Absolution",
        pos: "h1",
        icon: icons["abi_em_prayerofabsolution"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 30 Righteous Fury",
        description: talentText`Target groupmate gains 1 stack of Purity, Shield of Faith, and an enchantment for 60 seconds. For the duration, whenever target uses an ability, they will gain 1 stack of Enhanced Corporeal Resistance, Enhanced Elemental Resistance, or Enhanced Spiritual Resistance.`,
      },
      "Repent": {
        name: "Repent",
        pos: "i1",
        icon: icons["abi_em_repent01"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "15s cooldown",
        description: talentText`Target enemy will deal 50% less damage to you for 15 seconds. This effect is removed if you hit the target with an ability.`,
      },
	  "Prayer of Righteousness": {
        name: "Prayer of Righesousness",
        pos: "h4",
        icon: icons["abi_em_blastoffaith"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 30 Righteous Fury",
        description: talentText`Target groupmate gains 1 stack of Purity, Shield of Faith, and an enchantment for 60 seconds that causes them to deal 10% SAP + 115 spiritual damage each time they deal direct damage.`,
      },
	  "Wrath": {
        name: "Wrath",
        pos: "c5",
        icon: icons["abi_wrath"],
        maxRank: 1,
        reqPoints: 10,
        type: "skill",
        cost: "36 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 21% MAP + 280 impact damage to target enemy. Generates 25 Righteous Fury.\n\nAugmented: Deals 25% more damage.`,
      },
	  "Prayer of Devotion": {
        name: "Prayer of Devotion",
        pos: "h6",
        icon: icons["abi_devotion"],
        maxRank: 1,
        reqPoints: 15,
        type: "spell",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 30 Righteous Fury",
        description: talentText`Target groupmate gains 1 stack of Purity, Shield of Faith, and an enchantment for 60 seconds that heals the target for 6% RP + 85 each time they use an ability.`,
      },
	  "Sigmar's Comet": {
        name: "Sigmar's Comet",
        pos: "e8",
        icon: icons["abi_em_righteousblow"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 30 Righteous Fury\nOff the GCD",
        description: talentText`Applies a 5 second cripple to target enemy. At the end of the duration, you deal 25% SAP + 346 impact damage to target enemy and apply 2 stacks of Purity to them. This ability has 2 charges and generates 1 charge every 8 seconds.\n\nAugmented: applies to two other enemies within 20 feet of primary target.`,
      },
      "Supplication": {
        name: "Supplication",
        pos: "d9",
        icon: icons["abi_em_supplication"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "100 action points",
        range: "self",
        cast: "4.5s channel",
        cooldown: "no cooldown",
        description: talentText`Generates 20 Righteous Fury every 0.5 seconds.`,
      },
      "Martyr's Blessing": {
        name: "Martyr's Blessing",
        pos: "f9",
        icon: icons["abi_martyrsblessing"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "self",
        cast: "1.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Deals 13% SAP + 186 spiritual damage to up to 48 enemies within 30 feet in front of you. For each target hit that did not have Cover, all groupmates within 150 feet gain a stack. The stacks heal for 6% RP + 8 each at the end of their 3 second duration.`,
      },
	  "Sanctity": {
        name: "Sanctity",
        pos: "a5",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Prayers now apply to all groupmates within 150 feet when cast, but now only last 15 seconds.`,
      },
	  "Grace of Sigmar": {
        name: "Grace of Sigmar",
        pos: "g5",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`You will now dispel 1 ailment from all groupmates within 100 feet of you when you cast Penance.`,
      },
	  "Benediction": {
        name: "Benediction",
        pos: "b6",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Every 2 seconds, if you have more than 100 action points, convert 20 action points into 10 Righteous Fury.`,
      },
	  "Lay on Hands": {
        name: "Lay on Hands",
        pos: "e6",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`The range of Healing Hand is reduced to 75 feet but it now heals for 40% more.`,
      },
	  "Preserving Light": {
        name: "Preserving Light",
        pos: "a7",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Divine Light now has a 15 second duration and Shield of Faith now has a 7 second duration.`,
      },
	  "Refreshing Radiance": {
        name: "Refreshing Radiance",
        pos: "e7",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Shield of Faith now grants its targets 5 AP regen.`,
      },
	  "Weight of Guilt": {
        name: "Weight of Guilt",
        pos: "d8",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Sigmar's Comet",
		arrows: [
          { dir: "right", from: "d8", to: "e8" },
        ],
        type: "career tactic",
        description: talentText`Sigmar's Comet applies Marked to the target. Marked reduces the target's damage reduction by 15% for 10 seconds.`,
      },
	  "Divine Replenishment": {
        name: "Divine Replenishment",
        pos: "e3",
        icon: icons["abi_em_divinereplenishment"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Generates ${[
          4,
          8,
          12,
        ]} Righteous Fury every 3 seconds.`,
      },
	  "Castigation": {
        name: "Castigation",
        pos: "b4",
        icon: icons["abi_judgement"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Judgement now generates ${[
          3,
          6,
        ]} Righteous Fury.`,
      },
	  "Beacon of Courage": {
        name: "Beacon of Courage",
        pos: "e5",
        icon: icons["abi_em_hammerofsigmar"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`You generate ${[
          1,
          2,
          3,
          4,
          5,
        ]} Righteous Fury whenever an ally with your Shield of Faith is attacked by an enemy.`,
      },
	  "Armor of the Righteous": {
        name: "Armor of the Righteous",
        pos: "c6",
        icon: icons["abi_em_flawlessdefense"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`All groupmates within 100 feet of you gain 1 stack of Purity every ${[
          5,
          3,
        ]} seconds.`,
      },
	  "Stronger Faith": {
        name: "Stronger Faith",
        pos: "g6",
        icon: icons["abi_shieldoffaith"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Shield of Faith now absorbs ${[
          20,
          40,
          60,
		  80,
		  100,
        ]}% more damage.`,
      },
	  "Faith's Bastion": {
        name: "Faith's Bastion",
        pos: "d7",
        icon: icons["abi_em_penance"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Shield of Faith will now provide ${[
          1,
          2,
          3,
          4,
          5,
        ]} second cooldown reduction.`,
      },
	  "Touch of the Divine": {
        name: "Touch of the Divine",
        pos: "f7",
        icon: icons["abi_em_touchofthedivine"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Whenever Divine Light expires without absorbing all of its damage, you will generate ${[
          13,
          27,
          40,
        ]} Righteous Fury.`,
      },
	  "Pious Restoration": {
        name: "Pious Restoration",
        pos: "f8",
        icon: icons["abi_em_divineamazement"],
        maxRank: 4,
        reqPoints: 25,
        prereq: "Sigmar's Comet",
		arrows: [
          { dir: "right", from: "e8", to: "f8" },
        ],
        type: "passive",
        description: talentText`Sigmar's Comet will now restore ${[
          "2% RP + 60",
          "3% RP + 90",
          "4% RP + 120",
          "6% RP + 180",
        ]} health to allies that attack enemies affected by it.`,
      },
    },
  },
  "Cleansing Flame": {
    name: "Cleansing Flame",
    background: backgrounds["cleansingflame"],
    icon: icons["archetype_dps"],
    talents: {
      "Break Loose": {
        name: "Break Loose",
        pos: "a8",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 1,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 3,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 4,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Emperor's Ward": {
        name: "Emperor's Ward",
        pos: "a2",
        icon: icons["tac_race_empire"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet of you with this tactic gain a 20% wounds + 300 absorb for 3 seconds.`,
      },
      "Sigmar's Favored": {
        name: "Sigmar's Favored",
        pos: "b2",
        icon: icons["tac_race_empire"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you receive a direct heal, you will also be healed for 120 + 8% wounds.`,
      },
      "Charged Fury": {
        name: "Charged Fury",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Any ability that generates Righteous Fury will generate 10 more.`,
      },
      "Fueled Fury": {
        name: "Fueled Fury",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you are hit by an ability, you will gain 10 Righteous Fury.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_spechammer"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Cleansing Flame equip two-handed hammers.`,
      },
      "Leading the Prayer": {
        name: "Leading the Prayer",
        pos: "i4",
        icon: icons["morale_leadingtheprayer"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Applies Shield of Faith with the augmented modifer to all groupmates within 100 feet.`,
      },
      "Hammer Time": {
        name: "Hammer Time",
        pos: "i5",
        icon: icons["morale_hammertime"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Gain 250 Righteous Fury.`,
      },
      "Emperor's Champion": {
        name: "Emperor's Champion",
        pos: "i7",
        icon: icons["morale_empchamp"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 20 seconds. For the duration, You gain 250 ballistic skill, 250 intelligence, and 250 strength.`,
      },
      "Avatar of Sigmar": {
        name: "Avatar of Sigmar",
        pos: "i8",
        icon: icons["abi_avatarofsigmar"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Cleanses all Chaos Corruption from up to 96 allies and 96 enemies within 30 feet of you. You gain a buff for 30 seconds. For the duration, you generate 10 Righteous Fury per second, your outgoing damage is increased by 75%, your healing done is increased by 75%, and your HP4 is increased by 1000. At the end of the duration, you die and gain Forlorn.`,
      },
	  "Sever Nerve": {
        name: "Sever Nerve",
        pos: "f2",
        icon: icons["morale_severnerve"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "7.5ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Deals 50% MAP + 400 piercing damage to the target.`,
      },
      "Broad Swings": {
        name: "Broad Swings",
        pos: "g2",
        icon: icons["morale_broadswings"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 10 seconds. Your single target abilities will target two additional enemies within 20 feet in front of you.`,
      },
      "Force of Will": {
        name: "Force of Will",
        pos: "h2",
        icon: icons["morale_forceofwill"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100ft gain a buff for 10 seconds. Action point costs are reduced by 75% for the duration.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
	  "Shield of Faith": {
        name: "Shield of Faith",
        pos: "a1",
        icon: icons["abi_shieldoffaith"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Righteous Fury has a maximum value of 250.\n\nShield of Faith absorbs up to 6% RP + 80 damage over 5 seconds. When Augmented, it will absorb 75% more and apply 1 stack of Enhanced Dodge.`,
      },
      "Judgement": {
        name: "Judgement",
        pos: "b1",
        icon: icons["abi_judgement"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deals 3% SAP + 34 spiritual damage to target enemy. You generate 22 action points.`,
      },
      "Wrath": {
        name: "Wrath",
        pos: "c1",
        icon: icons["abi_wrath"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "36 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 21% MAP + 280 impact damage to target enemy. Generates 25 Righteous Fury.\n\nAugmented: Deals 25% more damage.`,
      },
      "Soulfire": {
        name: "Soulfire",
        pos: "d1",
        icon: icons["abi_em_scornofsigmar"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "10s cooldown",
		blue: "Off the GCD",
        description: talentText`Toggle: While active, all of your abilities will be augmented. You lose 30 Righteous Fury per second and this effect ends if you run out.`,
      },
      "Charge": {
        name: "Charge",
        pos: "e1",
        icon: icons["abi_dw_charge"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "30s cooldown",
        description: talentText`(Movement Skill) For the next 8 seconds, your movement speed is increased by 40%.`,
      },
      "Radiance": {
        name: "Radiance",
        pos: "f1",
        icon: icons["abi_radiance"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 19% MAP + 250 impact damage to target enemy. Your defensive target gains 1 stack of Enhanced Block if they are within 75ft. Generates 30 Righteous Fury.`,
      },
      "Vow of Silence": {
        name: "Vow of Silence",
        pos: "g1",
        icon: icons["abi_vowofsilence"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "30 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Applies Silenced and Inevitable to the target.\n\nSilenced prevents the use of spells for 5 seconds.\nInevitable prevents the application of Disarmed and Silenced for 20 seconds.\n\nAugmented: now has an 80 foot range.`,
      },
      "Prayer of Righteousness": {
        name: "Prayer of Righesousness",
        pos: "h1",
        icon: icons["abi_em_blastoffaith"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "150ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 30 Righteous Fury",
        description: talentText`Target groupmate gains 1 stack of Purity, Shield of Faith, and an enchantment for 60 seconds that causes them to deal 10% SAP + 115 spiritual damage each time they deal direct damage.`,
      },
      "Vigilance": {
        name: "Vigilance",
        pos: "i1",
        icon: icons["abi_vigilance"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        description: talentText`Your damage reduction is increased by 50% but your outgoing damage is reduced by 90% for 7 seconds.`,
      },
	  "Smite": {
        name: "Smite",
        pos: "h4",
        icon: icons["abi_em_smite"],
        maxRank: 1,
        reqPoints: 5,
        type: "spell",
        cost: "75 action points",
        range: "self",
        cast: "1.5s cast",
        cooldown: "no cooldown",
        blue: "Castable While Moving",
        description: talentText`Deals 13% SAP + 184 spiritual damage to up to 9 enemies within 30 feet in front of you.\n\nAugmented: deals 25% more damage.`,
      },
	  "Sigmar's Comet": {
        name: "Sigmar's Comet",
        pos: "a5",
        icon: icons["abi_em_righteousblow"],
        maxRank: 1,
        reqPoints: 10,
        type: "spell",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 30 Righteous Fury\nOff the GCD",
        description: talentText`Applies a 5 second cripple to target enemy. At the end of the duration, you deal 25% SAP + 346 impact damage to target enemy and apply 2 stacks of Purity to them. This ability has 2 charges and generates 1 charge every 8 seconds.\n\nAugmented: applies to two other enemies within 20 feet of primary target.`,
      },
	  "Smash": {
        name: "Smash",
        pos: "e6",
        icon: icons["abi_smash"],
        maxRank: 1,
        reqPoints: 15,
        type: "skill",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Applies Knocked-down and Unstoppable to target enemy.\n\nKnocked-down prevents all control of your character for 3 seconds.\nUnstoppable prevents application of Knocked-down and Staggered for 30 seconds.`,
      },
	  "Word of Damnation": {
        name: "Word of Damnation",
        pos: "e8",
        icon: icons["abi_em_absenceoffaith"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "no cost",
        range: "75ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 25 Righteous Fury",
        description: talentText`Dispels 1 enchantment from target enemy. Applies 1 stack of Enhanced Sagacity to your defensive target.`,
      },
      "Hammer of Sigmar": {
        name: "Capstone Ability 1",
        pos: "d9",
        icon: icons["abi_em_unbalancingblow"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "8s cooldown",
        blue: "Costs 60 Righteous Fury",
        description: talentText`Deals 44% MAP + 590 impact damage to target enemy. If used on an enemy under 40% health, you will generate 60 Righteous Fury.\n\nAugmented: ability has no cooldown.`,
      },
      "Whirlwind": {
        name: "Whirlwind",
        pos: "f9",
        icon: icons["archetype_tank_raze"],
        maxRank: 1,
        reqPoints: 30,
        type: "skill",
        cost: "150 action points",
        range: "self",
        cast: "3.0s channel",
        cooldown: "30s cooldown",
        description: talentText`Deals 6% MAP + 20 piercing damage to up to 96 enemies within 30 feet of you every 0.5 seconds. Each enemy hit will give you a stack of a buff that gives 10% outgoing damage up to 100 stacks.`,
      },
	  "Sanctity": {
        name: "Sanctity",
        pos: "c5",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Prayers now apply to all groupmates within 150 feet when cast, but now only last 15 seconds.`,
      },
	  "Unfair Advantage": {
        name: "Unfair Advantage",
        pos: "g5",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you hit an enemy you are flanking, you will gain a buff for 2 seconds. For the duration, you will gain outgoing damage equal to 100% of your accuracy.`,
      },
	  "Weight of Guilt": {
        name: "Weight of Guilt",
        pos: "b6",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Sigmar's Comet",
		arrows: [
          { dir: "right-down", from: "a5", to: "b5" },
          { dir: "right-down-down", from: "b5", to: "b6" }
        ],
        type: "career tactic",
        description: talentText`Sigmar's Comet applies Marked to the target. Marked reduces the target's damage reduction by 15% for 10 seconds.`,
      },
	  "Unwavering Faith": {
        name: "Unwavering Faith",
        pos: "h6",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Smite",
		arrows: [
          { dir: "down", from: "h4", to: "h6" },
        ],
        type: "career tactic",
        description: talentText`Smite and Absence of Faith now hit up to 24 enemies.`,
      },
	  "Guilty Soul": {
        name: "Guilty Soul",
        pos: "b7",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Whenever you critically hit an enemy, you will apply a 6 second ailment to them. For the duration, deal 8% SAP + 97 spiritual damage every 3 seconds to them.`,
      },
	  "Leading the Charge": {
        name: "Leading the Charge",
        pos: "e7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Divine Assault, Radiance, and Word of Damnation will always apply their effects to you in addition to your defensive target.`,
      },
	  "Purge": {
        name: "Purge",
        pos: "f8",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Word of Damnation",
		arrows: [
          { dir: "right", from: "e8", to: "f8" },
        ],
        type: "career tactic",
        description: talentText`Word of Damnation now cleanses a blessing from target enemy and deals 10% SAP + 190 spiritual damage.`,
      },
	  "Deny the Heretics": {
        name: "Deny the Heretics",
        pos: "e3",
        icon: icons["abi_em_weightofguilt"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever enemies attack allies with your Shield of Faith, you will deal ${[
          "4% MAP + 40",
          "8% MAP + 80",
          "12% MAP + 120",
          "16% MAP + 160",
          "20% MAP + 200",
        ]} impact damage to them.`,
      },
	  "Improved Vigilance": {
        name: "blueprint",
        pos: "e5",
        icon: icons["abi_vigilance"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Vigilance now only reduces your outgoing damage by ${[
          75,
		  60,
          45,
        ]}%.`,
      },
	  "Heart of Gryphon": {
        name: "Heart of Gryphon",
        pos: "d6",
        icon: icons["abi_em_purgatory"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`You have a ${[
          15,
          30,
        ]}% chance whenever you use any ability to apply a Shield of Faith on yourself.`,
      },
	  "Extra Crit": {
        name: "Extra Crit",
        pos: "f6",
        icon: icons["abi_extracrit"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Your chance to critically hit is increased by ${[
          2,
		  4,
          6,
		  8,
		  10,
        ]}%.`,
      },
	  "Divine Fury": {
        name: "Divine Fury",
        pos: "a7",
        icon: icons["abi_em_righteousblow"],
        maxRank: 3,
        reqPoints: 20,
        prereq: "Sigmar's Comet",
		arrows: [
          { dir: "down", from: "a5", to: "a7" },
        ],
        type: "passive",
        description: talentText`Sigmar's Comet now has up to ${[
          3,
          4,
          5,
        ]} charges.`,
      },
	  "Righteous Wrath": {
        name: "Righteous Wrath",
        pos: "h7",
        icon: icons["abi_wrath"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Wrath will now generate ${[
          3,
          6,
          10,
        ]} more Righteous Fury.`,
      },
	  "Absence of Faith": {
        name: "Absence of Faith",
        pos: "d8",
        icon: icons["abi_em_scornofsigmar"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Soulfire will now deal ${[
          "3% MAP + 61",
          "6% MAP + 122",
          "9% MAP + 183",
          "12% MAP + 244",
        ]} spiritual damage every 2 seconds to up to 9 enemies within 30 feet of you.`,
      },
    },
  },
};
