import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/empire"),
);
const icons = requireAll(require.context("../../assets/icons/empire"));

export const data: TalentData = {
  "Anvil and Torch": {
    name: "Anvil and Torch",
    background: backgrounds["anvilandtorch"],
    icon: icons["archetype_defsupport"],
    talents: {
      "Motivated": {
        name: "Motivated",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "b2",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 5 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 20 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "b4",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "b6",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a6",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a8",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Increases your mass by 1.`,
      },
      "Dissipation Expert": {
        name: "Dissipation Expert",
        pos: "a9",
        icon: icons["rrtac_dissipation"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`Whenever you use an ability that removes a buff or debuff, you will gain 15 adrenaline per second for 3 seconds.`,
      },
      "Morale 1 Class": {
        name: "Morale 1c",
        pos: "h2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Class": {
        name: "Morale 2c",
        pos: "h4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Arche": {
        name: "Morale 1a",
        pos: "i2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Race": {
        name: "Morale 3r",
        pos: "b8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Arche": {
        name: "Morale 4a",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Arche": {
        name: "Morale 2a",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Arche": {
        name: "Morale 3a",
        pos: "i6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "h6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "h8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Agility": {
        name: "Agility",
        pos: "b5",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases your Agility by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "b7",
        icon: icons["stat_bal"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "b3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e7",
        icon: icons["stat_int"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "h7",
        icon: icons["stat_str"],
        maxRank: 2,
        reqPoints: 30,
        description: talentText`Increases your Strength by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "e5",
        icon: icons["stat_tou"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "h3",
        icon: icons["stat_wil"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "h5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "e3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Far Sight": {
        name: "Far Sight",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Your range is increased by 20%.`,
      },
      "Emperor's Ward": {
        name: "Emperor's Ward",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you use a basic attack, you will gain a 500 absorb for 3 seconds.`,
      },
      "Sigmar's Favored": {
        name: "Sigmar's Favored",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you receive a direct heal, you will also be healed for 120 + 8% wounds.`,
      },
      "Gift of Life": {
        name: "Gift of Life",
        pos: "d9",
        icon: icons["abi_giftoflife"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`100ft range\n150 AP\n4.0s cast\nspell\n\nReturns target ally back to life at the location of its corpse with 2000 health and no other resources. Cannot be used on corpses with Forlorn. This spell has 0% pushback immunity.`,
      },
      "Supplication": {
        name: "Supplication",
        pos: "f9",
        icon: icons["abi_supplication"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`10s channel\nability\n\nYou generate 15 action points and 15 Righteous Fury every second.`,
      },
      "Shield of Faith": {
        name: "Shield of Faith",
        pos: "b1",
        icon: icons["abi_shieldoffaith"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Target absorbs up to 30% RP + 200 damage over 5 seconds. Shield of Faith does nothing without this passive.`,
      },
      "Conviction": {
        name: "Conviction",
        pos: "c1",
        icon: icons["abi_conviction"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Shield of Faith",
        arrows: [{ dir: "right", from: "b1", to: "c1" }],
        description: talentText`150ft range\n30 AP\n1.0s cast\nspell\n\nApplies Shield of Faith to target ally. You generate 50 Righteous Fury.`,
      },
      "Divine Light": {
        name: "Divine Light",
        pos: "d1",
        icon: icons["abi_divinelight"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`150ft range\n60 RF\ninstant cast\nspell\n\nPlace a tier2 buff on target ally that absorbs up to 100% RP + 200 damage over 5 seconds.`,
      },
      "Preserving Light": {
        name: "Preserving Light",
        pos: "d4",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Divine Light",
        arrows: [{ dir: "down", from: "d1", to: "d4" }],
        description: talentText`Divine Light now has a 10s duration.`,
      },
      "Prayer of Absolution": {
        name: "Prayer of Absolution",
        pos: "e1",
        icon: icons["abi_absolution"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`150ft range\n30 RF\ninstant cast\nspell\n\nApply Shield of Faith, 1 stack of Enhanced Elemental Resistance, and 1 stack of Enhanced Spiritual Resistance to target groupmate.`,
      },
      "Prayer of Immaculate Flesh": {
        name: "Prayer of Immaculate Flesh",
        pos: "f1",
        icon: icons["abi_immaculateflesh"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`150ft range\n30 RF\ninstant cast\nspell\n\nApply Shield of Faith, 1 stack of Enhanced Armor, and 1 stack of Enhanced Corporeal Resistance to target groupmate.`,
      },
      "Judgement": {
        name: "Judgement",
        pos: "g1",
        icon: icons["abi_judgement"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\ninstant cast\nskill\n\n(Basic Attack)Deals 160 spiritual damage to the target. You generate 30 action points.`,
      },
      "Haughty Judgement": {
        name: "Haughty Judgement",
        pos: "h1",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Judgement",
        arrows: [{ dir: "right", from: "g1", to: "h1" }],
        description: talentText`Judgement now has a 75ft range and deals additional damage equal to 15% SAP.`,
      },
      "Blessed Tome": {
        name: "Blessed Tome",
        pos: "c2",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`As long as you have 55 or more action points, you will gain 10 Righteous Fury and lose 5 action points every second.`,
      },
      "Repent": {
        name: "Repent",
        pos: "e2",
        icon: icons["abi_repent"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`150ft range\ninstant cast\n15s CD\nability\n\nTarget enemy will deal 50% less damage to you for 15 seconds. This effect is removed if you hit the target with an ability.`,
      },
      "Purify": {
        name: "Purify",
        pos: "f2",
        icon: icons["abi_purify"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`150ft range\n50 AP\ninstant cast\nspell\n\nDispels a tier1 debuff from target groupmate and applies Shield of Faith. Generates 30 Righteous Fury`,
      },
      "Feed the Masses": {
        name: "Feed the Masses",
        pos: "f6",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Purify",
        arrows: [{ dir: "down", from: "f2", to: "f6" }],
        description: talentText`Purify now affects all groupmates within 100ft.`,
      },
      "Shackle": {
        name: "Shackle",
        pos: "g2",
        icon: icons["abi_shackle2"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`75ft range\n50 AP\ninstant cast\n20s CD\nspell\n\nApplies Rooted and Immovable to target enemy.\n\nRooted reduces your movement speed to 0 for 5 seconds. Immovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Shackled Fury": {
        name: "Shackled Fury",
        pos: "g4",
        icon: icons["abi_shackle2"],
        maxRank: 2,
        reqPoints: 15,
        prereq: "Shackle",
        arrows: [{ dir: "down", from: "g2", to: "g4" }],
        description: talentText`Shackle will now generate ${[
          25,
          50,
        ]} Righteous Fury.`,
      },
      "Fueled Fury": {
        name: "Fueled Fury",
        pos: "c4",
        icon: icons["tac_class_2"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever you are hit by an ability, you will gain 10 Righteous Fury.`,
      },
      "Prayer of Devotion": {
        name: "Prayer of Devotion",
        pos: "c6",
        icon: icons["abi_devotion"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`150ft range\n30 RF\ninstant cast\nspell\n\nTarget groupmate gains Shield of Faith and a tier1 buff for 60 seconds that heals the target for 25% RP + 50 each time they hit an enemy with an ability.`,
      },
      "Sanctity": {
        name: "Sanctity",
        pos: "c8",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Prayer of Devotion",
        arrows: [{ dir: "down", from: "c6", to: "c8" }],
        description: talentText`Prayer of Devotion now applies to all groupmates within 150ft when cast, but now costs 75 Righteous Fury.`,
      },
      "Healing Hand": {
        name: "Healing Hand",
        pos: "d6",
        icon: icons["abi_healinghand"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`150ft range\n25 RF\ninstant cast\nspell\n\nApplies a tier 1 buff to target ally that heals for 20% RP + 100 every 3 seconds for 15 seconds.`,
      },
      "Lay on Hands": {
        name: "Lay on Hands",
        pos: "d8",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Healing Hand",
        arrows: [{ dir: "down", from: "d6", to: "d8" }],
        description: talentText`The range of Healing Hand is reduced to 75ft but it now heals for 30% RP + 100 every 3 seconds.`,
      },
      "Charged Fury": {
        name: "Charged Fury",
        pos: "e6",
        icon: icons["tac_class_1"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`Any ability that generates Righteous Fury will generate 10 more.`,
      },
      "Prayer of Righteousness": {
        name: "Prayer of Righteousness",
        pos: "g6",
        icon: icons["abi_righteousness"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`150ft range\n30 RF\ninstant cast\nspell\n\nTarget groupmate gains Shield of Faith and a tier1 buff for 60 seconds that deals an additional 15% SAP spiritual damage each time they hit an enemy with an ability.`,
      },
      "Probity": {
        name: "Probity",
        pos: "g8",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Prayer of Righteousness",
        arrows: [{ dir: "down", from: "g6", to: "g8" }],
        description: talentText`Prayer of Righteousness now applies to all groupmates within 150ft when cast, but now costs 75 Righteous Fury.`,
      },
      "Vow of Silence": {
        name: "Vow of Silence",
        pos: "e8",
        icon: icons["abi_vowofsilence"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`melee range\n40 AP\n10s CD\nskill\n\nApplies Silenced and Inevitable to the target.\n\nSilenced prevents the use of spells for 5 seconds. Inevitable prevents the application of Disarmed and Silenced for 20 seconds.`,
      },
      "Encompassing Vows": {
        name: "Encompassing Vows",
        pos: "f8",
        icon: icons["abi_vowofsilence"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Vow of Silence",
        arrows: [{ dir: "right", from: "e8", to: "f8" }],
        description: talentText`Vow of Silence now has a 75ft application range but also costs 50 action points.`,
      },
    },
  },
  "Silver Hammer": {
    name: "Silver Hammer",
    background: backgrounds["silverhammer"],
    icon: icons["archetype_healer"],
    talents: {
      "Motivated": {
        name: "Motivated",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "b2",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 5 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 20 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "b4",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "b6",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a6",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a8",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Increases your mass by 1.`,
      },
      "Loved By All": {
        name: "Loved By All",
        pos: "a9",
        icon: icons["rrtac_lovedbyall"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`You always have Unstoppable. Your mass is decreased by 2.`,
      },
      "Morale 1 Class": {
        name: "Morale 1c",
        pos: "h2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Class": {
        name: "Morale 2c",
        pos: "h4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Arche": {
        name: "Morale 1a",
        pos: "i2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Race": {
        name: "Morale 3r",
        pos: "b8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Arche": {
        name: "Morale 4a",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Arche": {
        name: "Morale 2a",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Arche": {
        name: "Morale 3a",
        pos: "i6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "h6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "h8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Agility": {
        name: "Agility",
        pos: "b5",
        icon: icons["stat_agl"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`Increases your Agility by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "b7",
        icon: icons["stat_bal"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "b3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e7",
        icon: icons["stat_int"],
        maxRank: 4,
        reqPoints: 30,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "h7",
        icon: icons["stat_str"],
        maxRank: 4,
        reqPoints: 30,
        description: talentText`Increases your Strength by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "e5",
        icon: icons["stat_tou"],
        maxRank: 2,
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "h3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "h5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "e3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 2.`,
      },
      "Emperor's Ward": {
        name: "Emperor's Ward",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you use a basic attack, you will gain a 500 absorb for 3 seconds.`,
      },
      "Sigmar's Favored": {
        name: "Sigmar's Favored",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you receive a direct heal, you will also be healed for 120 + 8% wounds.`,
      },
      "Sigmar's Shield": {
        name: "Sigmar's Shield",
        pos: "d9",
        icon: icons["abi_sigmarsshield"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`75ft range\n100 RF\ninstant cast\n7.0s CD\nspell\n\nApplies a tier2 buff to the target for 7 seconds. Each time they are attacked they will gain a Shield of Faith and 1 stack of a tier3 buff. The tier 3 buff stacks up to 10 times, lasts 3 seconds, and heals the target for 5% RP + 25 per stack.`,
      },
      "Martyr's Blessing": {
        name: "Martyr's Blessing",
        pos: "f9",
        icon: icons["abi_martyrsblessing"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`100 RF\n2.0s cast\n300s CD\nspell\n\nDeals 10% SAP + 50 spiritual damage to up to 48 enemies within 30ft in front of you. For each target hit that did not have Cover, all groupmates within 150ft gain a stack. The stacks heal for 20% RP + 10 each at the end of their 2 second duration.`,
      },
      "Shield of Faith": {
        name: "Shield of Faith",
        pos: "b1",
        icon: icons["abi_shieldoffaith"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Target absorbs up to 30% RP + 200 damage over 5 seconds. Shield of Faith does nothing without this passive.`,
      },
      "Twin-Tailed Blow": {
        name: "Twin-Tailed Blow",
        pos: "c1",
        icon: icons["abi_twintailedblow"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`10ft range\n50 AP\ninstant cast\nskill\n\nDeals 20% MAP + 160 spiritual damage to target enemy. Your defensive target will be healed for 150% of the damage dealt and applies Shield of Faith to groupmates within 75ft. Generates 30 Righteous Fury.`,
      },
      "Unberogen Creed": {
        name: "Unberogen Creed",
        pos: "c2",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 5,
        prereq: "Twin-Tailed Blow",
        arrows: [{ dir: "down", from: "c1", to: "c2" }],
        description: talentText`Twin-Tailed Blow and Radiance now have a 30ft range.`,
      },
      "Divine Light": {
        name: "Divine Light",
        pos: "d1",
        icon: icons["abi_divinelight"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`150ft range\n60 RF\ninstant cast\nspell\n\nPlace a tier2 buff on target ally that absorbs up to 100% RP + 200 damage over 5 seconds.`,
      },
      "Preserving Light": {
        name: "Preserving Light",
        pos: "d4",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Divine Light",
        arrows: [{ dir: "down", from: "d1", to: "d4" }],
        description: talentText`Divine Light now has a 10s duration.`,
      },
      "Wrath": {
        name: "Wrath",
        pos: "e1",
        icon: icons["abi_wrath"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\n50 AP\ninstant cast\nskill\n\nDeals 30% MAP + 300 physical damage to target enemy. Generates 50 Righteous Fury.`,
      },
      "Divine Assault": {
        name: "Divine Assault",
        pos: "f1",
        icon: icons["abi_divineassault"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\n80 RF\n3.0s channel\nskill\n\nDeals 10%MAP + 100 spiritual damage to the target every second. Your defensive target will be healed for 300% of the damage you dealt if they were within 75ft.`,
      },
      "Radiance": {
        name: "Radiance",
        pos: "f2",
        icon: icons["abi_radiance"],
        maxRank: 1,
        reqPoints: 5,
        prereq: "Divine Assault",
        arrows: [{ dir: "down", from: "f1", to: "f2" }],
        description: talentText`10ft range\n30 AP\ninstant cast\nskill\n\nDeals 20% MAP + 160 spiritual damage to target enemy. Your defensive target gains 1 stack of Enhanced Block if they are within 75ft. Generates 30 Righteous Fury.`,
      },
      "Leading the Charge": {
        name: "Leading the Charge",
        pos: "f6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Radiance",
        arrows: [{ dir: "down", from: "f2", to: "f6" }],
        description: talentText`Divine Assault and Radiance will always apply their effects to you in addition to your defensive target.`,
      },
      "Judgement": {
        name: "Judgement",
        pos: "g1",
        icon: icons["abi_judgement"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\ninstant cast\nskill\n\n(Basic Attack) Deals 160 spiritual damage to the target. You generate 30 action points.`,
      },
      "Exalted Defenses": {
        name: "Exalted Defenses",
        pos: "h1",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you block or dodge, you will gain 1 stack of Enhanced Willpower.`,
      },
      "Repel": {
        name: "Repel",
        pos: "e2",
        icon: icons["abi_repel"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`melee range\n50AP\ninstant cast\n10s CD\nskill\n\nKnocks the enemy away and applies Immovable to them. Generates 5 mechanic points.\n\nImmovable prevents application of Knockbacks, Pulls, and the Rooted status for 20 seconds.`,
      },
      "Vigilance": {
        name: "Vigilance",
        pos: "g2",
        icon: icons["abi_vigilance"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`instant cast\n60s CD\nability\n\nAll damage you take is reduced by 50% but all damage you deal is reduced by 90% for 5 seconds.`,
      },
      "Improved Vigilance": {
        name: "Improved Vigilance",
        pos: "g4",
        icon: icons["abi_vigilance"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Vigilance",
        arrows: [{ dir: "down", from: "g2", to: "g4" }],
        description: talentText`Vigilance now only reduces your outgoing damage by 75%.`,
      },
      "Fueled Fury": {
        name: "Fueled Fury",
        pos: "c4",
        icon: icons["tac_class_2"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever you are hit by an ability, you will gain 10 Righteous Fury.`,
      },
      "Prayer of Devotion": {
        name: "Prayer of Devotion",
        pos: "c6",
        icon: icons["abi_devotion"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`150ft range\n30 RF\ninstant cast\nspell\n\nTarget groupmate gains Shield of Faith and a tier1 buff for 60 seconds that heals the target for 25% RP + 50 each time they hit an enemy with an ability.`,
      },
      "Sanctity": {
        name: "Sanctity",
        pos: "c8",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Prayer of Devotion",
        arrows: [{ dir: "down", from: "c6", to: "c8" }],
        description: talentText`Prayer of Devotion now applies to all groupmates within 150ft when cast, but now costs 75 Righteous Fury.`,
      },
      "Healing Hand": {
        name: "Healing Hand",
        pos: "d6",
        icon: icons["abi_healinghand"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`150ft range\n25 RF\ninstant cast\nspell\n\nApplies a tier 1 buff to target ally that heals for 20% RP + 100 every 3 seconds for 15 seconds.`,
      },
      "Lay on Hands": {
        name: "Lay on Hands",
        pos: "d8",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Healing Hand",
        arrows: [{ dir: "down", from: "d6", to: "d8" }],
        description: talentText`The range of Healing Hand is reduced to 75ft but it now heals for 30% RP + 100 every 3 seconds.`,
      },
      "Charged Fury": {
        name: "Charged Fury",
        pos: "e6",
        icon: icons["tac_class_1"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`Any ability that generates Righteous Fury will generate 10 more.`,
      },
      "Spirit of the Heldenhammer": {
        name: "Spirit of the Heldenhammer",
        pos: "g6",
        icon: icons["abi_spiritofh"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`75ft range\ninstant cast\n5.0s CD\nspell\n\nApplies a tier3 buff to target ally that heals them for 7% of your wounds + 420 every second for 5 seconds. Applies a tier3 debuff to you that deals 7% of your wounds + 420 true damage every second and reduces your healing received by 70% for 5 seconds.`,
      },
      "Moved by the Spirit": {
        name: "Moved by the Spirit",
        pos: "g8",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Spirit of the Heldenhammer",
        arrows: [{ dir: "down", from: "g6", to: "g8" }],
        description: talentText`Spirit of the Heldenhammer now has a 30s CD, but you will gain 30% movement speed for 5 seconds.`,
      },
      "Vow of Silence": {
        name: "Vow of Silence",
        pos: "e8",
        icon: icons["abi_vowofsilence"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`melee range\n40 AP\n10s CD\nskill\n\nApplies Silenced and Inevitable to the target.\n\nSilenced prevents the use of spells for 5 seconds. Inevitable prevents the application of Disarmed and Silenced for 20 seconds.`,
      },
      "Encompassing Vows": {
        name: "Encompassing Vows",
        pos: "f8",
        icon: icons["abi_vowofsilence"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Vow of Silence",
        arrows: [{ dir: "right", from: "e8", to: "f8" }],
        description: talentText`Vow of Silence now has a 75ft application range but also costs 50 action points.`,
      },
    },
  },
  "Cleansing Flame": {
    name: "Cleansing Flame",
    background: backgrounds["cleansingflame"],
    icon: icons["archetype_dps"],
    talents: {
      "Motivated": {
        name: "Motivated",
        pos: "a2",
        icon: icons["rrtac_motivated"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`You gain 5 adrenaline every second while in combat.`,
      },
      "Strength in Numbers": {
        name: "Strength in Numbers",
        pos: "b2",
        icon: icons["rrtac_strengthinnumbers"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`Whenever you use a basic attack, all groupmates within 100 feet that also have this tactic will gain a stack. Max 5 stacks, each stack grants 2 adrenaline per second for a duration of 5 seconds.`,
      },
      "Uncontrolled": {
        name: "Uncontrolled",
        pos: "a4",
        icon: icons["rrtac_uncontrolled"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever Unstoppable, Inevitable, or Immovable is applied to you, you will gain 20 adrenaline per second over 5 seconds.`,
      },
      "Stay in Formation": {
        name: "Stay in Formation",
        pos: "b4",
        icon: icons["rrtac_stayinformation"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever you are attacked by an opponent you have Cover from, you will gain 10 adrenaline per second for 3 seconds.`,
      },
      "Gotta Go Fast": {
        name: "Gotta Go Fast",
        pos: "b6",
        icon: icons["rrtac_gottagofast"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 1 stack of Revelry every second while moving.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Festive Chaos": {
        name: "Festivity",
        pos: "a6",
        icon: icons["rrtac_festivechaos"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`You gain 2 stacks of Revelry each time you use an ability. Whenever you critically hit, you will lose all stacks of Revelry.\n\nRevelry: 1 adrenaline per second. Stacks 15 times and lasts 3 seconds.`,
      },
      "Fatass": {
        name: "Fatass",
        pos: "a8",
        icon: icons["rrtac_fatass"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`Increases your mass by 1.`,
      },
      "Break Loose": {
        name: "Break Loose",
        pos: "a9",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Morale 1 Class": {
        name: "Morale 1c",
        pos: "h2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Class": {
        name: "Morale 2c",
        pos: "h4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Arche": {
        name: "Morale 1a",
        pos: "i2",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Race": {
        name: "Morale 3r",
        pos: "b8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Arche": {
        name: "Morale 4a",
        pos: "i8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Arche": {
        name: "Morale 2a",
        pos: "i4",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`placeholder atm`,
      },
      "Morale 3 Arche": {
        name: "Morale 3a",
        pos: "i6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`placeholder atm`,
      },
      "Morale 4 Spec": {
        name: "Morale 4s",
        pos: "i9",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`placeholder atm`,
      },
      "Morale 1 Spec": {
        name: "Morale 1s",
        pos: "h6",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`placeholder atm`,
      },
      "Morale 2 Spec": {
        name: "Morale 2s",
        pos: "h8",
        icon: icons["noicon"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`placeholder atm`,
      },
      "Agility": {
        name: "Agility",
        pos: "b5",
        icon: icons["stat_agl"],
        maxRank: 1,
        reqPoints: 20,
        description: talentText`Increases your Agility by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "b7",
        icon: icons["stat_bal"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Ballistic Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "b3",
        icon: icons["stat_ini"],
        maxRank: 2,
        reqPoints: 10,
        description: talentText`Increases your Initiative by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "e7",
        icon: icons["stat_int"],
        maxRank: 4,
        reqPoints: 30,
        description: talentText`Increases your Intelligence by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "h7",
        icon: icons["stat_str"],
        maxRank: 3,
        reqPoints: 30,
        description: talentText`Increases your Strength by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "e5",
        icon: icons["stat_tou"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases your Toughness by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "h3",
        icon: icons["stat_wil"],
        maxRank: 1,
        reqPoints: 10,
        description: talentText`Increases your Willpower by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "h5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 20,
        description: talentText`Increases your Wounds by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "e3",
        icon: icons["stat_ws"],
        maxRank: 5,
        reqPoints: 10,
        description: talentText`Increases your Weapon Skill by ${[
          40,
          95,
          165,
          250,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "e4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 2.`,
      },
      "Emperor's Ward": {
        name: "Emperor's Ward",
        pos: "a1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you use a basic attack, you will gain a 500 absorb for 3 seconds.`,
      },
      "Sigmar's Favored": {
        name: "Sigmar's Favored",
        pos: "i1",
        icon: icons["tac_race_empire"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Whenever you receive a direct heal, you will also be healed for 120 + 8% wounds.`,
      },
      "Avatar of Sigmar": {
        name: "Avatar of Sigmar",
        pos: "d9",
        icon: icons["abi_avatarofsigmar"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`30 RF/s\ninstant cast\nability\n\nYou become master of all 4 elements...wait wrong avatar. Sigmar's power courses through granting you 250 weapon skill and 250 willpower and you will gain Shield of Faith every 2 seconds as long as the skill is toggled on.`,
      },
      "Soulfire": {
        name: "Soulfire",
        pos: "f9",
        icon: icons["abi_soulfire"],
        maxRank: 1,
        reqPoints: 40,
        description: talentText`30 RF/s\ninstant cast\nability\n\nYou deal 25% SAP + 75 spiritual damage every 2 seconds to up to 48 enemies within 30ft of you. Targets under Cover from you take no damage.`,
      },
      "Shield of Faith": {
        name: "Shield of Faith",
        pos: "b1",
        icon: icons["abi_shieldoffaith"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`Target will deal 10% SAP + 25 spiritual damage to the next enemy that attacks them in the next 5 seconds. Shield of Faith does nothing without this passive.`,
      },
      "Wrath": {
        name: "Wrath",
        pos: "c1",
        icon: icons["abi_wrath"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Shield of Faith",
        arrows: [{ dir: "right", from: "b1", to: "c1" }],
        description: talentText`melee range\n50 AP\ninstant cast\nskill\n\nDeals 30% MAP + 300 physical damage to target enemy. Generates 50 Righteous Fury.`,
      },
      "Heart of the Gryphon": {
        name: "Heart of the Gryphon",
        pos: "d1",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Wrath",
        arrows: [{ dir: "right", from: "c1", to: "d1" }],
        description: talentText`Whenever you cast Wrath or are the victim of a critical hit, you will gain Shield of Faith.`,
      },
      "Charge": {
        name: "Charge",
        pos: "e1",
        icon: icons["abi_charge"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`instant cast\n30s CD\nability\n\n(Movement Skill) You gain 40% movement speed for 8 seconds. Effect will end if you use any ability.`,
      },
      "Hammer of Sigmar": {
        name: "Hammer of Sigmar",
        pos: "f1",
        icon: icons["abi_hammerofsigmar"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\n50 AP\ninstant cast\nskill\n\nDeals 30% MAP + 300 physical damage to the target. If the target is below 50% health, deals 50% MAP + 300 physical damage to the target.`,
      },
      "Judgement": {
        name: "Judgement",
        pos: "g1",
        icon: icons["abi_judgement"],
        maxRank: 1,
        reqPoints: 0,
        description: talentText`melee range\ninstant cast\nskill\n\n(Basic Attack)Deals 160 spiritual damage to the target. You generate 30 action points.`,
      },
      "Haughty Judgement": {
        name: "Haughty Judgement",
        pos: "h1",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Judgement",
        arrows: [{ dir: "right", from: "g1", to: "h1" }],
        description: talentText`Judgement now has a 75ft range and deals additional damage equal to 15% SAP.`,
      },
      "Greathammer Mastery": {
        name: "Greathammer Mastery",
        pos: "g2",
        icon: icons["abi_greathammermastery"],
        maxRank: 1,
        reqPoints: 5,
        prereq: "Judgement",
        arrows: [{ dir: "down", from: "g1", to: "g2" }],
        description: talentText`Judgement will deal 60% more damage.`,
      },
      "Fueled Fury": {
        name: "Fueled Fury",
        pos: "c2",
        icon: icons["tac_class_2"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`Whenever you are hit by an ability, you will gain 10 Righteous Fury.`,
      },
      "Shackle": {
        name: "Shackle",
        pos: "d2",
        icon: icons["abi_shackle2"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`75ft range\n50 AP\ninstant cast\n20s CD\nspell\n\nApplies Rooted and Immovable to target enemy.\n\nRooted reduces your movement speed to 0 for 5 seconds. Immovable prevents application of Rooted, Knockbacks, and Pull effects for 20 seconds.`,
      },
      "Shackled Fury": {
        name: "Shackled Fury",
        pos: "d4",
        icon: icons["abi_shackle2"],
        maxRank: 2,
        reqPoints: 15,
        prereq: "Shackle",
        arrows: [{ dir: "down", from: "d2", to: "d4" }],
        description: talentText`Shackle will now generate ${[
          25,
          50,
        ]} Righteous Fury.`,
      },
      "Radiance": {
        name: "Radiance",
        pos: "e2",
        icon: icons["abi_radiance"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`10ft range\n30 AP\ninstant cast\nskill\n\nDeals 20% MAP + 160 spiritual damage to target enemy. Your defensive target gains 1 stack of Enhanced Block if they are within 75ft. Generates 30 Righteous Fury.`,
      },
      "Vigilance": {
        name: "Vigilance",
        pos: "f2",
        icon: icons["abi_vigilance"],
        maxRank: 1,
        reqPoints: 5,
        description: talentText`instant cast\n60s CD\nability\n\nAll damage you take is reduced by 50% but all damage you deal is reduced by 90% for 5 seconds.`,
      },
      "Improved Vigilance": {
        name: "Improved Vigilance",
        pos: "f4",
        icon: icons["abi_vigilance"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Vigilance",
        arrows: [{ dir: "down", from: "f2", to: "f4" }],
        description: talentText`Vigilance now only reduces your outgoing damage by 75%.`,
      },
      "Staying Power": {
        name: "Staying Power",
        pos: "f6",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Improved Vigilance",
        arrows: [{ dir: "down", from: "f4", to: "f6" }],
        description: talentText`Reduce the cooldown of Perseverance and Vigilance by 50%.`,
      },
      "Smite": {
        name: "Smite",
        pos: "c4",
        icon: icons["abi_smite"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`75 AP\n1.0s cast\nspell\n\nDeals 10% SAP + 75 spiritual damage to up to 9 enemies within 30ft in front of you. Generates 50 Righteous Fury`,
      },
      "Heldenhammer's Fury": {
        name: "Heldenhammer's Fury",
        pos: "g4",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 15,
        description: talentText`Whenever you critically hit an enemy, you will deal 75% SAP + 300 spiritual damage over 6 seconds to the target. This effect does not refresh.`,
      },
      "Weight of Guilt": {
        name: "Weight of Guilt",
        pos: "c6",
        icon: icons["abi_weightofguilt"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`melee range\n50 AP\ninstant cast\nskill\n\nDeals 15% MAP + 160 physical damage to the target and applies 1 stack of Reduced Healing Received. Generates 20 Righteous Fury`,
      },
      "Guilty Soul": {
        name: "Guilty Soul",
        pos: "c8",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 0,
        prereq: "Weight of Guilt",
        arrows: [{ dir: "down", from: "c6", to: "c8" }],
        description: talentText`Weight of Guilt will deal 37% MAP + 160 physical damage and apply 2 stacks.`,
      },
      "Twin-Tailed Comet": {
        name: "Twin-Tailed Comet",
        pos: "d6",
        icon: icons["abi_comet"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`75ft range\n25 RF\ninstant cast\nspell\n\nApplies a tier1 debuff to the target for 6 seconds. At the end of the duration the target will take 30% SAP + 160 physical damage to the target. This skill does not trigger the GCD.`,
      },
      "Fanatacism": {
        name: "Fanatacism",
        pos: "d8",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Twin-Tailed Comet",
        arrows: [{ dir: "down", from: "d6", to: "d8" }],
        description: talentText`your chance to critically hit is increased by 15% against targets marked by Twin-Tailed Comet.`,
      },
      "Charged Fury": {
        name: "Charged Fury",
        pos: "e6",
        icon: icons["tac_class_1"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`Any ability that generates Righteous Fury will generate 10 more.`,
      },
      "Prayer of Righteousness": {
        name: "Prayer of Righteousness",
        pos: "g6",
        icon: icons["abi_righteousness"],
        maxRank: 1,
        reqPoints: 25,
        description: talentText`150ft range\n30 RF\ninstant cast\nspell\n\nTarget groupmate gains Shield of Faith and a tier1 buff for 60 seconds that deals an additional 15% SAP spiritual damage each time they hit an enemy with an ability.`,
      },
      "Probity": {
        name: "Probity",
        pos: "g8",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Prayer of Righteousness",
        arrows: [{ dir: "down", from: "g6", to: "g8" }],
        description: talentText`Prayer of Righteousness now applies to all groupmates within 150ft when cast, but now costs 75 Righteous Fury.`,
      },
      "Vow of Silence": {
        name: "Vow of Silence",
        pos: "e8",
        icon: icons["abi_vowofsilence"],
        maxRank: 1,
        reqPoints: 35,
        description: talentText`melee range\n40 AP\n10s CD\nskill\n\nApplies Silenced and Inevitable to the target.\n\nSilenced prevents the use of spells for 5 seconds. Inevitable prevents the application of Disarmed and Silenced for 20 seconds.`,
      },
      "Encompassing Vows": {
        name: "Encompassing Vows",
        pos: "f8",
        icon: icons["abi_vowofsilence"],
        maxRank: 1,
        reqPoints: 35,
        prereq: "Vow of Silence",
        arrows: [{ dir: "right", from: "e8", to: "f8" }],
        description: talentText`Vow of Silence now has a 75ft application range but also costs 50 action points.`,
      },
    },
  },
};
