import { TalentData } from "../../TalentContext";
import { talentText, requireAll } from "../../utils";

const backgrounds = requireAll(
  require.context("../../assets/tree-backgrounds/dwarf"),
);
const icons = requireAll(require.context("../../assets/icons/dwarf"));

export const data: TalentData = {
  "Skavenslayer": {
    name: "Skavenslayer",
    background: backgrounds["skavenslayer"],
    icon: icons["archetype_dps"],
    talents: {
      "Break Loose": {
        name: "Break Loose",
        pos: "a8",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Ancestral Inheritance": {
        name: "Ancestral Inheritance",
        pos: "a2",
        icon: icons["tac_race_dwarf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You are immune to effects that apply stacks of Reduced Armor.`,
      },
      "Stoutness of Stone": {
        name: "Soutness of Stone",
        pos: "b2",
        icon: icons["tac_race_dwarf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Your mass is increased by 1.`,
      },
      "Push for More": {
        name: "Push for More",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you spend Bloodthirst, you will heal yourself for 480 + 32% wounds.`,
      },
      "Honor Restored": {
        name: "Class Tactic 2",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you die, you are instantly ressurected to 2000 health and deal 10% MAP + 150 impact damage to up to 24 enemies within 30 feet. This effect can only happen once every 90 seconds.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specaxe"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Skavenslayers dual wield one-handed axes.`,
      },
      "Onslaught": {
        name: "Onslaught",
        pos: "i4",
        icon: icons["abi_dw_axetoss"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`For 60 seconds, the next 8 basic attacks you do will deal an additional 10% MAP + 100 indirect, impact damage.`,
      },
      "Even the Odds": {
        name: "Even the Odds",
        pos: "i5",
        icon: icons["abi_dw_face20"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain 75 toughness for each enemy within 30 feet. Stacks up to 10 times and lasts for 15 seconds.`,
      },
      "Dwarven Sprint": {
        name: "Dwarven Sprint",
        pos: "i7",
        icon: icons["abi_dw_figure12"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 20 seconds. For the duration, you gain 5 mass and 25% movement speed.`,
      },
      "Unleashed Power": {
        name: "Unleashed Power",
        pos: "i8",
        icon: icons["abi_dw_unleashedpower"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Gain a buff for 20 seconds. Every second, you gain 20 rage and 1 Bloodthirst; you gain 33% damage reduction for the duration.`,
      },
	  "Sever Nerve": {
        name: "Sever Nerve",
        pos: "f2",
        icon: icons["morale_severnerve"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Deals 50% MAP + 400 piercing damage to the target.`,
      },
      "Broad Swings": {
        name: "Broad Swings",
        pos: "g2",
        icon: icons["morale_broadswings"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 10 seconds. Your single target abilities will target two additional enemies within 20 feet in front of you.`,
      },
      "Force of Will": {
        name: "Force of Will",
        pos: "h2",
        icon: icons["morale_forceofwill"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 10 seconds. Action point costs are reduced by 75% for the duration.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "Rage and Bloodthirst": {
        name: "Rage and Bloodthirst",
        pos: "a1",
        icon: icons["abi_dw_fierceness"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`You gain a buff for 5 seconds whenever you take or deal damage that increases your rage generated per second by 5.\nFurious (26-75 rage): Lose 50% of your armor and all resistances. Gain penetration equal to 20% of the amount lost.\nBerserk (76-100 rage): You lose 75% of your total incoming healing received stat. Gain melee attack power equal to 10 times the amount lost.\n\nBloodthirst lasts for 60 seconds and stacks up to 5 times. Gain 1 rage per second per stack.`,
      },
      "Grimnir's Fury": {
        name: "Grimnir's Fury",
        pos: "b1",
        icon: icons["abi_dw_melee05"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deal 4% MAP + 30 impact damage to target enemy. Generates 22 action points.`,
      },
      "Charge": {
        name: "Charge",
        pos: "c1",
        icon: icons["abi_dw_charge"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "30s cooldown",
        description: talentText`(Movement Skill) For the next 8 seconds, your movement speed is increased by 40%.`,
      },
      "Heavy Blow": {
        name: "Heavy Blow",
        pos: "d1",
        icon: icons["abi_dw_heavyblow"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 26% MAP + 348 piercing damage to target enemy.`,
      },
      "Cleft in Twain": {
        name: "Cleft in Twain",
        pos: "e1",
        icon: icons["abi_dw_cleftintwain"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 30 Rage",
        description: talentText`Deals 18% MAP + 232 piercing damage to target enemy and up to 2 other enemies within 20 feet of them.`,
      },
      "Fueled by Violence": {
        name: "Fueled by Violence",
        pos: "f1",
        icon: icons["abi_dw_eventheodds"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "2s cooldown",
        blue: "Off the GCD\nCosts 50 Rage",
        description: talentText`Generates 55 action points and 1 Bloodthirst.`,
      },
      "Anklecrusher": {
        name: "Anklecrusher",
        pos: "g1",
        icon: icons["abi_dw_foot04"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "40 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Applies Rooted and Immovable to target enemy. Generates 25 Rage.\n\nRooted prevents the character from moving for 5 seconds.\nImmovable prevents application of Rooted, Knockback, and Pull effects for 20 seconds.`,
      },
      "Deathblow": {
        name: "Deathblow",
        pos: "h1",
        icon: icons["abi_dw_grievousharm"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs Bloodthirst",
        description: talentText`Deals 44% MAP + 590 impact damage to target enemy.`,
      },
      "Vigilance": {
        name: "Vigilance",
        pos: "i1",
        icon: icons["abi_vigilance"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        description: talentText`All damage you take is reduced by 50% but all damage you deal is reduced by 90% for 7 seconds.`,
      },
	  "Flurry": {
        name: "Flurry",
        pos: "g4",
        icon: icons["abi_dw_flurry"],
        maxRank: 1,
        reqPoints: 5,
        type: "skill",
        cost: "75 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 10% MAP + 127 piercing damage to up to 9 enemies within 30 feet in front of you.`,
      },
	  "Devastate": {
        name: "Devastate",
        pos: "c5",
        icon: icons["abi_dw_devastate"],
        maxRank: 1,
        reqPoints: 10,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 75 Rage",
        description: talentText`Deals 37% MAP + 492 piercing damage to target enemy. Generates 1 Bloodthirst.`,
      },
	  "Wild Swing": {
        name: "Wild Swing",
        pos: "g6",
        icon: icons["abi_dw_wildswing"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Flurry",
        arrows: [{ dir: "down", from: "g4", to: "g6" }],
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs Bloodthirst",
        description: talentText`Deals 12% MAP + 170 piercing damage to up to 9 enemies within 30 feet in front of you.`,
      },
	  "Cave-In": {
        name: "Cave-In",
        pos: "e8",
        icon: icons["abi_dw_figure15"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Applies Knocked-down and Unstoppable to target enemy.\n\nKnocked-down prevents all control of your character for 3 seconds.\nUnstoppable prevents the application of Knocked-down and Staggered for 30 seconds.`,
      },
      "Slaughterer": {
        name: "Slaughterer",
        pos: "d9",
        icon: icons["abi_dw_deadlydetermination"],
        maxRank: 1,
        reqPoints: 30,
        type: "passive",
        description: talentText`Gain 150 maximum action points, gain 5 Rage per second, and Grimnir's Fury will deal 300% additional damage but no longer generate action points.`,
      },
      "Inevitable Doom": {
        name: "Inevitable Doom",
        pos: "f9",
        icon: icons["abi_dw_impendingdoom"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "self",
        cast: "1.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Applies a 6 second duration cripple to up to 9 enemies within 30 feet of you. Every 2 seconds up to 9 enemies within 20 feet of the target will take 3% MAP + 27 ichor damage.`,
      },
	  "Not Yet!": {
        name: "Not Yet!",
        pos: "a5",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Vigilance will now set your Rage to 0 and generate 1 Bloodthirst.`,
      },
	  "Unfair Advantage": {
        name: "Unfair Advantage",
        pos: "h5",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you hit an enemy you are flanking, you will gain a buff for 2 seconds. For the duration, you will gain outgoing damage equal to 100% of your accuracy.`,
      },
	  "Short Temper": {
        name: "Short Temper",
        pos: "d6",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Your action point costs are reduced by 20% whenever you are Furious and by 40% whenever you are Berserk. Enemies that attack you gain 5 action points.`,
      },
	  "Unbridled Ferocity": {
        name: "Unbridled Ferocity",
        pos: "f6",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Each stack of Bloodthirst now generates 2 Rage per second but reduces your adrenaline regen by 1.`,
      },
	  "Crushing Force": {
        name: "Crushing Force",
        pos: "a7",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Cleft in Twain will deal 50% additional damage to a target that has casted an active Guard effect.`,
      },
	  "Reckless Abandon": {
        name: "Reckless Abandon",
        pos: "b7",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Reckless Gamble",
		arrows: [{ dir: "down", from: "b6", to: "b7" }],
        type: "career tactic",
        description: talentText`Deals 3% MAP + 50 indirect, impact damage every 3 seconds to yourself and up to 9 enemies within 30 feet of you for each stack of Bloodthirst you have.`,
      },
	  "Extended Battle": {
        name: "Extended Battle",
        pos: "g8",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 25,
        prereq: "Wild Swing",
		arrows: [{ dir: "down", from: "g6", to: "g8" }],
        type: "career tactic",
        description: talentText`Flurry, Slam, and Wild Swing will now hit up to 24 enemies.`,
      },
	  "Fierce Might": {
        name: "Fierce Might",
        pos: "e3",
        icon: icons["abi_dw_face07"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Gain ${[
          1,
          2,
          3,
          4,
        ]}% chance to critically hit for each stack of Bloodthirst.`,
      },
	  "Doomseeker": {
        name: "Doomseeker",
        pos: "c4",
        icon: icons["abi_dw_fierceness"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Your outgoing damage is increased by ${[
          8,
          16,
        ]}% whenever you are below 40% health.`,
      },
	  "The Slayer Oath": {
        name: "The Slayer Oath",
        pos: "e5",
        icon: icons["abi_dw_melee11"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Grimnir's Fury now generates ${[
          1,
          2,
          3,
          4,
        ]} Rage. You generate ${[
          15,
          30,
          45,
          60,
        ]} Rage whenever you are Knocked-down.`,
      },
	  "Reckless Gamble": {
        name: "Reckless Gamble",
        pos: "b6",
        icon: icons["abi_dw_untouchable"],
        maxRank: 4,
        reqPoints: 15,
        type: "passive",
        description: talentText`Each time you deal direct damage to an enemy, you will deal ${[
          4,
          8,
          12,
          16,
        ]}% MAP indirect, ichor damage to them as well. You will deal half this amount to yourself.`,
      },
	  "Improved Vigilance": {
        name: "Improved Vigilance",
        pos: "e6",
        icon: icons["abi_vigilance"],
        maxRank: 3,
        reqPoints: 15,
        type: "passive",
        description: talentText`Vigilance now only reduces your outgoing damage by ${[
          75,
          60,
          45,
        ]}%.`,
      },
	  "Unhinged": {
        name: "Unhinged",
        pos: "e7",
        icon: icons["abi_dw_eventheodds"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Fueled by Violence now generates ${[
          70,
          85,
          100,
        ]} action points.`,
      },
	  "Wilder Swing": {
        name: "Wilder Swing",
        pos: "h7",
        icon: icons["abi_dw_wildswing"],
        maxRank: 3,
        reqPoints: 20,
        prereq: "Wild Swing",
		arrows: [
          { dir: "right-down", from: "g6", to: "h6" },
          { dir: "right-down-down", from: "h6", to: "h7" }
        ],
        type: "passive",
        description: talentText`Wild Swing deals ${[
          5,
          10,
          15,
        ]}% more damage.`,
      },
      "Power Through": {
        name: "Power Through",
        pos: "c8",
        icon: icons["abi_dw_grudgebornfury"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Whenever you are attacked you have a ${[
          4,
          12,
          24,
          40,
        ]}% chance to gain 1 stack of Enhanced Initiative.`,
      },
    },
  },
  "Giantslayer": {
    name: "Giantslayer",
    background: backgrounds["giantslayer"],
    icon: icons["archetype_dps"],
    talents: {
      "Break Loose": {
        name: "Break Loose",
        pos: "a8",
        icon: icons["rrtac_breakloose"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Movement skills you use will now remove Ensnared and Rooted from you.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 2,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 4,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Fleet-Footed": {
        name: "Fleet-Footed",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Your base movement speed is increased by 15%. Your mass is decreased by 1.`,
      },
      "Ancestral Inheritance": {
        name: "Ancestral Inheritance",
        pos: "a2",
        icon: icons["tac_race_dwarf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You are immune to effects that apply stacks of Reduced Armor.`,
      },
      "Stoutness of Stone": {
        name: "Soutness of Stone",
        pos: "b2",
        icon: icons["tac_race_dwarf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Your mass is increased by 1.`,
      },
      "Push for More": {
        name: "Push for More",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you spend Bloodthirst, you will heal yourself for 480 + 32% wounds.`,
      },
      "Honor Restored": {
        name: "Class Tactic 2",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you die, you are instantly ressurected to 2000 health and deal 10% MAP + 150 impact damage to up to 24 enemeies within 30 feet. This effect can only happen once every 90 seconds.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_specgreatweapon"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Giantslayers equip two-handed axes.`,
      },
      "Onslaught": {
        name: "Onslaught",
        pos: "i4",
        icon: icons["abi_dw_axetoss"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`For 60 seconds, the next 8 basic attacks you do will deal an additional 10% MAP + 100 indirect, impact damage.`,
      },
      "Even the Odds": {
        name: "Even the Odds",
        pos: "i5",
        icon: icons["abi_dw_face20"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain 75 toughness for each enemy within 30 feet. Stacks up to 10 times and lasts for 15 seconds.`,
      },
      "Dwarven Sprint": {
        name: "Dwarven Sprint",
        pos: "i7",
        icon: icons["abi_dw_figure12"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 20 seconds. For the duration, you gain 5 mass and 25% movement speed.`,
      },
      "Unleashed Power": {
        name: "Unleashed Power",
        pos: "i8",
        icon: icons["abi_dw_unleashedpower"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Gain a buff for 20 seconds. Every second you gain 20 rage and 1 Bloodthirst; you gain 33% damage reduction for the duration.`,
      },
	  "Sever Nerve": {
        name: "Sever Nerve",
        pos: "f2",
        icon: icons["morale_severnerve"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`Deals 50% MAP + 400 piercing damage to the target.`,
      },
      "Broad Swings": {
        name: "Broad Swings",
        pos: "g2",
        icon: icons["morale_broadswings"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain a buff for 10 seconds. Your single target abilities will target two additional enemies within 20 feet in front of you.`,
      },
      "Force of Will": {
        name: "Force of Will",
        pos: "h2",
        icon: icons["morale_forceofwill"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 10 seconds. Action point costs are reduced by 75% for the duration.`,
      },
      "Frenzied Slaughter": {
        name: "Frenzied Slaughter",
        pos: "i2",
        icon: icons["morale_frenziedslaughter"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`All groupmates within 100 feet gain a buff for 15 seconds. +40% outgoing damage and 50% reduced cooldowns for the duration.`,
      },
      "Rage and Bloodthirst": {
        name: "Rage and Bloodthirst",
        pos: "a1",
        icon: icons["abi_dw_fierceness"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`You gain a buff for 5 seconds whenever you take or deal damage that increases your rage generated per second by 5.\nFurious (26-75 rage): Lose 50% of your armor and all resistances. Gain penetration equal to 20% of the amount lost.\nBerserk (76-100 rage): You lose 75% of your total incoming healing received stat. Gain melee attack power equal to 10 times the amount lost.\n\nBloodthirst lasts for 60 seconds and stacks up to 5 times. Gain 1 rage per second per stack.`,
      },
      "Grimnir's Fury": {
        name: "Grimnir's Fury",
        pos: "b1",
        icon: icons["abi_dw_melee05"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deal 4% MAP + 30 impact damage to target enemy. Generates 22 action points.`,
      },
      "Devastate": {
        name: "Devastate",
        pos: "c1",
        icon: icons["abi_dw_devastate"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 75 Rage",
        description: talentText`Deals 28% MAP + 369 piercing damage to target enemy. Generates 1 Bloodthirst.`,
      },
      "Heavy Blow": {
        name: "Heavy Blow",
        pos: "d1",
        icon: icons["abi_dw_heavyblow"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 26% MAP + 348 piercing damage to target enemy.`,
      },
      "Charge": {
        name: "Charge",
        pos: "e1",
        icon: icons["abi_dw_charge"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "30s cooldown",
        description: talentText`(Movement Skill) For the next 8 seconds, your movement speed is increased by 40%.`,
      },
      "Deathblow": {
        name: "Deathblow",
        pos: "f1",
        icon: icons["abi_dw_grievousharm"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs Bloodthirst",
        description: talentText`Deals 44% MAP + 590 impact damage to target enemy.`,
      },
      "Cave-In": {
        name: "Cave-In",
        pos: "g1",
        icon: icons["abi_dw_figure15"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Applies Knocked-down and Unstoppable to target enemy.\n\nKnocked-down prevents all control of your character for 3 seconds.\nUnstoppable prevents the application of Knocked-down and Staggered for 30 seconds.`,
      },
      "Fueled by Violence": {
        name: "Fueled by Violence",
        pos: "h1",
        icon: icons["abi_dw_eventheodds"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "2s cooldown",
        blue: "Off the GCD\nCosts 50 Rage",
        description: talentText`Generates 55 action points and 1 Bloodthirst.`,
      },
      "Vigilance": {
        name: "Vigilance",
        pos: "i1",
        icon: icons["abi_vigilance"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        description: talentText`All damage you take is reduced by 50% but all damage you deal is reduced by 90% for 7 seconds.`,
      },
      "Flurry": {
        name: "Flurry",
        pos: "g4",
        icon: icons["abi_dw_flurry"],
        maxRank: 1,
        reqPoints: 5,
        type: "skill",
        cost: "75 action points",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 10% MAP + 127 piercing damage to up to 9 enemies within 30 feet in front of you.`,
      },
	  "Deep Wound": {
        name: "Deep Wound",
        pos: "c5",
        icon: icons["abi_dw_melee01"],
        maxRank: 1,
        reqPoints: 10,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs Bloodthirst",
        description: talentText`Applies a 9 second affliction to target enemy stacking up to 3 times. Every 3 seconds, the target takes 23% MAP + 314 indirect, ichor damage.`,
      },
	  "Wild Swing": {
        name: "Wild Swing",
        pos: "g6",
        icon: icons["abi_dw_wildswing"],
        maxRank: 1,
        reqPoints: 15,
        prereq: "Flurry",
        arrows: [{ dir: "down", from: "g4", to: "g6" }],
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs Bloodthirst",
        description: talentText`Deals 12% MAP + 170 piercing damage to up to 9 enemies within 30 feet in front of you.`,
      },
	  "Grievous Harm": {
        name: "Grevious Harm",
        pos: "e8",
        icon: icons["abi_dw_pulverizingstrike"],
        maxRank: 1,
        reqPoints: 25,
        type: "spell",
        cost: "no cost",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 40 Rage",
        description: talentText`Applies a 6 second cripple on target enemy. Deals 25% MAP + 346 indirect, ichor damage to them at the end of the duration and generates 1 Bloodthirst for you.`,
      },
      "The Harder They Fall": {
        name: "The Harder They Fall",
        pos: "d9",
        icon: icons["abi_dw_perilousassault"],
        maxRank: 1,
        reqPoints: 30,
        type: "passive",
        description: talentText`Gain 5 adrenaline per second. Gain 1 Bloodthirst every 6 seconds. Grimnir's Fury will deal 300% additional damage but no longer generate action points.`,
      },
      "Inevitable Doom": {
        name: "Inevitable Doom",
        pos: "f9",
        icon: icons["abi_dw_impendingdoom"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "self",
        cast: "1.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Applies a 6 second duration cripple to up to 9 enemies within 30 feet of you. Every 2 seconds up to 9 enemies within 20 feet of the target will take 3% MAP + 27 ichor damage.`,
      },
	  "Not Yet!": {
        name: "Not Yet!",
        pos: "a5",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Vigilance will now set your Rage to 0 and generate 1 Bloodthirst.`,
      },
	  "Unfair Advantage": {
        name: "Unfair Advantage",
        pos: "h5",
        icon: icons["tac_spec_2"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Whenever you hit an enemy you are flanking, you will gain a buff for 2 seconds. For the duration, you will gain outgoing damage equal to 100% of your accuracy.`,
      },
	  "Violent Impacts": {
        name: "Violent Impacts",
        pos: "c6",
        icon: icons["tac_spec_1"],
        maxRank: 1,
        reqPoints: 15,
		prereq: "Deep Wound",
        arrows: [{ dir: "down", from: "c5", to: "c6" }],
        type: "career tactic",
        description: talentText`Deep Wound and Grevious Harm can now critically hit.`,
      },
	  "Pulverize": {
        name: "Pulverize",
        pos: "f6",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Devestate now grants an additional Bloodthirst.`,
      },
	  "Breaking Point": {
        name: "Breaking Point",
        pos: "a7",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Whenever you hit an enemy with 40% or less health, you will apply a 5 second cripple to them. For the duration, they have -20% healing received.`,
      },
	  "Extended Battle": {
        name: "Extended Battle",
        pos: "g7",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 20,
        prereq: "Wild Swing",
		arrows: [{ dir: "down", from: "g6", to: "g7" }],
        type: "career tactic",
        description: talentText`Flurry, Slam, and Wild Swing will now hit up to 24 enemies.`,
      },
	  "Deadly Determination": {
        name: "Deadly Determination",
        pos: "f8",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Whenever you drop below 25% health, gain a 5 second blessing. This effect can only happen once every 60 seconds. For the duration, gain 30% outgoing damage, 100% damage reduction, -100% outgoing healing, and -100% healing received.`,
      },
	  "The Bigger They Are": {
        name: "The Bigger They Are",
        pos: "e3",
        icon: icons["abi_dw_retribution"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Gain ${[
          666,
          1333,
          2000,
        ]} potency for 4 seconds stacking up to 5 times whenever you spend Bloodthirst.`,
      },
	  "Doomseeker": {
        name: "Doomseeker",
        pos: "c4",
        icon: icons["abi_dw_fierceness"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Your outgoing damage is increased by ${[
          8,
          16,
        ]}% whenever you are below 40% health.`,
      },
	  "The Slayer Oath": {
        name: "The Slayer Oath",
        pos: "e5",
        icon: icons["abi_dw_melee11"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`Grimnir's Fury now generates ${[
          1,
          2,
          3,
          4,
        ]} Rage. You generate ${[
          15,
          30,
          45,
          60,
        ]} Rage whenever you are Knocked-down.`,
      },
	  "Unhinged": {
        name: "Unhinged",
        pos: "d6",
        icon: icons["abi_dw_eventheodds"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`Fueled by Violence now generates ${[
          70,
          85,
          100,
        ]} action points.`,
      },
	  "Extra Crit": {
        name: "Extra Crit",
        pos: "e6",
        icon: icons["abi_extracrit"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Your chance to critically hit is increased by ${[
          2,
          4,
		  6,
		  8,
		  10,
        ]}%.`,
	  },
	  "Improved Vigilance": {
        name: "Improved Vigilance",
        pos: "b7",
        icon: icons["abi_vigilance"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Vigilance now only reduces your outgoing damage by ${[
          75,
          60,
          45,
        ]}%.`,
      },
	  "Wilder Swing": {
        name: "Wilder Swing",
        pos: "h7",
        icon: icons["abi_dw_wildswing"],
        maxRank: 3,
        reqPoints: 20,
        prereq: "Wild Swing",
		arrows: [
          { dir: "right-down", from: "g6", to: "h6" },
          { dir: "right-down-down", from: "h6", to: "h7" }
        ],
        type: "passive",
        description: talentText`Wild Swing deals ${[
          5,
          10,
          15,
        ]}% more damage.`,
      },
	  "Enervating Blow": {
        name: "Enervating Blow",
        pos: "d8",
        icon: icons["abi_dw_grievousharm"],
        maxRank: 4,
        reqPoints: 25,
        type: "passive",
        description: talentText`Deathblow and Wild Swing now apply ${[
          1,
          2,
          3,
          4,
        ]} stacks of a 15 second buff. At 12 stacks, all stacks are removed and you gain 1 Bloodthirst.`,
      },
    },
  },
  "Brother of Grimnir": {
    name: "Exiled",
    background: backgrounds["Brother of Grimnir"],
    icon: icons["archetype_tank"],
    talents: {
      "Verge of Victory": {
        name: "Verge of Victory",
        pos: "a8",
        icon: icons["rrtac_vergeofvictory"],
        maxRank: 1,
        reqPoints: 25,
        type: "renown tactic",
        description: talentText`Whenever you land a killing blow, you will gain 20 adrenaline per second for 8 seconds. Whenever a groupmate within 100ft lands a killing blow, you will gain 5 adrenaline per second for 8 seconds.`,
      },
      "Agility": {
        name: "Agility",
        pos: "d5",
        icon: icons["stat_agl"],
        maxRank: 1,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Agility by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Ballistic Skill": {
        name: "Ballistic Skill",
        pos: "d4",
        icon: icons["stat_bal"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Ballistic Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Initiative": {
        name: "Initiative",
        pos: "c3",
        icon: icons["stat_ini"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Initiative by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Intelligence": {
        name: "Intelligence",
        pos: "f4",
        icon: icons["stat_int"],
        maxRank: 1,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Intelligence by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Strength": {
        name: "Strength",
        pos: "e4",
        icon: icons["stat_str"],
        maxRank: 5,
        reqPoints: 5,
        type: "passive",
        description: talentText`Increases your Strength by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Toughness": {
        name: "Toughness",
        pos: "d3",
        icon: icons["stat_tou"],
        maxRank: 5,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Toughness by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Willpower": {
        name: "Willpower",
        pos: "g3",
        icon: icons["stat_wil"],
        maxRank: 2,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Willpower by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Wounds": {
        name: "Wounds",
        pos: "f5",
        icon: icons["stat_wou"],
        maxRank: 4,
        reqPoints: 10,
        type: "passive",
        description: talentText`Increases your Wounds by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Weapon Skill": {
        name: "Weapon Skill",
        pos: "f3",
        icon: icons["stat_ws"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Increases your Weapon Skill by ${[
          100,
          185,
          255,
          310,
          350,
        ]}.`,
      },
      "Stabilized": {
        name: "Stabilized",
        pos: "a4",
        icon: icons["tac_arche"],
        maxRank: 1,
        reqPoints: 5,
        type: "career tactic",
        description: talentText`Increase your mass by 1.`,
      },
      "Ancestral Inheritance": {
        name: "Ancestral Inheritance",
        pos: "a2",
        icon: icons["tac_race_dwarf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`You are immune to effects that apply stacks of Reduced Armor.`,
      },
      "Stoutness of Stone": {
        name: "Soutness of Stone",
        pos: "b2",
        icon: icons["tac_race_dwarf"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Your mass is increased by 1.`,
      },
      "Push for More": {
        name: "Push for More",
        pos: "c2",
        icon: icons["tac_class_1"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you spend Bloodthirst, you will heal yourself for 480 + 32% wounds.`,
      },
      "Honor Restored": {
        name: "Class Tactic 2",
        pos: "d2",
        icon: icons["tac_class_2"],
        maxRank: 0,
        reqPoints: 0,
        type: "career tactic",
        description: talentText`Whenever you die, you are instantly ressurected to 2000 health and deal 10% MAP + 150 impact damage to up to 24 enemeies within 30 feet. This effect can only happen once every 90 seconds.`,
      },
      "Weapon Aptitude": {
        name: "Weapon Aptitude",
        pos: "e2",
        icon: icons["skl_spechammer"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`Exiled dual wield one-handed hammers.`,
      },
      "Onslaught": {
        name: "Onslaught",
        pos: "i4",
        icon: icons["abi_dw_axetoss"],
        maxRank: 1,
        reqPoints: 5,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`For 60 seconds, the next 8 basic attacks you do will deal an additional 10% MAP + 100 indirect, impact damage.`,
      },
      "Even the Odds": {
        name: "Even the Odds",
        pos: "i5",
        icon: icons["abi_dw_face20"],
        maxRank: 1,
        reqPoints: 10,
        type: "morale 2",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`You gain 75 toughness for each enemy within 30 feet. Stacks up to 10 times and lasts for 15 seconds.`,
      },
      "Dwarven Sprint": {
        name: "Dwarven Sprint",
        pos: "i7",
        icon: icons["abi_dw_figure12"],
        maxRank: 1,
        reqPoints: 20,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`You gain a buff for 20 seconds. For the duration, you gain 5 mass and 25% movement speed.`,
      },
      "Unleashed Power": {
        name: "Unleashed Power",
        pos: "i8",
        icon: icons["abi_dw_unleashedpower"],
        maxRank: 1,
        reqPoints: 25,
        type: "morale 4",
        cost: "no cost",
        range: "7.5ft range self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Gain a buff for 20 seconds. Every second you gain 20 rage and 1 Bloodthirst; you gain 33% damage reduction for the duration.`,
      },
	  "Hedgehog": {
        name: "Hedgehog",
        pos: "f2",
        icon: icons["morale_hedgehog"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 1",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 360 adrenaline",
        description: talentText`All groupmates within 100 feet gain 3 stacks of Enhanced Block.`,
      },
      "Champion's Challenge": {
        name: "Champion's Chalenge",
        pos: "g2",
        icon: icons["morale_grapple"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 2",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 720 adrenaline",
        description: talentText`Applies a debuff to target enemy and yourself for 10 seconds. Movement speed is reduced to 0 for the duration.`,
      },
      "Distracting Bellow": {
        name: "Distracting Bellow",
        pos: "h2",
        icon: icons["morale_distractingbellow"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 3",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 1800 adrenaline",
        description: talentText`Up to 48 enemies within 30 feet of you receive a debuff. For 10 seconds, they cannot benefit from Cover.`,
      },
      "Immaculate Defense": {
        name: "Immaculate Defense",
        pos: "i2",
        icon: icons["morale_immaculatedefense"],
        maxRank: 0,
        reqPoints: 0,
        type: "morale 4",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 3600 adrenaline",
        description: talentText`Groupmates within 100 feet gain 25 stacks of a buff for 20 seconds. Each stack grants 3% damage reduction. A stack is removed each time they are attacked by an ability; 4 additional stacks are removed if the ability is single target.`,
      },
      "Rage and Bloodthirst": {
        name: "Rage and Bloodthirst",
        pos: "a1",
        icon: icons["abi_dw_fierceness"],
        maxRank: 0,
        reqPoints: 0,
        type: "passive",
        description: talentText`You gain a buff for 5 seconds whenever you take or deal damage that increases your rage generated per second by 5.\nFurious (26-75 rage): Lose 50% of your armor and all resistances. Gain penetration equal to 20% of the amount lost.\nBerserk (76-100 rage): You lose 75% of your total incoming healing received stat. Gain melee attack power equal to 10 times the amount lost.\n\nBloodthirst lasts for 60 seconds and stacks up to 5 times. Gain 1 rage per second per stack.`,
      },
      "Grimnir's Fury": {
        name: "Grimnir's Fury",
        pos: "b1",
        icon: icons["abi_dw_melee05"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`(Basic Attack) Deal 4% MAP + 30 impact damage to target enemy. Generates 22 action points.`,
      },
      "Fueled by Violence": {
        name: "Fueled by Violence",
        pos: "c1",
        icon: icons["abi_dw_eventheodds"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "2s cooldown",
        blue: "Off the GCD\nCosts 50 Rage",
        description: talentText`Generates 55 action points and 1 Bloodthirst.`,
      },
      "Heavy Blow": {
        name: "Heavy Blow",
        pos: "d1",
        icon: icons["abi_dw_heavyblow"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        description: talentText`Deals 26% MAP + 348 piercing damage to target enemy.`,
      },
      "Rune of Absorption": {
        name: "Rune of Absorption",
        pos: "e1",
        icon: icons["abi_dw_figure11"],
        maxRank: 0,
        reqPoints: 0,
        type: "spell",
        cost: "no cost",
        range: "30ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 30 Rage\nOff the GCD",
        description: talentText`Apply a 5 second enchantment to target ally. For the duration, they will absorb up to 21% RP + 277 damage. Also apply a 5 second blessing to target ally. For the duration, they gain toughness equal to 50% of your toughness. This counts as a guard effect.`,
      },
      "Anklecrusher": {
        name: "Anklecrusher",
        pos: "f1",
        icon: icons["abi_dw_foot04"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "40 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Applies Rooted and Immovable to target enemy. Generates 25 Rage.\n\nRooted prevents the character from moving for 5 seconds.\nImmovable prevents application of Rooted, Knockback, and Pull effects for 20 seconds.`,
      },
      "Away With Ye": {
        name: "Away With Ye",
        pos: "g1",
        icon: icons["abi_dw_figure21"],
        maxRank: 0,
        reqPoints: 0,
        type: "skill",
        cost: "50 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "10s cooldown",
        description: talentText`Knocks target enemy away from you.`,
      },
      "Untouchable": {
        name: "Untouchable",
        pos: "h1",
        icon: icons["abi_dw_figure03"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs Bloodthrirst",
        description: talentText`Consumes all of your Bloodthirst to apply a buff to you with a duration of 2 seconds per Bloodthirst consumed. For the duration, gain 50% dodge.`,
      },
      "Vigilance": {
        name: "Vigilance",
        pos: "i1",
        icon: icons["abi_vigilance"],
        maxRank: 0,
        reqPoints: 0,
        type: "ability",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "60s cooldown",
        description: talentText`All damage you take is reduced by 50% but all damage you deal is reduced by 90% for 7 seconds.`,
      },
      "Cleft in Twain": {
        name: "Cleft in Twain",
        pos: "h4",
        icon: icons["abi_dw_cleftintwain"],
        maxRank: 1,
        reqPoints: 5,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs 30 Rage",
        description: talentText`Deals 18% MAP + 232 piercing damage to target enemy and up to 2 other enemies within 20 feet of them.`,
      },
	  "Cave-In": {
        name: "Cave-In",
        pos: "c5",
        icon: icons["abi_dw_figure15"],
        maxRank: 1,
        reqPoints: 10,
        type: "skill",
        cost: "60 action points",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "20s cooldown",
        description: talentText`Applies Knocked-down and Unstoppable to target enemy.\n\nKnocked-down prevents all control of your character for 3 seconds.\nUnstoppable prevents the application of Knocked-down and Staggered for 30 seconds.`,
      },
	  "Wild Swing": {
        name: "Wild Swing",
        pos: "e6",
        icon: icons["abi_dw_wildswing"],
        maxRank: 1,
        reqPoints: 15,
        type: "skill",
        cost: "no cost",
        range: "self",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs Bloodthirst",
        description: talentText`Deals 12% MAP + 170 piercing damage to up to 9 enemies within 30 feet in front of you.`,
      },
	  "Deathblow": {
        name: "Deathblow",
        pos: "d8",
        icon: icons["abi_dw_grievousharm"],
        maxRank: 1,
        reqPoints: 25,
        type: "skill",
        cost: "no cost",
        range: "8ft range",
        cast: "instant cast",
        cooldown: "no cooldown",
        blue: "Costs Bloodthirst",
        description: talentText`Deals 44% MAP + 590 impact damage to target enemy.`,
      },
	  "Retribution": {
        name: "Retribution",
        pos: "d9",
        icon: icons["abi_dw_untouchable"],
        maxRank: 1,
        reqPoints: 30,
        type: "passive",
        description: talentText`You have 10% increased maximum health, deal 7% MAP + 91 indirect, ichor damage to enemies that hit you with abilities, and Grimnir's Fury deals 300% additional damage but no longer generates action points.`,
      },
      "Quagmire": {
        name: "Quagmire",
        pos: "f9",
        icon: icons["abi_dw_gripofstone"],
        maxRank: 1,
        reqPoints: 30,
        type: "spell",
        cost: "150 action points",
        range: "self",
        cast: "1.0s cast",
        cooldown: "30s cooldown",
        description: talentText`Up to 48 enemies within 30 feet of you have their movement speed reduced by 90% for 4 seconds. Does not effect target that have Cover from you.`,
      },
	  "Not Yet!": {
        name: "Not Yet!",
        pos: "a5",
        icon: icons["tac_spec_4"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`Vigilance will now set your Rage to 0 and generate 1 Bloodthirst.`,
      },
	  "Blood of Grimnir": {
        name: "Blood of Grimnir",
        pos: "g5",
        icon: icons["tac_spec_6"],
        maxRank: 1,
        reqPoints: 10,
        type: "career tactic",
        description: talentText`You gain 3% damage reduction for each stack of Bloodthirst you have.`,
      },
	  "Short Temper": {
        name: "Short Temper",
        pos: "c6",
        icon: icons["tac_spec_8"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Your action point costs are reduced by 20% whenever you are Furious and by 40% whenever you are Berserk. Enemies that attack you gain 5 action points.`,
      },
	  "Gudrun's Warcry": {
        name: "Gudrun's Warcry",
        pos: "g6",
        icon: icons["tac_spec_3"],
        maxRank: 1,
        reqPoints: 15,
        type: "career tactic",
        description: talentText`Fueled by Violence now grants an additional Bloodthirst.`,
      },
	  "Can't Touch This": {
        name: "Can't Touch This",
        pos: "b7",
        icon: icons["tac_spec_9"],
        maxRank: 1,
        reqPoints: 20,
        type: "career tactic",
        description: talentText`Untouchable will now only cost 1 Bloodthirst and always lasts 4 seconds, but has a 10 second cooldown.`,
      },
	  "Crushing Force": {
        name: "Crushing Force",
        pos: "h7",
        icon: icons["tac_spec_5"],
        maxRank: 1,
        reqPoints: 20,
		prereq: "Cleft in Twain",
		arrows: [
          { dir: "down", from: "h4", to: "h7" },
        ],
        type: "career tactic",
        description: talentText`Cleft in Twain will deal 50% additional damage to a target that has casted an active Guard effect.`,
      },
	  "Taking Chances": {
        name: "Taking Chances",
        pos: "f8",
        icon: icons["tac_spec_7"],
        maxRank: 1,
        reqPoints: 25,
        type: "career tactic",
        description: talentText`Your mechanic no longer grants you penetration or melee attack power. Instead, groupmates within 30 feet of you will gain stats equal to half of what you lost.`,
      },
	  "No Escape": {
        name: "No Escape",
        pos: "b4",
        icon: icons["abi_dw_madness"],
        maxRank: 2,
        reqPoints: 5,
        type: "passive",
        description: talentText`You gain ${[
          1,
          2,
          3,
          4,
          5,
        ]}% accuracy per stack of Bloodthrist.`,
      },
	  "Oaths of Old": {
        name: "Oaths of Old",
        pos: "e5",
        icon: icons["abi_dw_oathfriend"],
        maxRank: 3,
        reqPoints: 10,
        type: "passive",
        description: talentText`You gain restoration power equal to ${[
          10,
          20,
          30,
          40,
          50,
        ]}% of your melee attack power.`,
      },
	  "Looks Like a Challenge": {
        name: "Looks Like a Challenge",
        pos: "e3",
        icon: icons["abi_dw_gudrunswarcry"],
        maxRank: 3,
        reqPoints: 0,
        type: "passive",
        description: talentText`Whenever you spend Rage, you have a ${[
          33,
          66,
          100,
        ]}% chance to gain 1 stack of Enhanced Initiative, Weaponskill, or Willpower.`,
      },
	  "Embrace the Pain": {
        name: "Embrace the Pain",
        pos: "d6",
        icon: icons["abi_dw_hand04"],
        maxRank: 2,
        reqPoints: 15,
        type: "passive",
        description: talentText`Gain ${[
          10,
          20,
        ]}% healing received.`,
      },
	  "Band Together": {
        name: "Band Together",
        pos: "f6",
        icon: icons["abi_bandtogether"],
        maxRank: 5,
        reqPoints: 15,
        type: "passive",
        description: talentText`Groupmates within 30 feet of you have their damage reduction increased by ${[
          2,
          4,
          6,
          8,
          10,
        ]}%. This effect is surpressed for 5 seconds whenever you are hit by a single-target ability.`,
      },
	  "Unhinged": {
        name: "Unhinged",
        pos: "a7",
        icon: icons["abi_dw_eventheodds"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Fueled by Violence now generates ${[
          70,
          85,
          100,
        ]} action points.`,
      },
	  "Engage": {
        name: "Engage",
        pos: "e7",
        icon: icons["abi_engage"],
        maxRank: 3,
        reqPoints: 20,
        type: "passive",
        description: talentText`Enemies that you deal direct damage to will have their outgoing damage reduced by ${[
          2,
          4,
          6,
        ]}% for 5 seconds.`,
      },
	  "Numbing Strikes": {
        name: "Numbing Strikes",
        pos: "e8",
        icon: icons["abi_dw_melee14"],
        maxRank: 4,
        reqPoints: 25,
        prereq: "Deathblow",
		arrows: [
          { dir: "right", from: "d8", to: "e8" },
        ],
        type: "passive",
        description: talentText`You have a ${[
          10,
          30,
          60,
          100,
        ]}% chance when you hit an enemy with Deathblow and a ${[
          4,
          12,
          24,
          40,
        ]}% chance when you hit an enemy with Wild Swing to apply a stack of Reduced Strength to the target.`,
      },
    },
  },
};
